#define NOMINMAX
#include <Windows.h>
#include <commdlg.h>
#include "editor_ui.hpp"
#include "editor_theme.hpp"
#include <imgui_internal.h>
#include <ImGuizmo.h>
#include <nlohmann/json.hpp>
#include <cstring>
#include <cmath>
#include <set>
namespace darkangel::editor_app {
namespace {
template<class F>void action(Controller& editor,F&& call){try{call();}catch(const std::exception& error){editor.log(error.what(),ConsoleSeverity::Error);}}
std::filesystem::path dialog(bool save){wchar_t file[32768]{};OPENFILENAMEW options{};options.lStructSize=sizeof(options);options.lpstrFile=file;options.nMaxFile=32768;options.lpstrFilter=L"DarkAngel scene\0*.dascene\0All files\0*.*\0";options.lpstrDefExt=L"dascene";options.Flags=OFN_NOCHANGEDIR|OFN_PATHMUSTEXIST|(save?OFN_OVERWRITEPROMPT:OFN_FILEMUSTEXIST);if(save?GetSaveFileNameW(&options):GetOpenFileNameW(&options))return file;return {};}
double property(const ObjectData& data,TypeId type,const PropertyMetadata& field){const void* component=type==1?static_cast<const void*>(&data.transform):static_cast<const void*>(&data.health);double value;std::memcpy(&value,static_cast<const char*>(component)+field.offset,sizeof(value));return value;}
}
ViewArea Shell::draw(Controller& editor,unsigned width,unsigned height,const char* backend,std::uint64_t generation,double seconds,ImTextureID scene_texture){
    forward=lateral=turn=0;walk=jump=false;controls_acquired=false;
    const auto menu_height=ImGui::GetFrameHeight();const auto toolbar_height=ImGui::GetFrameHeight()+ImGui::GetStyle().WindowPadding.y*2;const auto workspace_top=menu_height+toolbar_height;
    if(ImGui::BeginMainMenuBar()){ImGui::TextColored({.25f,.75f,.95f,1},"DarkAngel");ImGui::Separator();ImGui::BeginDisabled(dragging);
        if(ImGui::BeginMenu("File")){ImGui::BeginDisabled(!editor.assets||editor.preview.active()!=nullptr);if(ImGui::MenuItem("Import asset..."))choose_asset_import();ImGui::EndDisabled();if(ImGui::MenuItem("New Scene"))action(editor,[&]{editor.demo();});if(ImGui::MenuItem("Open..."))action(editor,[&]{auto path=dialog(false);if(!path.empty())editor.open(path);});if(ImGui::MenuItem("Save Scene"))action(editor,[&]{editor.save(editor.path);});if(ImGui::MenuItem("Save As..."))action(editor,[&]{auto path=dialog(true);if(!path.empty())editor.save(path);});if(ImGui::BeginMenu("Reload")){if(ImGui::MenuItem("Scripts"))action(editor,[&]{editor.reload_scripts();});if(ImGui::MenuItem("Models"))reload_model=true;if(ImGui::MenuItem("Shaders"))reload_shader=true;ImGui::EndMenu();}ImGui::EndMenu();}
        if(ImGui::BeginMenu("Tools")){if(ImGui::MenuItem("Console"))open_tool(ToolView::Console);if(ImGui::MenuItem("Authoring history"))open_tool(ToolView::AuthoringHistory);if(ImGui::MenuItem("Input bindings"))open_tool(ToolView::InputBindings);if(ImGui::MenuItem("Script source"))open_tool(ToolView::ScriptSource);if(ImGui::MenuItem("Runtime phases"))open_tool(ToolView::RuntimePhases);ImGui::EndMenu();}
        if(ImGui::BeginMenu("Settings")){if(ImGui::MenuItem("Editor settings")){if(workspace!=Workspace::Settings&&workspace!=Workspace::Tools)previous_workspace=workspace;project_settings=false;select_workspace(Workspace::Settings);}if(ImGui::MenuItem("Project settings")){if(workspace!=Workspace::Settings&&workspace!=Workspace::Tools)previous_workspace=workspace;project_settings=true;select_workspace(Workspace::Settings);}ImGui::EndMenu();}ImGui::EndDisabled();ImGui::TextDisabled("%s | %s",backend,editor.preview.active()?(editor.paused?"Paused":"Playing"):"Stopped");ImGui::EndMainMenuBar();}
    ImGui::SetNextWindowPos({0,menu_height});ImGui::SetNextWindowSize({float(width),toolbar_height});ImGui::Begin("Workflow navigation",nullptr,ImGuiWindowFlags_NoDecoration|ImGuiWindowFlags_NoDocking|ImGuiWindowFlags_NoSavedSettings);ImGui::BeginDisabled(dragging);if(ImGui::Selectable("Scene / Level Design",workspace==Workspace::Scene,0,{180,0}))select_workspace(Workspace::Scene);ImGui::SameLine();if(ImGui::Selectable("Assets",workspace==Workspace::Assets,0,{110,0}))select_workspace(Workspace::Assets);ImGui::SameLine();if(ImGui::Selectable("Character",workspace==Workspace::Character,0,{100,0}))select_workspace(Workspace::Character);ImGui::SameLine();if(ImGui::Selectable("Player",workspace==Workspace::Player,0,{90,0}))select_workspace(Workspace::Player);ImGui::SameLine();if(ImGui::Selectable("Ability",workspace==Workspace::Ability,0,{110,0}))select_workspace(Workspace::Ability);ImGui::SameLine();if(ImGui::Selectable("Animation",workspace==Workspace::Animation,0,{110,0}))select_workspace(Workspace::Animation);ImGui::SameLine();if(ImGui::Selectable("Game",workspace==Workspace::Game,0,{110,0}))select_workspace(Workspace::Game);ImGui::EndDisabled();ImGui::SameLine();if(editor.document->dirty())ImGui::TextColored(attention,"Unsaved");else ImGui::TextDisabled("Saved");ImGui::End();
    if(workspace!=Workspace::Scene&&docked)ImGui::DockSpace(ImHashStr("DarkAngelSceneDock"),{0,0},ImGuiDockNodeFlags_KeepAliveOnly);
    if(workspace!=Workspace::Game&&game_docked)ImGui::DockSpace(ImHashStr("DarkAngelGameDock"),{0,0},ImGuiDockNodeFlags_KeepAliveOnly);
    if(workspace==Workspace::Assets){controls_focus=false;ImGui::SetNextWindowPos({0,workspace_top});ImGui::SetNextWindowSize({float(width),float(height)-workspace_top});ImGui::Begin("Assets workspace",nullptr,ImGuiWindowFlags_NoDecoration|ImGuiWindowFlags_NoDocking|ImGuiWindowFlags_NoSavedSettings);draw_assets(editor,true);ImGui::End();draw_import(editor);return area;}
    composer_frame_seconds=std::isfinite(seconds)?std::clamp(seconds,0.,.1):0.;
    if(composer_dragging&&workspace!=Workspace::Ability&&workspace!=Workspace::Animation)cancel_composer_drag(editor);
    composer_visible=false;composer_texture=scene_texture;
    if(workspace==Workspace::Ability||workspace==Workspace::Animation||workspace==Workspace::Character||workspace==Workspace::Player){controls_focus=false;draw_authoring(editor,width,height,workspace_top);return area;}
    if(workspace==Workspace::Game){draw_game(editor,width,height,workspace_top,seconds,scene_texture);draw_import(editor);return area;}
    if(workspace==Workspace::Tools||workspace==Workspace::Settings){controls_focus=false;draw_auxiliary(editor,width,height,workspace_top);draw_import(editor);return area;}
    controls_focus=false;

    ImGui::SetNextWindowPos({0,workspace_top});ImGui::SetNextWindowSize({static_cast<float>(width),static_cast<float>(height)-workspace_top});ImGui::PushStyleVar(ImGuiStyleVar_WindowPadding,{0,0});ImGui::Begin("Workspace",nullptr,ImGuiWindowFlags_NoDecoration|ImGuiWindowFlags_NoDocking|ImGuiWindowFlags_NoBackground);auto dock=ImHashStr("DarkAngelSceneDock");ImGui::DockSpace(dock,{0,0},ImGuiDockNodeFlags_PassthruCentralNode);ImGui::End();ImGui::PopStyleVar();
    if(!docked){ImGui::DockBuilderRemoveNode(dock);ImGui::DockBuilderAddNode(dock,ImGuiDockNodeFlags_DockSpace);ImGui::DockBuilderSetNodeSize(dock,{static_cast<float>(width),static_cast<float>(height)-workspace_top});auto center=dock;auto left=ImGui::DockBuilderSplitNode(center,ImGuiDir_Left,.18f,nullptr,&center);auto right=ImGui::DockBuilderSplitNode(center,ImGuiDir_Right,.28f,nullptr,&center);auto bottom=ImGui::DockBuilderSplitNode(center,ImGuiDir_Down,.28f,nullptr,&center);auto content=ImGui::DockBuilderSplitNode(bottom,ImGuiDir_Left,.52f,nullptr,&bottom);ImGui::DockBuilderDockWindow("World Outliner",left);ImGui::DockBuilderDockWindow("Inspector",right);ImGui::DockBuilderDockWindow("Viewport",center);ImGui::DockBuilderDockWindow("Content Browser",content);ImGui::DockBuilderDockWindow("Console",bottom);ImGui::DockBuilderFinish(dock);docked=true;}
    ImGui::Begin("World Outliner");ImGui::SetNextItemWidth(-1);ImGui::InputTextWithHint("##filter","Search objects...",filter,sizeof(filter));icon_text(Icon::Object,"Scene placements");for(const auto& origin:editor.document->plan().origins){if(filter[0] && origin.name.find(filter)==std::string::npos)continue;ImGui::PushID(origin.object.text().c_str());if(icon_selectable(Icon::Object,(origin.name+"##object").c_str(),editor.selected==origin.object))editor.selected=origin.object;ImGui::TextDisabled("%s",origin.object.text().substr(24).c_str());ImGui::PopID();}ImGui::End();
    ImGui::Begin("Inspector");auto handle=editor.displayed().find(editor.selected);if(editor.displayed().valid(handle)){auto object=editor.displayed().read(handle);icon_text(Icon::Object,"Persistent object ID");ImGui::Text("%s",object.id.text().substr(0,16).c_str());ImGui::Text("%s",object.id.text().substr(16).c_str());ImGui::Text("World %llu | epoch %llu",handle.domain,handle.epoch);ImGui::Text("Handle %llu | valid",handle.runtime);int destination=scope==EditScope::Definition?1:0;const char* destinations[]={"Scene placement","Assembly definition"};ImGui::TextDisabled("Edit destination");ImGui::SetNextItemWidth(-1);if(ImGui::Combo("##Edit destination",&destination,destinations,2))scope=destination?EditScope::Definition:EditScope::Placement;ImGui::BeginDisabled(editor.preview.active()!=nullptr || dragging);
        for(const auto& type:metadata())if(type.id<=2 && ImGui::CollapsingHeader(std::string(type.name).c_str(),ImGuiTreeNodeFlags_DefaultOpen)){ImGui::TextDisabled("TypeId %u | schema %u",type.id,type.version);if(ImGui::BeginTable("Properties",2,ImGuiTableFlags_SizingStretchProp)){ImGui::TableSetupColumn("Property",ImGuiTableColumnFlags_WidthFixed,ImGui::CalcTextSize("maximum").x+8);ImGui::TableSetupColumn("Value",ImGuiTableColumnFlags_WidthStretch);for(const auto& field:type.properties)if(field.flags&Editable){ImGui::TableNextRow();ImGui::TableNextColumn();ImGui::TextUnformatted(std::string(field.name).c_str());ImGui::TableNextColumn();ImGui::SetNextItemWidth(-1);auto value=property(object,type.id,field);ImGui::PushID(static_cast<int>(type.id*100+field.id));const bool steppers=ImGui::GetContentRegionAvail().x>=ImGui::GetFrameHeight()*2+ImGui::GetFontSize()*6;if(ImGui::InputDouble("##value",&value,steppers?.1:0,steppers?1:0,"%.3f"))action(editor,[&]{PropertyChange change{object.id,type.id,field.id,value};auto prepared=editor.document->prepare(editor.document->revision(),{&change,1},scope);editor.document->commit(prepared);editor.log(prepared.summary);});ImGui::PopID();}ImGui::EndTable();}}
        if(ImGui::Button("Undo"))action(editor,[&]{editor.document->undo(editor.document->revision());});ImGui::SameLine();if(ImGui::Button("Redo"))action(editor,[&]{editor.document->redo(editor.document->revision());});ImGui::EndDisabled();
        if(ImGui::CollapsingHeader("Script Bindings",ImGuiTreeNodeFlags_DefaultOpen))for(const auto& binding:object.scripts.records){ImGui::TextWrapped("Attachment %s",binding.id.text().c_str());ImGui::TextWrapped("Asset %s",asset_id(binding.asset).text().c_str());ImGui::TextUnformatted(binding.config_json.c_str());if(editor.preview.active())for(const auto& info:editor.preview.active()->scripts->bindings())if(info.id==binding.id){ImGui::Text("%s | generation %llu",info.enabled?"Enabled":"Disabled",info.generation);ImGui::Text("Calls %llu | last %llu us",info.metrics.calls,info.metrics.last_microseconds);}}
        if(ImGui::CollapsingHeader("Provenance"))for(const auto& origin:editor.document->plan().origins)if(origin.object==object.id){ImGui::TextWrapped("Definition %s",origin.definition.text().c_str());ImGui::TextWrapped("Stable local path %s",origin.local_path.c_str());ImGui::TextWrapped("%s",origin.layer.c_str());}
    }else ImGui::TextDisabled("Select a scene object.");ImGui::End();
    ImGui::Begin("Content Browser");draw_assets(editor);ImGui::Separator();icon_text(Icon::Folder,"Scene models");std::set<AssetId> models;for(const auto& [object,asset]:editor.document->plan().models)models.insert(asset);for(auto asset:models)ImGui::TextWrapped("%s",asset.text().c_str());ImGui::Text("Resource generation %llu",generation);std::set<StableId> scripts;for(const auto& planned:editor.document->plan().bindings)scripts.insert(planned.binding.asset);for(auto id:scripts){ImGui::PushID(id.text().c_str());if(ImGui::Button("Edit script source"))action(editor,[&]{script_asset=asset_id(id);auto data=nlohmann::json::parse(editor.document->source(script_asset));strncpy_s(script,data.at("source").get<std::string>().c_str(),_TRUNCATE);show_script=true;open_tool(ToolView::ScriptSource);});ImGui::TextWrapped("%s",id.text().c_str());ImGui::PopID();}ImGui::TextDisabled("Source edits use native transactions.");ImGui::End();
    ImGui::Begin("Console");for(const auto& line:editor.console){auto error=line.severity==ConsoleSeverity::Error,warning=line.severity==ConsoleSeverity::Warning;icon_text(error?Icon::Error:warning?Icon::Warning:Icon::Info,error?"Error":warning?"Warning":"Info");ImGui::SameLine();ImGui::TextWrapped("%s",line.message.c_str());}ImGui::End();
    ImGui::Begin("Viewport");const char* modes[]={"Move","Rotate","Scale"};ImGui::SetNextItemWidth(100);ImGui::Combo("##gizmo",&operation,modes,3);ImGui::SameLine();ImGui::TextDisabled("%s | metres | RH Y-up",backend);auto pos=ImGui::GetCursorScreenPos(),size=ImGui::GetContentRegionAvail();size.x=std::max(size.x,1.f);size.y=std::max(size.y,1.f);area={pos.x,pos.y,size.x,size.y};viewport_draw=ImGui::GetWindowDrawList();ImGui::Image(scene_texture,size);ImGui::End();draw_import(editor);return area;
}
void Shell::gizmo(Controller& editor,const DirectX::XMFLOAT4X4& view,const DirectX::XMFLOAT4X4& projection){if(workspace!=Workspace::Scene||editor.preview.active())return;auto handle=editor.document->world().find(editor.selected);if(!editor.document->world().valid(handle))return;auto pose=draft?*draft:editor.document->world().read(handle).transform;using namespace DirectX;XMFLOAT4X4 matrix;XMStoreFloat4x4(&matrix,XMMatrixScaling(pose.scale,pose.scale,pose.scale)*XMMatrixRotationRollPitchYaw(pose.pitch,pose.yaw,pose.roll)*XMMatrixTranslation(pose.x,pose.y,pose.z));ImGuizmo::SetDrawlist(viewport_draw);ImGuizmo::SetRect(area.x,area.y,area.width,area.height);auto op=operation==1?ImGuizmo::ROTATE:operation==2?ImGuizmo::SCALEU:ImGuizmo::TRANSLATE;ImGuizmo::Manipulate(&view._11,&projection._11,op,ImGuizmo::LOCAL,&matrix._11);
    bool using_gizmo=ImGuizmo::IsUsing();if(using_gizmo && !dragging){gesture_object=editor.selected;gesture_revision=editor.document->revision();dragging=true;cancelled=false;}
    if(using_gizmo){float position[3],rotation[3],scale[3];ImGuizmo::DecomposeMatrixToComponents(&matrix._11,position,rotation,scale);pose.x=position[0];pose.y=position[1];pose.z=position[2];pose.pitch=rotation[0]*XM_PI/180;pose.yaw=rotation[1]*XM_PI/180;pose.roll=rotation[2]*XM_PI/180;pose.scale=scale[0];if(!cancelled)draft=pose;else draft.reset();if(ImGui::IsKeyPressed(ImGuiKey_Escape)){cancelled=true;draft.reset();}}
    if(dragging && !using_gizmo){if(!cancelled && draft)action(editor,[&]{auto value=*draft;PropertyChange changes[]={{gesture_object,1,1,value.yaw},{gesture_object,1,2,value.x},{gesture_object,1,3,value.y},{gesture_object,1,4,value.z},{gesture_object,1,5,value.pitch},{gesture_object,1,6,value.roll},{gesture_object,1,7,value.scale}};auto transaction=editor.document->prepare(gesture_revision,changes,scope);editor.document->commit(transaction);editor.log("Committed one transform gesture.");});draft.reset();dragging=false;}
}
}
