#define NOMINMAX
#include <Windows.h>
#include <commdlg.h>
#include "editor_ui.hpp"
#include <imgui_internal.h>
#include <ImGuizmo.h>
#include <nlohmann/json.hpp>
#include <cstring>
#include <cmath>
namespace darkangel::editor_app {
namespace {
template<class F>void action(Controller& editor,F&& call){try{call();}catch(const std::exception& error){editor.log(error.what());}}
std::filesystem::path dialog(bool save){wchar_t file[32768]{};OPENFILENAMEW options{};options.lStructSize=sizeof(options);options.lpstrFile=file;options.nMaxFile=32768;options.lpstrFilter=L"DarkAngel scene\0*.dascene\0All files\0*.*\0";options.lpstrDefExt=L"dascene";options.Flags=OFN_NOCHANGEDIR|OFN_PATHMUSTEXIST|(save?OFN_OVERWRITEPROMPT:OFN_FILEMUSTEXIST);if(save?GetSaveFileNameW(&options):GetOpenFileNameW(&options))return file;return {};}
double property(const ObjectData& data,TypeId type,const PropertyMetadata& field){const void* component=type==1?static_cast<const void*>(&data.transform):static_cast<const void*>(&data.health);double value;std::memcpy(&value,static_cast<const char*>(component)+field.offset,sizeof(value));return value;}
}
ViewArea Shell::draw(Controller& editor,unsigned width,unsigned height,const char* backend,std::uint64_t generation,double seconds,ImTextureID scene_texture){
    auto& style=ImGui::GetStyle();style.WindowRounding=3;style.FrameRounding=3;style.Colors[ImGuiCol_WindowBg]={.045f,.065f,.085f,1};style.Colors[ImGuiCol_Header]={.09f,.22f,.32f,1};style.Colors[ImGuiCol_Button]={.08f,.18f,.25f,1};
    if(ImGui::BeginMainMenuBar()){ImGui::TextColored({.25f,.75f,.95f,1},"DarkAngel");ImGui::Separator();if(ImGui::BeginMenu("File")){if(ImGui::MenuItem("New Scene"))action(editor,[&]{editor.demo();});if(ImGui::MenuItem("Open..."))action(editor,[&]{auto path=dialog(false);if(!path.empty())editor.open(path);});if(ImGui::MenuItem("Save Scene"))action(editor,[&]{editor.save(editor.path);});if(ImGui::MenuItem("Save As..."))action(editor,[&]{auto path=dialog(true);if(!path.empty())editor.save(path);});ImGui::EndMenu();}ImGui::SameLine();ImGui::Text("%s | %s",backend,editor.preview.active()?(editor.paused?"Paused":"Playing"):"Stopped");ImGui::EndMainMenuBar();}
    ImGui::SetNextWindowPos({0,24});ImGui::SetNextWindowSize({static_cast<float>(width),48});ImGui::Begin("Toolbar",nullptr,ImGuiWindowFlags_NoDecoration|ImGuiWindowFlags_NoDocking|ImGuiWindowFlags_NoSavedSettings);
    if(ImGui::Button("Save Scene"))action(editor,[&]{editor.save(editor.path);});ImGui::SameLine();if(ImGui::Button(editor.preview.active()?"Stop":"Play"))action(editor,[&]{if(editor.preview.active())editor.stop();else editor.play();});ImGui::SameLine();ImGui::BeginDisabled(!editor.preview.active());if(ImGui::Button(editor.paused?"Resume":"Pause"))editor.paused=!editor.paused;ImGui::EndDisabled();ImGui::SameLine();if(ImGui::Button("Step"))action(editor,[&]{editor.step();});ImGui::SameLine();if(ImGui::Button("Reload Scripts"))action(editor,[&]{editor.reload_scripts();});ImGui::SameLine();if(ImGui::Button("Reload Model"))reload_model=true;ImGui::SameLine();if(ImGui::Button("Reload Shaders"))reload_shader=true;ImGui::SameLine();ImGui::Text("TestScene%s  |  revision %llu",editor.document->dirty()?" *":"",static_cast<unsigned long long>(editor.document->revision()));ImGui::End();
    ImGui::SetNextWindowPos({0,72});ImGui::SetNextWindowSize({static_cast<float>(width),static_cast<float>(height)-72});ImGui::PushStyleVar(ImGuiStyleVar_WindowPadding,{0,0});ImGui::Begin("Workspace",nullptr,ImGuiWindowFlags_NoDecoration|ImGuiWindowFlags_NoDocking|ImGuiWindowFlags_NoBackground);auto dock=ImGui::GetID("DarkAngelWorkspace");ImGui::DockSpace(dock,{0,0},ImGuiDockNodeFlags_PassthruCentralNode);ImGui::End();ImGui::PopStyleVar();
    if(!docked){ImGui::DockBuilderRemoveNode(dock);ImGui::DockBuilderAddNode(dock,ImGuiDockNodeFlags_DockSpace);ImGui::DockBuilderSetNodeSize(dock,{static_cast<float>(width),static_cast<float>(height)-72});auto center=dock;auto left=ImGui::DockBuilderSplitNode(center,ImGuiDir_Left,.18f,nullptr,&center);auto right=ImGui::DockBuilderSplitNode(center,ImGuiDir_Right,.28f,nullptr,&center);auto bottom=ImGui::DockBuilderSplitNode(center,ImGuiDir_Down,.28f,nullptr,&center);auto content=ImGui::DockBuilderSplitNode(bottom,ImGuiDir_Left,.38f,nullptr,&bottom);auto phases=ImGui::DockBuilderSplitNode(bottom,ImGuiDir_Right,.35f,nullptr,&bottom);ImGui::DockBuilderDockWindow("World Outliner",left);ImGui::DockBuilderDockWindow("Inspector",right);ImGui::DockBuilderDockWindow("Viewport",center);ImGui::DockBuilderDockWindow("Content Browser",content);ImGui::DockBuilderDockWindow("Console",bottom);ImGui::DockBuilderDockWindow("Runtime Phases",phases);ImGui::DockBuilderFinish(dock);docked=true;}
    ImGui::Begin("World Outliner");ImGui::InputTextWithHint("##filter","Search objects...",filter,sizeof(filter));ImGui::TextDisabled("Scene placements");for(const auto& origin:editor.document->plan().origins){if(filter[0] && origin.name.find(filter)==std::string::npos)continue;ImGui::PushID(origin.object.text().c_str());if(ImGui::Selectable((origin.name+"##object").c_str(),editor.selected==origin.object))editor.selected=origin.object;ImGui::TextDisabled("%s",origin.object.text().substr(24).c_str());ImGui::PopID();}ImGui::End();
    ImGui::Begin("Inspector");auto handle=editor.displayed().find(editor.selected);if(editor.displayed().valid(handle)){auto object=editor.displayed().read(handle);ImGui::TextDisabled("Persistent object ID");ImGui::Text("%s",object.id.text().substr(0,16).c_str());ImGui::Text("%s",object.id.text().substr(16).c_str());ImGui::Text("World %llu | epoch %llu",handle.domain,handle.epoch);ImGui::Text("Handle %llu | valid",handle.runtime);int destination=scope==EditScope::Definition?1:0;const char* destinations[]={"Scene placement","Assembly definition"};if(ImGui::Combo("Edit destination",&destination,destinations,2))scope=destination?EditScope::Definition:EditScope::Placement;ImGui::BeginDisabled(editor.preview.active()!=nullptr || dragging);
        for(const auto& type:metadata())if(type.id<=2 && ImGui::CollapsingHeader(std::string(type.name).c_str(),ImGuiTreeNodeFlags_DefaultOpen)){ImGui::TextDisabled("TypeId %u | schema %u",type.id,type.version);for(const auto& field:type.properties)if(field.flags&Editable){auto value=property(object,type.id,field);ImGui::PushID(static_cast<int>(type.id*100+field.id));if(ImGui::InputDouble(std::string(field.name).c_str(),&value,.1,1,"%.3f"))action(editor,[&]{PropertyChange change{object.id,type.id,field.id,value};auto prepared=editor.document->prepare(editor.document->revision(),{&change,1},scope);editor.document->commit(prepared);editor.log(prepared.summary);});ImGui::PopID();}}
        if(ImGui::Button("Undo"))action(editor,[&]{editor.document->undo(editor.document->revision());});ImGui::SameLine();if(ImGui::Button("Redo"))action(editor,[&]{editor.document->redo(editor.document->revision());});ImGui::EndDisabled();
        if(ImGui::CollapsingHeader("Script Bindings",ImGuiTreeNodeFlags_DefaultOpen))for(const auto& binding:object.scripts.records){ImGui::TextWrapped("Attachment %s",binding.id.text().c_str());ImGui::TextWrapped("Asset %s",asset_id(binding.asset).text().c_str());ImGui::TextUnformatted(binding.config_json.c_str());if(editor.preview.active())for(const auto& info:editor.preview.active()->scripts->bindings())if(info.id==binding.id){ImGui::Text("%s | generation %llu",info.enabled?"Enabled":"Disabled",info.generation);ImGui::Text("Calls %llu | last %llu us",info.metrics.calls,info.metrics.last_microseconds);}}
        if(ImGui::CollapsingHeader("Provenance"))for(const auto& origin:editor.document->plan().origins)if(origin.object==object.id){ImGui::TextWrapped("Definition %s",origin.definition.text().c_str());ImGui::TextWrapped("Stable local path %s",origin.local_path.c_str());ImGui::TextWrapped("%s",origin.layer.c_str());}
    }else ImGui::TextDisabled("Select a scene object.");ImGui::End();
    ImGui::Begin("Content Browser");ImGui::TextDisabled("Cooked static model");ImGui::TextWrapped("%s",editor.model.text().c_str());ImGui::Text("Resource generation %llu",generation);if(ImGui::Button("Edit Spinner source")){action(editor,[&]{auto data=nlohmann::json::parse(editor.document->source(AssetId::parse("33333333-3333-4333-8333-333333333333")));strncpy_s(script,data.at("source").get<std::string>().c_str(),_TRUNCATE);show_script=true;});}ImGui::TextDisabled("Source edits use native transactions.");ImGui::End();
    if(show_script){ImGui::Begin("Spinner Script",&show_script);ImGui::InputTextMultiline("##source",script,sizeof(script),{-1,300});if(ImGui::Button("Apply source"))action(editor,[&]{auto asset=AssetId::parse("33333333-3333-4333-8333-333333333333");auto source=nlohmann::json::parse(editor.document->source(asset));source["source"]=script;auto transaction=editor.document->prepare_source(editor.document->revision(),asset,source.dump());editor.document->commit(transaction);editor.log("Source saved in authoring memory. Reload Scripts validates/activates it.");});ImGui::End();}
    ImGui::Begin("Console");for(const auto& line:editor.console)ImGui::TextWrapped("%s",line.c_str());ImGui::End();ImGui::Begin("Runtime Phases");ImGui::Text("Frame %.2f ms",seconds*1000);ImGui::TextUnformatted("Idle > Script > Commit > Publish");ImGui::TextDisabled("Structural writes merge at Commit.");if(editor.preview.active()){auto& runtime=*editor.preview.active()->scripts;ImGui::Text("Bindings %u | tasks %u",static_cast<unsigned>(runtime.instance_count()),static_cast<unsigned>(runtime.tasks().size()));ImGui::Text("VM %.1f KiB",runtime.memory_bytes()/1024.);auto error=runtime.diagnostic();if(!error.empty())ImGui::TextWrapped("%s",error.c_str());}else ImGui::TextDisabled("Authoring world idle; scripts stopped.");ImGui::End();
    ImGui::Begin("Viewport");const char* modes[]={"Move","Rotate","Scale"};ImGui::SetNextItemWidth(100);ImGui::Combo("##gizmo",&operation,modes,3);ImGui::SameLine();ImGui::TextDisabled("%s | metres | RH Y-up",backend);auto pos=ImGui::GetCursorScreenPos(),size=ImGui::GetContentRegionAvail();size.x=std::max(size.x,1.f);size.y=std::max(size.y,1.f);area={pos.x,pos.y,size.x,size.y};viewport_draw=ImGui::GetWindowDrawList();ImGui::Image(scene_texture,size);ImGui::End();return area;
}
void Shell::gizmo(Controller& editor,const DirectX::XMFLOAT4X4& view,const DirectX::XMFLOAT4X4& projection){if(editor.preview.active())return;auto handle=editor.document->world().find(editor.selected);if(!editor.document->world().valid(handle))return;auto pose=draft?*draft:editor.document->world().read(handle).transform;using namespace DirectX;XMFLOAT4X4 matrix;XMStoreFloat4x4(&matrix,XMMatrixScaling(pose.scale,pose.scale,pose.scale)*XMMatrixRotationRollPitchYaw(pose.pitch,pose.yaw,pose.roll)*XMMatrixTranslation(pose.x,pose.y,pose.z));ImGuizmo::SetDrawlist(viewport_draw);ImGuizmo::SetRect(area.x,area.y,area.width,area.height);auto op=operation==1?ImGuizmo::ROTATE:operation==2?ImGuizmo::SCALEU:ImGuizmo::TRANSLATE;ImGuizmo::Manipulate(&view._11,&projection._11,op,ImGuizmo::LOCAL,&matrix._11);
    bool using_gizmo=ImGuizmo::IsUsing();if(using_gizmo && !dragging){gesture_object=editor.selected;gesture_revision=editor.document->revision();dragging=true;cancelled=false;}
    if(using_gizmo){float position[3],rotation[3],scale[3];ImGuizmo::DecomposeMatrixToComponents(&matrix._11,position,rotation,scale);pose.x=position[0];pose.y=position[1];pose.z=position[2];pose.pitch=rotation[0]*XM_PI/180;pose.yaw=rotation[1]*XM_PI/180;pose.roll=rotation[2]*XM_PI/180;pose.scale=scale[0];if(!cancelled)draft=pose;else draft.reset();if(ImGui::IsKeyPressed(ImGuiKey_Escape)){cancelled=true;draft.reset();}}
    if(dragging && !using_gizmo){if(!cancelled && draft)action(editor,[&]{auto value=*draft;PropertyChange changes[]={{gesture_object,1,1,value.yaw},{gesture_object,1,2,value.x},{gesture_object,1,3,value.y},{gesture_object,1,4,value.z},{gesture_object,1,5,value.pitch},{gesture_object,1,6,value.roll},{gesture_object,1,7,value.scale}};auto transaction=editor.document->prepare(gesture_revision,changes,scope);editor.document->commit(transaction);editor.log("Committed one transform gesture.");});draft.reset();dragging=false;}
}
}
