#include "editor_ui.hpp"
#include "editor_theme.hpp"
#include <imgui_internal.h>
#include <nlohmann/json.hpp>
#include <algorithm>
#include <darkangel/hash.hpp>
namespace darkangel::editor_app {
namespace {
template<class F>void perform(Controller& editor,F call){try{call();}catch(const std::exception& error){editor.log(error.what(),ConsoleSeverity::Error);}}
const char* edge_name(InputEdge edge){switch(edge){case InputEdge::Pressed:return "Pressed";case InputEdge::Hold:return "Hold";case InputEdge::Released:return "Released";case InputEdge::Tapped:return "Tapped";}return "Unknown";}
}
void Shell::open_native_asset(Controller& editor,AssetId id){
 if(!editor.assets||id==AssetId{})throw std::runtime_error("Choose a native authoring asset");auto& draft=editor.authoring.open(*editor.assets,id);auto kind=draft.value.at("kind").get<std::string>();
 if(kind!="character"&&kind!="player"&&kind!="input"&&kind!="combat_kit"&&kind!="action"&&kind!="graph"&&kind!="ability"&&kind!="effect"&&kind!="attributes")throw std::runtime_error("No native authoring workflow for this asset type");
 if(kind=="character"){character_selection=id;select_workspace(Workspace::Character);}else if(kind=="player"){player_selection=id;select_workspace(Workspace::Player);}else if(kind=="input"){input_authoring_asset=id;open_tool(ToolView::InputBindings);}else{authored_selection=id;if(kind=="combat_kit")editor.authoring_kit=id;select_workspace(kind=="action"||kind=="graph"?Workspace::Animation:Workspace::Ability);}author_diagnostic.clear();
}
void Shell::select_workspace(Workspace target){if(workspace!=target){composer_playing=false;controls_focus=false;controls_acquired=false;forward=lateral=turn=0;walk=jump=false;workspace=target;}}
void Shell::open_tool(ToolView selected){if(workspace!=Workspace::Tools&&workspace!=Workspace::Settings)previous_workspace=workspace;tool=selected;select_workspace(Workspace::Tools);}
void Shell::draw_console(Controller& editor){for(const auto& line:editor.console){bool error=line.severity==ConsoleSeverity::Error,warning=line.severity==ConsoleSeverity::Warning;icon_text(error?Icon::Error:warning?Icon::Warning:Icon::Info,error?"Error":warning?"Warning":"Info");ImGui::SameLine();ImGui::TextWrapped("%s",line.message.c_str());}}
void Shell::draw_game(Controller& editor,unsigned width,unsigned height,float top,double seconds,ImTextureID image){
    ImGui::SetNextWindowPos({0,top});ImGui::SetNextWindowSize({float(width),float(height)-top});ImGui::PushStyleVar(ImGuiStyleVar_WindowPadding,{0,0});ImGui::Begin("Game dockspace",nullptr,ImGuiWindowFlags_NoDecoration|ImGuiWindowFlags_NoDocking|ImGuiWindowFlags_NoBackground);auto dock=ImHashStr("DarkAngelGameDock");ImGui::DockSpace(dock,{0,0},ImGuiDockNodeFlags_PassthruCentralNode);ImGui::End();ImGui::PopStyleVar();
    if(!game_docked){ImGui::DockBuilderRemoveNode(dock);ImGui::DockBuilderAddNode(dock,ImGuiDockNodeFlags_DockSpace);ImGui::DockBuilderSetNodeSize(dock,{float(width),float(height)-top});auto center=dock;auto right=ImGui::DockBuilderSplitNode(center,ImGuiDir_Right,.28f,nullptr,&center);auto console=ImGui::DockBuilderSplitNode(center,ImGuiDir_Down,.22f,nullptr,&center);auto input_dock=ImGui::DockBuilderSplitNode(right,ImGuiDir_Down,.35f,nullptr,&right);ImGui::DockBuilderDockWindow("Game Viewport",center);ImGui::DockBuilderDockWindow("Game Profiler",right);ImGui::DockBuilderDockWindow("Gameplay Inspector",right);ImGui::DockBuilderDockWindow("Input Monitor",input_dock);ImGui::DockBuilderDockWindow("Game Console",console);ImGui::DockBuilderFinish(dock);game_docked=true;}
    ImGui::Begin("Game Viewport");const bool playing=editor.preview.active()!=nullptr;if(playing){ImGui::PushStyleColor(ImGuiCol_Button,{.53f,.28f,.10f,1});ImGui::PushStyleColor(ImGuiCol_ButtonHovered,attention);}if(icon_button(playing?Icon::Stop:Icon::Play,playing?"Stop":"Play"))perform(editor,[&]{if(playing)editor.stop();else editor.play();});if(playing)ImGui::PopStyleColor(2);ImGui::SameLine();ImGui::BeginDisabled(!editor.preview.active());if(icon_button(editor.paused?Icon::Play:Icon::Pause,editor.paused?"Resume":"Pause"))editor.paused=!editor.paused;ImGui::EndDisabled();ImGui::SameLine();if(icon_button(Icon::Step,"Step","Advance one simulation tick"))perform(editor,[&]{editor.step();});
    if(native_controls){ImGui::SameLine();ImGui::TextDisabled(controls_focus?"Input active | Esc releases":"Click viewport to control");}
    auto pos=ImGui::GetCursorScreenPos(),size=ImGui::GetContentRegionAvail();size.x=std::max(1.f,size.x);size.y=std::max(1.f,size.y);area={pos.x,pos.y,size.x,size.y};ImGui::Image(image,size);
    if(!editor.preview.active()||editor.paused||ImGui::IsKeyPressed(ImGuiKey_Escape)||ImGui::IsPopupOpen(nullptr,ImGuiPopupFlags_AnyPopupId))controls_focus=false;
    if(native_controls&&!controls_focus&&editor.preview.active()&&!editor.paused&&ImGui::IsItemHovered()&&ImGui::IsMouseClicked(ImGuiMouseButton_Left)){controls_focus=true;controls_acquired=true;}
    if(!ImGui::IsWindowFocused()||ImGui::GetIO().WantTextInput)controls_focus=false;ImGui::End();
    frame_ms.push_back(float(std::max(0.,seconds)*1000));if(frame_ms.size()>120)frame_ms.erase(frame_ms.begin());
    ImGui::Begin("Game Profiler");ImGui::Text("Frame interval %.2f ms",seconds*1000);ImGui::PlotLines("##frame interval",frame_ms.data(),static_cast<int>(frame_ms.size()),0,nullptr,0,std::max(20.f,*std::max_element(frame_ms.begin(),frame_ms.end())),{0,70});ImGui::TextDisabled("Last 120 rendered frame intervals");if(gameplay_metrics)ImGui::TextWrapped("%s",gameplay_metrics().c_str());else ImGui::TextDisabled("No character session active");ImGui::Text("Input evaluation %.1f us",input_processing_us);ImGui::Text("Recent input edges: %u",static_cast<unsigned>(input_events.size()));ImGui::End();
    if(focus_gameplay_inspector){ImGui::SetNextWindowFocus();focus_gameplay_inspector=false;}ImGui::Begin("Gameplay Inspector");if(draw_gameplay_inspector)perform(editor,[&]{draw_gameplay_inspector();});else ImGui::TextDisabled("Start Play to inspect gameplay state.");ImGui::End();
    ImGui::Begin("Input Monitor");if(input){for(const auto& action:input->profile().actions){auto state=input->state(action.id);if(state.down)ImGui::Text("%s %.2f | %.0f ms",action.name.c_str(),state.value,double(state.held_us)/1000);}ImGui::Separator();for(auto it=input_events.rbegin();it!=input_events.rend();++it){auto definition=std::find_if(input->profile().actions.begin(),input->profile().actions.end(),[&](const auto& action){return action.id==it->action;});auto name=definition==input->profile().actions.end()?"Previous profile":definition->name.c_str();ImGui::TextWrapped("%s: %s%s",name,edge_name(it->edge),it->cancelled?" (cancelled)":"");}}else ImGui::TextWrapped("No input profile in the cooked package.");ImGui::End();
    ImGui::Begin("Game Console");draw_console(editor);ImGui::End();
}
void Shell::draw_auxiliary(Controller& editor,unsigned width,unsigned height,float top){
    ImGui::SetNextWindowPos({0,top});ImGui::SetNextWindowSize({float(width),float(height)-top});ImGui::Begin(workspace==Workspace::Settings?"Settings workspace":"Tools workspace",nullptr,ImGuiWindowFlags_NoDecoration|ImGuiWindowFlags_NoDocking|ImGuiWindowFlags_NoSavedSettings);if(ImGui::Button("Back to workspace"))select_workspace(previous_workspace);ImGui::Separator();
    if(workspace==Workspace::Settings){ImGui::TextUnformatted(project_settings?"Project settings":"Editor settings");ImGui::TextDisabled("Settings will be added here as their systems are designed.");}
    else if(tool==ToolView::Console){ImGui::TextUnformatted("Console");draw_console(editor);}
    else if(tool==ToolView::ScriptSource){ImGui::TextUnformatted("Script Source");if(show_script){ImGui::InputTextMultiline("##source",script,sizeof(script),{-1,300});ImGui::BeginDisabled(editor.preview.active()!=nullptr);if(ImGui::Button("Apply source"))perform(editor,[&]{auto source=nlohmann::json::parse(editor.document->source(script_asset));source["source"]=script;auto transaction=editor.document->prepare_source(editor.document->revision(),script_asset,source.dump());editor.document->commit(transaction);editor.log("Source updated. Reload Scripts validates and activates it.");});ImGui::EndDisabled();}else ImGui::TextDisabled("Select a script in the Scene Content Browser.");}
    else if(tool==ToolView::RuntimePhases){ImGui::TextUnformatted("Runtime phases");ImGui::TextWrapped("Idle > Script > Commit > Publish");if(editor.preview.active()){auto& runtime=*editor.preview.active()->scripts;ImGui::Text("Bindings %u | Tasks %u",static_cast<unsigned>(runtime.instance_count()),static_cast<unsigned>(runtime.tasks().size()));ImGui::Text("VM %.1f KiB",runtime.memory_bytes()/1024.);ImGui::TextWrapped("%s",runtime.diagnostic().c_str());}else ImGui::TextDisabled("Authoring idle; scripts stopped.");}
    else if(tool==ToolView::AuthoringHistory){draw_authoring_history(editor);}
    else if(editor.assets){draw_input_authoring(editor);}
    else{ImGui::TextUnformatted("Input bindings");if(input){ImGui::TextWrapped("Profile %s",input->profile().id.text().c_str());ImGui::TextDisabled("Bindings come from the cooked project input profile.");if(ImGui::BeginTable("Bindings",3,ImGuiTableFlags_RowBg|ImGuiTableFlags_ScrollY,{0,ImGui::GetContentRegionAvail().y})){ImGui::TableSetupColumn("Action");ImGui::TableSetupColumn("Controls");ImGui::TableSetupColumn("Consumption",ImGuiTableColumnFlags_WidthFixed,130);ImGui::TableHeadersRow();for(const auto& binding:input->profile().bindings){ImGui::TableNextRow();ImGui::TableNextColumn();auto action=std::find_if(input->profile().actions.begin(),input->profile().actions.end(),[&](const auto& a){return a.id==binding.action;});ImGui::TextUnformatted(action->name.c_str());ImGui::TableNextColumn();std::string label;for(auto control:binding.controls){if(!label.empty())label+=" + ";label+=input_control_name(control);}ImGui::TextWrapped("%s",label.c_str());ImGui::TableNextColumn();ImGui::TextUnformatted(binding.consumption==InputConsumption::All?"All controls":binding.consumption==InputConsumption::Trigger?"Trigger":"None");}ImGui::EndTable();}}else ImGui::TextDisabled("No input profile in the cooked package.");}
    ImGui::End();
}
void Shell::draw_authoring_history(Controller& c){
 ImGui::BeginChild("Authoring history",{0,0});ImGui::TextUnformatted("Shared native authoring history");ImGui::TextWrapped("Commands are newest first. Undo/Redo changes drafts; Save publishes validated sources. Pending creation can be undone before Save. Published assets are retained; creation entries leave Undo after publication. Scene transactions have their own history.");
 if(!c.assets){ImGui::TextDisabled("Open project sources to inspect authoring history.");ImGui::EndChild();return;}
 auto run=[&](auto operation){try{operation();author_diagnostic.clear();}catch(const std::exception& error){author_diagnostic=error.what();c.log(author_diagnostic,ConsoleSeverity::Error);}};if(!author_diagnostic.empty())ImGui::TextWrapped("Needs attention: %s",author_diagnostic.c_str());
 ImGui::BeginDisabled(c.preview.active()!=nullptr);ImGui::BeginDisabled(!c.authoring.can_undo());if(ImGui::Button("Undo latest command"))run([&]{c.authoring.undo(*c.assets);c.refresh_assets();});ImGui::EndDisabled();ImGui::SameLine();ImGui::BeginDisabled(!c.authoring.can_redo());if(ImGui::Button("Redo next command"))run([&]{c.authoring.redo(*c.assets);c.refresh_assets();});ImGui::EndDisabled();ImGui::SameLine();if(ImGui::Button("Save pending changes"))run([&]{c.save_gameplay();c.refresh_assets();});ImGui::EndDisabled();
 auto navigate=[&](AssetId id){run([&]{open_native_asset(c,id);});};
 if(ImGui::CollapsingHeader("Open sources / pending changes",ImGuiTreeNodeFlags_DefaultOpen)){auto inventory=c.assets->assets();for(const auto& [id,draft]:c.authoring.drafts){ImGui::PushID(id.text().c_str());if(ImGui::SmallButton(draft.asset.path.c_str()))navigate(id);ImGui::SameLine();ImGui::TextDisabled(draft.pending?"New / not published":draft.dirty()?"Pending Save":"Saved");auto latest=std::find_if(inventory.begin(),inventory.end(),[&](const auto& asset){return asset.id==id;});if(ImGui::IsItemHovered()){ImGui::BeginTooltip();ImGui::Text("UUID: %s",id.text().c_str());if(latest!=inventory.end())ImGui::Text("Catalog generation: %llu",latest->generation);ImGui::TextWrapped(draft.pending?"Creation base SHA: %s":"Saved source SHA: %s",sha256(draft.saved).c_str());ImGui::EndTooltip();}ImGui::PopID();}}
 for(bool redo:{false,true}){ImGui::PushID(redo?1:0);auto history=c.authoring.history(redo);ImGui::SeparatorText(redo?"Redo branch":"Undo history");if(history.empty())ImGui::TextDisabled("Empty");for(unsigned i=0;i<history.size();++i){ImGui::PushID(i);auto label=history[i].label+" / "+std::to_string(history[i].assets.size())+" sources";ImGui::SetNextItemOpen(i==0,ImGuiCond_Once);if(ImGui::TreeNode(label.c_str())){for(auto id:history[i].assets){auto found=c.authoring.drafts.find(id);if(found!=c.authoring.drafts.end()){ImGui::PushID(id.text().c_str());if(ImGui::SmallButton(found->second.asset.path.c_str()))navigate(id);ImGui::PopID();}}auto changes=c.authoring.history_changes(redo,i);for(const auto& change:changes)ImGui::TextWrapped("%s %s = %s",change.operation.c_str(),change.path.c_str(),change.value.c_str());if(changes.size()==128)ImGui::TextDisabled("Change preview limited to128 entries.");ImGui::TreePop();}ImGui::PopID();}ImGui::PopID();}
 ImGui::EndChild();
}

}
