#include "editor_ui.hpp"
#include "editor_theme.hpp"
#include <algorithm>
#include <fstream>
namespace darkangel::editor_app {
namespace {
using Json=nlohmann::json;
bool number(const char* label,Json& v){double n=v.get<double>();if(!ImGui::InputDouble(label,&n,0,0,"%.3f"))return false;v=n;return true;}
bool integer(const char* label,Json& v){int n=v.get<int>();if(!ImGui::InputInt(label,&n))return false;v=n;return true;}
void flag(const char* label,Json& v){bool n=v.get<bool>();if(ImGui::Checkbox(label,&n))v=n;}
void choice(const char* label,Json& v,std::initializer_list<const char*> choices){auto name=v.get<std::string>();if(ImGui::BeginCombo(label,name.c_str())){for(auto c:choices)if(ImGui::Selectable(c,name==c))v=c;ImGui::EndCombo();}}
void text(const char* label,Json& v){char buffer[129]{};auto s=v.get<std::string>();strncpy_s(buffer,s.c_str(),_TRUNCATE);if(ImGui::InputText(label,buffer,sizeof(buffer)))v=buffer;}
Json schema(Controller& c,const Json& v,const char* key){if(!v.contains("sources")||!v["sources"].contains(key))return Json::array();std::ifstream f(c.assets->source_root()/v["sources"][key].get<std::string>());return Json::parse(f).at(key);}
void ids(const char* label,Json& list,const Json& definitions){if(ImGui::TreeNode(label)){for(const auto& d:definitions){auto id=d["id"];auto it=std::find(list.begin(),list.end(),id);bool selected=it!=list.end();if(ImGui::Checkbox(d["name"].get<std::string>().c_str(),&selected)){if(selected)list.push_back(id);else list.erase(it);}}ImGui::TreePop();}}
void attribute(const char* label,Json& value,const Json& defs){std::string current="Choose attribute";for(const auto& d:defs)if(d["id"]==value)current=d["name"];if(ImGui::BeginCombo(label,current.c_str())){for(const auto& d:defs)if(ImGui::Selectable(d["name"].get<std::string>().c_str(),d["id"]==value))value=d["id"];ImGui::EndCombo();}}
bool picker(const char* label,AssetId& selected,Controller& c,const char* extension,const Json* attributes=nullptr){std::string name="Choose asset";for(const auto& a:c.asset_inventory)if(a.id==selected)name=std::filesystem::path(a.path).stem().string();bool changed=false;if(ImGui::BeginCombo(label,name.c_str())){for(const auto& a:c.asset_inventory){if(std::filesystem::path(a.path).extension()!=extension)continue;if(std::string_view(extension)==".glb"){std::ifstream meta(c.assets->source_root()/(a.path+".daimport"));if(!meta||Json::parse(meta).value("importer","")!="clip-gltf-v1")continue;}if(attributes){std::ifstream f(c.assets->source_root()/a.path);auto v=Json::parse(f);if(!v.contains("attributes")||v["attributes"]!=*attributes)continue;}ImGui::PushID(a.id.text().c_str());if(ImGui::Selectable(std::filesystem::path(a.path).stem().string().c_str(),selected==a.id)){selected=a.id;changed=true;}ImGui::PopID();}ImGui::EndCombo();}return changed;}
}
void Shell::draw_authoring(Controller& c,unsigned width,unsigned height,float top){
 ImGui::SetNextWindowPos({0,top});ImGui::SetNextWindowSize({float(width),float(height)-top});ImGui::Begin("Ability workspace",nullptr,ImGuiWindowFlags_NoDecoration|ImGuiWindowFlags_NoDocking|ImGuiWindowFlags_NoSavedSettings);
 if(!c.assets){ImGui::TextWrapped("Open a project source mount to author gameplay assets.");ImGui::End();return;}
 auto perform=[&](auto f){try{f();}catch(const std::exception& e){if(author_diagnostic!=e.what())c.log(e.what(),ConsoleSeverity::Error);author_diagnostic=e.what();}};
 ImGui::BeginDisabled(c.preview.active()!=nullptr);if(ImGui::Button("Save gameplay changes"))perform([&]{author_diagnostic.clear();c.authoring.save_all(*c.assets);c.refresh_assets();c.log("Saved gameplay sources. Next Play prepares the complete scene and combat kit.");});ImGui::SameLine();ImGui::TextDisabled(c.authoring.dirty()?"Unsaved gameplay changes":"Gameplay saved");ImGui::EndDisabled();if(c.preview.active())ImGui::TextWrapped("Stop in Game to edit abilities and effects.");if(!author_diagnostic.empty())ImGui::TextWrapped("Needs attention: %s",author_diagnostic.c_str());
 if(ImGui::BeginTable("Authoring panels",3,ImGuiTableFlags_Resizable|ImGuiTableFlags_BordersInnerV)){ImGui::TableSetupColumn("Gameplay assets",ImGuiTableColumnFlags_WidthFixed,240);ImGui::TableSetupColumn("Ability / Effect");ImGui::TableSetupColumn("Combat kit",ImGuiTableColumnFlags_WidthFixed,330);ImGui::TableHeadersRow();ImGui::TableNextRow();ImGui::TableNextColumn();
 ImGui::BeginChild("Gameplay browser",{0,0});ImGui::InputTextWithHint("##authorsearch","Search gameplay...",asset_filter,sizeof(asset_filter));if(ImGui::Button("Refresh"))perform([&]{c.refresh_assets();});for(const auto& a:c.asset_inventory){auto ext=std::filesystem::path(a.path).extension();if(ext!=".daability"&&ext!=".daeffect"&&ext!=".daaction")continue;auto name=std::filesystem::path(a.path).filename().string();if(asset_filter[0]&&name.find(asset_filter)==name.npos)continue;ImGui::PushID(a.id.text().c_str());if(ImGui::Selectable(name.c_str(),authored_selection==a.id))perform([&]{c.authoring.open(*c.assets,a.id);authored_selection=a.id;});ImGui::PopID();}ImGui::EndChild();ImGui::TableNextColumn();ImGui::BeginChild("Gameplay properties",{0,0});ImGui::PushItemWidth(-140.f);ImGui::BeginDisabled(c.preview.active()!=nullptr);
 if(authored_selection!=AssetId{})perform([&]{auto& draft=c.authoring.open(*c.assets,authored_selection);auto& v=draft.value;ImGui::TextUnformatted(std::filesystem::path(draft.asset.path).stem().string().c_str());ImGui::InputText("New name",author_name,sizeof(author_name));if(ImGui::Button("Create from template")){authored_selection=c.authoring.duplicate(*c.assets,authored_selection,author_name,true);c.refresh_assets();return;}ImGui::SameLine();if(ImGui::Button("Duplicate")){authored_selection=c.authoring.duplicate(*c.assets,authored_selection,author_name);c.refresh_assets();return;}if(ImGui::Button("Revert draft")){v=Json::parse(draft.saved);}ImGui::SameLine();if(ImGui::Button("Reload source")){c.authoring.drafts.erase(authored_selection);c.authoring.open(*c.assets,authored_selection);return;}
 ImGui::TextDisabled("60 gameplay ticks = 1 second");auto kind=v["kind"].get<std::string>();
 if(kind=="ability"){auto attrs=schema(c,v,"attributes");AssetId action=AssetId::parse(v["action"].get<std::string>());if(picker("Action",action,c,".daaction")){v["action"]=action.text();for(const auto& a:c.asset_inventory)if(a.id==action)v["sources"]["action"]=a.path;}if(ImGui::Button("Edit action timeline")){c.authoring.open(*c.assets,action);authored_selection=action;return;}ImGui::SeparatorText("Costs and activation");for(unsigned i=0;i<v["costs"].size();++i){ImGui::PushID(i);auto& cost=v["costs"][i];attribute("Resource",cost["attribute"],attrs);number("Cost",cost["amount"]);if(ImGui::Button("Remove cost")){v["costs"].erase(i);ImGui::PopID();break;}ImGui::PopID();}if(ImGui::Button("Add cost")&&v["costs"].size()<8)v["costs"].push_back({{"attribute",3},{"amount",10}});integer("Cooldown ticks",v["cooldown_ticks"]);integer("Cooldown group",v["cooldown_group"]);choice("Activate on",v["activate_on"],{"pressed","hold","released","tapped"});integer("Minimum held us",v["minimum_held_us"]);flag("Cancel on release",v["cancel_on_release"]);flag("Interruptible",v["interruptible"]);
 ImGui::SeparatorText("Melee hit windows");for(auto& hit:v["melee"]){ImGui::PushID(hit["block"].get<int>());ImGui::Text("Hit window %u",hit["block"].get<unsigned>());number("Damage",hit["power"]);number("Radius",hit["radius"]);for(unsigned j=0;j<3;++j){ImGui::PushID(j);number(j==0?"Offset X":j==1?"Offset Y":"Offset Z",hit["offset"][j]);ImGui::PopID();}ImGui::PopID();}if(v.contains("requirements")){auto tags=schema(c,v,"tags");for(const char* key:{"all","any","none"})ids(key,v["requirements"][key],tags);}}
 if(kind=="effect"){auto attrs=schema(c,v,"attributes"),tags=schema(c,v,"tags");choice("Lifetime",v["lifetime"],{"instant","finite","until_removed"});integer("Duration ticks",v["duration_ticks"]);integer("Period ticks",v["period_ticks"]);choice("Stacking",v["stacking"],{"independent","refresh_per_source"});flag("Execute on apply",v["execute_on_apply"]);flag("Remove on death",v["remove_on_death"]);flag("Remove with source",v["remove_with_source"]);flag("Interrupt action",v["interrupt_action"]);int execution=v["evaluator"].get<int>()==2?1:0;const char* executions[]={"Modifiers / status only","Health damage (Ashen Roots)"};if(ImGui::Combo("Execution",&execution,executions,2))v["evaluator"]=execution?2:0;choice("Visibility",v["visibility"],{"public","owner","server"});ids("Granted status tags",v["granted_tags"],tags);ImGui::TextDisabled("Tag definitions require a rebuilt native consumer.");for(const char* group:{"application","ongoing"})if(ImGui::TreeNode(group)){for(const char* key:{"all","any","none"})ids(key,v[group][key],tags);ImGui::TreePop();}choice("Ongoing policy",v["ongoing_policy"],{"suppress","remove"});
 ImGui::SeparatorText("Attribute modifiers");for(unsigned i=0;i<v["modifiers"].size();++i){ImGui::PushID(i);auto& m=v["modifiers"][i];attribute("Attribute",m["attribute"],attrs);choice("Modifier",m["kind"],{"flat","channel_bonus","post","override"});number("Magnitude",m["magnitude"]);text("Channel",m["channel"]);integer("Priority",m["priority"]);if(ImGui::Button("Remove modifier")){v["modifiers"].erase(i);ImGui::PopID();break;}ImGui::PopID();}if(ImGui::Button("Add modifier")&&v["modifiers"].size()<16)v["modifiers"].push_back({{"attribute",6},{"kind","flat"},{"magnitude",0},{"channel",""},{"priority",0}});for(auto& cue:v["cues"])text("Status label",cue["key"]);if(v["cues"].empty()&&ImGui::Button("Add status label"))v["cues"].push_back({{"id",AssetId::random().text()},{"key","Status.New"}});}
 if(kind=="action"){ImGui::TextDisabled("Timeline ticks (60 per second)");double duration=v["duration"].get<double>()/1024;if(ImGui::InputDouble("Duration ticks",&duration))v["duration"]=static_cast<long long>(duration*1024);for(auto& b:v["blocks"]){ImGui::PushID(b["id"].get<int>());ImGui::Text("%s | %s",b["kind"].get<std::string>().c_str(),b["key"].get<std::string>().c_str());double begin=b["begin"].get<double>()/1024,end=b["end"].get<double>()/1024;if(ImGui::InputDouble("Begin tick",&begin))b["begin"]=static_cast<long long>(begin*1024);if(ImGui::InputDouble("End tick",&end))b["end"]=static_cast<long long>(end*1024);ImGui::PopID();}if(v.contains("motion")){AssetId clip=AssetId::parse(v["motion"]["clip"].get<std::string>());if(picker("Clip",clip,c,".glb")){v["motion"]["clip"]=clip.text();for(const auto& a:c.asset_inventory)if(a.id==clip)v["motion"]["source"]=a.path;}ImGui::TextWrapped("Clip and rig compatibility are validated on Save.");}}
 });else ImGui::TextWrapped("Select an ability, effect or action. Create starts from a compatible template; Duplicate preserves its authored settings.");ImGui::EndDisabled();ImGui::PopItemWidth();ImGui::EndChild();ImGui::TableNextColumn();ImGui::BeginChild("Kit composition",{0,0});ImGui::PushItemWidth(-110.f);ImGui::BeginDisabled(c.preview.active()!=nullptr);
 perform([&]{picker("Play kit",c.authoring_kit,c,".dakit");if(c.authoring_kit==AssetId{})return;auto& k=c.authoring.open(*c.assets,c.authoring_kit).value;for(unsigned i=0;i<k["slots"].size();++i){auto& slot=k["slots"][i];AssetId ability;if(!slot["ability"].is_null())ability=AssetId::parse(slot["ability"].get<std::string>());ImGui::PushID(i);if(picker(slot["slot"].get<std::string>().c_str(),ability,c,".daability",&k["attributes"]))c.authoring.assign(*c.assets,c.authoring_kit,i,ability);ImGui::PopID();}ImGui::SeparatorText("On-hit effects");picker("Ability",binding_ability,c,".daability",&k["attributes"]);picker("Effect",binding_effect,c,".daeffect",&k["attributes"]);if(binding_ability!=AssetId{}){auto& a=c.authoring.open(*c.assets,binding_ability).value;std::string current="Hit window "+std::to_string(binding_block);if(ImGui::BeginCombo("Hit window",current.c_str())){for(const auto& hit:a["melee"]){auto block=hit["block"].get<int>();auto label="Window "+std::to_string(block);if(ImGui::Selectable(label.c_str(),block==binding_block))binding_block=block;}ImGui::EndCombo();}}ImGui::InputDouble("Effect power",&binding_power);if(ImGui::Button("Bind effect")&&binding_ability!=AssetId{}&&binding_effect!=AssetId{})c.authoring.bind(*c.assets,c.authoring_kit,binding_ability,binding_block,binding_effect,binding_power);if(k.contains("effect_bindings"))for(unsigned i=0;i<k["effect_bindings"].size();++i){auto& b=k["effect_bindings"][i];ImGui::PushID(i);auto name=[&](const Json& id){for(const auto& a:c.asset_inventory)if(a.id.text()==id.get<std::string>())return std::filesystem::path(a.path).stem().string();return std::string("Missing asset");};ImGui::TextWrapped("%s / window %u > %s",name(b["ability"]).c_str(),b["hit_block"].get<unsigned>(),name(b["effect"]).c_str());number("Power",b["power"]);if(ImGui::Button("Remove binding")){k["effect_bindings"].erase(i);ImGui::PopID();break;}ImGui::PopID();}ImGui::TextWrapped("Save here, then enter Game and Play. Each Play prepares current scene and kit sources.");});ImGui::EndDisabled();ImGui::PopItemWidth();ImGui::EndChild();ImGui::EndTable();}ImGui::End();
}
}
