#include "native_authoring.hpp"
#include <darkangel/hash.hpp>
#include <fstream>
#include <set>
#include <algorithm>
#include <cctype>
namespace darkangel::editor_app {
namespace {void require(bool v,const char* m){if(!v)throw std::runtime_error(m);}std::string read(const std::filesystem::path& p){std::ifstream f(p,std::ios::binary);require(bool(f),"Cannot read native source");std::string s{std::istreambuf_iterator<char>(f),{}};require(s.size()<=65536,"Native draft size limit");return s;}}
NativeDraft& NativeAuthoring::open(AssetService& assets,AssetId id){if(auto i=drafts.find(id);i!=drafts.end())return i->second;auto inventory=assets.assets();auto found=std::find_if(inventory.begin(),inventory.end(),[&](const auto& a){return a.id==id;});require(found!=inventory.end(),"Native source is missing; refresh assets");auto ext=std::filesystem::path(found->path).extension();require(ext==".daability"||ext==".daeffect"||ext==".daaction"||ext==".dakit","Choose a native gameplay asset");auto bytes=read(assets.source_root()/found->path);return drafts.emplace(id,NativeDraft{*found,bytes,nlohmann::json::parse(bytes)}).first->second;}
CookResult NativeAuthoring::save(AssetService& assets,AssetId id){auto& d=open(assets,id);auto bytes=d.value.dump(2)+"\n";CookResult result;try{result=assets.edit_native(d.asset.path,sha256(d.saved),bytes);}catch(const std::exception& e){throw std::runtime_error(std::filesystem::path(d.asset.path).filename().string()+": "+e.what());}d.saved=bytes;d.asset.generation=result.generation;return result;}
AssetId NativeAuthoring::duplicate(AssetService& assets,AssetId id,std::string_view name,bool blank){auto& d=open(assets,id);require(!name.empty()&&name.size()<=64&&std::all_of(name.begin(),name.end(),[](unsigned char c){return std::isalnum(c)||c=='_'||c=='-';}),"Use a name with letters, numbers, underscores or hyphens");auto value=d.value;auto fresh=AssetId::random();value["asset"]=fresh.text();if(value.contains("cues"))for(auto& cue:value["cues"])cue["id"]=AssetId::random().text();if(blank&&value["kind"]=="effect"){value["evaluator"]=0;value["period_ticks"]=0;value["granted_tags"]=nlohmann::json::array();value["modifiers"]=nlohmann::json::array();value["cues"]=nlohmann::json::array();}if(blank&&value["kind"]=="ability"){value["costs"]=nlohmann::json::array();value["cooldown_ticks"]=0;for(auto& hit:value["melee"])hit["power"]=0;}
 auto path=std::filesystem::path(d.asset.path).parent_path()/(std::string(name)+std::filesystem::path(d.asset.path).extension().string());assets.create_native(path.generic_string(),value.dump(2)+"\n");open(assets,fresh);return fresh;}
void NativeAuthoring::assign(AssetService& assets,AssetId kit,std::size_t slot,AssetId ability){auto& k=open(assets,kit).value;auto& a=open(assets,ability);require(k["kind"]=="combat_kit"&&a.value["kind"]=="ability"&&slot<k["slots"].size(),"Select a kit slot and ability");require(k["attributes"]==a.value["attributes"],"Ability uses an incompatible attribute schema");auto old=k["slots"][slot]["ability"];k["slots"][slot]["ability"]=ability.text();k["sources"]["abilities"][ability.text()]=a.asset.path;
 bool retained=false;for(const auto& s:k["slots"])retained|=s["ability"]==old;if(!old.is_null()&&!retained){k["sources"]["abilities"].erase(old.get<std::string>());if(k.contains("effect_bindings")){auto& bindings=k["effect_bindings"];bindings.erase(std::remove_if(bindings.begin(),bindings.end(),[&](const auto& b){return b["ability"]==old;}),bindings.end());}}
}
void NativeAuthoring::bind(AssetService& assets,AssetId kit,AssetId ability,unsigned block,AssetId effect,double power){auto& k=open(assets,kit).value;auto& a=open(assets,ability).value;auto& e=open(assets,effect);require(e.value["kind"]=="effect"&&k["attributes"]==e.value["attributes"],"Effect uses an incompatible attribute schema");bool granted=false,hit=false;for(const auto& s:k["slots"])granted|=s["ability"]==ability.text();for(const auto& h:a["melee"])hit|=h["block"]==block;require(granted&&hit,"Assign ability to the kit and select its hit window first");auto& effects=k["effects"];if(effects.is_null())effects=nlohmann::json::array();if(std::find(effects.begin(),effects.end(),effect.text())==effects.end())effects.push_back(effect.text());k["sources"]["effects"][effect.text()]=e.asset.path;auto& bindings=k["effect_bindings"];if(bindings.is_null())bindings=nlohmann::json::array();for(auto& b:bindings)if(b["ability"]==ability.text()&&b["hit_block"]==block&&b["effect"]==effect.text()){b["power"]=power;return;}bindings.push_back({{"ability",ability.text()},{"hit_block",block},{"effect",effect.text()},{"power",power}});}
bool NativeAuthoring::dirty()const{for(const auto& [id,d]:drafts)if(d.dirty())return true;return false;}
void NativeAuthoring::save_all(AssetService& assets){unsigned saved{};try{for(const char* kind:{"action","effect","ability","combat_kit"})for(auto& [id,d]:drafts)if(d.value["kind"]==kind&&d.dirty()){save(assets,id);++saved;}}catch(const std::exception& e){throw std::runtime_error(std::string(e.what())+(saved?". Earlier changes were saved; correct this asset and Save again.":""));}}
void package_authoring(AssetService& assets,std::span<const AssetId> roots,const std::filesystem::path& output){require(!roots.empty()&&roots.size()<=64,"Scene package root bounds");assets.scan();auto inventory=assets.assets();for(auto id:roots){auto found=std::find_if(inventory.begin(),inventory.end(),[&](const auto& a){return a.id==id;});require(found!=inventory.end(),"Scene package source is missing");assets.cook(found->path);}assets.package(roots.front(),output,roots.subspan(1));}
}
