#include "ability_wire.hpp"
#include "session_wire.hpp"
#include <cmath>
#include <set>
namespace darkangel::session_detail {
namespace {
void write_id(Writer& w,AssetId id){for(auto b:id.bytes)w.bytes.push_back(static_cast<std::byte>(b));}
AssetId read_id(Reader& r){wire_require(r.bytes.size()-r.at>=16,"Truncated ability AssetID");AssetId id;for(auto& b:id.bytes)b=std::to_integer<unsigned char>(r.bytes[r.at++]);AssetId::parse(id.text());return id;}
void generation(Writer& w,const std::string& value){wire_require(value.size()==64&&value.find_first_not_of("0123456789abcdef")==value.npos,"Ability action generation");for(auto c:value)w.bytes.push_back(static_cast<std::byte>(c));}
std::string generation(Reader& r){wire_require(r.bytes.size()-r.at>=64,"Truncated action generation");std::string result;for(unsigned i=0;i<64;++i)result.push_back(static_cast<char>(r.bytes[r.at++]));wire_require(result.find_first_not_of("0123456789abcdef")==result.npos,"Invalid action generation");return result;}
void write_tags(Writer& w,const ActorTagSnapshot& tags){
    wire_require(tags.values.size()<=128,"Actor tag wire bound");if(tags.registry==AssetId{}){wire_require(tags.generation.empty()&&tags.values.empty(),"Unprepared native tag registry cannot enter wire state");w.u64(0);return;}w.u64(1);write_id(w,tags.registry);generation(w,tags.generation);w.u64(tags.values.size());std::set<TagId> unique;for(auto id:tags.values){wire_require(id&&unique.insert(id).second,"Actor tag wire identity");w.u64(id);}
}
ActorTagSnapshot read_tags(Reader& r){ActorTagSnapshot tags;auto present=r.u64();wire_require(present<=1,"Actor tag registry flag");if(!present)return tags;tags.registry=read_id(r);wire_require(tags.registry!=AssetId{},"Actor tag registry identity");tags.generation=generation(r);auto count=r.u64();wire_require(count<=128,"Actor tag wire count");std::set<TagId> unique;for(std::uint64_t i=0;i<count;++i){auto id=r.u64();wire_require(id&&id<=UINT32_MAX&&unique.insert(static_cast<TagId>(id)).second,"Actor tag wire identity");tags.values.push_back(static_cast<TagId>(id));}return tags;}
}
std::vector<std::byte> encode_ability_correction(const AbilityCorrection& correction){
    const auto& state=correction.ability;wire_require(state.attributes.size()<=64&&state.cooldowns.size()<=32&&state.operations.size()<=128,"Ability correction encoding bounds");
    Writer w;w.u64(3);w.u64(correction.network);w.u64(correction.session_epoch);w.u64(correction.world_revision);write_motor(w,correction.motor);
    for(auto value:{state.tick,state.grant_generation,state.revision,state.highest_operation,state.retired_through})w.u64(value);
    w.u64(state.health_attribute);w.u64(state.maximum_health_attribute);
    w.u64(state.next_activation);
    for(const auto& input:state.input){for(auto value:{std::uint64_t(input.active),std::uint64_t(input.hold_sent),std::uint64_t(input.rearm),input.pressed,input.released,input.duration})w.u64(value);}
    w.u64(state.attributes.size());for(const auto& field:state.attributes){w.u64(field.id);w.number(field.value);}
    w.u64(state.cooldowns.size());for(const auto& [group,until]:state.cooldowns){w.u64(group);w.u64(until);}
    w.u64(state.operations.size());for(const auto& operation:state.operations){w.u64(operation.operation);w.u64(static_cast<unsigned>(operation.failure));w.u64(operation.activation);w.u64(operation.committed);}
    wire_require(bool(state.active)==bool(state.action),"Ability correction active/action pairing");w.u64(state.active?1:0);
    if(state.active){const auto& action=*state.action;w.u64(state.active->activation);write_id(w,state.ability);write_id(w,state.action_definition);generation(w,state.ability_generation);w.u64(static_cast<unsigned>(state.active_slot));for(auto value:{action.tick,action.clock,std::uint64_t(action.rate),std::uint64_t(action.phase),std::uint64_t(action.entered)})w.u64(value);generation(w,action.generation);}
    write_tags(w,state.tags);wire_require(w.bytes.size()<=8192,"Ability correction byte bound");return std::move(w.bytes);
}
AbilityCorrection decode_ability_correction(std::span<const std::byte> bytes){
    wire_require(bytes.size()<=8192,"Ability correction decode byte bound");Reader r{bytes};wire_require(r.u64()==3,"Ability correction schema");AbilityCorrection result;result.network=r.u64();result.session_epoch=r.u64();result.world_revision=r.u64();wire_require(result.network&&result.session_epoch,"Ability correction identity");result.motor=read_motor(r);auto& state=result.ability;state.owner.network=result.network;state.owner.session_epoch=result.session_epoch;
    state.tick=r.u64();state.grant_generation=r.u64();state.revision=r.u64();state.highest_operation=r.u64();state.retired_through=r.u64();wire_require(state.tick==result.motor.tick&&state.retired_through<=state.highest_operation,"Ability correction coherent tick/operation retirement");
    auto health=r.u64(),maximum=r.u64();wire_require(health&&maximum&&health!=maximum&&health<=UINT32_MAX&&maximum<=UINT32_MAX,"Ability correction Health schema IDs");state.health_attribute=static_cast<AttributeId>(health);state.maximum_health_attribute=static_cast<AttributeId>(maximum);
    state.next_activation=r.u64();wire_require(state.next_activation,"Ability correction activation sequence");
    for(auto& input:state.input){auto active=r.u64(),hold=r.u64(),rearm=r.u64();input.pressed=r.u64();input.released=r.u64();input.duration=r.u64();wire_require(active<=1&&hold<=1&&rearm<=1&&input.pressed<=state.tick&&input.released<=state.tick&&input.duration<=10000000&&(!active||!input.released),"Ability correction input state");input.active=active!=0;input.hold_sent=hold!=0;input.rearm=rearm!=0;}
    auto count=r.u64();wire_require(count>0&&count<=64,"Ability correction attribute count");std::set<AttributeId> attributes;
    for(std::uint64_t i=0;i<count;++i){auto id=r.u64();auto value=r.number();wire_require(id&&id<=UINT32_MAX&&std::isfinite(value)&&attributes.insert(static_cast<AttributeId>(id)).second,"Ability correction attribute ID/value");state.attributes.push_back({static_cast<AttributeId>(id),value});}
    wire_require(attributes.contains(state.health_attribute)&&attributes.contains(state.maximum_health_attribute),"Ability correction missing Health attributes");
    count=r.u64();wire_require(count<=32,"Ability correction cooldown count");std::set<std::uint32_t> cooldowns;
    for(std::uint64_t i=0;i<count;++i){auto group=r.u64(),until=r.u64();wire_require(group&&group<=UINT32_MAX&&until>state.tick&&cooldowns.insert(static_cast<std::uint32_t>(group)).second,"Ability correction cooldown identity/expiry");state.cooldowns.emplace_back(static_cast<std::uint32_t>(group),until);}
    count=r.u64();wire_require(count<=128,"Ability correction operation count");std::uint64_t previous=state.retired_through;
    for(std::uint64_t i=0;i<count;++i){AbilitySnapshotOperation operation;operation.operation=r.u64();auto failure=r.u64();operation.activation=r.u64();auto committed=r.u64();wire_require(operation.operation>previous&&operation.operation<=state.highest_operation&&operation.activation<state.next_activation&&failure<=static_cast<unsigned>(AbilityFailure::TagRequirements)&&committed<=1&&(!committed||(failure==0&&operation.activation)),"Ability correction terminal operation");previous=operation.operation;operation.failure=static_cast<AbilityFailure>(failure);operation.committed=committed!=0;state.operations.push_back(operation);}
    state.retained_operations=state.operations.size();auto active=r.u64();wire_require(active<=1,"Ability correction active flag");
    if(active){auto activation=r.u64();state.ability=read_id(r);state.action_definition=read_id(r);state.ability_generation=generation(r);auto slot=r.u64();ActionState action;action.activation=activation;action.tick=r.u64();action.clock=r.u64();auto rate=r.u64(),phase=r.u64(),entered=r.u64();wire_require(activation&&activation<state.next_activation&&slot<combat_slot_count&&action.tick==state.tick&&action.clock<=600*action_tick_units*8&&rate<=4*action_tick_units&&phase==static_cast<unsigned>(ActionPhase::Active)&&entered==1,"Ability correction active action state");action.rate=static_cast<unsigned>(rate);action.phase=ActionPhase::Active;action.entered=true;action.generation=generation(r);state.active_slot=static_cast<CombatSlot>(slot);state.active=AbilityActivationHandle{state.owner,activation};state.action=action;}
    state.tags=read_tags(r);r.end();return result;
}
std::vector<std::byte> encode_ability_public(const AbilityPublicFrame& frame){
    const auto& state=frame.ability;wire_require(!state.attributes.empty()&&state.attributes.size()<=64&&bool(state.active)==bool(state.action),"Public ability encoding bounds");Writer w;w.u64(2);w.u64(frame.network);w.u64(frame.session_epoch);w.u64(frame.world_revision);write_motor(w,frame.motor);w.u64(state.tick);w.u64(state.revision);w.u64(state.health_attribute);w.u64(state.maximum_health_attribute);
    w.u64(state.attributes.size());for(const auto& value:state.attributes){w.u64(value.id);w.number(value.value);}w.u64(state.active?1:0);
    if(state.active){w.u64(state.active->activation);write_id(w,state.action_definition);const auto& action=*state.action;for(auto value:{action.tick,action.clock,std::uint64_t(action.rate),std::uint64_t(action.phase),std::uint64_t(action.entered)})w.u64(value);generation(w,action.generation);}
    write_tags(w,state.tags);wire_require(w.bytes.size()<=4096,"Public ability byte bound");return std::move(w.bytes);
}
AbilityPublicFrame decode_ability_public(std::span<const std::byte> bytes){
    wire_require(bytes.size()<=4096,"Public ability decode byte bound");Reader r{bytes};wire_require(r.u64()==2,"Public ability schema");AbilityPublicFrame result;result.network=r.u64();result.session_epoch=r.u64();result.world_revision=r.u64();wire_require(result.network&&result.session_epoch,"Public ability identity");result.motor=read_motor(r);auto& state=result.ability;state.owner.network=result.network;state.owner.session_epoch=result.session_epoch;state.tick=r.u64();state.revision=r.u64();wire_require(state.tick==result.motor.tick,"Public motor/action coherent tick");auto health=r.u64(),maximum=r.u64();wire_require(health&&maximum&&health!=maximum&&health<=UINT32_MAX&&maximum<=UINT32_MAX,"Public Health schema");state.health_attribute=static_cast<AttributeId>(health);state.maximum_health_attribute=static_cast<AttributeId>(maximum);
    auto count=r.u64();wire_require(count>0&&count<=64,"Public attribute count");std::set<AttributeId> attributes;for(std::uint64_t i=0;i<count;++i){auto id=r.u64();auto value=r.number();wire_require(id&&id<=UINT32_MAX&&std::isfinite(value)&&attributes.insert(static_cast<AttributeId>(id)).second,"Public attribute identity/value");state.attributes.push_back({static_cast<AttributeId>(id),value});}wire_require(attributes.contains(state.health_attribute)&&attributes.contains(state.maximum_health_attribute),"Public Health attributes missing");
    auto active=r.u64();wire_require(active<=1,"Public active flag");if(active){auto activation=r.u64();state.action_definition=read_id(r);ActionState action;action.activation=activation;action.tick=r.u64();action.clock=r.u64();auto rate=r.u64(),phase=r.u64(),entered=r.u64();wire_require(activation&&action.tick==state.tick&&action.clock<=600*action_tick_units*8&&rate<=4*action_tick_units&&phase==static_cast<unsigned>(ActionPhase::Active)&&entered==1,"Public active action bounds");action.rate=static_cast<unsigned>(rate);action.phase=ActionPhase::Active;action.entered=true;action.generation=generation(r);state.active=AbilityActivationHandle{state.owner,activation};state.action=std::move(action);}state.tags=read_tags(r);r.end();return result;
}
}
