#include <darkangel/eos_session.hpp>
#include <darkangel/hash.hpp>
#include <algorithm>
#include <eos_sdk.h>
#include <eos_connect.h>
#include <eos_lobby.h>
#include <eos_p2p.h>
#include <atomic>
#include <array>
#include <cstring>
#include <deque>
#include <map>
#include <set>
#include <stdexcept>
#include <thread>
namespace darkangel {
namespace {
void require(bool ok,const char* message){if(!ok)throw std::runtime_error(message);}
unsigned sdk_users{};std::thread::id owner;std::atomic<std::uint64_t> tokens{1};
void acquire(){if(sdk_users){require(owner==std::this_thread::get_id(),"EOS owner thread mismatch");++sdk_users;return;}EOS_InitializeOptions options{};options.ApiVersion=EOS_INITIALIZE_API_LATEST;options.ProductName="DarkAngel";options.ProductVersion="0.0.1";require(EOS_Initialize(&options)==EOS_Success,"EOS SDK initialization failed");owner=std::this_thread::get_id();++sdk_users;}
void release(){if(--sdk_users==0)EOS_Shutdown();}
}
struct EosSessionProvider::Impl {
    EosConfiguration config;SessionHandshake hello;EosState status{EosState::Idle};std::string error,lobby,bucket;bool active{true};std::uint64_t membership_epoch{1},next_participant{1};
    EOS_HPlatform platform{};EOS_HConnect connect{};EOS_HLobby lobbies{};EOS_HP2P p2p{};EOS_ProductUserId local{},host_id{};EOS_ContinuanceToken continuation{};EOS_HLobbySearch find{};
    EOS_P2P_SocketId socket{EOS_P2P_SOCKETID_API_LATEST,"DarkAngelM3"};EOS_NotificationId incoming{EOS_INVALID_NOTIFICATIONID},expiration{EOS_INVALID_NOTIFICATIONID};
    struct Member {EOS_ProductUserId user;std::deque<TransportMessage> packets;std::size_t bytes{};bool leased{};};std::map<std::uint64_t,Member> members;
    std::vector<EOS_HLobbyDetails> results;
    Impl(EosConfiguration c,SessionHandshake h):config(std::move(c)),hello(std::move(h)){
        for(const auto* value:{&config.product,&config.sandbox,&config.deployment,&config.client_id,&config.public_client_secret,&config.cache_directory})require(!value->empty() && value->size()<=1024 && value->find('\0')==value->npos,"Missing/invalid EOS deployment or public-client configuration");auto proof=create_loopback(hello);bucket=sha256(std::to_string(hello.protocol)+":"+hello.schema_hash+":"+hello.content_hash);acquire();
        EOS_Platform_Options options{};options.ApiVersion=EOS_PLATFORM_OPTIONS_API_LATEST;options.ProductId=config.product.c_str();options.SandboxId=config.sandbox.c_str();options.DeploymentId=config.deployment.c_str();options.ClientCredentials={config.client_id.c_str(),config.public_client_secret.c_str()};options.CacheDirectory=config.cache_directory.c_str();options.Flags=EOS_PF_DISABLE_OVERLAY;platform=EOS_Platform_Create(&options);if(!platform){release();throw std::runtime_error("EOS platform creation failed; verify deployment/public-client policy");}connect=EOS_Platform_GetConnectInterface(platform);lobbies=EOS_Platform_GetLobbyInterface(platform);p2p=EOS_Platform_GetP2PInterface(platform);
        EOS_P2P_SetPacketQueueSizeOptions queues{EOS_P2P_SETPACKETQUEUESIZE_API_LATEST,512*1024,512*1024};EOS_P2P_SetPacketQueueSize(p2p,&queues);
        EOS_P2P_AddNotifyPeerConnectionRequestOptions requests{EOS_P2P_ADDNOTIFYPEERCONNECTIONREQUEST_API_LATEST,nullptr,&socket};incoming=EOS_P2P_AddNotifyPeerConnectionRequest(p2p,&requests,this,[](const EOS_P2P_OnIncomingConnectionRequestInfo* info){auto& self=*static_cast<Impl*>(info->ClientData);if(!self.active || self.status!=EosState::InLobby || !info->SocketId || std::strcmp(info->SocketId->SocketName,self.socket.SocketName)!=0)return;for(const auto& [id,member]:self.members)if(member.user==info->RemoteUserId){EOS_P2P_AcceptConnectionOptions accept{EOS_P2P_ACCEPTCONNECTION_API_LATEST,self.local,info->RemoteUserId,&self.socket};EOS_P2P_AcceptConnection(self.p2p,&accept);return;}});
        EOS_Connect_AddNotifyAuthExpirationOptions expiry{EOS_CONNECT_ADDNOTIFYAUTHEXPIRATION_API_LATEST};expiration=EOS_Connect_AddNotifyAuthExpiration(connect,&expiry,this,[](const EOS_Connect_AuthExpirationCallbackInfo* info){auto& self=*static_cast<Impl*>(info->ClientData);if(self.active){self.status=EosState::RefreshRequired;self.clear_members();}});
    }
    void thread() const{require(owner==std::this_thread::get_id(),"EOS owner thread mismatch");}
    void clear_members(){for(const auto& [id,m]:members){EOS_P2P_CloseConnectionOptions close{EOS_P2P_CLOSECONNECTION_API_LATEST,local,m.user,&socket};EOS_P2P_CloseConnection(p2p,&close);}members.clear();++membership_epoch;}
    ~Impl(){if(incoming!=EOS_INVALID_NOTIFICATIONID)EOS_P2P_RemoveNotifyPeerConnectionRequest(p2p,incoming);if(expiration!=EOS_INVALID_NOTIFICATIONID)EOS_Connect_RemoveNotifyAuthExpiration(connect,expiration);for(auto details:results)EOS_LobbyDetails_Release(details);if(find)EOS_LobbySearch_Release(find);EOS_Platform_Release(platform);release();}
    void fail(EOS_EResult result){status=EosState::Failed;error=EOS_EResult_ToString(result);clear_members();}
    void adopt(const char* id){lobby=id;EOS_Lobby_CopyLobbyDetailsHandleOptions options{EOS_LOBBY_COPYLOBBYDETAILSHANDLE_API_LATEST,lobby.c_str(),local};EOS_HLobbyDetails details{};if(EOS_Lobby_CopyLobbyDetailsHandle(lobbies,&options,&details)!=EOS_Success){fail(EOS_NotFound);return;}EOS_LobbyDetails_CopyInfoOptions copy{EOS_LOBBYDETAILS_COPYINFO_API_LATEST};EOS_LobbyDetails_Info* info{};auto result=EOS_LobbyDetails_CopyInfo(details,&copy,&info);if(result==EOS_Success){if(info->MaxMembers>4 || !info->BucketId || bucket!=info->BucketId){EOS_LobbyDetails_Info_Release(info);EOS_LobbyDetails_Release(details);fail(EOS_IncompatibleVersion);return;}host_id=info->LobbyOwnerUserId;EOS_LobbyDetails_Info_Release(info);status=EosState::InLobby;}else fail(result);EOS_LobbyDetails_Release(details);}
    void roster(){if(status!=EosState::InLobby)return;EOS_Lobby_CopyLobbyDetailsHandleOptions options{EOS_LOBBY_COPYLOBBYDETAILSHANDLE_API_LATEST,lobby.c_str(),local};EOS_HLobbyDetails details{};auto result=EOS_Lobby_CopyLobbyDetailsHandle(lobbies,&options,&details);if(result!=EOS_Success){fail(result);return;}EOS_LobbyDetails_CopyInfoOptions copy{EOS_LOBBYDETAILS_COPYINFO_API_LATEST};EOS_LobbyDetails_Info* info{};result=EOS_LobbyDetails_CopyInfo(details,&copy,&info);if(result!=EOS_Success){EOS_LobbyDetails_Release(details);fail(result);return;}if(info->LobbyOwnerUserId!=host_id){EOS_LobbyDetails_Info_Release(info);EOS_LobbyDetails_Release(details);fail(EOS_InvalidState);return;}EOS_LobbyDetails_Info_Release(info);EOS_LobbyDetails_GetMemberCountOptions count_options{EOS_LOBBYDETAILS_GETMEMBERCOUNT_API_LATEST};auto count=EOS_LobbyDetails_GetMemberCount(details,&count_options);if(count>4){EOS_LobbyDetails_Release(details);fail(EOS_LimitExceeded);return;}std::set<EOS_ProductUserId> current;for(std::uint32_t i=0;i<count;++i){EOS_LobbyDetails_GetMemberByIndexOptions index{EOS_LOBBYDETAILS_GETMEMBERBYINDEX_API_LATEST,i};auto user=EOS_LobbyDetails_GetMemberByIndex(details,&index);if(user && user!=local && (local==host_id || user==host_id))current.insert(user);}EOS_LobbyDetails_Release(details);for(auto it=members.begin();it!=members.end();)if(!current.contains(it->second.user)){EOS_P2P_CloseConnectionOptions close{EOS_P2P_CLOSECONNECTION_API_LATEST,local,it->second.user,&socket};EOS_P2P_CloseConnection(p2p,&close);it=members.erase(it);}else ++it;for(auto user:current){bool exists=false;for(const auto& [id,m]:members)exists|=m.user==user;if(!exists)members.emplace(next_participant++,Member{user});}}
    void receive(){if(status!=EosState::InLobby)return;for(unsigned work=0;work<32;++work){std::array<std::byte,EOS_P2P_MAX_PACKET_SIZE> data{};EOS_ProductUserId remote{};EOS_P2P_SocketId received{};std::uint8_t channel{};std::uint32_t size{};EOS_P2P_ReceivePacketOptions options{EOS_P2P_RECEIVEPACKET_API_LATEST,local,static_cast<std::uint32_t>(data.size()),nullptr};auto result=EOS_P2P_ReceivePacket(p2p,&options,&remote,&received,&channel,data.data(),&size);if(result==EOS_NotFound)return;if(result!=EOS_Success){fail(result);return;}if(std::strcmp(received.SocketName,socket.SocketName)!=0 || channel>1 || size<8 || size>1008)continue;for(auto& [id,m]:members)if(m.user==remote && m.leased){if(m.packets.size()>=32 || m.bytes+size>128*1024){fail(EOS_LimitExceeded);return;}std::uint64_t seq{};for(unsigned i=0;i<8;++i)seq|=std::uint64_t(std::to_integer<unsigned>(data[i]))<<(i*8);if(!seq)continue;m.packets.push_back({{},channel?Delivery::UnreliableState:Delivery::ReliableOrdered,seq,{data.begin()+8,data.begin()+size}});m.bytes+=size-8;break;}}}
};
namespace {
class EosTransport final:public Transport {
    std::shared_ptr<EosSessionProvider::Impl> session;std::uint64_t participant,token=tokens.fetch_add(1),epoch,sequence{};bool opened{};
    ConnectionHandle peer() const{return {token,epoch,participant};}
    void check(ConnectionHandle h) const{require(h==peer() && connected(),"Stale/foreign/unapproved EOS participant");}
public:
    EosTransport(std::shared_ptr<EosSessionProvider::Impl> s,std::uint64_t id):session(std::move(s)),participant(id),epoch(session->membership_epoch){auto& m=session->members.at(id);require(!m.leased,"EOS participant already owns a transport");m.leased=true;}
    ~EosTransport() override{if(auto it=session->members.find(participant);it!=session->members.end()){EOS_P2P_CloseConnectionOptions close{EOS_P2P_CLOSECONNECTION_API_LATEST,session->local,it->second.user,&session->socket};EOS_P2P_CloseConnection(session->p2p,&close);it->second.leased=false;it->second.packets.clear();it->second.bytes=0;}}
    ConnectionHandle open(const SessionHandshake& h) override{session->thread();const auto& e=session->hello;require(h.protocol==e.protocol && h.schema_hash==e.schema_hash && h.content_hash==e.content_hash && h.session_epoch==e.session_epoch && session->status==EosState::InLobby && session->members.contains(participant),"EOS descriptor or lobby membership mismatch");opened=true;return peer();}
    bool connected() const override{session->thread();return opened && session->active && session->status==EosState::InLobby && epoch==session->membership_epoch && session->members.contains(participant);}
    TransportLimits limits() const override{return {32,1000,128*1024};}
    bool send(ConnectionHandle h,Delivery channel,std::span<const std::byte> bytes) override{check(h);require(bytes.size()<=1000 && (channel==Delivery::ReliableOrdered || channel==Delivery::UnreliableState),"EOS payload/channel limit");std::vector<std::byte> wire;for(unsigned i=0;i<8;++i)wire.push_back(static_cast<std::byte>(((sequence+1)>>(i*8))&255));wire.insert(wire.end(),bytes.begin(),bytes.end());EOS_P2P_SendPacketOptions options{};options.ApiVersion=EOS_P2P_SENDPACKET_API_LATEST;options.LocalUserId=session->local;options.RemoteUserId=session->members.at(participant).user;options.SocketId=&session->socket;options.Channel=channel==Delivery::ReliableOrdered?0:1;options.DataLengthBytes=static_cast<std::uint32_t>(wire.size());options.Data=wire.data();options.bAllowDelayedDelivery=EOS_TRUE;options.bDisableAutoAcceptConnection=EOS_TRUE;options.Reliability=channel==Delivery::ReliableOrdered?EOS_PR_ReliableOrdered:EOS_PR_UnreliableUnordered;EOS_P2P_AcceptConnectionOptions accept{EOS_P2P_ACCEPTCONNECTION_API_LATEST,session->local,options.RemoteUserId,&session->socket};EOS_P2P_AcceptConnection(session->p2p,&accept);auto result=EOS_P2P_SendPacket(session->p2p,&options);if(result==EOS_LimitExceeded)return false;require(result==EOS_Success,"EOS packet send failed");++sequence;return true;}
    std::vector<TransportMessage> poll(std::size_t count) override{session->thread();require(count<=32,"EOS poll work limit");std::vector<TransportMessage> messages;if(!connected())return messages;auto& m=session->members.at(participant);while(!m.packets.empty() && messages.size()<count){auto message=std::move(m.packets.front());m.packets.pop_front();m.bytes-=message.bytes.size();message.sender=peer();messages.push_back(std::move(message));}return messages;}
    void disconnect(ConnectionHandle h) override{check(h);auto& m=session->members.at(participant);EOS_P2P_CloseConnectionOptions close{EOS_P2P_CLOSECONNECTION_API_LATEST,session->local,m.user,&session->socket};EOS_P2P_CloseConnection(session->p2p,&close);opened=false;++epoch;m.packets.clear();m.bytes=0;}
};
}
EosSessionProvider::EosSessionProvider(EosConfiguration c,SessionHandshake h):impl_(std::make_shared<Impl>(std::move(c),std::move(h))){}
EosSessionProvider::~EosSessionProvider(){impl_->active=false;impl_->status=EosState::Stopped;impl_->clear_members();}
void EosSessionProvider::login(EosIdentityProvider provider,std::string token){auto& s=*impl_;s.thread();require(s.status==EosState::Idle || s.status==EosState::LoggedIn || s.status==EosState::RefreshRequired,"EOS login state mismatch");require(!token.empty() && token.size()<=8192 && token.find('\0')==token.npos,"EOS identity token size/content limit");require(provider==EosIdentityProvider::EpicIdToken || provider==EosIdentityProvider::SteamSessionTicket,"Unsupported Connect provider");EOS_Connect_Credentials credentials{EOS_CONNECT_CREDENTIALS_API_LATEST,token.c_str(),provider==EosIdentityProvider::EpicIdToken?EOS_ECT_EPIC_ID_TOKEN:EOS_ECT_STEAM_SESSION_TICKET};EOS_Connect_LoginOptions options{EOS_CONNECT_LOGIN_API_LATEST,&credentials,nullptr};s.status=EosState::LoginPending;EOS_Connect_Login(s.connect,&options,&s,[](const EOS_Connect_LoginCallbackInfo* info){auto& s=*static_cast<Impl*>(info->ClientData);if(!s.active)return;if(info->ResultCode==EOS_InvalidUser){s.continuation=info->ContinuanceToken;s.status=EosState::CreateUserRequired;}else if(info->ResultCode==EOS_Success){if(s.local && s.local!=info->LocalUserId){s.fail(EOS_InvalidUser);return;}s.local=info->LocalUserId;s.status=s.lobby.empty()?EosState::LoggedIn:EosState::InLobby;}else s.fail(info->ResultCode);});}
void EosSessionProvider::create_user(){auto& s=*impl_;s.thread();require(s.status==EosState::CreateUserRequired && s.continuation,"No EOS continuance token");EOS_Connect_CreateUserOptions options{EOS_CONNECT_CREATEUSER_API_LATEST,s.continuation};s.status=EosState::LoginPending;EOS_Connect_CreateUser(s.connect,&options,&s,[](const EOS_Connect_CreateUserCallbackInfo* info){auto& s=*static_cast<Impl*>(info->ClientData);if(!s.active)return;if(info->ResultCode==EOS_Success){s.local=info->LocalUserId;s.continuation=nullptr;s.status=EosState::LoggedIn;}else s.fail(info->ResultCode);});}
void EosSessionProvider::host(){auto& s=*impl_;s.thread();require(s.status==EosState::LoggedIn && s.lobby.empty(),"EOS host state mismatch");EOS_Lobby_CreateLobbyOptions options{};options.ApiVersion=EOS_LOBBY_CREATELOBBY_API_LATEST;options.LocalUserId=s.local;options.MaxLobbyMembers=4;options.PermissionLevel=EOS_LPL_PUBLICADVERTISED;options.BucketId=s.bucket.c_str();options.bDisableHostMigration=EOS_TRUE;s.status=EosState::LobbyPending;EOS_Lobby_CreateLobby(s.lobbies,&options,&s,[](const EOS_Lobby_CreateLobbyCallbackInfo* info){auto& s=*static_cast<Impl*>(info->ClientData);if(!s.active)return;if(info->ResultCode==EOS_Success)s.adopt(info->LobbyId);else s.fail(info->ResultCode);});}
void EosSessionProvider::search(){auto& s=*impl_;s.thread();require(s.status==EosState::LoggedIn && s.lobby.empty(),"EOS search state mismatch");for(auto result:s.results)EOS_LobbyDetails_Release(result);s.results.clear();if(s.find){EOS_LobbySearch_Release(s.find);s.find=nullptr;}EOS_Lobby_CreateLobbySearchOptions options{EOS_LOBBY_CREATELOBBYSEARCH_API_LATEST,16};require(EOS_Lobby_CreateLobbySearch(s.lobbies,&options,&s.find)==EOS_Success,"EOS search allocation failed");EOS_Lobby_AttributeData bucket{};bucket.ApiVersion=EOS_LOBBY_ATTRIBUTEDATA_API_LATEST;bucket.Key="bucket";bucket.ValueType=EOS_AT_STRING;bucket.Value.AsUtf8=s.bucket.c_str();EOS_LobbySearch_SetParameterOptions parameter{EOS_LOBBYSEARCH_SETPARAMETER_API_LATEST,&bucket,EOS_CO_EQUAL};require(EOS_LobbySearch_SetParameter(s.find,&parameter)==EOS_Success,"EOS search filter failed");EOS_LobbySearch_FindOptions find{EOS_LOBBYSEARCH_FIND_API_LATEST,s.local};s.status=EosState::SearchPending;EOS_LobbySearch_Find(s.find,&find,&s,[](const EOS_LobbySearch_FindCallbackInfo* info){auto& s=*static_cast<Impl*>(info->ClientData);if(!s.active)return;if(info->ResultCode!=EOS_Success){s.fail(info->ResultCode);return;}EOS_LobbySearch_GetSearchResultCountOptions count{EOS_LOBBYSEARCH_GETSEARCHRESULTCOUNT_API_LATEST};auto n=EOS_LobbySearch_GetSearchResultCount(s.find,&count);for(std::uint32_t i=0;i<std::min(n,16u);++i){EOS_LobbySearch_CopySearchResultByIndexOptions copy{EOS_LOBBYSEARCH_COPYSEARCHRESULTBYINDEX_API_LATEST,i};EOS_HLobbyDetails details{};if(EOS_LobbySearch_CopySearchResultByIndex(s.find,&copy,&details)==EOS_Success)s.results.push_back(details);}s.status=EosState::LoggedIn;});}
void EosSessionProvider::join(std::size_t index){auto& s=*impl_;s.thread();require(s.status==EosState::LoggedIn && s.lobby.empty() && index<s.results.size(),"Invalid EOS search result/join state");EOS_Lobby_JoinLobbyOptions options{};options.ApiVersion=EOS_LOBBY_JOINLOBBY_API_LATEST;options.LocalUserId=s.local;options.LobbyDetailsHandle=s.results[index];s.status=EosState::LobbyPending;EOS_Lobby_JoinLobby(s.lobbies,&options,&s,[](const EOS_Lobby_JoinLobbyCallbackInfo* info){auto& s=*static_cast<Impl*>(info->ClientData);if(!s.active)return;if(info->ResultCode==EOS_Success)s.adopt(info->LobbyId);else s.fail(info->ResultCode);});}
void EosSessionProvider::leave(){auto& s=*impl_;s.thread();require(s.status==EosState::InLobby,"EOS leave state mismatch");s.clear_members();EOS_Lobby_LeaveLobbyOptions options{EOS_LOBBY_LEAVELOBBY_API_LATEST,s.local,s.lobby.c_str()};s.status=EosState::LobbyPending;EOS_Lobby_LeaveLobby(s.lobbies,&options,&s,[](const EOS_Lobby_LeaveLobbyCallbackInfo* info){auto& s=*static_cast<Impl*>(info->ClientData);if(!s.active)return;if(info->ResultCode==EOS_Success){s.lobby.clear();s.host_id=nullptr;s.status=EosState::LoggedIn;}else s.fail(info->ResultCode);});}
void EosSessionProvider::tick(){impl_->thread();EOS_Platform_Tick(impl_->platform);impl_->roster();impl_->receive();}
EosState EosSessionProvider::state() const{impl_->thread();return impl_->status;}
std::string EosSessionProvider::diagnostic() const{impl_->thread();return impl_->error;}
std::size_t EosSessionProvider::search_results() const{impl_->thread();return impl_->results.size();}
std::vector<OnlineParticipant> EosSessionProvider::participants() const{impl_->thread();std::vector<OnlineParticipant> result;for(const auto& [id,m]:impl_->members)result.push_back({id,m.user==impl_->host_id});return result;}
std::unique_ptr<Transport> EosSessionProvider::transport(std::uint64_t id){impl_->thread();require(impl_->status==EosState::InLobby && impl_->members.contains(id),"EOS transport needs authorized current lobby participant");return std::make_unique<EosTransport>(impl_,id);}
void probe_eos_sdk(){acquire();release();}
}
