#include "assets_internal.hpp"
#include <darkangel/actor_assets.hpp>
#include <darkangel/hash.hpp>
#include <set>
#include <cmath>
#include <algorithm>
namespace darkangel {
using namespace assets_detail;
namespace {
void fields(const Json& value,std::initializer_list<const char*> keys){require(value.is_object()&&value.size()==keys.size(),"Actor definition field count");for(auto key:keys)require(value.contains(key),"Actor definition missing/unknown field");}
AssetId actor_reference(const Json& value){auto id=AssetId::parse(value.get<std::string>());require(id!=AssetId{},"Actor reference must be nonzero");return id;}
std::vector<AbilityAttributeValue> starting_attributes(const Json& loadout){
 auto base=loadout;base.erase("starting_attributes");base.erase("masks");base.erase("active_mask");fields(base,{"kit"});std::vector<AbilityAttributeValue> result;std::set<AttributeId> used;
 if(loadout.contains("starting_attributes")){auto& values=loadout.at("starting_attributes");require(values.is_array()&&values.size()<=64,"Actor starting attribute count");for(const auto& value:values){fields(value,{"attribute","value"});require(value.at("attribute").is_number_unsigned()&&value.at("attribute").get<std::uint64_t>()<=UINT32_MAX&&value.at("value").is_number(),"Actor starting attribute type");auto id=value.at("attribute").get<AttributeId>();auto amount=value.at("value").get<double>();require(id&&used.insert(id).second&&std::isfinite(amount),"Actor starting attribute identity/value");result.push_back({id,amount});}}
 return result;
}
void equipped_masks(const Json& loadout,ActorLoadoutDefinition& result){
 require(loadout.contains("masks")==loadout.contains("active_mask"),"Actor mask slots/active mask pair");if(!loadout.contains("masks"))return;
 const auto& masks=loadout.at("masks");require(masks.is_array()&&masks.size()==mask_slot_count&&loadout.at("active_mask").is_number_unsigned()&&loadout.at("active_mask").get<std::uint64_t>()<mask_slot_count,"Actor needs exactly four mask slots and an active slot index");
 std::set<AssetId> used;for(unsigned slot=0;slot<mask_slot_count;++slot)if(!masks[slot].is_null()){result.masks[slot]=actor_reference(masks[slot]);require(used.insert(result.masks[slot]).second,"A mask can be equipped in one slot only");}
 result.active_mask=loadout.at("active_mask").get<unsigned>();result.masked=true;require(result.masks[result.active_mask]!=AssetId{},"The active mask slot must hold a mask");
}
MaskDefinition mask_definition(const Json& value){
 auto base=value;base.erase("visual");base.erase("tint");base.erase("attachment");fields(base,{"schema","kind","asset","name","kit"});require(value.at("schema")==1&&value.at("kind")=="mask","Mask definition schema/type");
 MaskDefinition result;result.id=actor_reference(value.at("asset"));result.kit=actor_reference(value.at("kit"));result.name=value.at("name").get<std::string>();require(!result.name.empty()&&result.name.size()<=64,"Mask display name bounds");
 if(value.contains("visual"))result.visual=actor_reference(value.at("visual"));
 auto number=[](const Json& v,double low,double high){require(v.is_number(),"Mask number type");auto n=v.get<double>();require(std::isfinite(n)&&n>=low&&n<=high,"Mask number bounds");return static_cast<float>(n);};
 if(value.contains("tint")){const auto& tint=value.at("tint");require(tint.is_array()&&tint.size()==4,"Mask tint needs four components");for(unsigned i=0;i<4;++i)result.tint[i]=number(tint[i],0,4);}
 if(value.contains("attachment")){const auto& a=value.at("attachment");fields(a,{"socket","position","rotation","scale"});result.socket=a.at("socket").get<std::string>();require(!result.socket.empty()&&result.socket.size()<=32&&result.socket.find_first_not_of("abcdefghijklmnopqrstuvwxyz0123456789_")==result.socket.npos,"Mask attachment socket name");
  require(a.at("position").is_array()&&a.at("position").size()==3&&a.at("rotation").is_array()&&a.at("rotation").size()==3,"Mask attachment offset shape");for(unsigned i=0;i<3;++i){result.position[i]=number(a.at("position")[i],-2,2);result.rotation[i]=number(a.at("rotation")[i],-360,360);}result.scale=number(a.at("scale"),.01,100);}
 return result;
}
void validate(const Json& value,bool player){
 auto base=value;if(player)base.erase("input_profile");fields(base,player?std::initializer_list<const char*>{"schema","kind","asset","character","loadout"}:std::initializer_list<const char*>{"schema","kind","asset","skin"});
 require(value.at("schema")==1&&value.at("kind")== (player?"player":"character"),"Actor definition schema/type");actor_reference(value.at("asset"));
 if(player){if(value.contains("input_profile"))actor_reference(value.at("input_profile"));actor_reference(value.at("character"));starting_attributes(value.at("loadout"));actor_reference(value.at("loadout").at("kit"));ActorLoadoutDefinition masks;equipped_masks(value.at("loadout"),masks);}else actor_reference(value.at("skin"));
}
struct Frozen {
 std::map<AssetId,Json> records;std::filesystem::path cas;
 Frozen(const std::filesystem::path& path,const std::filesystem::path& storage):cas(storage){auto registry=json(read(path,1024*1024));require(registry.at("schema")==1&&registry.at("assets").is_array()&&!registry.at("assets").empty()&&registry.at("assets").size()<=512,"Actor registry bounds");for(const auto& record:registry.at("assets"))require(records.emplace(actor_reference(record.at("id")),record).second,"Actor registry duplicate identity");require(records.contains(actor_reference(registry.at("root"))),"Actor registry root missing");}
 Json load(AssetId id,bool player){auto& record=records.at(id);std::string kind=player?"player":"character",extension=kind+".json";require(record.at("kind")==kind&&record.at("extension")==extension,"Actor product type");auto digest=record.at("sha256").get<std::string>();require(digest.size()==64&&digest.find_first_not_of("0123456789abcdef")==digest.npos,"Actor product digest");auto bytes=read(cas/(digest+"."+extension),65536);require(sha256(bytes)==digest,"Actor product hash mismatch");auto data=json(bytes,65536);auto frozen=data.at("frozen");require(frozen.is_object()&&!frozen.empty()&&frozen.size()<=256,"Actor frozen closure bounds");for(const auto& [key,hash]:frozen.items())require(records.at(AssetId::parse(key)).at("sha256")==hash,"Actor frozen generation mismatch");auto pinned=[&](AssetId dep){require(frozen.contains(dep.text()),"Actor missing frozen dependency");};if(player){pinned(actor_reference(data.at("character")));pinned(actor_reference(data.at("loadout").at("kit")));}else pinned(actor_reference(data.at("skin")));if(player&&data.contains("input_profile"))pinned(actor_reference(data.at("input_profile")));if(player){ActorLoadoutDefinition masks;equipped_masks(data.at("loadout"),masks);for(auto mask:masks.masks)if(mask!=AssetId{})pinned(mask);}data.erase("frozen");validate(data,player);require(actor_reference(data.at("asset"))==id,"Actor product identity mismatch");data["generation"]=digest;return data;}
};
}
std::vector<AttributeDefinition> resolve_actor_attributes(const AttributeAsset& schema,std::span<const AbilityAttributeValue> values){
 auto definitions=schema.definitions();std::set<AttributeId> used;
 for(const auto& value:values){auto field=std::find_if(definitions.begin(),definitions.end(),[&](const auto& field){return field.id==value.id;});require(field!=definitions.end()&&used.insert(value.id).second&&std::isfinite(value.value)&&value.value>=field->minimum&&value.value<=field->maximum,"Actor starting attribute violates schema");field->base=value.value;}
 AttributeSet probe(definitions);for(const auto& value:values)require(probe.value(value.id)==value.value,"Actor starting attribute exceeds effective bounds");return definitions;
}
CookedCharacter load_cooked_character(const std::filesystem::path& registry,const std::filesystem::path& cas,AssetId id){Frozen frozen(registry,cas);auto data=frozen.load(id,false);CharacterDefinition definition{id,actor_reference(data.at("skin")),data.at("generation")};return {definition,load_cooked_skinned_model(registry,cas,definition.skin)};}
CookedMask load_cooked_mask(const std::filesystem::path& registry,const std::filesystem::path& cas,AssetId id){
 Frozen frozen(registry,cas);auto& record=frozen.records.at(id);require(record.at("kind")=="mask"&&record.at("extension")=="mask.json","Mask product type");auto digest=record.at("sha256").get<std::string>();require(digest.size()==64&&digest.find_first_not_of("0123456789abcdef")==digest.npos,"Mask product digest");auto bytes=read(cas/(digest+".mask.json"),65536);require(sha256(bytes)==digest,"Mask product hash mismatch");
 auto data=json(bytes,65536);auto pins=data.at("frozen");require(pins.is_object()&&!pins.empty()&&pins.size()<=256,"Mask frozen closure bounds");for(const auto& [key,hash]:pins.items())require(frozen.records.at(AssetId::parse(key)).at("sha256")==hash,"Mask frozen generation mismatch");data.erase("frozen");
 auto definition=mask_definition(data);require(definition.id==id&&pins.contains(definition.kit.text())&&(definition.visual==AssetId{}||pins.contains(definition.visual.text())),"Mask product identity/frozen references");definition.generation=digest;
 return {definition,load_cooked_combat_kit(registry,cas,definition.kit)};
}
CookedPlayer load_cooked_player(const std::filesystem::path& registry,const std::filesystem::path& cas,AssetId id){Frozen frozen(registry,cas);auto data=frozen.load(id,true);PlayerDefinition definition{id,actor_reference(data.at("character")),{actor_reference(data.at("loadout").at("kit")),starting_attributes(data.at("loadout"))},data.at("generation"),data.contains("input_profile")?actor_reference(data.at("input_profile")):AssetId{}};equipped_masks(data.at("loadout"),definition.loadout);auto character=load_cooked_character(registry,cas,definition.character);auto kit=load_cooked_combat_kit(registry,cas,definition.loadout.kit);
 // Every equipped mask must fit this actor: same attribute schema, input semantics and rig as the base kit.
 std::array<std::optional<MaskDefinition>,mask_slot_count> masks;
 if(definition.loadout.masked){std::optional<CookedCombatKit> active;for(unsigned slot=0;slot<mask_slot_count;++slot)if(definition.loadout.masks[slot]!=AssetId{}){auto mask=load_cooked_mask(registry,cas,definition.loadout.masks[slot]);require(mask.kit.attributes.id==kit.attributes.id&&mask.kit.attributes.generation==kit.attributes.generation&&mask.kit.input.id==kit.input.id&&mask.kit.stance.rig.definition.id==kit.stance.rig.definition.id&&mask.kit.stance.rig.definition.signature==kit.stance.rig.definition.signature,"Equipped mask kit must share the Player's attribute schema, input profile and rig");masks[slot]=mask.definition;if(slot==definition.loadout.active_mask)active=std::move(mask.kit);}kit=std::move(*active);}require(character.skin.rig.definition.id==kit.stance.rig.definition.id&&character.skin.rig.definition.signature==kit.stance.rig.definition.signature,"Player Character/kit rig mismatch");auto attributes=resolve_actor_attributes(kit.attributes,definition.loadout.starting_attributes);auto input=definition.input_profile==AssetId{}?kit.input:load_cooked_input(registry,cas,definition.input_profile);validate_combat_kit(*kit.definition,input);for(const auto& action:kit.input.actions){auto found=std::find_if(input.actions.begin(),input.actions.end(),[&](const auto& candidate){return candidate.id==action.id;});require(found!=input.actions.end()&&found->name==action.name&&found->kind==action.kind,"Player input profile reinterprets a semantic action");}return {std::move(masks),definition,std::move(character),std::move(kit),std::move(attributes),std::move(input)};}
namespace assets_detail {
Import import_actor(const std::filesystem::path& root,const std::filesystem::path& source,const std::map<std::string,AssetId>& ids,bool inspect){
 if(source.extension()==".dafacemask"){
  auto bytes=read(source,65536);auto data=json(bytes,65536);auto locators=data.at("sources");data.erase("sources");auto mask=mask_definition(data);if(!inspect)require(ids.size()==1&&ids.at("$source")==mask.id,"Mask source identity");
  require(locators.is_object()&&data.contains("visual")==locators.contains("visual"),"Mask visual reference/locator pair");auto base=locators;base.erase("visual");fields(base,{"kit"});
  Import result;result.inputs[source.lexically_relative(root).generic_string()]=sha256(bytes);std::map<AssetId,Product> products;std::set<AssetId> closure;
  auto merge=[&](Import imported){for(auto dep:imported.identities){require(dep!=mask.id,"Mask self/dependency identity conflict");closure.insert(dep);}for(const auto& [path,hash]:imported.inputs){auto [found,inserted]=result.inputs.emplace(path,hash);require(inserted||found->second==hash,"Mask source changed during cook");}for(auto& product:imported.products){closure.insert(product.id);auto [found,inserted]=products.emplace(product.id,product);require(inserted||(found->second.kind==product.kind&&found->second.extension==product.extension&&found->second.bytes==product.bytes&&found->second.required==product.required),"Mask conflicting shared generations");}};
  auto kit=within(root,locators.at("kit").get<std::string>());require(kit.extension()==".dakit"&&actor_reference(json(read(kit,65536)).at("asset"))==mask.kit,"Mask kit source type/identity");merge(import_combat_kit(root,kit,{{"$source",mask.kit}},inspect));
  if(mask.visual!=AssetId{}){auto visual=within(root,locators.at("visual").get<std::string>());require(visual.extension()==".glb"||visual.extension()==".gltf","Mask visual source type");auto sidecar=visual;sidecar+=".daimport";auto metadata=json(read(sidecar,1024*1024));require(metadata.at("schema")==1&&metadata.at("importer")=="static-gltf-v1"&&actor_reference(metadata.at("id"))==mask.visual,"Mask visual must be an imported static model");
   std::map<std::string,AssetId> mapping{{"$source",mask.visual}};for(const auto& [key,value]:metadata.at("subassets").items())mapping.emplace(key,actor_reference(value));auto imported=import_gltf(root,visual,mapping,inspect);for(const auto& [key,asset]:mapping)imported.identities.push_back(asset);merge(std::move(imported));result.inputs[sidecar.lexically_relative(root).generic_string()]=file_sha256(sidecar);}
  require(!closure.empty()&&closure.size()<=256,"Mask closure bounds");result.identities.assign(closure.begin(),closure.end());result.identities.push_back(mask.id);result.product_count=result.identities.size();if(inspect)return result;require(products.size()==closure.size(),"Mask closure product count");
  Json frozen=Json::object();std::vector<AssetId> dependencies;for(const auto& [asset,product]:products){frozen[asset.text()]=sha256(product.bytes);dependencies.push_back(asset);result.products.push_back(product);}data["frozen"]=std::move(frozen);result.products.push_back({mask.id,"mask","mask.json",data.dump(),dependencies});return result;
 }
 bool player=source.extension()==".daplayer";auto bytes=read(source,65536);auto data=json(bytes,65536);auto locators=data.at("sources");data.erase("sources");validate(data,player);auto locations=locators;if(player){require(data.contains("input_profile")==locators.contains("input_profile"),"Player input reference/locator pair");locations.erase("input_profile");require(data.at("loadout").contains("masks")==locators.contains("masks"),"Player mask slots/locators pair");locations.erase("masks");}fields(locations,player?std::initializer_list<const char*>{"character","kit"}:std::initializer_list<const char*>{"skin"});auto id=actor_reference(data.at("asset"));if(!inspect)require(ids.size()==1&&ids.at("$source")==id,"Actor source identity");
 Import result;result.inputs[source.lexically_relative(root).generic_string()]=sha256(bytes);std::map<AssetId,Product> products;std::set<AssetId> closure;
 auto merge=[&](Import imported){require(!imported.identities.empty(),"Actor dependency identities missing");for(auto dep:imported.identities){require(dep!=id,"Actor self/dependency identity conflict");closure.insert(dep);}for(const auto& [path,hash]:imported.inputs){auto [found,inserted]=result.inputs.emplace(path,hash);require(inserted||found->second==hash,"Actor source changed during cook");}for(auto& product:imported.products){auto [found,inserted]=products.emplace(product.id,product);require(inserted||(found->second.kind==product.kind&&found->second.extension==product.extension&&found->second.bytes==product.bytes&&found->second.required==product.required),"Actor conflicting shared generations");}};
 if(player){auto character=within(root,locators.at("character").get<std::string>()),kit=within(root,locators.at("kit").get<std::string>());require(character.extension()==".dacharacter"&&kit.extension()==".dakit","Player dependency type");auto character_id=actor_reference(data.at("character")),kit_id=actor_reference(data.at("loadout").at("kit"));require(actor_reference(json(read(character,65536)).at("asset"))==character_id&&actor_reference(json(read(kit,65536)).at("asset"))==kit_id,"Player source reference identity");merge(import_actor(root,character,{{"$source",character_id}},inspect));merge(import_combat_kit(root,kit,{{"$source",kit_id}},inspect));if(data.contains("input_profile")){auto input=within(root,locators.at("input_profile").get<std::string>());require(input.extension()==".dainput","Player input source type");auto selected=decode_input_source(read(input,65536));require(selected.id==actor_reference(data.at("input_profile")),"Player input source identity");auto kit_data=json(read(kit,65536));auto base=decode_input_source(read(within(root,kit_data.at("sources").at("input").get<std::string>()),65536));for(const auto& action:base.actions){auto found=std::find_if(selected.actions.begin(),selected.actions.end(),[&](const auto& candidate){return candidate.id==action.id;});require(found!=selected.actions.end()&&found->name==action.name&&found->kind==action.kind,"Player input profile reinterprets a semantic action");}merge(import_input(root,input,{{"$source",selected.id}},inspect));}
  ActorLoadoutDefinition loadout;equipped_masks(data.at("loadout"),loadout);if(loadout.masked){const auto& paths=locators.at("masks");std::size_t equipped{};auto base_kit=json(read(kit,65536));for(auto mask:loadout.masks)if(mask!=AssetId{}){++equipped;auto path=within(root,paths.at(mask.text()).get<std::string>());require(path.extension()==".dafacemask","Player mask source type");auto mask_data=json(read(path,65536));require(actor_reference(mask_data.at("asset"))==mask,"Player mask source identity");auto mask_kit=json(read(within(root,mask_data.at("sources").at("kit").get<std::string>()),65536));require(mask_kit.at("attributes")==base_kit.at("attributes")&&mask_kit.at("input")==base_kit.at("input"),"Equipped mask kit must share the Player's attribute schema and input profile");merge(import_actor(root,path,{{"$source",mask}},inspect));}require(paths.is_object()&&paths.size()==equipped,"Player mask locator catalogue");}}
 else {auto skin=within(root,locators.at("skin").get<std::string>());require(skin.extension()==".glb","Character skin source type");auto metadata_path=skin;metadata_path+=".daimport";auto metadata=json(read(metadata_path,1024*1024));require(metadata.at("schema")==1&&metadata.at("importer")=="human-gltf-v2"&&actor_reference(metadata.at("id"))==actor_reference(data.at("skin")),"Character requires matching renderable skin source");std::map<std::string,AssetId> mapping{{"$source",actor_reference(metadata.at("id"))}};for(const auto& [key,value]:metadata.at("subassets").items())mapping.emplace(key,actor_reference(value));auto canonical=within(root,metadata.at("canonical_source").get<std::string>());auto skeleton=json(read(canonical,65536));auto imported=import_human(root,skin,mapping,canonical,inspect,true);for(const auto& [key,asset]:mapping)imported.identities.push_back(asset);imported.identities.push_back(actor_reference(skeleton.at("asset")));imported.identities.push_back(actor_reference(skeleton.at("runtime")));merge(std::move(imported));result.inputs[metadata_path.lexically_relative(root).generic_string()]=file_sha256(metadata_path);}
 require(!closure.empty()&&closure.size()<=256,"Actor closure bounds");result.identities.assign(closure.begin(),closure.end());result.identities.push_back(id);result.product_count=result.identities.size();if(inspect)return result;
 require(products.size()==closure.size(),"Actor closure product count");
 if(player){auto character=json(products.at(actor_reference(data.at("character"))).bytes);auto skin=json(products.at(actor_reference(character.at("skin"))).bytes);auto kit=json(products.at(actor_reference(data.at("loadout").at("kit"))).bytes);auto graph=json(products.at(actor_reference(kit.at("locomotion_stance"))).bytes);resolve_actor_attributes(decode_attribute_asset(products.at(actor_reference(kit.at("attributes"))).bytes),starting_attributes(data.at("loadout")));bool checked=false;for(const auto& node:graph.at("nodes"))if(node.at("kind")=="clip"){auto clip=decode_clip_manifest(products.at(actor_reference(node.at("clip"))).bytes);require(clip.skeleton==actor_reference(skin.at("skeleton"))&&clip.signature==skin.at("signature").get<std::string>(),"Player Character/kit rig mismatch");checked=true;break;}require(checked,"Player kit graph requires a clip");}
 Json frozen=Json::object();std::vector<AssetId> dependencies;for(const auto& [asset,product]:products){frozen[asset.text()]=sha256(product.bytes);dependencies.push_back(asset);result.products.push_back(product);}data["frozen"]=std::move(frozen);result.products.push_back({id,player?"player":"character",player?"player.json":"character.json",data.dump(),dependencies});return result;
}
}
}
