#include "assets_internal.hpp"
#include <darkangel/actor_assets.hpp>
#include <darkangel/hash.hpp>
#include <set>
#include <cmath>
#include <algorithm>
namespace darkangel {
using namespace assets_detail;
namespace {
void fields(const Json& value,std::initializer_list<const char*> keys){require(value.is_object()&&value.size()==keys.size(),"Actor definition field count");for(auto key:keys)require(value.contains(key),"Actor definition missing/unknown field");}
AssetId actor_reference(const Json& value){auto id=AssetId::parse(value.get<std::string>());require(id!=AssetId{},"Actor reference must be nonzero");return id;}
std::vector<AbilityAttributeValue> starting_attributes(const Json& loadout){
 auto base=loadout;base.erase("starting_attributes");fields(base,{"kit"});std::vector<AbilityAttributeValue> result;std::set<AttributeId> used;
 if(loadout.contains("starting_attributes")){auto& values=loadout.at("starting_attributes");require(values.is_array()&&values.size()<=64,"Actor starting attribute count");for(const auto& value:values){fields(value,{"attribute","value"});require(value.at("attribute").is_number_unsigned()&&value.at("attribute").get<std::uint64_t>()<=UINT32_MAX&&value.at("value").is_number(),"Actor starting attribute type");auto id=value.at("attribute").get<AttributeId>();auto amount=value.at("value").get<double>();require(id&&used.insert(id).second&&std::isfinite(amount),"Actor starting attribute identity/value");result.push_back({id,amount});}}
 return result;
}
void validate(const Json& value,bool player){
 auto base=value;if(player)base.erase("input_profile");fields(base,player?std::initializer_list<const char*>{"schema","kind","asset","character","loadout"}:std::initializer_list<const char*>{"schema","kind","asset","skin"});
 require(value.at("schema")==1&&value.at("kind")== (player?"player":"character"),"Actor definition schema/type");actor_reference(value.at("asset"));
 if(player){if(value.contains("input_profile"))actor_reference(value.at("input_profile"));actor_reference(value.at("character"));starting_attributes(value.at("loadout"));actor_reference(value.at("loadout").at("kit"));}else actor_reference(value.at("skin"));
}
struct Frozen {
 std::map<AssetId,Json> records;std::filesystem::path cas;
 Frozen(const std::filesystem::path& path,const std::filesystem::path& storage):cas(storage){auto registry=json(read(path,1024*1024));require(registry.at("schema")==1&&registry.at("assets").is_array()&&!registry.at("assets").empty()&&registry.at("assets").size()<=512,"Actor registry bounds");for(const auto& record:registry.at("assets"))require(records.emplace(actor_reference(record.at("id")),record).second,"Actor registry duplicate identity");require(records.contains(actor_reference(registry.at("root"))),"Actor registry root missing");}
 Json load(AssetId id,bool player){auto& record=records.at(id);std::string kind=player?"player":"character",extension=kind+".json";require(record.at("kind")==kind&&record.at("extension")==extension,"Actor product type");auto digest=record.at("sha256").get<std::string>();require(digest.size()==64&&digest.find_first_not_of("0123456789abcdef")==digest.npos,"Actor product digest");auto bytes=read(cas/(digest+"."+extension),65536);require(sha256(bytes)==digest,"Actor product hash mismatch");auto data=json(bytes,65536);auto frozen=data.at("frozen");require(frozen.is_object()&&!frozen.empty()&&frozen.size()<=256,"Actor frozen closure bounds");for(const auto& [key,hash]:frozen.items())require(records.at(AssetId::parse(key)).at("sha256")==hash,"Actor frozen generation mismatch");auto pinned=[&](AssetId dep){require(frozen.contains(dep.text()),"Actor missing frozen dependency");};if(player){pinned(actor_reference(data.at("character")));pinned(actor_reference(data.at("loadout").at("kit")));}else pinned(actor_reference(data.at("skin")));if(player&&data.contains("input_profile"))pinned(actor_reference(data.at("input_profile")));data.erase("frozen");validate(data,player);require(actor_reference(data.at("asset"))==id,"Actor product identity mismatch");data["generation"]=digest;return data;}
};
}
std::vector<AttributeDefinition> resolve_actor_attributes(const AttributeAsset& schema,std::span<const AbilityAttributeValue> values){
 auto definitions=schema.definitions();std::set<AttributeId> used;
 for(const auto& value:values){auto field=std::find_if(definitions.begin(),definitions.end(),[&](const auto& field){return field.id==value.id;});require(field!=definitions.end()&&used.insert(value.id).second&&std::isfinite(value.value)&&value.value>=field->minimum&&value.value<=field->maximum,"Actor starting attribute violates schema");field->base=value.value;}
 AttributeSet probe(definitions);for(const auto& value:values)require(probe.value(value.id)==value.value,"Actor starting attribute exceeds effective bounds");return definitions;
}
CookedCharacter load_cooked_character(const std::filesystem::path& registry,const std::filesystem::path& cas,AssetId id){Frozen frozen(registry,cas);auto data=frozen.load(id,false);CharacterDefinition definition{id,actor_reference(data.at("skin")),data.at("generation")};return {definition,load_cooked_skinned_model(registry,cas,definition.skin)};}
CookedPlayer load_cooked_player(const std::filesystem::path& registry,const std::filesystem::path& cas,AssetId id){Frozen frozen(registry,cas);auto data=frozen.load(id,true);PlayerDefinition definition{id,actor_reference(data.at("character")),{actor_reference(data.at("loadout").at("kit")),starting_attributes(data.at("loadout"))},data.at("generation"),data.contains("input_profile")?actor_reference(data.at("input_profile")):AssetId{}};auto character=load_cooked_character(registry,cas,definition.character);auto kit=load_cooked_combat_kit(registry,cas,definition.loadout.kit);require(character.skin.rig.definition.id==kit.stance.rig.definition.id&&character.skin.rig.definition.signature==kit.stance.rig.definition.signature,"Player Character/kit rig mismatch");auto attributes=resolve_actor_attributes(kit.attributes,definition.loadout.starting_attributes);auto input=definition.input_profile==AssetId{}?kit.input:load_cooked_input(registry,cas,definition.input_profile);validate_combat_kit(*kit.definition,input);for(const auto& action:kit.input.actions){auto found=std::find_if(input.actions.begin(),input.actions.end(),[&](const auto& candidate){return candidate.id==action.id;});require(found!=input.actions.end()&&found->name==action.name&&found->kind==action.kind,"Player input profile reinterprets a semantic action");}return {definition,std::move(character),std::move(kit),std::move(attributes),std::move(input)};}
namespace assets_detail {
Import import_actor(const std::filesystem::path& root,const std::filesystem::path& source,const std::map<std::string,AssetId>& ids,bool inspect){
 bool player=source.extension()==".daplayer";auto bytes=read(source,65536);auto data=json(bytes,65536);auto locators=data.at("sources");data.erase("sources");validate(data,player);auto locations=locators;if(player){require(data.contains("input_profile")==locators.contains("input_profile"),"Player input reference/locator pair");locations.erase("input_profile");}fields(locations,player?std::initializer_list<const char*>{"character","kit"}:std::initializer_list<const char*>{"skin"});auto id=actor_reference(data.at("asset"));if(!inspect)require(ids.size()==1&&ids.at("$source")==id,"Actor source identity");
 Import result;result.inputs[source.lexically_relative(root).generic_string()]=sha256(bytes);std::map<AssetId,Product> products;std::set<AssetId> closure;
 auto merge=[&](Import imported){require(!imported.identities.empty(),"Actor dependency identities missing");for(auto dep:imported.identities){require(dep!=id,"Actor self/dependency identity conflict");closure.insert(dep);}for(const auto& [path,hash]:imported.inputs){auto [found,inserted]=result.inputs.emplace(path,hash);require(inserted||found->second==hash,"Actor source changed during cook");}for(auto& product:imported.products){auto [found,inserted]=products.emplace(product.id,product);require(inserted||(found->second.kind==product.kind&&found->second.extension==product.extension&&found->second.bytes==product.bytes&&found->second.required==product.required),"Actor conflicting shared generations");}};
 if(player){auto character=within(root,locators.at("character").get<std::string>()),kit=within(root,locators.at("kit").get<std::string>());require(character.extension()==".dacharacter"&&kit.extension()==".dakit","Player dependency type");auto character_id=actor_reference(data.at("character")),kit_id=actor_reference(data.at("loadout").at("kit"));require(actor_reference(json(read(character,65536)).at("asset"))==character_id&&actor_reference(json(read(kit,65536)).at("asset"))==kit_id,"Player source reference identity");merge(import_actor(root,character,{{"$source",character_id}},inspect));merge(import_combat_kit(root,kit,{{"$source",kit_id}},inspect));if(data.contains("input_profile")){auto input=within(root,locators.at("input_profile").get<std::string>());require(input.extension()==".dainput","Player input source type");auto selected=decode_input_source(read(input,65536));require(selected.id==actor_reference(data.at("input_profile")),"Player input source identity");auto kit_data=json(read(kit,65536));auto base=decode_input_source(read(within(root,kit_data.at("sources").at("input").get<std::string>()),65536));for(const auto& action:base.actions){auto found=std::find_if(selected.actions.begin(),selected.actions.end(),[&](const auto& candidate){return candidate.id==action.id;});require(found!=selected.actions.end()&&found->name==action.name&&found->kind==action.kind,"Player input profile reinterprets a semantic action");}merge(import_input(root,input,{{"$source",selected.id}},inspect));}}
 else {auto skin=within(root,locators.at("skin").get<std::string>());require(skin.extension()==".glb","Character skin source type");auto metadata_path=skin;metadata_path+=".daimport";auto metadata=json(read(metadata_path,1024*1024));require(metadata.at("schema")==1&&metadata.at("importer")=="human-gltf-v2"&&actor_reference(metadata.at("id"))==actor_reference(data.at("skin")),"Character requires matching renderable skin source");std::map<std::string,AssetId> mapping{{"$source",actor_reference(metadata.at("id"))}};for(const auto& [key,value]:metadata.at("subassets").items())mapping.emplace(key,actor_reference(value));auto canonical=within(root,metadata.at("canonical_source").get<std::string>());auto skeleton=json(read(canonical,65536));auto imported=import_human(root,skin,mapping,canonical,inspect,true);for(const auto& [key,asset]:mapping)imported.identities.push_back(asset);imported.identities.push_back(actor_reference(skeleton.at("asset")));imported.identities.push_back(actor_reference(skeleton.at("runtime")));merge(std::move(imported));result.inputs[metadata_path.lexically_relative(root).generic_string()]=file_sha256(metadata_path);}
 require(!closure.empty()&&closure.size()<=256,"Actor closure bounds");result.identities.assign(closure.begin(),closure.end());result.identities.push_back(id);result.product_count=result.identities.size();if(inspect)return result;
 require(products.size()==closure.size(),"Actor closure product count");
 if(player){auto character=json(products.at(actor_reference(data.at("character"))).bytes);auto skin=json(products.at(actor_reference(character.at("skin"))).bytes);auto kit=json(products.at(actor_reference(data.at("loadout").at("kit"))).bytes);auto graph=json(products.at(actor_reference(kit.at("locomotion_stance"))).bytes);resolve_actor_attributes(decode_attribute_asset(products.at(actor_reference(kit.at("attributes"))).bytes),starting_attributes(data.at("loadout")));bool checked=false;for(const auto& node:graph.at("nodes"))if(node.at("kind")=="clip"){auto clip=decode_clip_manifest(products.at(actor_reference(node.at("clip"))).bytes);require(clip.skeleton==actor_reference(skin.at("skeleton"))&&clip.signature==skin.at("signature").get<std::string>(),"Player Character/kit rig mismatch");checked=true;break;}require(checked,"Player kit graph requires a clip");}
 Json frozen=Json::object();std::vector<AssetId> dependencies;for(const auto& [asset,product]:products){frozen[asset.text()]=sha256(product.bytes);dependencies.push_back(asset);result.products.push_back(product);}data["frozen"]=std::move(frozen);result.products.push_back({id,player?"player":"character",player?"player.json":"character.json",data.dump(),dependencies});return result;
}
}
}
