#include "assets_internal.hpp"
#include <darkangel/effect_assets.hpp>
#include <darkangel/animation_assets.hpp>
#include <darkangel/hash.hpp>
#include <algorithm>
#include <set>
namespace darkangel {
using namespace assets_detail;
namespace {
void fields(const Json& value,std::initializer_list<const char*> expected){require(value.is_object()&&value.size()==expected.size(),"Effect/tag fields");for(auto key:expected)require(value.contains(key),"Missing effect/tag field");}
std::uint64_t integer(const Json& value,std::uint64_t maximum){require(value.is_number_integer()&&!value.is_boolean()&&(value.is_number_unsigned()||value.get<std::int64_t>()>=0),"Effect/tag nonnegative integer");auto result=value.get<std::uint64_t>();require(result<=maximum,"Effect/tag integer bound");return result;}
AssetId reference(const Json& value){return AssetId::parse(value.get<std::string>());}
TagAsset tags(const Json& source){
 fields(source,{"schema","kind","asset","tags"});require(source.at("schema")==1&&source.at("kind")=="tags"&&source.at("tags").is_array()&&source.at("tags").size()<=128,"Tag registry schema/bound");TagAsset result;result.id=reference(source.at("asset"));require(result.id!=AssetId{},"Tag registry root identity");result.generation=sha256(source.dump());std::set<AssetId> keys;
 for(const auto& entry:source.at("tags")){fields(entry,{"key","id","parent","name","visibility"});TagAssetField field;field.key=reference(entry.at("key"));require(field.key!=AssetId{}&&keys.insert(field.key).second,"Persistent tag key");field.definition.id=static_cast<TagId>(integer(entry.at("id"),UINT32_MAX));field.definition.parent=static_cast<TagId>(integer(entry.at("parent"),UINT32_MAX));field.definition.name=entry.at("name").get<std::string>();auto visibility=entry.at("visibility").get<std::string>();require(visibility=="server"||visibility=="owner"||visibility=="public","Tag visibility");field.definition.visibility=visibility=="public"?AttributeVisibility::Public:visibility=="owner"?AttributeVisibility::Owner:AttributeVisibility::Server;result.fields.push_back(std::move(field));}
 result.dictionary();return result;
}
std::vector<TagId> tag_ids(const Json& array){require(array.is_array()&&array.size()<=16,"Effect tag list bound");std::vector<TagId> result;for(const auto& id:array)result.push_back(static_cast<TagId>(integer(id,UINT32_MAX)));return result;}
TagRequirement requirement(const Json& source){fields(source,{"all","any","none"});return {tag_ids(source.at("all")),tag_ids(source.at("any")),tag_ids(source.at("none"))};}
// The optional reaction is a typed reference to one native Composer action. Its
// frozen definition is supplied by the cooked closure; inspection validates shape only.
std::shared_ptr<const EffectDefinition> effect(const Json& source,const AttributeAsset& attributes,const TagAsset& registry,std::shared_ptr<const ActionDefinition> reaction={},bool reaction_inspected=false){
 auto base=source;base.erase("visibility");base.erase("cues");base.erase("reaction");base.erase("reaction_loop");base.erase("lock_movement");fields(base,{"schema","kind","asset","attributes","tags","lifetime","stacking","duration_ticks","period_ticks","execute_on_apply","remove_on_death","remove_with_source","interrupt_action","evaluator","granted_tags","application","ongoing","ongoing_policy","modifiers"});
 require(source.at("schema")==1&&source.at("kind")=="effect"&&reference(source.at("attributes"))==attributes.id&&reference(source.at("tags"))==registry.id,"Effect schema/dependency identity");EffectDefinition d;d.id=reference(source.at("asset"));d.generation=sha256(source.dump()+attributes.generation+registry.generation+(reaction?reaction->generation:std::string{}));
 if(source.contains("reaction")){auto action=reference(source.at("reaction"));require(action!=AssetId{}&&action!=d.id&&(reaction_inspected||(reaction&&reaction->id==action)),"Effect reaction action identity");d.reaction=std::move(reaction);}else require(!reaction,"Unexpected effect reaction action");
 auto lifetime=source.at("lifetime").get<std::string>();require(lifetime=="instant"||lifetime=="finite"||lifetime=="until_removed","Effect lifetime");d.lifetime=lifetime=="instant"?EffectLifetime::Instant:lifetime=="finite"?EffectLifetime::Finite:EffectLifetime::UntilRemoved;
 auto stacking=source.at("stacking").get<std::string>();require(stacking=="independent"||stacking=="refresh_per_source","Effect stacking");d.stacking=stacking=="independent"?EffectStack::Independent:EffectStack::RefreshPerSource;
 if(source.contains("visibility")){auto audience=source.at("visibility").get<std::string>();require(audience=="server"||audience=="owner"||audience=="public","Effect visibility");d.visibility=audience=="public"?AttributeVisibility::Public:audience=="owner"?AttributeVisibility::Owner:AttributeVisibility::Server;}
 // Optional flags; sources without them keep their generation.
 if(source.contains("reaction_loop")){require(source.at("reaction_loop").is_boolean(),"Effect reaction loop flag");d.reaction_loop=source.at("reaction_loop").get<bool>();}
 if(source.contains("lock_movement")){require(source.at("lock_movement").is_boolean(),"Effect movement lock flag");d.lock_movement=source.at("lock_movement").get<bool>();}
 if(source.contains("cues")){auto& cues=source.at("cues");require(cues.is_array()&&cues.size()<=4,"Effect cue source count");for(const auto& cue:cues){fields(cue,{"id","key"});d.cues.push_back({reference(cue.at("id")),cue.at("key").get<std::string>()});}}
 auto policy=source.at("ongoing_policy").get<std::string>();require(policy=="suppress"||policy=="remove","Effect ongoing policy");d.ongoing_policy=policy=="suppress"?EffectOngoingPolicy::Suppress:EffectOngoingPolicy::Remove;
 d.duration_ticks=integer(source.at("duration_ticks"),36000);d.period_ticks=integer(source.at("period_ticks"),36000);d.evaluator=static_cast<std::uint32_t>(integer(source.at("evaluator"),UINT32_MAX));d.execute_on_apply=source.at("execute_on_apply").get<bool>();d.remove_on_death=source.at("remove_on_death").get<bool>();d.remove_with_source=source.at("remove_with_source").get<bool>();d.interrupt_action=source.at("interrupt_action").get<bool>();d.tags=tag_ids(source.at("granted_tags"));d.application=requirement(source.at("application"));d.ongoing=requirement(source.at("ongoing"));
 require(source.at("modifiers").is_array()&&source.at("modifiers").size()<=16,"Effect modifier count");for(const auto& entry:source.at("modifiers")){fields(entry,{"attribute","kind","magnitude","channel","priority"});AttributeModifier m;m.attribute=static_cast<AttributeId>(integer(entry.at("attribute"),UINT32_MAX));auto kind=entry.at("kind").get<std::string>();require(kind=="flat"||kind=="channel_bonus"||kind=="post"||kind=="override","Effect modifier kind");m.kind=kind=="flat"?AttributeModifierKind::Flat:kind=="channel_bonus"?AttributeModifierKind::ChannelBonus:kind=="post"?AttributeModifierKind::Post:AttributeModifierKind::Override;require(entry.at("magnitude").is_number()&&entry.at("priority").is_number_integer(),"Effect modifier scalar types");m.magnitude=entry.at("magnitude").get<double>();require(!entry.at("priority").is_number_unsigned()||entry.at("priority").get<std::uint64_t>()<=32767,"Effect unsigned priority bound");auto priority=entry.at("priority").get<std::int64_t>();require(priority>=-32768&&priority<=32767,"Effect modifier priority bound");m.priority=static_cast<int>(priority);m.channel=entry.at("channel").get<std::string>();d.modifiers.push_back(std::move(m));}
 // Inspection has no frozen reaction action yet; the reference/flag pairing is still checked here.
 require(!d.reaction_loop||source.contains("reaction"),"Effect reaction loop needs a reaction timeline");if(reaction_inspected&&!d.reaction)d.reaction_loop=false;
 return freeze_effect_definition(d,AttributeSet(attributes.definitions()),*registry.dictionary());
}
struct Registry {
 std::map<AssetId,Json> records;std::filesystem::path cas;
 Registry(const std::filesystem::path& path,const std::filesystem::path& storage):cas(storage){auto manifest=json(read(path,1024*1024));require(manifest.at("schema")==1&&manifest.at("assets").is_array()&&!manifest.at("assets").empty()&&manifest.at("assets").size()<=512,"Effect registry schema/bound");for(const auto& record:manifest.at("assets"))require(records.emplace(reference(record.at("id")),record).second,"Duplicate effect registry identity");require(records.contains(reference(manifest.at("root"))),"Effect registry root missing");}
 Json load(AssetId id,const char* kind,const char* extension)const{auto found=records.find(id);require(found!=records.end(),"Missing effect dependency");auto& record=found->second;require(record.at("kind")==kind&&record.at("extension")==extension,"Effect dependency product type");auto hash=record.at("sha256").get<std::string>();require(hash.size()==64&&hash.find_first_not_of("0123456789abcdef")==hash.npos,"Effect product digest");auto bytes=read(cas/(hash+"."+extension),65536);require(sha256(bytes)==hash,"Effect product hash mismatch");auto result=json(bytes,65536);require(reference(result.at("asset"))==id,"Effect product identity mismatch");return result;}
};
}
std::shared_ptr<const TagDictionary> TagAsset::dictionary()const{std::vector<TagDefinition> definitions;for(const auto& field:fields)definitions.push_back(field.definition);return std::make_shared<const TagDictionary>(std::move(definitions),id,generation);}
TagAsset load_cooked_tags(const std::filesystem::path& registry,const std::filesystem::path& cas,AssetId id){return tags(Registry(registry,cas).load(id,"tags","tags.json"));}
TagAsset decode_tag_asset(std::string_view bytes){return tags(json(bytes,65536));}
CookedEffect load_cooked_effect(const std::filesystem::path& registry,const std::filesystem::path& cas,AssetId id){
 Registry records(registry,cas);auto source=records.load(id,"effect","effect.json");auto attributes=load_cooked_attributes(registry,cas,reference(source.at("attributes")));auto dictionary=tags(records.load(reference(source.at("tags")),"tags","tags.json"));require(source.at("attributes_generation")==attributes.generation&&source.at("tags_generation")==dictionary.generation,"Effect frozen dependency generation mismatch");source.erase("attributes_generation");source.erase("tags_generation");
 std::shared_ptr<const ActionDefinition> reaction;if(source.contains("reaction")){reaction=std::make_shared<const ActionDefinition>(load_cooked_action(registry,cas,reference(source.at("reaction"))));require(source.at("reaction_generation")==reaction->generation,"Effect frozen reaction generation mismatch");source.erase("reaction_generation");}else require(!source.contains("reaction_generation"),"Unexpected effect reaction generation");
 return {effect(source,attributes,dictionary,std::move(reaction)),std::move(attributes),std::move(dictionary)};
}
namespace assets_detail {
Import import_effect(const std::filesystem::path& root,const std::filesystem::path& source,const std::map<std::string,AssetId>& ids,bool inspect){
 auto bytes=read(source,65536);auto data=json(bytes,65536);auto id=reference(data.at("asset"));Import result;result.inputs[source.lexically_relative(root).generic_string()]=sha256(bytes);result.identities.push_back(id);if(!inspect)require(ids.size()==1&&ids.at("$source")==id,"Effect/tag source UUID mismatch");
 if(source.extension()==".datags"){tags(data);result.product_count=1;if(!inspect)result.products.push_back({id,"tags","tags.json",data.dump(),{}});return result;}
 require(source.extension()==".daeffect"&&data.contains("sources"),"Effect source locators");auto locations=data.at("sources");require(locations.is_object()&&data.contains("reaction")==locations.contains("reaction"),"Effect reaction reference/locator pair");if(data.contains("reaction"))fields(locations,{"attributes","tags","reaction"});else fields(locations,{"attributes","tags"});data.erase("sources");auto attributes_path=within(root,locations.at("attributes").get<std::string>()),tags_path=within(root,locations.at("tags").get<std::string>());require(attributes_path.extension()==".daattributes"&&tags_path.extension()==".datags","Effect source dependency type");
 auto attributes_import=import_ability(root,attributes_path,{{"$source",reference(data.at("attributes"))}},false);auto dictionary=tags(json(read(tags_path,65536)));require(dictionary.id==reference(data.at("tags")),"Effect tag source identity mismatch");
 auto attributes=decode_attribute_asset(attributes_import.products.at(0).bytes);
 Import reaction_import;std::shared_ptr<const ActionDefinition> reaction;
 if(data.contains("reaction")){
  auto action_id=reference(data.at("reaction"));auto action_path=within(root,locations.at("reaction").get<std::string>());require(action_path.extension()==".daaction","Effect reaction source type");auto action_bytes=read(action_path,65536);auto action_source=json(action_bytes,65536);
  // Early typed source diagnostics; the frozen definition repeats them at preparation.
  require(reference(action_source.at("asset"))==action_id&&action_source.at("schema")==2&&action_source.contains("motion"),"Effect reaction needs a Composer action with a clip");require(action_source.at("slot")=="full-body"&&!action_source.contains("mask")&&action_source.at("loops")==1&&action_source.at("motion").at("policy")=="none","Effect reaction needs a one-shot full-body action with root policy none");
  for(const auto& block:action_source.at("blocks"))require(block.at("kind")=="cue","Effect reaction action cannot carry gameplay blocks; presentation never executes them");
  reaction_import=import_action(root,action_path,{{"$source",action_id}},inspect);const auto& closure=reaction_import.identities;require(std::none_of(closure.begin(),closure.end(),[&](AssetId asset){return asset==id||asset==attributes.id||asset==dictionary.id;}),"Effect reaction closure identity conflict");
  if(!inspect)for(const auto& product:reaction_import.products)if(product.id==action_id)reaction=std::make_shared<const ActionDefinition>(decode_action_source(product.bytes));
  result.inputs.insert(reaction_import.inputs.begin(),reaction_import.inputs.end());
 }
 effect(data,attributes,dictionary,reaction,inspect);require(id!=attributes.id&&id!=dictionary.id&&attributes.id!=dictionary.id,"Effect closure duplicate UUID");result.product_count=3+reaction_import.product_count;result.inputs.insert(attributes_import.inputs.begin(),attributes_import.inputs.end());result.inputs[tags_path.lexically_relative(root).generic_string()]=sha256(read(tags_path,65536));result.identities.push_back(attributes.id);result.identities.push_back(dictionary.id);result.identities.insert(result.identities.end(),reaction_import.identities.begin(),reaction_import.identities.end());
 if(!inspect){data["attributes_generation"]=attributes.generation;data["tags_generation"]=dictionary.generation;std::vector<AssetId> required{attributes.id,dictionary.id};if(reaction){data["reaction_generation"]=reaction->generation;required.push_back(reaction->id);}result.products.push_back({id,"effect","effect.json",data.dump(),std::move(required)});for(auto& product:reaction_import.products)result.products.push_back(std::move(product));result.products.push_back(std::move(attributes_import.products.at(0)));auto tag_data=json(read(tags_path,65536));result.products.push_back({dictionary.id,"tags","tags.json",tag_data.dump(),{}});}return result;
}
}
}
