#include <darkangel/ability_observer.hpp>
#include <darkangel/ability_prediction.hpp>
#include "../engine/runtime/ability_wire.hpp"
#include <algorithm>
#include <iostream>
#include <limits>
using namespace darkangel;
namespace {
void check(bool b,const char* error){if(!b)throw std::runtime_error(error);}
template<class F>void rejects(F f){bool rejected=false;try{f();}catch(const std::exception&){rejected=true;}check(rejected,"Expected bounded public-state rejection");}
std::uint64_t word(std::span<const std::byte> bytes,std::size_t at){std::uint64_t value{};for(unsigned n=0;n<8;++n)value|=std::uint64_t(std::to_integer<unsigned char>(bytes[at+n]))<<(n*8);return value;}
class Delayed:public Transport {
    Transport& inner;
public:
    bool hold{};std::deque<TransportMessage> delayed;std::size_t maximum_packet{};
    explicit Delayed(Transport& value):inner(value){}
    ConnectionHandle open(const SessionHandshake& h)override{return inner.open(h);}bool connected()const override{return inner.connected();}bool valid(ConnectionHandle h)const override{return inner.valid(h);}TransportLimits limits()const override{return inner.limits();}
    bool send(ConnectionHandle h,Delivery d,std::span<const std::byte> bytes)override{return inner.send(h,d,bytes);}void disconnect(ConnectionHandle h)override{inner.disconnect(h);}
    std::vector<TransportMessage> poll(std::size_t count)override{std::vector<TransportMessage> result;if(!hold)while(!delayed.empty()&&result.size()<count){result.push_back(std::move(delayed.front()));delayed.pop_front();}for(auto& message:inner.poll(count-result.size())){maximum_packet=std::max(maximum_packet,message.bytes.size());if(hold&&word(message.bytes,8)==15){check(delayed.size()<128,"Fixture delayed packet bound");delayed.push_back(std::move(message));}else result.push_back(std::move(message));}return result;}
};
double value(const std::vector<AbilityAttributeValue>& fields,AttributeId id){for(auto field:fields)if(field.id==id)return field.value;return -1;}
struct Fixture {
    SessionHandshake hello{3,std::string(64,'a'),std::string(64,'b'),77};LoopbackPair transport=create_loopback(hello);Delayed delayed{*transport.client};WorldSession server{SessionRole::Server,hello},client{SessionRole::Client,hello};ConnectionHandle hp,cp;std::uint64_t id{};AbilityOwnerHandle owner;
    std::vector<AttributeDefinition> schema{{1,"MaxHealth",AttributeKind::Statistic,100,0,1000,0,AttributeVisibility::Public},{2,"Health",AttributeKind::Resource,100,0,1000,1,AttributeVisibility::Public},{3,"Stamina",AttributeKind::Resource,60,0,60,0,AttributeVisibility::Owner},{4,"Barrier",AttributeKind::Resource,60,0,60,0,AttributeVisibility::Public},{5,"Secret",AttributeKind::Resource,77,0,100,0,AttributeVisibility::Server}};
    InputProfile input;std::shared_ptr<CombatKitDefinition> kit=std::make_shared<CombatKitDefinition>();std::shared_ptr<ActionDefinition> action=std::make_shared<ActionDefinition>();std::shared_ptr<AbilityDefinition> ability=std::make_shared<AbilityDefinition>();std::array<std::shared_ptr<const AbilityDefinition>,1> catalogue;
    Fixture(){hp=transport.host->open(hello);cp=delayed.open(hello);server.attach(*transport.host,hp);client.attach(delayed,cp);ObjectData object;object.id={4,1};id=server.create(object);for(unsigned i=6;i<=64;++i)schema.push_back({i,"Public"+std::to_string(i),AttributeKind::Statistic,double(i),0,1000,0,AttributeVisibility::Public});owner=server.configure_abilities(id,schema,2,1);
        input.id=AssetId::random();kit->id=AssetId::random();kit->generation="kit";kit->locomotion_stance=AssetId::random();for(unsigned i=0;i<combat_slot_count;++i){input.actions.push_back({i+1,"combat."+std::to_string(i),InputActionKind::Button});kit->slots[i]={static_cast<CombatSlot>(i),i+1,{}};}
        action->id=AssetId::random();action->generation=std::string(64,'c');action->duration=10*action_tick_units;action->loops=1;action->blocks={{1,0,0,0,ActionBlockKind::Cue,"attack"}};ability->id=AssetId::random();ability->generation=std::string(64,'d');ability->action=action;ability->costs={{3,20},{4,5}};kit->slots[0].ability=ability->id;catalogue={ability};server.equip_combat_kit(owner,kit,input,catalogue);server.own_motor(id,hp);server.publish_motor(id,{});
    }
    void pump(unsigned count=16){for(unsigned i=0;i<count;++i){server.tick();client.tick();}}
    AbilityReceipt activate(){return server.request_ability({owner,1,1,CombatSlot::Light,{1,InputEdge::Pressed,0,0,1,false},false});}
    void step(){auto tick=server.ability_snapshot(owner).tick+1;server.advance_abilities(tick);server.drain_ability_actions();auto motor=server.motors().at(id);motor.tick=tick;motor.sequence=tick;motor.position.z=double(tick);motor.achieved.z=1;server.publish_motor(id,motor);}
    ObserverAbility buffer(){return {schema,2,1,std::array<std::shared_ptr<const ActionDefinition>,1>{action}};}
};
void privacy_late_join(){Fixture f;f.pump();check(f.activate().committed,"Authoritative activation");f.server.drain_ability_actions();f.step();f.step();f.pump();auto owner=f.client.ability_corrections().at(f.id).ability;check(value(owner.attributes,3)==40&&value(owner.attributes,5)==-1,"Owner correction includes private resource and excludes server-only values");OwnerAbilityPrediction predictor(owner,f.schema,f.kit,f.input,f.catalogue);check(value(predictor.view().attributes,3)==40&&value(predictor.view().attributes,5)==-1,"Prediction schema omits server-only state");
    auto pair=create_loopback(f.hello);WorldSession observer(SessionRole::Client,f.hello);auto hp=pair.host->open(f.hello),cp=pair.client->open(f.hello);f.server.attach(*pair.host,hp);observer.attach(*pair.client,cp);for(unsigned i=0;i<24;++i){f.server.tick();f.client.tick();observer.tick();}
    const auto& public_frame=observer.public_abilities().at(f.id);check(observer.ability_corrections().empty()&&public_frame.ability.active&&public_frame.ability.action->clock==2*action_tick_units&&public_frame.motor.tick==2,"Active late join receives current coherent phase without private grants/receipts");check(value(public_frame.ability.attributes,3)==-1&&value(public_frame.ability.attributes,5)==-1&&value(public_frame.ability.attributes,4)==55,"Public resource outcome obeys cooked visibility");check(observer.world().valid(public_frame.ability.owner.entity)&&!observer.public_ability_needs_resync(f.id),"Public owner resolves through current lifecycle baseline");check(f.server.drain_ability_actions().empty(),"Late join cannot replay previous start cues or damage");auto buffer=f.buffer();buffer.push(public_frame);check(buffer.sample(2).action_clock==2*action_tick_units,"Late observer samples actual clock instead of starting at zero");
    for(unsigned i=0;i<8;++i){f.step();f.server.tick();f.client.tick();observer.tick();}for(unsigned i=0;i<16;++i){f.server.tick();observer.tick();}check(!observer.public_abilities().at(f.id).ability.active,"Reliable current public state releases completed action");
    f.server.destroy(f.id);for(unsigned i=0;i<24;++i){f.server.tick();f.client.tick();observer.tick();}check(observer.public_abilities().empty()&&observer.objects().empty(),"Despawn reliable baseline removes public action and resource references");
}
void interpolation(){Fixture f;f.activate();f.server.drain_ability_actions();f.step();f.pump();auto first=f.client.public_abilities().at(f.id);auto buffer=f.buffer();buffer.push(first);f.step();f.step();f.pump();auto second=f.client.public_abilities().at(f.id);buffer.push(second);auto middle=buffer.sample(2);check(middle.frame.motor.position.z==2&&middle.action_clock==2*action_tick_units,"Motor and action share delayed interpolation clock");auto extrapolated=buffer.sample(4);check(extrapolated.extrapolated&&!extrapolated.held&&extrapolated.action_clock==4*action_tick_units,"Observer permits bounded phase extrapolation");auto held=buffer.sample(100);check(held.held&&held.frame.motor.position.z==5&&held.action_clock==5*action_tick_units,"After two ticks observer holds instead of unbounded extrapolation");
    auto invalid=second;invalid.ability.action->generation=std::string(64,'e');rejects([&]{buffer.push(invalid);});check(buffer.size()==2&&buffer.sample(2).action_clock==2*action_tick_units,"Failed asset preparation retains prior observer buffer");
    auto teleported=second;teleported.motor.epoch++;teleported.motor.position.z=20;buffer.push(teleported);check(buffer.size()==1&&buffer.sample(3).frame.motor.position.z==20,"Avatar epoch resets interpolation history");
    auto private_field=teleported;private_field.ability.attributes.push_back({3,40});rejects([&]{buffer.push(private_field);});check(buffer.size()==1,"Observer preparation rejects leaked private attribute");
}
void fragmentation_recovery(){Fixture f;f.delayed.hold=true;f.pump();check(f.client.public_abilities().empty()&&f.delayed.delayed.size()>=2,"Partial public fragments cannot publish state");std::reverse(f.delayed.delayed.begin(),f.delayed.delayed.end());f.delayed.delayed.push_back(f.delayed.delayed.front());f.delayed.hold=false;f.pump();check(f.client.public_abilities().at(f.id).ability.attributes.size()==62&&f.delayed.maximum_packet<=1000,"Reordered duplicate public fragments publish within packet budget");
    Fixture lost;lost.delayed.hold=true;lost.pump();auto fragment=std::move(lost.delayed.delayed.front());lost.delayed.delayed.clear();lost.delayed.delayed.push_back(std::move(fragment));lost.delayed.hold=false;lost.client.tick();lost.delayed.hold=true;for(unsigned i=0;i<35;++i)lost.client.tick();check(lost.client.public_abilities().empty()&&lost.client.public_ability_needs_resync(lost.id),"Incomplete group expires with explicit observer resync");lost.delayed.delayed.clear();lost.delayed.hold=false;lost.pump(64);check(lost.client.public_abilities().contains(lost.id)&&!lost.client.public_ability_needs_resync(lost.id),"Periodic public keyframe recovers missing fragments");
}
void codec(){Fixture f;f.pump();auto frame=f.client.public_abilities().at(f.id);auto bytes=session_detail::encode_ability_public(frame);check(session_detail::decode_ability_public(bytes).ability.attributes.size()==62,"Public explicit codec roundtrip");bytes.pop_back();rejects([&]{session_detail::decode_ability_public(bytes);});auto bad=frame;bad.ability.attributes[0].value=std::numeric_limits<double>::infinity();rejects([&]{session_detail::decode_ability_public(session_detail::encode_ability_public(bad));});bad=frame;bad.ability.tick++;rejects([&]{session_detail::decode_ability_public(session_detail::encode_ability_public(bad));});bad=frame;bad.ability.attributes[1].id=bad.ability.attributes[0].id;rejects([&]{session_detail::decode_ability_public(session_detail::encode_ability_public(bad));});}
void conflict_and_direction(){Fixture f;f.delayed.hold=true;f.pump();check(f.delayed.delayed.size()>=2,"Captured public group for conflict probe");auto original=f.delayed.delayed.front(),conflict=original;conflict.bytes.back()^=std::byte{1};f.delayed.delayed.clear();f.delayed.delayed.push_back(original);f.delayed.delayed.push_back(conflict);f.delayed.hold=false;rejects([&]{f.client.tick();});check(f.client.public_abilities().empty(),"Conflicting duplicate fragments cannot publish a partial public state");
    Fixture forged;forged.delayed.hold=true;forged.pump();auto packet=forged.delayed.delayed.front();check(forged.delayed.send(forged.cp,Delivery::UnreliableState,packet.bytes),"Fixture forged public packet delivered");rejects([&]{forged.server.tick();});check(forged.server.world().read(forged.owner.entity).health.current==100,"Wrong-direction public frame cannot change server Health");
}
void bounds_and_hold(){Fixture f;for(unsigned i=0;i<3;++i){ObjectData object;object.id={4,i+2};auto id=f.server.create(object);f.server.configure_abilities(id,f.schema,2,1);f.server.own_motor(id,f.hp);f.server.publish_motor(id,{});}f.pump(64);check(f.client.public_abilities().size()==4&&f.client.ability_corrections().size()==4,"Four actors publish bounded public and private audiences without starvation at rest");
    Fixture stopped;stopped.activate();stopped.server.drain_ability_actions();stopped.step();stopped.pump();auto frame=stopped.client.public_abilities().at(stopped.id);auto buffer=stopped.buffer();frame.ability.action->rate=0;buffer.push(frame);check(buffer.sample(3).action_clock==action_tick_units,"Replicated hitstop holds observer action clock during extrapolation");buffer.reset();check(buffer.size()==0,"Lifecycle reset releases prior actor presentation");rejects([&]{buffer.sample(3);});
}
}
int main(){try{privacy_late_join();interpolation();fragmentation_recovery();codec();conflict_and_direction();bounds_and_hold();std::cout<<"Public ability visibility, coherent observer phase/motor, active late join, lifecycle, fragmented recovery and prepared bounded interpolation passed\n";return 0;}catch(const std::exception& error){std::cerr<<error.what()<<'\n';return 1;}}
