#include <darkangel/gns_transport.hpp>
#include <darkangel/world_session.hpp>
#include <chrono>
#include <thread>
#include <iostream>
using namespace darkangel;
namespace {void check(bool b,const char* message){if(!b)throw std::runtime_error(message);}}
int main(int argc,char** argv){try{
    check(argc==2,"Use --host or --client");bool host=std::string(argv[1])=="--host";check(host||std::string(argv[1])=="--client","Unknown GNS role");SessionHandshake hello{3,std::string(64,'a'),std::string(64,'b'),337};auto transport=host?create_gns_host("127.0.0.1:27149",hello):create_gns_client("127.0.0.1:27149",hello);auto peer=transport->open(hello);auto connect_deadline=std::chrono::steady_clock::now()+std::chrono::seconds(10);while(!transport->connected()&&std::chrono::steady_clock::now()<connect_deadline)std::this_thread::sleep_for(std::chrono::milliseconds(2));check(transport->connected(),"GNS ability connect deadline");WorldSession session(host?SessionRole::Server:SessionRole::Client,hello);session.attach(*transport,peer);AbilityOwnerHandle owner;
    if(host){ObjectData object;object.id={77,1};auto id=session.create(object);owner=session.configure_abilities(id,{{1,"MaxHealth",AttributeKind::Statistic,100,0,1000,0},{2,"Health",AttributeKind::Resource,100,0,1000,1},{3,"Stamina",AttributeKind::Resource,60,0,60,0}},2,1);InputProfile input;input.id=AssetId::random();auto kit=std::make_shared<CombatKitDefinition>();kit->id=AssetId::random();kit->generation="kit";kit->locomotion_stance=AssetId::random();for(unsigned i=0;i<combat_slot_count;++i){input.actions.push_back({i+1,"combat."+std::to_string(i),InputActionKind::Button});kit->slots[i]={static_cast<CombatSlot>(i),i+1,{}};}auto action=std::make_shared<ActionDefinition>();action->id=AssetId::random();action->generation=std::string(64,'a');action->duration=8*action_tick_units;action->loops=1;auto ability=std::make_shared<AbilityDefinition>();ability->id=AssetId::random();ability->generation=std::string(64,'b');ability->action=action;ability->costs={{2,10},{3,20}};kit->slots[0].ability=ability->id;std::array<std::shared_ptr<const AbilityDefinition>,1> catalogue{ability};session.equip_combat_kit(owner,kit,input,catalogue);session.own_motor(id,peer);session.publish_motor(id,MotorState{});}
    unsigned submitted{},executed{},terminal{};std::uint64_t activation{};bool saw_inclusion{},acked{};auto deadline=std::chrono::steady_clock::now()+std::chrono::seconds(20);
    while(std::chrono::steady_clock::now()<deadline){session.tick();if(session.readiness(peer)==SessionReadiness::Ready){
        if(!host&&session.ability_corrections().contains(1)){const auto& correction=session.ability_corrections().at(1);
            for(const auto& notice:session.drain_ability_receipts()){check(notice.terminal&&notice.receipt.committed&&notice.receipt.operation==1,"GNS canonical accepted receipt");if(activation)check(activation==notice.receipt.handle.activation,"GNS duplicate activation identity");activation=notice.receipt.handle.activation;++terminal;}
            for(const auto& operation:correction.ability.operations)if(operation.operation==1){check(operation.committed&&operation.activation,"GNS exact authoritative inclusion");if(activation)check(operation.activation==activation,"GNS receipt/inclusion identity");else activation=operation.activation;saw_inclusion=true;}
            if(correction.ability.highest_operation==1&&correction.ability.attributes[1].value==90&&correction.ability.attributes[2].value==40){check(correction.motor.tick==correction.ability.tick,"GNS coherent owner bundle");session.acknowledge_ability_correction(1);acked=true;}
            if(submitted<6&&correction.motor.tick==submitted){auto next=submitted+1;if(next==1){AbilityIntent intent{1,1,1,correction.motor.epoch,correction.ability.grant_generation,CombatSlot::Light,InputEdge::Pressed,false,false};check(session.submit_ability_intent(intent)&&session.submit_ability_intent(intent),"GNS duplicate intent send");}check(session.submit_motor(1,{next,next,correction.motor.epoch}),"GNS typed step/control input");++submitted;}
            if(submitted==6&&correction.motor.tick==6&&activation&&terminal&&saw_inclusion&&acked&&correction.ability.retired_through==1&&session.public_abilities().contains(1)&&session.public_abilities().at(1).motor.tick==6){const auto& public_frame=session.public_abilities().at(1);check(public_frame.ability.attributes.size()==2&&public_frame.ability.active&&public_frame.ability.action->clock==5*action_tick_units,"GNS public phase/resource audience");check(session.objects().at(1).health.current==90,"GNS public Health baseline and action phase");check(session.submit_motor(1,{7,7,correction.motor.epoch}),"GNS final snapshot delivery fence");std::cout<<"GNS client ability acceptance/inclusion, Health90/Stamina40, coherent tick6 and prepared retirement passed\n";std::this_thread::sleep_for(std::chrono::milliseconds(300));return 0;}
        }
        if(host&&executed<6&&session.motor_input_ready(1,executed+1)){auto tick=executed+1;session.consume_motor(1,tick,1);session.advance_abilities(tick);session.drain_ability_actions();auto state=session.motors().at(1);state.tick=tick;state.sequence=tick;state.position.x=.1*tick;session.publish_motor(1,state);++executed;}
        if(host&&executed==6&&session.ability_snapshot(owner).retired_through==1&&session.motor_input_ready(1,7)){check(session.objects().at(1).health.current==90&&session.ability_snapshot(owner).attributes[2].value==40,"GNS authoritative costs exactly once");std::cout<<"GNS host typed intent/native commit/correction ACK retired operation1; Health90/Stamina40 tick6\n";std::this_thread::sleep_for(std::chrono::milliseconds(300));return 0;}
    }std::this_thread::sleep_for(std::chrono::milliseconds(host?5:2));}throw std::runtime_error("GNS ability intent/correction deadline");
}catch(const std::exception& e){std::cerr<<e.what()<<'\n';return 1;}}
