#include <darkangel/ability_prediction.hpp>
#include <darkangel/ability_observer.hpp>
#include "../engine/runtime/ability_wire.hpp"
#include <iostream>
#include <stdexcept>
using namespace darkangel;
namespace {
void check(bool b,const char* m){if(!b)throw std::runtime_error(m);}
template<class F>void rejects(F f){bool failed=false;try{f();}catch(const std::exception&){failed=true;}check(failed,"Expected prepared tag rejection");}
double stamina(const AbilityOwnerSnapshot& s){for(auto a:s.attributes)if(a.id==3)return a.value;throw std::runtime_error("Stamina missing");}
struct Fixture {
 SessionHandshake hello{3,std::string(64,'a'),std::string(64,'b'),77};LoopbackPair pair=create_loopback(hello);ConnectionHandle hp,cp;WorldSession server{SessionRole::Server,hello},client{SessionRole::Client,hello};AbilityOwnerHandle owner;std::uint64_t id;
 std::vector<AttributeDefinition> schema{{1,"MaxHealth",AttributeKind::Statistic,100,0,1000,0,AttributeVisibility::Public},{2,"Health",AttributeKind::Resource,100,0,1000,1,AttributeVisibility::Public},{3,"Stamina",AttributeKind::Resource,60,0,60,0,AttributeVisibility::Owner}};
 std::shared_ptr<const TagDictionary> dictionary=std::make_shared<const TagDictionary>(std::vector<TagDefinition>{{1,0,"State",AttributeVisibility::Public},{2,1,"State.Blocked",AttributeVisibility::Public},{3,0,"Secret",AttributeVisibility::Server},{4,0,"Private",AttributeVisibility::Owner}},AssetId::random(),std::string(64,'e'));
 InputProfile input;std::shared_ptr<CombatKitDefinition> kit=std::make_shared<CombatKitDefinition>();std::shared_ptr<ActionDefinition> action=std::make_shared<ActionDefinition>();std::shared_ptr<AbilityDefinition> ability=std::make_shared<AbilityDefinition>();std::array<std::shared_ptr<const AbilityDefinition>,1> catalogue;
 Fixture(){hp=pair.host->open(hello);cp=pair.client->open(hello);server.attach(*pair.host,hp);client.attach(*pair.client,cp);ObjectData object;object.id={11,1};id=server.create(object);owner=server.configure_abilities(id,schema,2,1);server.configure_ability_tags(owner,dictionary);input.id=AssetId::random();kit->id=AssetId::random();kit->generation="tag-fixture";kit->locomotion_stance=AssetId::random();for(unsigned i=0;i<combat_slot_count;++i){input.actions.push_back({i+1,"combat."+std::to_string(i),InputActionKind::Button});kit->slots[i]={static_cast<CombatSlot>(i),i+1,{}};}action->id=AssetId::random();action->generation=std::string(64,'c');action->duration=6*action_tick_units;action->loops=1;ability->id=AssetId::random();ability->generation=std::string(64,'d');ability->action=action;ability->costs={{3,20}};ability->tag_registry=dictionary->registry();ability->tag_generation=dictionary->generation();ability->requirements.none={2};kit->slots[0].ability=ability->id;catalogue={ability};server.equip_combat_kit(owner,kit,input,catalogue);server.own_motor(id,hp);server.publish_motor(id,{});pump();}
 void pump(unsigned count=24){for(unsigned i=0;i<count;++i){server.tick();client.tick();}}
 EffectHandle tag(TagId tag,std::uint64_t duration=4){EffectDefinition d;d.id=AssetId::random();d.generation=std::string(64,'f');d.tags={tag};d.duration_ticks=duration;d.lifetime=duration?EffectLifetime::Finite:EffectLifetime::UntilRemoved;return server.apply_effect(owner,owner,d,0);}
 void step(){auto tick=server.ability_snapshot(owner).tick+1;server.advance_abilities(tick);server.drain_ability_actions();auto motor=server.motors().at(id);motor.tick=tick;motor.sequence=tick;server.publish_motor(id,motor);pump();}
 AbilityIntent intent(std::uint64_t operation,std::uint64_t tick,InputEdge edge=InputEdge::Pressed){return {id,operation,tick,1,1,CombatSlot::Light,edge};}
 OwnerAbilityPrediction predictor(){return {client.ability_corrections().at(id).ability,schema,kit,input,catalogue,1,dictionary};}
 ObserverAbility observer(){return {schema,2,1,std::array<std::shared_ptr<const ActionDefinition>,1>{action},dictionary};}
};
void audiences_generation_codec(){
 Fixture f;f.tag(2);f.tag(3,0);f.tag(4,0);f.pump();const auto& owner=f.client.ability_corrections().at(f.id);const auto& public_state=f.client.public_abilities().at(f.id);check(owner.ability.tags.values==std::vector<TagId>{2,4}&&public_state.ability.tags.values==std::vector<TagId>{2},"Owner/public audiences exclude server-only and private tags");check(owner.ability.tags.registry==f.dictionary->registry()&&owner.ability.tags.generation==f.dictionary->generation(),"Actor tag frames carry frozen registry identity");auto predictor=f.predictor();auto observer=f.observer();observer.push(public_state);check(observer.sample(0).frame.ability.tags.values==std::vector<TagId>{2},"Prepared observer reconstructs current tag state");
 auto private_frame=public_state;private_frame.ability.tags.values.push_back(4);rejects([&]{observer.push(private_frame);});auto unknown=public_state;unknown.ability.tags.values={99};rejects([&]{observer.push(unknown);});auto stale=public_state;stale.ability.tags.generation=std::string(64,'a');rejects([&]{observer.push(stale);});check(observer.size()==1&&observer.sample(0).frame.ability.tags.values==std::vector<TagId>{2},"Unknown/private/stale generation failure preserves observer buffer");rejects([&]{ObserverAbility missing(f.schema,2,1,std::array<std::shared_ptr<const ActionDefinition>,1>{f.action});missing.push(public_state);});
 auto bytes=session_detail::encode_ability_correction(owner);check(bytes.size()<=8192&&std::to_integer<unsigned>(bytes[0])==4,"Owner tag correction keeps schema-4 byte budget");auto roundtrip=session_detail::decode_ability_correction(bytes);check(roundtrip.ability.tags.values==owner.ability.tags.values,"Tag correction roundtrip");bytes[0]=std::byte{3};rejects([&]{session_detail::decode_ability_correction(bytes);});auto malformed=owner;malformed.ability.tags.values={2,2};rejects([&]{session_detail::encode_ability_correction(malformed);});malformed=owner;malformed.ability.tags.registry={};rejects([&]{session_detail::encode_ability_correction(malformed);});
 auto dense=owner;dense.ability.tags.values.clear();dense.ability.attributes.clear();dense.ability.cooldowns.clear();dense.ability.operations.clear();for(unsigned i=1;i<=128;++i){dense.ability.tags.values.push_back(i);dense.ability.operations.push_back({i,AbilityFailure::InputIgnored,0,false});if(i<=64)dense.ability.attributes.push_back({i,i<=2?100.:double(i)});if(i<=32)dense.ability.cooldowns.push_back({i,1});}dense.ability.highest_operation=128;dense.ability.retained_operations=128;auto dense_bytes=session_detail::encode_ability_correction(dense);auto dense_state=session_detail::decode_ability_correction(dense_bytes);check(dense_bytes.size()<=8192&&dense_state.ability.tags.values.size()==128&&dense_state.ability.operations.size()==128,"Dense tag/attribute/cooldown/operation maxima retain existing owner byte budget");std::vector<TagDefinition> broad;for(unsigned i=1;i<=128;++i)broad.push_back({i,0,"Public."+std::to_string(i),AttributeVisibility::Public});OwnedTags restored(std::make_shared<const TagDictionary>(broad,dense.ability.tags.registry,dense.ability.tags.generation));restored.restore_snapshot(dense.ability.tags,AttributeVisibility::Owner);check(restored.values().size()==128,"Owner aggregate restore supports dictionary maximum without contributor internals");
 auto duplicate=public_state;duplicate.ability.tags.values={1,2};auto payload=session_detail::encode_ability_public(duplicate);check(std::to_integer<unsigned>(payload[0])==2&&payload.size()<=4096,"Public tag state schema-2 byte budget");for(unsigned i=0;i<8;++i)payload[payload.size()-8+i]=static_cast<std::byte>(i?0:1);rejects([&]{session_detail::decode_ability_public(payload);});auto wrong=owner.ability;wrong.revision++;wrong.tags.generation=std::string(64,'a');rejects([&]{predictor.reconcile(wrong);});check(predictor.needs_resync()&&predictor.view().tags.values==owner.ability.tags.values,"Wrong owner registry generation rejects candidate and retains old view");
}
void activation_prediction_replay(){
 Fixture f;f.tag(2);f.pump();auto predictor=f.predictor();auto pressed=f.intent(1,1);predictor.advance(1,std::array<AbilityPredictionInput,1>{{{pressed,0}}});check(stamina(predictor.view())==60&&!predictor.view().active&&predictor.pending()==1,"Confirmed blocker prevents predicted costs/action");check(f.client.submit_ability_intent(pressed),"Tag intent submitted");f.pump();f.step();auto notices=f.client.drain_ability_receipts();check(notices.size()==1&&notices[0].receipt.failure==AbilityFailure::TagRequirements&&!notices[0].receipt.committed,"Server uses native tag requirements and terminal reason");predictor.receipt(notices[0]);check(predictor.reconcile(f.client.ability_corrections().at(f.id).ability)&&predictor.pending()==0&&stamina(predictor.view())==60,"Exact inclusion retires denied operation without cost");
 for(unsigned tick=2;tick<=4;++tick){predictor.advance(tick);f.step();check(predictor.reconcile(f.client.ability_corrections().at(f.id).ability),"Confirmed tag state reconciles");}check(predictor.view().tags.values.empty(),"Simulation expiry removes authoritative blocker before activation");auto release=f.intent(2,5,InputEdge::Released);predictor.advance(5,std::array<AbilityPredictionInput,1>{{{release,0}}});check(f.client.submit_ability_intent(release),"Release submitted");f.pump();f.step();for(auto notice:f.client.drain_ability_receipts())predictor.receipt(notice);predictor.reconcile(f.client.ability_corrections().at(f.id).ability);auto next=f.intent(3,6);predictor.advance(6,std::array<AbilityPredictionInput,1>{{{next,0}}});check(stamina(predictor.view())==40&&predictor.view().active,"Fresh press after confirmed expiry predicts cost/action");check(f.client.submit_ability_intent(next),"Accepted tag intent submitted");f.pump();f.step();auto accepted=f.client.drain_ability_receipts();check(accepted.size()==1&&accepted[0].receipt.committed,"Server agrees with corrected tag prediction");predictor.receipt(accepted[0]);predictor.reconcile(f.client.ability_corrections().at(f.id).ability);check(predictor.pending()==0&&stamina(predictor.view())==40,"Accepted inclusion spends once");
 Fixture rejected;auto optimistic=rejected.predictor();auto operation=rejected.intent(1,1);optimistic.advance(1,std::array<AbilityPredictionInput,1>{{{operation,0}}});check(stamina(optimistic.view())==40,"Prediction before newer blocker is provisional");rejected.tag(2);check(rejected.client.submit_ability_intent(operation),"Provisional intent submitted");rejected.pump();rejected.step();for(auto notice:rejected.client.drain_ability_receipts())optimistic.receipt(notice);optimistic.reconcile(rejected.client.ability_corrections().at(rejected.id).ability);check(stamina(optimistic.view())==60&&!optimistic.view().active&&optimistic.pending()==0,"Newer blocker rejection rebuilds pending cost/action from current baseline");
}
void private_dependencies_and_late_join(){
 Fixture f;auto hidden=std::make_shared<AbilityDefinition>(*f.ability);hidden->requirements.none={3};std::array<std::shared_ptr<const AbilityDefinition>,1> catalogue{hidden};rejects([&]{OwnerAbilityPrediction unavailable(f.client.ability_corrections().at(f.id).ability,f.schema,f.kit,f.input,catalogue,1,f.dictionary);});auto mismatched=std::make_shared<AbilityDefinition>(*f.ability);mismatched->tag_generation=std::string(64,'b');auto old=f.server.ability_snapshot(f.owner);rejects([&]{f.server.equip_combat_kit(f.owner,f.kit,f.input,std::array<std::shared_ptr<const AbilityDefinition>,1>{mismatched});});check(f.server.ability_snapshot(f.owner).grant_generation==old.grant_generation,"Mismatched tagged grants retain prior kit");f.tag(2);f.tag(3,0);f.tag(4,0);f.step();auto late_pair=create_loopback(f.hello);auto hp=late_pair.host->open(f.hello),cp=late_pair.client->open(f.hello);WorldSession late(SessionRole::Client,f.hello);f.server.attach(*late_pair.host,hp);late.attach(*late_pair.client,cp);for(unsigned i=0;i<32;++i){f.server.tick();f.client.tick();late.tick();}check(late.ability_corrections().empty()&&late.public_abilities().at(f.id).ability.tags.values==std::vector<TagId>{2},"Late observer receives current public tags without owner private state");auto buffer=f.observer();buffer.push(late.public_abilities().at(f.id));check(buffer.sample(1).frame.ability.tags.values==std::vector<TagId>{2},"Late current tags restore without historical effect/cue execution");
}
}
int main(){try{audiences_generation_codec();activation_prediction_replay();private_dependencies_and_late_join();std::cout<<"Owner/public tagged frames, generation/privacy preparation, native activation blockers, corrected prediction and observer late join passed\n";return 0;}catch(const std::exception& e){std::cerr<<e.what()<<'\n';return 1;}}
