#include <darkangel/world_session.hpp>
#include <algorithm>
#include <iostream>
using namespace darkangel;
namespace {
void check(bool b,const char* message){if(!b)throw std::runtime_error(message);}
template<class F>void rejects(F f){bool rejected=false;try{f();}catch(const std::exception&){rejected=true;}check(rejected,"Expected checked rejection");}
struct Fixture {
    SessionHandshake hello{3,std::string(64,'a'),std::string(64,'b'),77};LoopbackPair pair=create_loopback(hello);WorldSession server{SessionRole::Server,hello},client{SessionRole::Client,hello};ConnectionHandle hp,cp;std::uint64_t id{};AbilityOwnerHandle owner;std::shared_ptr<AbilityDefinition> ability=std::make_shared<AbilityDefinition>();std::shared_ptr<CombatKitDefinition> kit=std::make_shared<CombatKitDefinition>();InputProfile input;
    Fixture(InputEdge edge=InputEdge::Pressed,std::uint64_t held=0,bool cancel=false){hp=pair.host->open(hello);cp=pair.client->open(hello);server.attach(*pair.host,hp);client.attach(*pair.client,cp);ObjectData object;object.id={4,1};id=server.create(object);owner=server.configure_abilities(id,{{1,"MaxHealth",AttributeKind::Statistic,100,0,1000,0},{2,"Health",AttributeKind::Resource,100,0,1000,1},{3,"Stamina",AttributeKind::Resource,100,0,100,0}},2,1);
        auto action=std::make_shared<ActionDefinition>();action->id=AssetId::random();action->generation=std::string(64,'a');action->duration=20*action_tick_units;action->loops=1;ability->id=AssetId::random();ability->generation=std::string(64,'b');ability->action=action;ability->activate_on=edge;ability->minimum_held_us=held;ability->cancel_on_release=cancel;ability->costs={{3,20}};
        kit->id=AssetId::random();kit->generation="kit";kit->locomotion_stance=AssetId::random();input.id=AssetId::random();for(unsigned i=0;i<combat_slot_count;++i){input.actions.push_back({i+1,"combat."+std::to_string(i),InputActionKind::Button});kit->slots[i]={static_cast<CombatSlot>(i),i+1,{}};}kit->slots[0].ability=ability->id;equip();server.own_motor(id,hp);MotorState motor;server.publish_motor(id,motor);pump();check(client.ability_corrections().contains(id),"Owner receives initial grant/correction");
    }
    void equip(){std::array<std::shared_ptr<const AbilityDefinition>,1> catalogue{ability};server.equip_combat_kit(owner,kit,input,catalogue);}
    void pump(unsigned count=8){for(unsigned i=0;i<count;++i){server.tick();client.tick();}}
    AbilityIntent intent(std::uint64_t op,std::uint64_t tick,InputEdge edge=InputEdge::Pressed){return {id,op,tick,server.motors().at(id).epoch,server.ability_snapshot(owner).grant_generation,CombatSlot::Light,edge,false,false};}
    void send(const AbilityIntent& intent){check(client.submit_ability_intent(intent),"Typed client intent queued through transport");server.tick();}
    void step(){auto tick=server.ability_snapshot(owner).tick+1;server.advance_abilities(tick);server.drain_ability_actions();auto motor=server.motors().at(id);motor.tick=tick;motor.sequence=tick;server.publish_motor(id,motor);pump();}
    double stamina(){for(const auto& value:server.ability_snapshot(owner).attributes)if(value.id==3)return value.value;throw std::runtime_error("Missing stamina");}
    AbilityOperationNotice receipt(){auto receipts=client.drain_ability_receipts();check(receipts.size()==1,"One operation notice");return receipts.front();}
};
void press(){Fixture f;auto intent=f.intent(1,1);f.send(intent);check(f.stamina()==100&&!f.server.ability_snapshot(f.owner).active,"Transport callbacks queue rather than execute abilities");f.step();auto receipt=f.receipt();check(receipt.terminal&&receipt.receipt.committed&&receipt.receipt.tick==1&&receipt.receipt.operation==1&&f.stamina()==80,"Owned fixed-tick command commits through native ability state");check(f.server.ability_snapshot(f.owner).action->clock==0,"New activation begins on its accepted tick, without retroactive advancement");f.send(intent);f.step();auto duplicate=f.receipt();check(duplicate.receipt.duplicate&&duplicate.receipt.handle.activation==receipt.receipt.handle.activation&&f.stamina()==80,"Duplicate wire operation retains canonical receipt and does not spend twice");}
void hold(){Fixture f(InputEdge::Hold,100000,true);f.send(f.intent(1,1));f.step();check(f.receipt().receipt.failure==AbilityFailure::InputIgnored,"Press arms hold without activating");f.send(f.intent(2,2,InputEdge::Hold));f.step();check(f.receipt().receipt.failure==AbilityFailure::InputIgnored&&f.stamina()==100,"Client cannot invent held duration");for(unsigned i=0;i<5;++i)f.step();f.send(f.intent(3,8,InputEdge::Hold));f.step();check(f.receipt().receipt.committed&&f.stamina()==80,"Held duration reconstructed on authoritative ticks");f.send(f.intent(4,9,InputEdge::Hold));f.step();check(f.receipt().receipt.failure==AbilityFailure::InputIgnored&&f.stamina()==80,"A physical hold edge is consumed once");f.send(f.intent(5,10,InputEdge::Released));f.step();check(f.receipt().receipt.failure==AbilityFailure::None&&!f.server.ability_snapshot(f.owner).active&&f.stamina()==80,"Release cancellation uses native cleanup without refund");}
void tap(){Fixture f(InputEdge::Tapped);f.send(f.intent(1,1,InputEdge::Tapped));f.step();check(f.receipt().receipt.failure==AbilityFailure::InputIgnored,"Tap requires a matching press/release gesture");f.send(f.intent(2,2));f.step();f.receipt();f.send(f.intent(3,3,InputEdge::Released));f.send(f.intent(4,3,InputEdge::Tapped));f.step();auto receipts=f.client.drain_ability_receipts();check(receipts.size()==2&&receipts[1].receipt.committed&&f.stamina()==80,"Tap follows authoritative release with bounded duration");auto repeat=f.intent(5,4,InputEdge::Tapped);repeat.replace_active=true;f.send(repeat);f.step();check(f.receipt().receipt.failure==AbilityFailure::InputIgnored&&f.stamina()==80,"Completed tap gesture cannot be reused");}
void stale(){Fixture f;f.send(f.intent(1,1));f.equip();f.step();check(f.receipt().receipt.failure==AbilityFailure::StaleGrant&&f.stamina()==100,"Queued old grant cannot activate replacement");auto avatar=f.intent(2,2);avatar.avatar_epoch=9;f.send(avatar);f.step();check(f.receipt().receipt.failure==AbilityFailure::AvatarMismatch&&f.stamina()==100,"Avatar epoch checked at execution");auto future=f.intent(3,5);f.send(future);f.step();check(f.client.drain_ability_receipts().empty()&&f.stamina()==100,"Future bounded input waits for its simulation tick");f.step();f.step();check(f.receipt().receipt.committed,"Future input starts at its requested tick");}
void expiry(){Fixture f;f.step();f.step();f.send(f.intent(1,1));f.step();check(f.receipt().receipt.failure==AbilityFailure::InputExpired&&f.stamina()==100,"Expired input gets terminal rejection without backdating");auto too_far=f.intent(2,20);check(!f.client.submit_ability_intent(too_far),"Client lead bound fails closed");}
void lost(){Fixture f(InputEdge::Hold,0,true);f.send(f.intent(1,1));f.step();f.receipt();f.send(f.intent(2,2,InputEdge::Hold));f.step();f.receipt();f.step();auto release=f.intent(3,2,InputEdge::Released);f.send(release);f.step();check(f.receipt().receipt.failure==AbilityFailure::InputExpired&&!f.server.ability_snapshot(f.owner).active&&f.stamina()==80,"Expired release cleans channel ownership without executing release activation");}
void disconnect(){Fixture f;f.ability->interruptible=false;f.equip();f.send(f.intent(1,1));f.step();f.receipt();f.server.drain_ability_actions();f.server.detach(f.hp);check(!f.server.ability_snapshot(f.owner).active&&f.stamina()==80,"Connection removal force-cleans action without refund");auto updates=f.server.drain_ability_actions();check(updates.size()==1&&updates[0].reason==AbilityActionReason::Disconnected,"Disconnect cleanup is explicit and balanced");}
void receipt_lifecycle(){Fixture f;f.send(f.intent(1,1));f.step();auto object=ObjectData{};object.id={4,2};f.server.create(object);f.pump();auto receipt=f.receipt();check(f.client.world().valid(receipt.receipt.handle.owner.entity)&&receipt.receipt.handle.owner.network==f.id,"Queued receipt re-resolves local identity after lifecycle baseline replacement");}
void bounds(){Fixture f;for(std::uint64_t op=1;op<=128;++op){auto request=AbilityRequest{f.owner,op,f.server.ability_snapshot(f.owner).grant_generation,CombatSlot::Spell1,{5,InputEdge::Pressed,op,0,1,false},false};check(f.server.request_ability(request).failure==AbilityFailure::Unassigned,"Fill native receipt retention");}f.pump();f.send(f.intent(129,1));f.step();auto pending=f.receipt();check(!pending.terminal&&pending.receipt.failure==AbilityFailure::HistoryFull&&f.stamina()==100&&f.client.ability_correction_needs_resync(),"History exhaustion is explicit resync/backpressure, not a forgotten terminal rejection");f.client.acknowledge_ability_correction(f.id);f.pump();f.step();check(f.receipt().terminal&&f.stamina()==100,"Pending input resolves after prepared correction releases native storage");}
}
int main(){try{press();hold();tap();stale();expiry();lost();disconnect();receipt_lifecycle();bounds();std::cout<<"Owned ability intents, fixed-tick expiry/lead, authoritative gestures, deduplication, receipts, disconnect and bounded resync passed\n";return 0;}catch(const std::exception& e){std::cerr<<e.what()<<'\n';return 1;}}
