#include <darkangel/ability_prediction.hpp>
#include "../engine/runtime/ability_wire.hpp"
#include <algorithm>
#include <iostream>
using namespace darkangel;
namespace {
void check(bool b,const char* message){if(!b)throw std::runtime_error(message);}
template<class F>void rejects(F f){bool failed=false;try{f();}catch(const std::exception&){failed=true;}check(failed,"Expected reservation rejection");}
double value(const AbilityOwnerSnapshot& state,AttributeId id){for(auto field:state.attributes)if(field.id==id)return field.value;throw std::runtime_error("Missing reservation attribute");}
struct Fixture {
 SessionHandshake hello{3,std::string(64,'a'),std::string(64,'b'),77};LoopbackPair pair=create_loopback(hello);WorldSession server{SessionRole::Server,hello},client{SessionRole::Client,hello};ConnectionHandle hp,cp;AbilityOwnerHandle owner;
 std::vector<AttributeDefinition> schema{{1,"MaxHealth",AttributeKind::Statistic,100,0,1000,0,AttributeVisibility::Public},{2,"Health",AttributeKind::Resource,100,0,1000,1,AttributeVisibility::Public},{3,"Stamina",AttributeKind::Resource,100,0,1000,4,AttributeVisibility::Owner},{4,"MaxStamina",AttributeKind::Statistic,100,0,1000,0,AttributeVisibility::Owner}};
 std::shared_ptr<const TagDictionary> tags=std::make_shared<const TagDictionary>(std::vector<TagDefinition>{{1,0,"State",AttributeVisibility::Public},{2,1,"State.Invulnerable",AttributeVisibility::Public},{3,1,"State.Blocked",AttributeVisibility::Public}},AssetId::random(),std::string(64,'e'));
 InputProfile input;std::shared_ptr<CombatKitDefinition> kit=std::make_shared<CombatKitDefinition>();std::shared_ptr<ActionDefinition> action=std::make_shared<ActionDefinition>();std::shared_ptr<AbilityDefinition> ability=std::make_shared<AbilityDefinition>();std::array<std::shared_ptr<const AbilityDefinition>,1> catalogue;
 Fixture(unsigned marker=2*action_tick_units,double cost=20){hp=pair.host->open(hello);cp=pair.client->open(hello);server.attach(*pair.host,hp);client.attach(*pair.client,cp);ObjectData object;object.id={41,1};owner=server.configure_abilities(server.create(object),schema,2,1);server.configure_ability_tags(owner,tags);input.id=AssetId::random();kit->id=AssetId::random();kit->generation="reservation";kit->locomotion_stance=AssetId::random();for(unsigned i=0;i<combat_slot_count;++i){input.actions.push_back({i+1,"combat."+std::to_string(i),InputActionKind::Button});kit->slots[i]={static_cast<CombatSlot>(i),i+1,{}};}action->id=AssetId::random();action->generation=std::string(64,'c');action->duration=4*action_tick_units;action->loops=1;action->blocks={{1,0,marker,marker,ActionBlockKind::Commit,"Ability.Commit"},{2,1,0,3*action_tick_units,ActionBlockKind::Invulnerability,"Charging"}};ability->id=AssetId::random();ability->generation=std::string(64,'d');ability->action=action;ability->costs={{3,cost}};ability->cooldown_group=1;ability->cooldown_ticks=6;ability->cancel_on_release=true;ability->tag_registry=tags->registry();ability->tag_generation=tags->generation();ability->action_tags={{2,2}};ability->requirements.none={3};ability->deferred_commit_block=1;kit->slots[0].ability=ability->id;catalogue={ability};server.equip_combat_kit(owner,kit,input,catalogue);server.own_motor(owner.network,hp);server.publish_motor(owner.network,{});pump();}
 void pump(){for(unsigned i=0;i<24;++i){server.tick();client.tick();}}
 AbilityReceipt activate(std::uint64_t operation,bool replace=false){return server.request_ability({owner,operation,server.ability_snapshot(owner).grant_generation,CombatSlot::Light,{1,InputEdge::Pressed,operation*1000,0,1,false},replace});}
 void step(unsigned rate=action_tick_units){auto tick=server.ability_snapshot(owner).tick+1;server.advance_abilities(tick,rate);server.drain_ability_actions();auto motor=server.motors().at(owner.network);motor.tick=tick;motor.sequence=tick;server.publish_motor(owner.network,motor);pump();}
 void delta(AttributeId id,double amount){EffectDefinition instant;instant.id=AssetId::random();instant.generation=std::string(64,'f');instant.lifetime=EffectLifetime::Instant;instant.execute_on_apply=true;instant.evaluator=next_evaluator++;server.register_effect_evaluator(instant.evaluator,[=](const EffectContext&){return std::vector<ResourceDelta>{{id,amount}};});server.apply_effect(owner,owner,instant,0);}
 std::uint32_t next_evaluator{1};
 AbilityIntent intent(std::uint64_t operation,std::uint64_t tick,InputEdge edge=InputEdge::Pressed){return {owner.network,operation,tick,1,1,CombatSlot::Light,edge};}
 const AbilityOwnerSnapshot& baseline(){return client.ability_corrections().at(owner.network).ability;}
 OwnerAbilityPrediction predictor(){return {baseline(),schema,kit,input,catalogue,1,tags};}
};
void reservation_consume_cancel(){
 Fixture f;auto receipt=f.activate(1);auto state=f.server.ability_snapshot(f.owner);check(receipt.committed&&state.reservation&&state.active_operation==1&&value(state,3)==100&&f.server.ability_available(f.owner,3)==80&&state.cooldowns.empty(),"Deferred activation reserves without spending or starting cooldown");auto reserved=f.server.drain_ability_commitments();check(reserved.size()==1&&reserved[0].phase==AbilityCommitPhase::Reserved&&reserved[0].operation==1&&reserved[0].block==1,"Reservation has correlated activation/operation/marker identity");check(f.server.request_ability({f.owner,1,1,CombatSlot::Light,{1,InputEdge::Pressed,1000,0,1,false}}).duplicate&&f.server.drain_ability_commitments().empty(),"Duplicate request cannot reserve twice");check(f.activate(2).failure==AbilityFailure::Busy&&f.server.ability_available(f.owner,3)==80,"Concurrent request cannot spend a reserved slot");f.step(0);check(value(f.server.ability_snapshot(f.owner),3)==100&&f.server.ability_snapshot(f.owner).reservation,"Hitstop does not consume a future marker");f.step();f.step();state=f.server.ability_snapshot(f.owner);auto commits=f.server.drain_ability_commitments();check(!state.reservation&&value(state,3)==80&&state.cooldowns.size()==1&&state.cooldowns.front().second==9&&commits.size()==1&&commits[0].phase==AbilityCommitPhase::Committed&&commits[0].operation==1,"Marker consumes once and begins cooldown at current simulation tick");f.server.cancel_ability(receipt.handle);check(value(f.server.ability_snapshot(f.owner),3)==80&&f.server.drain_ability_commitments().empty(),"Post-commit cancellation refunds neither cost nor cooldown");
 Fixture cancelled;auto handle=cancelled.activate(1).handle;cancelled.server.drain_ability_commitments();cancelled.server.cancel_ability(handle);cancelled.server.cancel_ability(handle);auto releases=cancelled.server.drain_ability_commitments();check(releases.size()==1&&releases[0].phase==AbilityCommitPhase::Released&&cancelled.server.ability_available(cancelled.owner,3)==100&&value(cancelled.server.ability_snapshot(cancelled.owner),3)==100&&cancelled.server.ability_snapshot(cancelled.owner).cooldowns.empty(),"Idempotent pre-commit cancellation releases all claims without spending");
 Fixture entry(0);entry.activate(1);check(!entry.server.ability_snapshot(entry.owner).reservation&&value(entry.server.ability_snapshot(entry.owner),3)==80&&entry.server.drain_ability_commitments().front().phase==AbilityCommitPhase::Committed,"Explicit time-zero marker commits once at entry");
}
void revalidation_lifecycle_and_rollback(){
 Fixture low;low.activate(1);low.server.drain_ability_commitments();low.delta(3,-90);check(low.server.ability_available(low.owner,3)==0,"Availability subtracts the claim after authoritative resource loss");low.step(4*action_tick_units);auto failed=low.server.drain_ability_commitments();check(failed.size()==1&&failed[0].phase==AbilityCommitPhase::Rejected&&failed[0].failure==AbilityFailure::Resources&&!low.server.ability_snapshot(low.owner).active&&value(low.server.ability_snapshot(low.owner),3)==10&&low.server.ability_snapshot(low.owner).cooldowns.empty(),"Crossed completed marker rejection releases claims without restoring older resources");
 Fixture blocked;blocked.activate(1);blocked.server.drain_ability_commitments();EffectDefinition blocker;blocker.id=AssetId::random();blocker.generation=std::string(64,'f');blocker.lifetime=EffectLifetime::UntilRemoved;blocker.tags={3};blocked.server.apply_effect(blocked.owner,blocked.owner,blocker,0);blocked.step(4*action_tick_units);failed=blocked.server.drain_ability_commitments();check(failed.size()==1&&failed[0].failure==AbilityFailure::TagRequirements&&blocked.server.ability_available(blocked.owner,3)==100,"Marker rechecks new blockers before consumption");
 Fixture grant;grant.activate(1);grant.server.drain_ability_commitments();grant.server.equip_combat_kit(grant.owner,grant.kit,grant.input,grant.catalogue);check(grant.server.drain_ability_commitments().front().phase==AbilityCommitPhase::Released&&grant.server.ability_available(grant.owner,3)==100,"Grant removal releases reservations");Fixture disconnected;disconnected.activate(1);disconnected.server.drain_ability_commitments();disconnected.server.detach(disconnected.hp);check(disconnected.server.drain_ability_commitments().front().phase==AbilityCommitPhase::Released,"Disconnect releases reservations");Fixture death;death.activate(1);death.server.drain_ability_commitments();death.delta(2,-100);check(death.server.drain_ability_commitments().front().phase==AbilityCommitPhase::Released&&!death.server.ability_snapshot(death.owner).active,"Authoritative death releases a pre-commit claim");Fixture despawn;despawn.activate(1);despawn.server.drain_ability_commitments();despawn.server.destroy(despawn.owner.network);check(despawn.server.drain_ability_commitments().front().phase==AbilityCommitPhase::Released,"Despawn publishes reservation release before owner retirement");
 Fixture bounded;for(unsigned i=1;i<=64;++i){auto handle=bounded.activate(i).handle;bounded.server.cancel_ability(handle);bounded.server.drain_ability_actions();}auto before=bounded.server.ability_snapshot(bounded.owner);rejects([&]{bounded.activate(65);});check(bounded.server.ability_snapshot(bounded.owner).next_activation==before.next_activation&&bounded.server.ability_available(bounded.owner,3)==100,"Commitment queue exhaustion rejects the whole reservation candidate");check(bounded.server.drain_ability_commitments().size()==128&&bounded.activate(65).committed,"Draining permits exact safe retry");
}
void prediction_and_wire(){
 Fixture f;auto predicted=f.predictor();auto press=f.intent(1,1);predicted.advance(1,std::array<AbilityPredictionInput,1>{{{press,0}}});check(predicted.view().reservation&&value(predicted.view(),3)==100&&predicted.view().active_operation==1,"Owner subset predicts a reversible claim without spending");check(f.client.submit_ability_intent(press),"Deferred semantic press submitted");f.pump();f.step();for(auto notice:f.client.drain_ability_receipts())predicted.receipt(notice);predicted.reconcile(f.baseline());check(predicted.pending()==0&&predicted.view().reservation&&value(predicted.view(),3)==100,"Acceptance/inclusion retires input while retaining the active claim");f.client.acknowledge_ability_correction(f.owner.network);f.pump();predicted.reconcile(f.baseline());check(f.baseline().operations.empty()&&f.baseline().active_operation==1,"Retired start operation remains explicitly correlated with the active execution");auto restored=f.predictor();restored.advance(2);restored.advance(3);check(!restored.view().reservation&&value(restored.view(),3)==80,"Prepared active claim replays through its marker after operation retirement");f.step();f.step();check(restored.reconcile(f.baseline())&&value(restored.view(),3)==80&&!restored.view().reservation,"Authoritative marker baseline does not charge twice");
 Fixture cancel;auto view=cancel.predictor();press=cancel.intent(1,1);view.advance(1,std::array<AbilityPredictionInput,1>{{{press,0}}});auto release=cancel.intent(2,2,InputEdge::Released);view.advance(2,std::array<AbilityPredictionInput,1>{{{release,1}}});check(!view.view().reservation&&!view.view().active&&value(view.view(),3)==100,"Pending release reverses the claim without restoring resources");
 Fixture active;active.activate(1);active.pump();auto correction=active.client.ability_corrections().at(active.owner.network);auto bytes=session_detail::encode_ability_correction(correction);check(std::to_integer<unsigned>(bytes[0])==5&&session_detail::decode_ability_correction(bytes).ability.reservation->costs.front().amount==20,"Owner schema5 carries frozen resource/cooldown claims");auto malformed=correction;malformed.ability.reservation->costs.push_back(malformed.ability.reservation->costs.front());rejects([&]{session_detail::encode_ability_correction(malformed);});auto bad=active.predictor();auto baseline=active.baseline();baseline.revision++;baseline.reservation->costs.front().amount=30;rejects([&]{bad.reconcile(baseline);});check(bad.needs_resync()&&bad.view().reservation->costs.front().amount==20,"Forged claim magnitude rejects preparation without changing the view");
 auto dense=correction;dense.ability.attributes.clear();dense.ability.cooldowns.clear();dense.ability.operations.clear();dense.ability.tags.values.clear();dense.ability.action_only_tags.clear();dense.ability.reservation->costs.clear();dense.ability.highest_operation=128;dense.ability.next_activation=129;for(unsigned i=1;i<=128;++i){dense.ability.tags.values.push_back(i);dense.ability.operations.push_back({i,AbilityFailure::InputIgnored,0,false});if(i<=64)dense.ability.attributes.push_back({i,100});if(i<=32)dense.ability.cooldowns.push_back({i,1});if(i<=16)dense.ability.action_only_tags.push_back(i);if(i<=8)dense.ability.reservation->costs.push_back({i,1});}check(session_detail::encode_ability_correction(dense).size()<=8192,"Maximum active owner state plus eight reserved resources retains byte limits");
}
void exact_marker_tags_and_frozen_policy(){
 Fixture f;EffectDefinition bonus;bonus.id=AssetId::random();bonus.generation=std::string(64,'f');bonus.lifetime=EffectLifetime::UntilRemoved;bonus.ongoing.all={2};bonus.modifiers={{0,0,4,AttributeModifierKind::Flat,100}};f.server.apply_effect(f.owner,f.owner,bonus,0);f.activate(1);f.delta(3,80);check(value(f.server.ability_snapshot(f.owner),3)==180,"Charging tag enables a maximum-resource modifier");f.step(4*action_tick_units);check(value(f.server.ability_snapshot(f.owner),3)==100&&!f.server.ability_snapshot(f.owner).active,"Fast crossing consumes at the marker before later maximum-resource clamping");
 auto invalid=std::make_shared<AbilityDefinition>(*f.ability);invalid->deferred_commit_block=2;rejects([&]{freeze_ability_definition(*invalid,AttributeSet(f.schema),f.tags.get());});invalid=std::make_shared<AbilityDefinition>(*f.ability);auto loop=std::make_shared<ActionDefinition>(*f.action);loop->loops=2;invalid->action=loop;rejects([&]{freeze_ability_definition(*invalid,AttributeSet(f.schema),f.tags.get());});
 Fixture replacement;replacement.activate(1);replacement.server.drain_ability_commitments();check(replacement.activate(2,true).committed&&replacement.server.ability_available(replacement.owner,3)==80,"Replacement exchanges the old claim for one new claim");auto changes=replacement.server.drain_ability_commitments();check(changes.size()==2&&changes[0].phase==AbilityCommitPhase::Released&&changes[1].phase==AbilityCommitPhase::Reserved,"Replacement cleanup and new reservation have distinct correlated identities");
 Fixture lethal;auto health_cost=std::make_shared<AbilityDefinition>(*lethal.ability);health_cost->costs={{2,100}};lethal.catalogue={health_cost};lethal.server.equip_combat_kit(lethal.owner,lethal.kit,lethal.input,lethal.catalogue);lethal.activate(1);lethal.server.drain_ability_commitments();lethal.step(4*action_tick_units);auto death=lethal.server.drain_ability_commitments();check(death.size()==1&&death[0].phase==AbilityCommitPhase::Committed&&lethal.server.objects().at(lethal.owner.network).health.current==0&&!lethal.server.ability_snapshot(lethal.owner).active,"Lethal marker cost commits once and cancels even when the tick crosses completion");
}
}
int main(){try{reservation_consume_cancel();revalidation_lifecycle_and_rollback();prediction_and_wire();exact_marker_tags_and_frozen_policy();std::cout<<"Deferred typed marker reservations, atomic consumption/revalidation, lifecycle release, owner schema5/replay and bounded rollback passed\n";return 0;}catch(const std::exception& e){std::cerr<<e.what()<<'\n';return 1;}}
