#include <darkangel/ability_prediction.hpp>
#include <darkangel/ability_observer.hpp>
#include "../engine/runtime/ability_wire.hpp"
#include <algorithm>
#include <iostream>
#include <stdexcept>
using namespace darkangel;
namespace {
void check(bool b,const char* message){if(!b)throw std::runtime_error(message);}
template<class F>void rejects(F f){bool failed=false;try{f();}catch(const std::exception&){failed=true;}check(failed,"Expected action tag rejection");}
struct Fixture {
 SessionHandshake hello{3,std::string(64,'a'),std::string(64,'b'),77};LoopbackPair pair=create_loopback(hello);ConnectionHandle hp,cp;WorldSession server{SessionRole::Server,hello},client{SessionRole::Client,hello};AbilityOwnerHandle owner;
 std::vector<AttributeDefinition> schema{{1,"MaxHealth",AttributeKind::Statistic,100,0,1000,0,AttributeVisibility::Public},{2,"Health",AttributeKind::Resource,100,0,1000,1,AttributeVisibility::Public},{3,"Stamina",AttributeKind::Resource,100,0,100,0,AttributeVisibility::Owner},{4,"Speed",AttributeKind::Statistic,6,0,100,0,AttributeVisibility::Owner}};
 std::shared_ptr<const TagDictionary> tags=std::make_shared<const TagDictionary>(std::vector<TagDefinition>{{1,0,"State",AttributeVisibility::Public},{2,1,"State.Invulnerable",AttributeVisibility::Public},{3,0,"Secret",AttributeVisibility::Server},{4,1,"State.MovementLocked",AttributeVisibility::Owner},{5,1,"State.Blocked",AttributeVisibility::Public}},AssetId::random(),std::string(64,'e'));
 InputProfile input;std::shared_ptr<CombatKitDefinition> kit=std::make_shared<CombatKitDefinition>();std::shared_ptr<ActionDefinition> action=std::make_shared<ActionDefinition>();std::shared_ptr<AbilityDefinition> ability=std::make_shared<AbilityDefinition>();std::array<std::shared_ptr<const AbilityDefinition>,1> catalogue;
 Fixture(){hp=pair.host->open(hello);cp=pair.client->open(hello);server.attach(*pair.host,hp);client.attach(*pair.client,cp);ObjectData object;object.id={11,1};owner=server.configure_abilities(server.create(object),schema,2,1);server.configure_ability_tags(owner,tags);input.id=AssetId::random();kit->id=AssetId::random();kit->generation="action-tags";kit->locomotion_stance=AssetId::random();for(unsigned i=0;i<combat_slot_count;++i){input.actions.push_back({i+1,"combat."+std::to_string(i),InputActionKind::Button});kit->slots[i]={static_cast<CombatSlot>(i),i+1,{}};}action->id=AssetId::random();action->generation=std::string(64,'c');action->duration=4*action_tick_units;action->loops=2;action->blocks={{1,0,0,2*action_tick_units,ActionBlockKind::Invulnerability,"dodge"},{2,0,action_tick_units,3*action_tick_units,ActionBlockKind::MovementLock,"locked"},{3,1,action_tick_units,3*action_tick_units,ActionBlockKind::Invulnerability,"overlap"}};ability->id=AssetId::random();ability->generation=std::string(64,'d');ability->action=action;ability->costs={{3,10}};ability->cancel_on_release=true;ability->tag_registry=tags->registry();ability->tag_generation=tags->generation();ability->action_tags={{1,2},{2,4},{3,2}};ability->requirements.none={5};kit->slots[0].ability=ability->id;catalogue={ability};server.equip_combat_kit(owner,kit,input,catalogue);server.own_motor(owner.network,hp);server.publish_motor(owner.network,{});pump();}
 void pump(){for(unsigned i=0;i<24;++i){server.tick();client.tick();}}
 void step(unsigned rate=action_tick_units){auto tick=server.ability_snapshot(owner).tick+1;server.advance_abilities(tick,rate);server.drain_ability_actions();auto motor=server.motors().at(owner.network);motor.tick=tick;motor.sequence=tick;server.publish_motor(owner.network,motor);pump();}
 AbilityReceipt activate(std::uint64_t operation,bool replace=false){return server.request_ability({owner,operation,server.ability_snapshot(owner).grant_generation,CombatSlot::Light,{1,InputEdge::Pressed,operation*1000,0,1,false},replace});}
 EffectHandle external(TagId tag){EffectDefinition definition;definition.id=AssetId::random();definition.generation=std::string(64,'f');definition.lifetime=EffectLifetime::UntilRemoved;definition.tags={tag};return server.apply_effect(owner,owner,definition,0);}
 AbilityIntent intent(std::uint64_t operation,std::uint64_t tick,InputEdge edge=InputEdge::Pressed){return {owner.network,operation,tick,1,1,CombatSlot::Light,edge};}
 OwnerAbilityPrediction predictor(){return {client.ability_corrections().at(owner.network).ability,schema,kit,input,catalogue,1,tags};}
 const AbilityOwnerSnapshot& baseline(){return client.ability_corrections().at(owner.network).ability;}
 void values(std::initializer_list<TagId> expected){check(server.ability_tags(owner)==std::vector<TagId>(expected),"Authoritative action tag interval/cleanup mismatch");}
};
void intervals_and_cleanup(){
 Fixture f;auto handle=f.activate(1).handle;f.values({2});check(f.server.ability_snapshot(f.owner).action_only_tags==std::vector<TagId>{2},"Time-zero tags own only their contribution");f.step(0);f.values({2});f.step();f.values({2,4});f.step();f.values({2,4});f.step();f.values({});f.step();f.values({2});f.step(3*action_tick_units);f.values({});f.step();f.values({});check(!f.server.ability_snapshot(f.owner).active,"Completed looped action removes its token");
 auto shield=f.external(2);handle=f.activate(2).handle;f.values({2});check(f.server.ability_snapshot(f.owner).action_only_tags.empty(),"External overlap is not action-only");f.server.cancel_ability(handle);f.values({2});auto newer=f.activate(3).handle;f.server.cancel_ability(handle);check(f.server.ability_snapshot(f.owner).active==newer,"Old cancellation cannot stop new token owner");f.server.remove_effect(f.owner,shield);f.values({2});f.server.cancel_ability(newer);f.values({});
 f.activate(4);auto replacement=f.activate(5,true);check(replacement.committed,"Interruptible replacement commits");f.values({2});f.server.equip_combat_kit(f.owner,f.kit,f.input,f.catalogue);f.values({});check(!f.server.ability_snapshot(f.owner).active,"Grant removal cleans action token");
 Fixture disconnected;disconnected.external(2);disconnected.activate(1);disconnected.server.detach(disconnected.hp);disconnected.values({2});check(!disconnected.server.ability_snapshot(disconnected.owner).active,"Disconnect removes action contribution while retaining external contributor");
 Fixture death;death.activate(1);EffectDefinition lethal;lethal.id=AssetId::random();lethal.generation=std::string(64,'f');lethal.lifetime=EffectLifetime::Instant;lethal.execute_on_apply=true;lethal.evaluator=9;death.server.register_effect_evaluator(9,[](const EffectContext&){return std::vector<ResourceDelta>{{2,-100}};});death.server.apply_effect(death.owner,death.owner,lethal,0);death.values({});check(!death.server.ability_snapshot(death.owner).active,"Death cleans time-zero action token");
}
void correction_and_rejection(){
 Fixture f;auto prediction=f.predictor();auto press=f.intent(1,1);prediction.advance(1,std::array<AbilityPredictionInput,1>{{{press,0}}});prediction.advance(2);check(prediction.view().tags.values==std::vector<TagId>({2,4}),"Pending action predicts current typed tags");check(f.client.submit_ability_intent(press),"Press submitted");f.pump();f.step();for(auto notice:f.client.drain_ability_receipts())prediction.receipt(notice);check(prediction.reconcile(f.baseline())&&prediction.pending()==0&&prediction.view().tags.values==std::vector<TagId>({2,4}),"Active correction reconstructs own token and replays intervals");
 f.external(2);f.pump();check(f.baseline().action_only_tags.empty()&&prediction.reconcile(f.baseline()),"Same-tick overlap correction keeps external origin");auto release=f.intent(2,3,InputEdge::Released);prediction.advance(3,std::array<AbilityPredictionInput,1>{{{release,1}}});check(prediction.view().tags.values==std::vector<TagId>{2},"Pending cancellation removes own movement tag and retains external invulnerability");check(f.client.submit_ability_intent(release),"Release submitted");f.pump();f.step();prediction.reconcile(f.baseline());check(prediction.view().tags.values==std::vector<TagId>{2},"Replay after intermediate correction preserves external contributor");f.step();for(auto notice:f.client.drain_ability_receipts())prediction.receipt(notice);prediction.reconcile(f.baseline());check(prediction.pending()==0&&prediction.view().tags.values==std::vector<TagId>{2},"Exact cancellation inclusion retains only external tags");
 Fixture solo;auto own=solo.predictor();auto op=solo.intent(1,1);own.advance(1,std::array<AbilityPredictionInput,1>{{{op,0}}});check(solo.client.submit_ability_intent(op),"Solo press submitted");solo.pump();solo.step();own.reconcile(solo.baseline());auto cancel=solo.intent(2,2,InputEdge::Released);own.advance(2,std::array<AbilityPredictionInput,1>{{{cancel,1}}});check(own.view().tags.values.empty(),"Reconstructed action-only token reverses on pending cancel");
 Fixture rejected;rejected.external(2);rejected.pump();auto provisional=rejected.predictor();op=rejected.intent(1,1);provisional.advance(1,std::array<AbilityPredictionInput,1>{{{op,0}}});provisional.advance(2);rejected.external(5);check(rejected.client.submit_ability_intent(op),"Rejected press submitted");rejected.pump();rejected.step();for(auto notice:rejected.client.drain_ability_receipts())provisional.receipt(notice);check(!provisional.view().active&&provisional.view().tags.values==std::vector<TagId>{2},"Terminal rejection reverses pending tags and preserves external baseline");provisional.reconcile(rejected.baseline());check(provisional.view().tags.values==std::vector<TagId>({2,5}),"New blocker baseline survives rejected replay");
}
void preparation_and_wire(){
 Fixture f;auto before=f.server.ability_snapshot(f.owner);auto invalid=std::make_shared<AbilityDefinition>(*f.ability);invalid->action_tags[0].block=99;rejects([&]{f.server.equip_combat_kit(f.owner,f.kit,f.input,std::array<std::shared_ptr<const AbilityDefinition>,1>{invalid});});check(f.server.ability_snapshot(f.owner).grant_generation==before.grant_generation,"Failed binding preparation preserves grants");invalid=std::make_shared<AbilityDefinition>(*f.ability);invalid->action_tags.push_back(invalid->action_tags.front());rejects([&]{freeze_ability_definition(*invalid,AttributeSet(f.schema),f.tags.get());});invalid->action_tags={{1,3}};rejects([&]{OwnerAbilityPrediction private_binding(f.baseline(),f.schema,f.kit,f.input,std::array<std::shared_ptr<const AbilityDefinition>,1>{invalid},1,f.tags);});
 f.activate(1);f.pump();auto correction=f.client.ability_corrections().at(f.owner.network);auto bytes=session_detail::encode_ability_correction(correction);check(session_detail::decode_ability_correction(bytes).ability.action_only_tags==std::vector<TagId>{2},"Owner schema4 preserves action-only provenance");auto bad=correction;bad.ability.action_only_tags={2,2};rejects([&]{session_detail::encode_ability_correction(bad);});bad=correction;bad.ability.action_only_tags={4};rejects([&]{session_detail::encode_ability_correction(bad);});bytes[bytes.size()-8]=std::byte{99};rejects([&]{session_detail::decode_ability_correction(bytes);});auto predictor=f.predictor();bad=correction;bad.ability.revision++;bad.ability.tags.values.push_back(4);bad.ability.action_only_tags.push_back(4);rejects([&]{predictor.reconcile(bad.ability);});check(predictor.needs_resync()&&predictor.view().tags.values==std::vector<TagId>{2},"Non-current action provenance fails atomically");
 auto dense=correction;dense.ability.attributes.clear();dense.ability.tags.values.clear();dense.ability.cooldowns.clear();dense.ability.operations.clear();dense.ability.action_only_tags.clear();dense.ability.highest_operation=128;dense.ability.next_activation=129;for(unsigned i=1;i<=128;++i){dense.ability.tags.values.push_back(i);dense.ability.operations.push_back({i,AbilityFailure::InputIgnored,0,false});if(i<=64)dense.ability.attributes.push_back({i,100});if(i<=32)dense.ability.cooldowns.push_back({i,1});if(i<=16)dense.ability.action_only_tags.push_back(i);}auto packed=session_detail::encode_ability_correction(dense);check(packed.size()<=8192&&session_detail::decode_ability_correction(packed).ability.action_only_tags.size()==16,"Active maximum owner aggregate/attributes/operations/provenance fits existing byte bound");
 auto public_frame=f.client.public_abilities().at(f.owner.network);check(public_frame.ability.tags.values==std::vector<TagId>{2},"Public current action tags exclude private movement tags");ObserverAbility observer(f.schema,2,1,std::array<std::shared_ptr<const ActionDefinition>,1>{f.action},f.tags);observer.push(public_frame);check(observer.sample(0).frame.ability.tags.values==std::vector<TagId>{2},"Active observer restores current tags without executing history");
}
void effect_policy_and_credit(){
 Fixture f;EffectDefinition slow;slow.id=AssetId::random();slow.generation=std::string(64,'f');slow.lifetime=EffectLifetime::UntilRemoved;slow.ongoing.all={4};slow.modifiers={{0,0,4,AttributeModifierKind::Flat,-2}};auto handle=f.server.apply_effect(f.owner,f.owner,slow,0);check(f.server.ability_effects(f.owner).front().suppressed,"Movement dependent effect initially suppressed");f.activate(1);f.step();check(!f.server.ability_effects(f.owner).front().suppressed&&f.server.ability_snapshot(f.owner).attributes[3].value==4,"Action tags feed native ongoing policy in the same tick");f.server.cancel_ability(*f.server.ability_snapshot(f.owner).active);check(f.server.ability_effects(f.owner).front().suppressed&&f.server.ability_snapshot(f.owner).attributes[3].value==6,"Cancellation suppresses dependent effect and restores modifiers");f.server.remove_effect(f.owner,handle);
 EffectDefinition strike;strike.id=AssetId::random();strike.generation=std::string(64,'f');strike.lifetime=EffectLifetime::Instant;strike.execute_on_apply=true;strike.evaluator=1;f.server.register_effect_evaluator(1,[](const EffectContext& context){return std::vector<ResourceDelta>{{2,context.target_tags.has(2)?0.:-10.}};});auto dodge=f.activate(2).handle;f.server.apply_effect(f.owner,f.owner,strike,10,dodge.activation);check(f.server.objects().at(f.owner.network).health.current==100,"Game-owned evaluator sees authoritative action invulnerability");f.server.cancel_ability(dodge);f.server.apply_effect(f.owner,f.owner,strike,10);check(f.server.objects().at(f.owner.network).health.current==90,"Removing only action token permits next authoritative damage");
 Fixture maximum;EffectDefinition bonus;bonus.id=AssetId::random();bonus.generation=std::string(64,'f');bonus.lifetime=EffectLifetime::UntilRemoved;bonus.ongoing.all={2};bonus.modifiers={{0,0,1,AttributeModifierKind::Flat,100}};maximum.server.apply_effect(maximum.owner,maximum.owner,bonus,0);maximum.activate(1);EffectDefinition heal=strike;heal.evaluator=7;maximum.server.register_effect_evaluator(7,[](const EffectContext&){return std::vector<ResourceDelta>{{2,80}};});maximum.server.apply_effect(maximum.owner,maximum.owner,heal,0);check(maximum.server.objects().at(maximum.owner.network).health.current==180,"Action-conditioned maximum bonus is active");check(maximum.activate(2,true).committed&&maximum.server.objects().at(maximum.owner.network).health.current==180,"Replacement publishes one final tag view without transient max-resource clamp");maximum.server.detach(maximum.hp);check(maximum.server.objects().at(maximum.owner.network).health.maximum==100&&maximum.server.objects().at(maximum.owner.network).health.current==100&&maximum.server.ability_snapshot(maximum.owner).attributes[1].value==100,"Disconnect publishes resource clamps with action-tag cleanup");
}
}
int main(){try{intervals_and_cleanup();correction_and_rejection();preparation_and_wire();effect_policy_and_credit();std::cout<<"Typed action interval tags, token cleanup, external overlap, owner correction/rejection, bounded provenance and native effect policy passed\n";return 0;}catch(const std::exception& e){std::cerr<<e.what()<<'\n';return 1;}}
