#include <darkangel/action.hpp>
#include <darkangel/assets.hpp>
#include <darkangel/editor_document.hpp>
#include <darkangel/character_motor.hpp>
#include <nlohmann/json.hpp>
#include <filesystem>
#include <fstream>
#include <iostream>
#include <map>
using namespace darkangel;
namespace {
void require(bool b,const char* s){if(!b)throw std::runtime_error(s);}
std::string read(const std::filesystem::path& p){std::ifstream f(p);return {std::istreambuf_iterator<char>(f),{}};}
std::vector<ActionEvent> trace(const std::shared_ptr<const ActionDefinition>& definition,unsigned rate){ActionTimeline action(definition,1,0);auto events=action.enter().events;SimulationClock clock;for(unsigned frame=0;frame<rate;++frame){auto ticks=clock.advance(1.0/rate);for(unsigned n=0;n<ticks;++n)if(action.state().phase==ActionPhase::Active){auto batch=action.advance(action.state().tick+1);events.insert(events.end(),batch.events.begin(),batch.events.end());}}require(action.state().phase==ActionPhase::Completed,"Timeline completes independent of render rate");return events;}
}
int main(){try{
    auto fixture=std::filesystem::path(DAE_SOURCE_DIR)/"content/animation/m5_attack.daaction";auto native=read(fixture);auto mutable_definition=std::make_shared<ActionDefinition>(decode_action_source(native));std::shared_ptr<const ActionDefinition> definition=mutable_definition;
    ActionTimeline action(definition,17,100),independent(definition,18,100);ActionCueLedger ledger;auto entry=action.enter();require(entry.events.size()==2&&entry.events[0].kind==ActionBlockKind::Cue&&entry.events[1].edge==ActionEdge::Begin,"Explicit ordered time-zero entry");require(ledger.accept(entry.events[0])&&!ledger.accept(entry.events[0]),"Predicted/confirmed cue identity deduplicates");auto baseline=action.state();auto batch=action.advance(101);require(batch.traversed.size()==2&&batch.traversed[0].kind==ActionBlockKind::HitWindow&&batch.traversed[0].from==512&&batch.traversed[0].to==768,"Whole crossed hit window retained for owning collision evaluator");require(batch.events.size()==3&&batch.events[0].edge==ActionEdge::Begin&&batch.events[1].edge==ActionEdge::End,"Crossed window emits balanced boundaries");auto stopped=action.advance(102,0);require(stopped.events.empty()&&stopped.traversed.empty()&&action.state().clock==1024&&action.state().tick==102,"Hitstop freezes action motion and suppresses hit reevaluation");
    independent.enter();require(independent.state().clock==0,"Independent mutable clocks");auto fast=action.advance(103,4096);require(action.state().clock==5120,"Bounded playback crosses loop boundary");unsigned repeated=0;for(const auto& e:fast.events)if(e.kind==ActionBlockKind::Cue){require(ledger.accept(e),"New loop cue unique identity");++repeated;}require(repeated==1,"Loop marker dispatched once");auto cancel=action.cancel();require(cancel.events.size()==2&&cancel.events[0].loop==1&&cancel.events[0].edge==ActionEdge::End,"Cancellation releases current movement and immunity tokens");
    action.restore(baseline);action.advance(101);action.advance(102,0);auto replay=action.advance(103,4096);for(const auto& e:replay.events)if(e.kind==ActionBlockKind::Cue)require(!ledger.accept(e),"Replay cannot duplicate already-presented cue");require(action.cancel().events==cancel.events,"Replay reproduces cleanup identity");
    auto state=action.state();auto wrong=baseline;wrong.generation=std::string(64,'f');bool rejected=false;try{action.restore(wrong);}catch(...){rejected=true;}require(rejected&&action.state().clock==state.clock&&action.state().phase==state.phase,"Generation-mismatched correction rejects atomically");action.restore(baseline);rejected=false;try{action.advance(101,4097);}catch(...){rejected=true;}require(rejected&&action.state().tick==100,"Rate work bound rejects before mutation");
    require(trace(definition,30)==trace(definition,60)&&trace(definition,60)==trace(definition,144),"30/60/144 event traces match headless ticks");auto events=trace(definition,60);std::map<std::pair<unsigned,unsigned>,int> balances;for(const auto& e:events)if(e.kind!=ActionBlockKind::Cue)balances[{e.block,e.loop}]+=e.edge==ActionEdge::Begin?1:-1;for(auto [id,count]:balances)require(count==0,"Completion balances every interval in every loop");
    mutable_definition->duration=999999;require(action.definition().duration==4096,"Active generation pins immutable definition");*mutable_definition=decode_action_source(native);
    ActionCueLedger bounded;for(unsigned n=1;n<=256;++n){auto cue=entry.events[0];cue.activation=n;require(bounded.accept(cue),"Bounded cue insertion");}auto cue=entry.events[0];cue.activation=257;rejected=false;try{bounded.accept(cue);}catch(...){rejected=true;}require(rejected,"Full ledger does not silently forget events");bounded.retire(1);require(bounded.accept(cue),"Explicit retired activation releases cue budget");
    auto root=std::filesystem::path(DAE_BINARY_DIR)/("action-fixture-"+AssetId::random().text());std::filesystem::create_directories(root/"sources");std::filesystem::copy_file(fixture,root/"sources/attack.daaction");AssetId id=definition->id;std::string first_generation;
    {AssetService assets(root/"sources",root/"cache");require(assets.adopt("attack.daaction")==id,"Native embedded action UUID");require(assets.cook("attack.daaction").changed&&!assets.cook("attack.daaction").changed,"Action warm cook");assets.package(id,root/"registry.json");first_generation=load_cooked_action(root/"registry.json",assets.cas_path(),id).generation;auto edit=nlohmann::json::parse(native);edit["duration"]=0;std::ofstream(root/"sources/attack.daaction")<<edit.dump();rejected=false;try{assets.cook("attack.daaction");}catch(...){rejected=true;}require(rejected,"Zero duration fails before publication");assets.package(id,root/"registry.json");require(load_cooked_action(root/"registry.json",assets.cas_path(),id).generation==first_generation,"Failed action generation preserves frozen product");}
    std::ofstream(root/"sources/attack.daaction")<<native;{AssetService fresh(root/"sources",root/"fresh");fresh.scan();fresh.cook("attack.daaction");fresh.package(id,root/"fresh.json");require(load_cooked_action(root/"fresh.json",fresh.cas_path(),id).generation==first_generation,"Fresh cache retains action identity/generation");}
    auto assembly=AssetId::random();nlohmann::json source={{"schema",1},{"asset",assembly.text()},{"entities",nlohmann::json::object()},{"mounts",nlohmann::json::object()}};EditorDocument doc(assembly,{8,1},{{assembly,source.dump()},{id,native}});auto edit=nlohmann::json::parse(native);edit["priority"]=20;doc.commit(doc.prepare_source(doc.revision(),id,edit.dump()),"Action source edit");doc.undo(doc.revision());require(!doc.dirty(),"Action undo preserves saved source");doc.redo(doc.revision());doc.save(root/"action.dadoc");require(EditorDocument::open(root/"action.dadoc")->source(id)==edit.dump(),"Action native save/Open");edit["blocks"][1]["end"]=512;rejected=false;try{doc.prepare_source(doc.revision(),id,edit.dump());}catch(...){rejected=true;}require(rejected,"Invalid hit interval rejected during prepare");
    std::cout<<"Native integer action clocks, crossed intervals, finite loops, hitstop/cancellation, replay cue identities, CAS and authoring passed\n";return 0;
}catch(const std::exception& e){std::cerr<<e.what()<<'\n';return 1;}}
