#include <darkangel/assets.hpp>
#include <darkangel/action.hpp>
#include <darkangel/animation_assets.hpp>
#include <darkangel/character_motor.hpp>
#include <nlohmann/json.hpp>
#include <fstream>
#include <iostream>
#include <cmath>
using namespace darkangel;
using Json=nlohmann::json;
namespace {
void check(bool b,const char* message){if(!b)throw std::runtime_error(message);}
template<class F>void rejects(F f){bool denied=false;try{f();}catch(const std::exception&){denied=true;}check(denied,"Expected action binding rejection");}
Json read(const std::filesystem::path& path){std::ifstream file(path);return Json::parse(file);}
void write(const std::filesystem::path& path,const Json& value){std::ofstream(path)<<value.dump(2);}
}
int main(){try{
    auto root=std::filesystem::path(DAE_BINARY_DIR)/("action-clip-"+AssetId::random().text()),sources=root/"sources";std::filesystem::create_directories(sources/"animation");auto content=std::filesystem::path(DAE_SOURCE_DIR)/"content";
    std::filesystem::copy_file(content/"animation/canonical_human.daskeleton",sources/"animation/canonical_human.daskeleton");std::filesystem::copy_file(content/"royal_district/clips/attack.glb",sources/"attack.glb");auto metadata=read(content/"royal_district/clips/attack.glb.daimport");write(sources/"attack.glb.daimport",metadata);
    auto action=read(content/"animation/m5_attack.daaction");auto id=AssetId::random();action["asset"]=id.text();action["schema"]=2;action["duration"]=52*action_tick_units;action["loops"]=1;action["motion"]={{"clip",metadata.at("id")},{"source","attack.glb"},{"policy","motor"}};write(sources/"attack.daaction",action);ActionDefinition pinned;CookedClip cooked;CookedRig rig;
    {
        AssetService service(sources,root/"cache");check(service.adopt("attack.daaction")==id,"Bound action embedded identity");service.cook("attack.daaction");auto converted=service.conversion_count();check(!service.cook("attack.daaction").changed&&service.conversion_count()==converted,"Bound action warm cook skips conversion");service.package(id,root/"registry.json");check(read(root/"registry.json").at("assets").size()==5,"Action owns frozen clip/rig closure");pinned=load_cooked_action(root/"registry.json",service.cas_path(),id);check(pinned.motion&&pinned.motion->clip.ticks==52&&pinned.motion->motor_root,"Action clock binds actual native attack clip");cooked=load_cooked_clip(root/"registry.json",service.cas_path(),pinned.motion->clip.id);rig=load_cooked_rig(root/"registry.json",service.cas_path(),pinned.motion->clip.skeleton);
        auto invalid=action;invalid["duration"]=51*action_tick_units;write(sources/"attack.daaction",invalid);rejects([&]{service.cook("attack.daaction");});invalid=action;invalid["loops"]=2;write(sources/"attack.daaction",invalid);rejects([&]{service.cook("attack.daaction");});invalid=action;invalid["slot"]="upper-body";write(sources/"attack.daaction",invalid);rejects([&]{service.cook("attack.daaction");});invalid=action;invalid["motion"]["source"]="../attack.glb";write(sources/"attack.daaction",invalid);rejects([&]{service.cook("attack.daaction");});service.package(id,root/"after-failure.json");check(load_cooked_action(root/"after-failure.json",service.cas_path(),id).generation==pinned.generation,"Failed binding preserves head");write(sources/"attack.daaction",action);
        auto changed=metadata;changed["subassets"]["runtime"]=AssetId::random().text();write(sources/"attack.glb.daimport",changed);service.cook("attack.daaction");service.package(id,root/"changed.json");check(load_cooked_action(root/"changed.json",service.cas_path(),id).generation!=pinned.generation,"Clip generation invalidates action");auto mixed=read(root/"registry.json"),new_manifest=read(root/"changed.json");for(auto& record:mixed["assets"])if(record["id"]==metadata["id"])for(const auto& replacement:new_manifest["assets"])if(replacement["id"]==record["id"])record=replacement;write(root/"bad.json",mixed);rejects([&]{load_cooked_action(root/"bad.json",service.cas_path(),id);});write(sources/"attack.glb.daimport",metadata);service.cook("attack.daaction");
        std::filesystem::rename(sources,root/"offline-sources");check(load_cooked_action(root/"registry.json",service.cas_path(),id).generation==pinned.generation,"Action binding loads without sources");std::filesystem::rename(root/"offline-sources",sources);
    }
    auto trace=[&](unsigned rate){ActionTimeline running(std::make_shared<const ActionDefinition>(pinned),9,0);running.enter();SimulationClock clock;std::vector<std::array<double,5>> result;for(unsigned frame=0;frame<rate;++frame)for(unsigned count=clock.advance(1.0/rate);count&&running.state().phase==ActionPhase::Active;--count){auto before=running.state().clock;running.advance(running.state().tick+1);auto request=action_motion_between(pinned,before,running.state().clock);result.push_back({request.root.translation[0],request.root.translation[1],request.root.translation[2],request.root.yaw,request.movement_lock?1.:0.});}check(result.size()==52,"Bound action finishes under render schedule");return result;};check(trace(30)==trace(60)&&trace(60)==trace(144),"Bound root/action traces match at synthetic 30/60/144 rendering");
    auto source=std::make_shared<ActionDefinition>(pinned);ActionTimeline timeline(source,7,0);timeline.enter();source->motion->clip.root.back()[2]=50;check(timeline.definition().motion->clip.root.back()[2]==0,"Active binding cannot change through mutable alias");
    PhysicsWorld physics;CollisionBox floor;floor.id=1;floor.center={0,-.5,0};floor.half={10,.5,10};physics.add(floor);CollisionBox wall;wall.id=2;wall.center={0,1,.47};wall.half={2,1,.1};physics.add(wall);CharacterMotor motor(physics,{0,0,0},3);double maximum{},requested_peak{};std::uint64_t previous{};
    AnimationClip clip(cooked.definition,cooked.archive);RigPose pose(rig.definition,rig.archive);
    for(unsigned tick=1;tick<=52;++tick){timeline.advance(tick);auto motion=action_motion_between(timeline.definition(),previous,timeline.state().clock);previous=timeline.state().clock;MotionRequest request;request.root={motion.root.translation[0],motion.root.translation[1],motion.root.translation[2]};request.action=7;request.lock=motion.movement_lock;motor.step({tick,tick,motor.state().epoch},request);physics.step();motor.post_physics();physics.finish_tick();maximum=std::max(maximum,motor.state().position.z);requested_peak=std::max(requested_peak,double(pinned.motion->clip.root[tick][2]));pose.sample(clip,double(timeline.state().clock)/action_tick_units);check(motor.state().action==7,"Motor retains action root owner");}
    check(requested_peak>.06&&maximum<requested_peak-.005,"Jolt collision determines achieved root motion");check(timeline.state().phase==ActionPhase::Completed&&timeline.state().clock==52*action_tick_units,"Pose and action share the complete clip clock");auto frozen=action_motion_between(pinned,10*action_tick_units,10*action_tick_units);check(frozen.root.translation==std::array<double,3>{}&&!frozen.movement_lock,"Zero-rate interval requests no root motion");check(action_motion_between(pinned,action_tick_units,action_tick_units).movement_lock,"Hitstop retains the active movement lock");rejects([&]{action_motion_between(pinned,10*action_tick_units,9*action_tick_units);});
    std::cout<<"Frozen action clip/rig, coherent timeline/root clock and collision-achieved motor ownership passed\n";return 0;
}catch(const std::exception& error){std::cerr<<error.what()<<'\n';return 1;}}
