#include <darkangel/actor_assets.hpp>
#include <darkangel/hash.hpp>
#include <fstream>
#include <iostream>
#include <nlohmann/json.hpp>
using namespace darkangel;using Json=nlohmann::json;
namespace {
std::string read(const std::filesystem::path& path){std::ifstream file(path,std::ios::binary);return {std::istreambuf_iterator<char>(file),{}};}
void write(const std::filesystem::path& path,const Json& data){std::ofstream(path,std::ios::binary)<<data.dump(2)<<'\n';}
void check(bool value,const char* message){if(!value)throw std::runtime_error(message);}
template<class F>void rejects(F f){bool rejected=false;try{f();}catch(const std::exception&){rejected=true;}check(rejected,"Expected actor asset rejection");}
}
int main(int argc,char** argv){try{
 check(argc==2,"Pass authoring fixture");auto fixture=Json::parse(read(argv[1]));auto root=std::filesystem::path(argv[1]).parent_path()/("actor-"+AssetId::random().text()),source=root/"sources";std::filesystem::create_directories(root);std::filesystem::copy(fixture.at("source").get<std::string>(),source,std::filesystem::copy_options::recursive);AssetService assets(source,root/"cache");assets.scan();
 auto skin=AssetId::parse(Json::parse(read(source/"royal_district/character/canonical-human.glb.daimport")).at("id").get<std::string>());auto kit=AssetId::parse(fixture.at("kit").get<std::string>());auto character_id=AssetId::random(),player_id=AssetId::random();
 Json character={{"schema",1},{"kind","character"},{"asset",character_id.text()},{"skin",skin.text()},{"sources",{{"skin","royal_district/character/canonical-human.glb"}}}};
 Json player={{"schema",1},{"kind","player"},{"asset",player_id.text()},{"character",character_id.text()},{"loadout",{{"kit",kit.text()}}},{"sources",{{"character","royal_district/character/test.dacharacter"},{"kit","royal_district/combat/player.dakit"}}}};
 assets.create_native("royal_district/character/test.dacharacter",character.dump());assets.create_native("royal_district/combat/test.daplayer",player.dump());assets.package(player_id,root/"player.json");auto old=load_cooked_player(root/"player.json",assets.cas_path(),player_id);check(!assets.cook("royal_district/combat/test.daplayer").changed&&!assets.cook("royal_district/character/test.dacharacter").changed,"Actor unchanged cache reuse failed");check(old.character.definition.skin==skin&&old.definition.character==character_id&&old.kit.definition->id==kit,"Player did not resolve separate native Character and kit");check(!old.character.skin.meshes.empty(),"Character skin closure missing");
 auto forbidden=character;forbidden["kit"]=kit.text();rejects([&]{assets.edit_native("royal_district/character/test.dacharacter",sha256(read(source/"royal_district/character/test.dacharacter")),forbidden.dump());});check(Json::parse(read(source/"royal_district/character/test.dacharacter"))==character,"Failed Character edit changed source");
 auto bad=player;bad["character"]=AssetId::random().text();rejects([&]{assets.edit_native("royal_district/combat/test.daplayer",sha256(read(source/"royal_district/combat/test.daplayer")),bad.dump());});assets.package(player_id,root/"failed.json");check(read(root/"player.json")==read(root/"failed.json"),"Failed actor validation replaced playable generation");
 auto other_kit=Json::parse(read(source/"royal_district/combat/player.dakit"));auto other_id=AssetId::random();other_kit["asset"]=other_id.text();other_kit["slots"][1]["ability"]=nullptr;auto heavy=old.kit.definition->slots[1].ability;other_kit["sources"]["abilities"].erase(heavy.text());if(other_kit.contains("effect_bindings")){auto& bindings=other_kit["effect_bindings"];for(auto it=bindings.begin();it!=bindings.end();)if((*it)["ability"]==heavy.text())it=bindings.erase(it);else ++it;}
 assets.create_native("royal_district/combat/alternate.dakit",other_kit.dump());auto second_id=AssetId::random();auto second=player;second["asset"]=second_id.text();second["loadout"]["kit"]=other_id.text();second["sources"]["kit"]="royal_district/combat/alternate.dakit";assets.create_native("royal_district/combat/second.daplayer",second.dump());assets.package(second_id,root/"second.json");auto other=load_cooked_player(root/"second.json",assets.cas_path(),second_id);check(other.definition.character==old.definition.character&&other.kit.definition->id!=old.kit.definition->id&&old.kit.definition->slots[1].ability!=AssetId{}&&other.kit.definition->slots[1].ability==AssetId{},"Shared Character forced same gameplay loadout or changed old generation");
 auto kit_path=source/"royal_district/combat/player.dakit";auto kit_bytes=read(kit_path);auto replacement=other_kit;replacement["asset"]=kit.text();NativeSourceEdit edit{"royal_district/combat/player.dakit",sha256(kit_bytes),replacement.dump()};auto prepared=assets.prepare_native({&edit,1});check(read(kit_path)==kit_bytes,"Actor consumer preparation published source");auto prepared_player=load_cooked_player(prepared.registry(),assets.cas_path(),player_id);check(prepared_player.kit.definition->slots[1].ability==AssetId{},"Changed kit did not reprepare Player consumer");assets.commit_native(prepared);assets.package(player_id,root/"updated.json");auto updated=load_cooked_player(root/"updated.json",assets.cas_path(),player_id);check(updated.definition.generation!=old.definition.generation&&old.kit.definition->slots[1].ability!=AssetId{}&&updated.kit.definition->slots[1].ability==AssetId{},"Coordinated actor consumer did not publish frozen replacement");NativeSourceEdit restore{"royal_district/combat/player.dakit",sha256(read(kit_path)),kit_bytes};auto restore_candidate=assets.prepare_native({&restore,1});assets.commit_native(restore_candidate);assets.package(player_id,root/"player.json");
 auto manifest=Json::parse(read(root/"player.json"));for(auto& record:manifest["assets"])if(record["id"]==kit.text())record["sha256"]=std::string(64,'0');write(root/"mixed.json",manifest);rejects([&]{load_cooked_player(root/"mixed.json",assets.cas_path(),player_id);});
 Json result={{"source",source.generic_string()},{"cache",(root/"cache").generic_string()},{"registry",(root/"player.json").generic_string()},{"character",character_id.text()},{"player",player_id.text()},{"kit",kit.text()}};write(std::filesystem::path(argv[1]).parent_path()/"actor-fixture.json",result);std::cout<<"Actor assets: presentation Character, shared loadout refs, two Player kits, frozen closure, invalid ownership/reference rollback and mixed generation rejection passed\n";return 0;
 }catch(const std::exception& error){std::cerr<<error.what()<<'\n';return 1;}}
