#include "../apps/editor/native_authoring.hpp"
#include <darkangel/effect_assets.hpp>
#include <fstream>
#include <iostream>
#include <algorithm>
using namespace darkangel;using namespace darkangel::editor_app;using Json=nlohmann::json;
std::string read(const std::filesystem::path& p){std::ifstream f(p);return {std::istreambuf_iterator<char>(f),{}};}
void check(bool b,const char* m){if(!b)throw std::runtime_error(m);}
template<class F>void rejects(F f){bool rejected=false;try{f();}catch(const std::exception&){rejected=true;}check(rejected,"Expected attribute authoring rejection");}
int main(int argc,char** argv){try{
 check(argc==2,"Pass isolated authoring fixture");auto fixture=Json::parse(read(argv[1]));auto root=std::filesystem::path(argv[1]).parent_path()/("aa-"+AssetId::random().text());auto source=root/"s";std::filesystem::create_directories(root);std::filesystem::copy(fixture["source"].get<std::string>(),source,std::filesystem::copy_options::recursive);
 AssetService assets(source,root/"cache");assets.scan();NativeAuthoring author;auto attributes_path="royal_district/combat/base.daattributes";auto schema=Json::parse(read(source/attributes_path));auto id=AssetId::parse(schema["asset"].get<std::string>());auto& value=author.open(assets,id).value;
 auto added=author.add_attribute(assets,id,"AttackPower",AttributeKind::Statistic);auto edited=value;author.undo(assets);check(value==schema,"Attribute creation Undo failed");author.redo(assets);check(value==edited,"Attribute creation Redo failed");rejects([&]{author.add_attribute(assets,id,"AttackPower",AttributeKind::Statistic);});check(value==edited,"Duplicate attribute mutated draft");
 auto copied=author.duplicate(assets,id,"attribute_copy");check(copied!=id&&author.open(assets,copied).value["attributes"]==value["attributes"],"Schema creation did not preserve fields with fresh asset identity");
 value["attributes"].back()["base"]=20;author.record_changes(assets,"Set AttackPower base");auto burn=AssetId::parse(Json::parse(read(source/"royal_district/combat/burn.daeffect"))["asset"].get<std::string>());auto effect=author.duplicate(assets,burn,"standalone_modifier",true);auto& definition=author.open(assets,effect).value;
 definition["modifiers"].push_back({{"attribute",added},{"kind","flat"},{"magnitude",7},{"channel",""},{"priority",0}});author.record_changes(assets,"Configure ordinary modifier");author.save_all(assets);assets.package(effect,root/"effect.json");auto cooked=load_cooked_effect(root/"effect.json",assets.cas_path(),effect);
 AttributeSet target(cooked.attributes.definitions());OwnedEffects effects(cooked.tags.dictionary());auto handle=effects.apply(*cooked.definition,{1,3,7,0,{}},0,target,{}).first;check(target.value(added)==27&&target.value(2)==100,"Modifier did not use authored statistic without evaluator");effects.remove(handle,target);check(target.value(added)==20,"Modifier cleanup changed base statistic");
 auto saved_schema=read(source/attributes_path),saved_effect=read(source/author.open(assets,effect).asset.path);author.remove_attribute(assets,id,added);rejects([&]{author.save_all(assets);});check(read(source/attributes_path)==saved_schema&&read(source/author.open(assets,effect).asset.path)==saved_effect,"Broken standalone consumer changed sources");assets.package(effect,root/"failed.json");check(read(root/"effect.json")==read(root/"failed.json"),"Broken consumer changed prior effect head");author.undo(assets);check(value==Json::parse(saved_schema),"Schema deletion Undo failed");
 definition["modifiers"].clear();author.record_changes(assets,"Remove modifier reference");author.remove_attribute(assets,id,added);author.save_all(assets);auto newer=author.add_attribute(assets,id,"AttackPowerNext",AttributeKind::Statistic);check(newer>added,"Removed attribute ID reused in session");author.undo(assets);assets.package(effect,root/"clean.json");auto clean=load_cooked_effect(root/"clean.json",assets.cas_path(),effect);check(clean.attributes.fields.size()==schema["attributes"].size()&&clean.definition->modifiers.empty(),"Explicit schema/consumer cleanup did not cook");
 check(cooked.attributes.fields.size()==schema["attributes"].size()+1,"Prior frozen attribute generation changed");Json result={{"source",source.generic_string()},{"cache",(root/"cache").generic_string()},{"attributes",id.text()},{"effect",effect.text()}};std::ofstream(std::filesystem::path(argv[1]).parent_path()/"attribute-authoring-fixture.json")<<result.dump(2);
 std::cout<<"Attribute authoring: stable IDs, create/remove history, standalone effect consumer rollback, frozen generations and evaluator-free modifier20->27->20 passed\n";return 0;
 }catch(const std::exception& e){std::cerr<<e.what()<<'\n';return 1;}}
