#include <darkangel/gns_transport.hpp>
#include <darkangel/combat_kit_assets.hpp>
#include <darkangel/world_session.hpp>
#include <chrono>
#include <thread>
#include <iostream>
using namespace darkangel;
namespace {struct EmptyQuery final:MeleeQuery {bool matches(std::uint64_t,const MotorState&)const override{return true;}MeleeCandidates query(std::uint64_t,const MotorState&,const AbilityMelee&)const override{return {};}};void check(bool b,const char* e){if(!b)throw std::runtime_error(e);}}
int main(int argc,char** argv){try{
 check(argc==5,"Use --host/--client registry cas kit");bool host=std::string_view(argv[1])=="--host";check(host||std::string_view(argv[1])=="--client","Unknown role");auto cooked=load_cooked_combat_kit(argv[2],argv[3],AssetId::parse(argv[4]));const auto& bindings=cooked.definition->effect_bindings;auto edited=std::find_if(bindings.begin(),bindings.end(),[](const auto& value){return value.power==7;});check(edited!=bindings.end(),"Use the edited authoring fixture with effect power7");auto binding=*edited;auto effect=*std::find_if(cooked.effects.begin(),cooked.effects.end(),[&](auto e){return e->id==binding.effect;});check(effect->duration_ticks==120&&effect->period_ticks==30,"GNS consumes the newly cooked authored status");SessionHandshake hello{3,cooked.definition->generation,cooked.definition->generation,27152};auto transport=host?create_gns_host("127.0.0.1:27152",hello):create_gns_client("127.0.0.1:27152",hello);auto peer=transport->open(hello);WorldSession session(host?SessionRole::Server:SessionRole::Client,hello);
 AbilityOwnerHandle target;std::uint64_t activation{};
 if(host){ObjectData caster;caster.id={88,1};auto source=session.create(caster);ObjectData victim;victim.id={88,2};auto network=session.create(victim);auto credit=session.configure_abilities(source,cooked.attributes.definitions(),2,1);target=session.configure_abilities(network,cooked.attributes.definitions(),2,1);session.configure_ability_tags(credit,cooked.tags->dictionary());session.configure_ability_tags(target,cooked.tags->dictionary());session.register_effect_evaluator(2,[](const EffectContext& context){return std::vector<ResourceDelta>{{2,-context.credit.power}};});session.bind_melee_query(std::make_shared<EmptyQuery>());session.register_damage_evaluator(1,[](const DamageContext& context){return context.power;});session.equip_combat_kit(credit,cooked.definition,cooked.input,cooked.abilities);session.advance_abilities(1);auto receipt=session.request_ability({credit,1,session.ability_snapshot(credit).grant_generation,CombatSlot::Light,{8,InputEdge::Pressed,1000,0,1,false},false});check(receipt.committed,"Native activation owns effect attribution");activation=receipt.handle.activation;session.apply_effect(target,credit,*effect,binding.power,activation);session.destroy(source);for(unsigned tick=2;tick<=20;++tick)session.advance_abilities(tick);session.drain_effect_outcomes();}
 auto deadline=std::chrono::steady_clock::now()+std::chrono::seconds(10);while(!transport->connected()&&std::chrono::steady_clock::now()<deadline)std::this_thread::sleep_for(std::chrono::milliseconds(2));check(transport->connected(),"GNS connect deadline");session.attach(*transport,peer);if(host){session.own_motor(2,peer);for(unsigned tick=1;tick<=20;++tick)session.consume_motor(2,tick,1);MotorState state;state.tick=20;state.sequence=20;session.publish_motor(2,state);}
 EffectPresentation owner(AttributeVisibility::Owner,AttributeSet(cooked.attributes.definitions()),cooked.tags->dictionary(),cooked.effects),observer(AttributeVisibility::Public,AttributeSet(cooked.attributes.definitions()),cooked.tags->dictionary(),cooked.effects);bool joined=false;unsigned begins{},ends{};std::uint64_t executed=20,submitted=20;deadline=std::chrono::steady_clock::now()+std::chrono::seconds(20);
 while(std::chrono::steady_clock::now()<deadline){session.tick();if(session.readiness(peer)==SessionReadiness::Ready){if(!host){auto push=[&](AttributeVisibility audience,EffectPresentation& view){auto f=session.effect_frames(audience).find(2);if(f!=session.effect_frames(audience).end())view.push(f->second);};push(AttributeVisibility::Owner,owner);push(AttributeVisibility::Public,observer);for(auto cue:observer.drain_cues()){begins+=cue.edge==EffectCueEdge::Begin;ends+=cue.edge==EffectCueEdge::End;}owner.drain_cues();if(!joined&&owner.current()&&observer.current()&&observer.current()->effects.size()==1&&session.ability_corrections().contains(2)&&session.ability_corrections().at(2).motor.tick==20&&session.motors().contains(2)){auto status=observer.current()->effects.front();check(status.definition==effect->id&&status.start==1&&status.end==121&&status.next_period==31&&observer.cues().size()==1,"Owner/public join uses authored identity and timers");joined=true;}
 if(joined&&session.motors().contains(2)&&session.motors().at(2).tick==submitted&&submitted<121){auto next=++submitted;check(session.submit_motor(2,{next,next,session.motors().at(2).epoch}),"Next effect tick");}
 if(joined&&submitted==121&&session.motors().contains(2)&&session.motors().at(2).tick==121&&owner.current()->effects.empty()&&observer.current()->effects.empty()){check(session.objects().at(2).health.current==79&&begins==1&&ends==1&&observer.cues().empty(),"Edited Burn7 applies three periods and expires for owner/public");check(session.submit_motor(2,{122,122,session.motors().at(2).epoch}),"Delivery fence");std::cout<<"Authored GNS client: owner/public Burn120 period30 power7, Health100->79, one status lifetime passed\n";std::this_thread::sleep_for(std::chrono::milliseconds(300));return 0;}}
 if(host&&executed<121&&session.motor_input_ready(2,executed+1)){auto tick=++executed;session.consume_motor(2,tick,1);session.advance_abilities(tick);session.drain_effect_outcomes();auto state=session.motors().at(2);state.tick=tick;state.sequence=tick;session.publish_motor(2,state);}
 if(host&&executed==121&&session.motor_input_ready(2,122)){check(session.objects().at(2).health.current==79,"Authored native Health result");std::cout<<"Authored GNS host: frozen edited kit/effect and native activation synchronized\n";std::this_thread::sleep_for(std::chrono::milliseconds(300));return 0;}}
 std::this_thread::sleep_for(std::chrono::milliseconds(host?5:2));}throw std::runtime_error("Authored GNS deadline");
}catch(const std::exception& e){std::cerr<<e.what()<<'\n';return 1;}}
