#include <darkangel/character_scene.hpp>
#include <darkangel/combat_kit_assets.hpp>
#include <darkangel/assets.hpp>
#include <darkangel/hash.hpp>
#include <nlohmann/json.hpp>
#include <fstream>
#include <iostream>
using namespace darkangel;
namespace {void check(bool value,const char* message){if(!value)throw std::runtime_error(message);}}
int main(){try{
    auto content=std::filesystem::path(DAE_SOURCE_DIR)/"content",cache=std::filesystem::path(DAE_BINARY_DIR)/("character-combat-"+AssetId::random().text());std::ifstream source(content/"royal_district/combat/player.dakit");auto data=nlohmann::json::parse(source);auto id=AssetId::parse(data.at("asset").get<std::string>());AssetService assets(content,cache);assets.cook("royal_district/combat/player.dakit");assets.package(id,cache/"registry.json");auto cooked=load_cooked_combat_kit(cache/"registry.json",assets.cas_path(),id);
    CharacterSceneCombat combat;combat.kit=cooked.definition;combat.input=cooked.input;combat.attributes=cooked.attributes.definitions();combat.health=2;combat.maximum_health=1;combat.abilities=cooked.abilities;combat.target={9,2};combat.evaluator=1;combat.damage=[](const DamageContext& context){return context.power;};for(const auto& ability:cooked.abilities){auto clip=load_cooked_clip(cache/"registry.json",assets.cas_path(),ability->action->motion->clip.id);combat.clips.emplace(clip.definition.id,std::make_shared<const AnimationClip>(clip.definition,clip.archive));}
    ObjectData player;player.id={9,1};ObjectData target;target.id=combat.target;target.transform.z=1.2;target.transform.yaw=3.141592653589793;std::array<ObjectData,2> objects{player,target};World authoring(WorldDomain::Authoring);for(auto object:objects)authoring.create(object);auto original=authoring.serialize();CollisionDefinition collision;collision.id=AssetId::random();collision.schema=2;collision.boxes={{100,{0,-.5,0},{16,.5,16}}};SessionHandshake hello{3,sha256("character combat scene wire3"),sha256(cooked.definition->generation),703};
    {CharacterSceneSession bounded(hello,objects,player.id,collision,cooked.stance.plan,cooked.stance.rig.definition,cooked.stance.rig.archive,combat);CharacterSceneInput excessive;excessive.combat_events.assign(33,{8,InputEdge::Pressed,1000,0,1,false});bool rejected=false;try{bounded.advance(0,excessive);}catch(const std::exception&){rejected=true;}check(rejected,"Combat queue overflow rejects explicitly");bounded.advance(1./60,{});check(!bounded.ability()->active,"Rejected input batch cannot leave a queued partial activation");}
    CharacterSceneSession session(hello,objects,player.id,collision,cooked.stance.plan,cooked.stance.rig.definition,cooked.stance.rig.archive,combat);
    CharacterSceneInput pressed;pressed.combat_events={{8,InputEdge::Pressed,1000,0,1,false}};check(session.advance(1./144,pressed)==0,"Render edge retained before fixed tick");while(session.motor().tick<1)session.advance(1./144,{});check(session.ability()&&session.ability()->active,"Serialized owned intent starts existing native action");check(session.predicted_ability()&&session.predicted_ability()->active==session.ability()->active&&session.pending_abilities()==0,"Atomic owner prediction is published only after prepared motor correction");
    CharacterSceneInput released;released.combat_events={{8,InputEdge::Released,2000,0,0,false},{8,InputEdge::Tapped,2000,0,1,false}};session.step(released);while(session.motor().tick<30)session.step({});auto remote=session.observer(player.id,28);check(remote.frame.ability.active&&remote.action_clock==27*action_tick_units,"Royal observer buffers current action phase on the motor render clock");auto public_target=session.observer(target.id,30);check(public_target.frame.ability.attributes.size()==2,"Royal public schema preserves owner-only Stamina/Essence privacy");while(session.motor().tick<60)session.step({});auto health=[&]{return session.presentation().read(session.presentation().find(target.id)).health.current;};check(health()==75,"Authoritative hit replicates target Health through existing baseline");check(session.pending_prediction()==0&&!session.ability()->active,"Motor correction and action completion retire execution");
    auto stamina=[&]{for(const auto& attribute:session.ability()->attributes)if(attribute.id==3)return attribute.value;return -1.;};check(stamina()==90,"Tap/release cannot duplicate the Pressed cost");
    for(unsigned attack=2;attack<=4;++attack){session.step(pressed);session.step(released);while(session.motor().tick<60*attack)session.step({});check(stamina()==100-10*attack,"Repeated serialized operations charge once per activation");check(health()==100-25*attack,"One damage outcome per action/target despite persistent hit window");}
    check(health()==0&&authoring.serialize()==original,"Death baseline and gameplay isolation preserve authoring");session.step(pressed);session.step(released);while(session.motor().tick<300)session.step({});check(health()==0&&stamina()==50,"Dead target never receives repeated damage");
    std::cout<<"Cooked Royal combat: serialized intent, action/root/pose, Jolt target damage/Health, exact owner correction and authoring isolation passed\n";return 0;
}catch(const std::exception& error){std::cerr<<error.what()<<'\n';return 1;}}
