#include <darkangel/character_motor.hpp>
#include <darkangel/collision_asset.hpp>
#include <darkangel/world_session.hpp>
#include <fstream>
#include <iostream>
#include <cmath>
#include <deque>
#include <algorithm>
#include <bit>
using namespace darkangel;
namespace {
void require(bool b,const char* message){if(!b)throw std::runtime_error(message);}
std::uint64_t field(std::span<const std::byte> bytes,unsigned offset){std::uint64_t n{};for(unsigned i=0;i<8;++i)n|=std::uint64_t(std::to_integer<unsigned>(bytes[offset+i]))<<(8*i);return n;}
class FaultStream:public Transport {
    Transport& inner;std::deque<TransportMessage> pending;
public:bool drop{},drop_always{};unsigned dropped{},duplicates{},packets{};std::size_t maximum_bytes{};
    explicit FaultStream(Transport& value):inner(value){}
    ConnectionHandle open(const SessionHandshake& h)override{return inner.open(h);}bool connected()const override{return inner.connected();}bool valid(ConnectionHandle h)const override{return inner.valid(h);}TransportLimits limits()const override{return inner.limits();}bool send(ConnectionHandle h,Delivery d,std::span<const std::byte> b)override{return inner.send(h,d,b);}void disconnect(ConnectionHandle h)override{inner.disconnect(h);pending.clear();}
    std::vector<TransportMessage> poll(std::size_t limit)override{auto incoming=inner.poll(limit);std::reverse(incoming.begin(),incoming.end());for(auto& message:incoming){if(message.bytes.size()>=72&&field(message.bytes,8)==9){++packets;maximum_bytes=std::max(maximum_bytes,message.bytes.size());if((drop||drop_always)&&field(message.bytes,64)==0){drop=false;++dropped;continue;}require(pending.size()<128,"Fault queue bound");pending.push_back(message);++duplicates;}pending.push_back(std::move(message));}std::vector<TransportMessage> out;while(!pending.empty()&&out.size()<limit){out.push_back(std::move(pending.front()));pending.pop_front();}return out;}
};
}
int main(){try{
    SessionHandshake hello{3,std::string(64,'a'),std::string(64,'b'),603};auto pair=create_loopback(hello);FaultStream receiver(*pair.client);auto hp=pair.host->open(hello),cp=receiver.open(hello);WorldSession server(SessionRole::Server,hello),client(SessionRole::Client,hello);server.attach(*pair.host,hp);client.attach(receiver,cp);ObjectData object;object.id={6,1};auto owner=server.create(object);object.id={6,2};auto peer=server.create(object);server.own_motor(owner,hp);
    std::ifstream input(std::string(DAE_SOURCE_DIR)+"/content/physics/m4_cave.dacollision");std::string native{std::istreambuf_iterator<char>(input),{}};auto scene=decode_collision_source(native);PhysicsWorld physics;physics.load_scene(scene);physics.add({3,{4,.5,0},{.4,.5,.4},{},{},0,0,false,true,50});CharacterMotor local(physics,{-3,0,0},owner),remote(physics,{2,0,0},peer);server.publish_motor(owner,local.state());server.publish_motor(peer,remote.state());server.publish_collision(collision_stream(physics.capture()));auto prepared=physics.capture().meshes;
    for(unsigned n=0;n<20;++n){server.tick();client.tick();}require(client.readiness(cp)==SessionReadiness::Ready&&!client.collisions().empty(),"Collision state arrives after atomic WorldSession Ready");MotorState baseline;std::vector<MotorInput> commands;
    require(!client.collision_control_ready()&&!client.submit_motor(owner,{1,1,1,1}),"Avatar control waits for native-prepared collision state");std::vector<std::byte> premature;auto put=[&](std::uint64_t n){for(unsigned byte=0;byte<8;++byte)premature.push_back(static_cast<std::byte>((n>>(8*byte))&255));};for(auto n:{0x3253454144ULL,7ULL,603ULL,0ULL,1ULL,0ULL,0ULL,1ULL,1ULL,1ULL})put(n);for(double n:{1.0,0.0,0.0})put(std::bit_cast<std::uint64_t>(n));put(0);put(0);require(receiver.send(cp,Delivery::ReliableOrdered,premature),"Raw premature command injection");server.tick();require(!server.motor_input_ready(owner,1),"Server also rejects control before native-prepared collision ACK");
    prepare_collision_frame(client.collisions().back(),prepared);client.acknowledge_collision(0);client.tick();server.tick();require(client.collision_control_ready()&&server.collision_diagnostics(hp).ack_topology==physics.topology(),"Prepared initial collision topology enables control");
    for(unsigned n=1;n<=40;++n){MotorInput command{n,n,1,1};require(client.submit_motor(owner,command),"Prepared loopback command submit");server.tick();auto accepted=server.consume_motor(owner,n,1);require(accepted.sequence==n&&accepted.x==1,"Prepared native control command consumed once");local.step(accepted);remote.step({n,n,1,-.1});physics.step();local.post_physics();remote.post_physics();server.publish_motor(owner,local.state());server.publish_motor(peer,remote.state());server.publish_collision(collision_stream(physics.capture()));server.tick();client.tick();if(n==10)baseline=local.state();if(n>10)commands.push_back(command);}
    require(client.collisions().size()==31&&client.collisions().front().tick==10&&client.collisions().back().tick==40,"Bounded atomic collision history");CollisionHistory history;for(const auto& frame:client.collisions())history.retain(prepare_collision_frame(frame,prepared));auto before=physics.capture();MotorState corrected;require(replay_motor(baseline,commands,history,corrected,owner)==ReplayResult::Applied&&std::abs(corrected.position.x-local.state().position.x)<.02,"Owner replay consumes network-fed actor/prop/mesh history");require(physics.capture().tick==before.tick&&physics.capture().actors[0].foot==before.actors[0].foot&&physics.capture().boxes[0].center==before.boxes[0].center,"Network correction never rewinds live physics");
    PhysicsWorld predicted(PhysicsWorld::Mode::Prediction);predicted.load(*history.find(10),owner);CharacterMotor predicted_motor(predicted,baseline.position,owner,baseline.crouched);predicted.load(*history.find(10),owner);predicted_motor.restore(baseline);OwnerPrediction prediction(predicted,predicted_motor);
    for(const auto& command:commands){require(predicted.update_prediction(*history.find(command.tick-1),predicted_motor),"Start-tick authoritative proxies applied");prediction.predict(command);predicted.step();predicted_motor.post_physics();require(predicted.update_prediction(*history.find(command.tick),predicted_motor),"Completed-tick authoritative proxies applied");predicted_motor.post_physics();}
    require(prediction.reconcile(baseline,history)==ReplayResult::Applied&&prediction.pending()==30&&std::abs(predicted_motor.state().position.x-local.state().position.x)<.02,"Owner helper reconciles from authoritative network collision history");
    CollisionHistory missing;require(prediction.reconcile(baseline,missing)==ReplayResult::MissingHistory&&prediction.needs_resync(),"Incomplete authoritative history forces bounded owner resynchronization");auto stale=*history.find(39);auto current_pose=predicted_motor.state().position;require(!predicted.update_prediction(stale,predicted_motor)&&predicted.needs_resync()&&predicted.tick()==40&&predicted_motor.state().position==current_pose,"Prediction proxy update cannot rewind live tick");
    client.acknowledge_collision(40);client.tick();server.tick();require(server.collision_diagnostics(hp).has_ack&&server.collision_diagnostics(hp).ack_tick==40,"Native-prepared complete collision frame acknowledged by application");
    auto invalid=client.collisions().back();invalid.meshes[0].signature=std::string(64,'f');bool rejected=false;try{prepare_collision_frame(invalid,prepared);}catch(...){rejected=true;}require(rejected&&physics.capture().topology==before.topology,"Unprepared geometry generation requires resynchronization before mutation");rejected=false;try{client.publish_collision(client.collisions().back());}catch(...){rejected=true;}require(rejected,"Client collision authority denied");
    // A maximum-inventory frame spans the shared packet budget. Lose one chunk,
    // reorder and duplicate the others; no prefix may become collision history.
    auto large=client.collisions().back();large.tick=70;large.topology++;large.meshes.clear();large.boxes.clear();for(unsigned n=1;n<=64;++n)large.boxes.push_back({n,{double(n)*3,-.5,0},{1,.5,1}});receiver.drop=true;server.publish_collision(large);for(unsigned n=0;n<8;++n){server.tick();client.tick();}require(receiver.dropped==1&&client.collisions().back().tick==40,"Lost collision chunk cannot publish a partial frame");large.tick=71;server.publish_collision(large);for(unsigned n=0;n<8;++n){server.tick();client.tick();}require(!client.collision_control_ready(),"New unprepared collision topology blocks avatar control");require(client.collisions().back().tick==71&&client.collisions().back().boxes.size()==64&&receiver.duplicates>0&&receiver.maximum_bytes<=1000,"New complete collision frame recovers with reordered duplicates within packet bound");
    large.tick=72;receiver.drop_always=true;server.publish_collision(large);for(unsigned n=0;n<40;++n){server.tick();client.tick();}require(client.collisions().back().tick==71&&client.collision_diagnostics(cp).expired>0&&client.collision_diagnostics(cp).needs_resync,"Partial collision frame expires and signals resynchronization");rejected=false;try{client.acknowledge_collision(72);}catch(...){rejected=true;}require(rejected&&server.collision_diagnostics(hp).ack_tick==40,"Incomplete collision frame cannot be acknowledged");receiver.drop_always=false;large.tick=73;server.publish_collision(large);for(unsigned n=0;n<8;++n){server.tick();client.tick();}prepare_collision_frame(client.collisions().back(),{});client.acknowledge_collision(73);client.tick();server.tick();require(client.collision_control_ready()&&!client.collision_diagnostics(cp).needs_resync&&server.collision_diagnostics(hp).ack_tick==73&&server.collision_diagnostics(hp).sent_bytes>0,"Fresh prepared frame clears collision resync and ACKs current state");
    // A newly attached peer receives current collision state without old commands.
    auto late=create_loopback(hello);auto lp=late.host->open(hello),lc=late.client->open(hello);server.attach(*late.host,lp);WorldSession joined(SessionRole::Client,hello);joined.attach(*late.client,lc);for(unsigned n=0;n<30;++n){server.tick();joined.tick();client.tick();}require(joined.readiness(lc)==SessionReadiness::Ready&&!joined.collisions().empty()&&joined.collisions().back().tick==73&&joined.collisions().back().boxes.size()==64,"Late join restores current collision frame");
    std::cout<<"WorldSession atomic collision frames, network-fed isolated replay, loss/reorder/duplicate bounds and late join passed; max_packet_bytes="<<receiver.maximum_bytes<<" dropped="<<receiver.dropped<<'\n';return 0;
}catch(const std::exception& e){std::cerr<<e.what()<<'\n';return 1;}}
