#include <darkangel/collision_asset.hpp>
#include <cmath>
#include <iostream>
using namespace darkangel;
void require(bool b,const char* s){if(!b)throw std::runtime_error(s);}
int main(){try{
    CollisionStreamFrame a;a.tick=10;a.topology=1;CollisionBox box{2,{0,1,0},{1,1,1}};box.dynamic=true;box.rotation={0,0,0,1};a.boxes.push_back(box);a.actors.push_back({1,1,{0,0,0},{},3.124139361});a.meshes.push_back({7,AssetId::parse("c3f81392-186e-4f11-b716-2adfc6706c1e"),std::string(64,'a')});auto b=a;b.tick=20;b.boxes[0].center.x=10;b.boxes[0].rotation={0,1,0,0};b.actors[0].foot.x=4;b.actors[0].yaw=-3.124139361;b.actors[0].crouched=true;
    ObserverCollision first,second;first.push(a);first.push(b);second.push(a);auto middle=first.sample(15);require(middle.tick==15&&!middle.held&&middle.poses.size()==3,"Interpolated timestamped presentation frame");require(std::abs(middle.poses[0].position.x-5)<1e-9&&std::abs(middle.poses[0].rotation[1]-std::sqrt(.5))<1e-9&&std::abs(middle.poses[0].rotation[3]-std::sqrt(.5))<1e-9,"Dynamic prop position and shortest quaternion slerp");require(std::abs(middle.poses[2].position.x-2)<1e-9&&std::abs(middle.poses[2].rotation[1]-1)<.00001&&std::abs(middle.poses[2].rotation[3])<.00001,"Character shortest yaw wrap");require(second.sample(15).held&&second.sample(15).poses[0].position.x==0,"Independent observer buffers and underrun hold");require(first.sample(100).held&&first.sample(100).poses[0].position.x==10&&first.sample(0).poses[0].position.x==0,"No extrapolation before/after available history");first.push(a);require(first.size()==2,"Stale packet cannot reset observer");
    require(!middle.poses[2].crouched&&first.sample(20).poses[2].crouched,"Discrete stance changes at authoritative sample boundary");
    auto teleported=b;teleported.tick=21;teleported.actors[0].epoch=2;teleported.actors[0].foot.x=100;first.push(teleported);require(first.size()==1&&first.sample(20.5).poses[2].position.x==100,"Teleport epoch resets interpolation");auto streamed=teleported;streamed.tick=22;streamed.topology=2;streamed.boxes[0].center.x=100;first.push(streamed);require(first.size()==1&&first.sample(21.5).poses[0].position.x==100,"Streamed topology resets interpolation");auto geometry=streamed;geometry.tick=23;geometry.meshes[0].signature=std::string(64,'f');first.push(geometry);require(first.size()==1,"Unchanged topology with different geometry cannot interpolate");for(unsigned n=24;n<40;++n){geometry.tick=n;first.push(geometry);}require(first.size()==8,"Bounded observer history");bool denied=false;try{first.sample(NAN);}catch(...){denied=true;}require(denied,"Invalid presentation clock rejects");
    std::cout<<"SDK-free character/prop presentation interpolation, shortest quaternion/yaw, hold, epoch/topology/geometry resets and independent bounded buffers passed\n";return 0;
}catch(const std::exception& e){std::cerr<<e.what()<<'\n';return 1;}}
