#include <darkangel/combat_kit_assets.hpp>
#include <darkangel/assets.hpp>
#include <darkangel/world_session.hpp>
#include <nlohmann/json.hpp>
#include <fstream>
#include <iostream>
using namespace darkangel;
using Json=nlohmann::json;
namespace {
void check(bool b,const char* message){if(!b)throw std::runtime_error(message);}
template<class F>void rejects(F f){bool denied=false;try{f();}catch(const std::exception&){denied=true;}check(denied,"Expected CombatKit rejection");}
Json read(const std::filesystem::path& path){std::ifstream file(path);return Json::parse(file);}
void write(const std::filesystem::path& path,const Json& value){std::ofstream(path)<<value.dump(2);}
}
int main(){try{
    auto root=std::filesystem::path(DAE_BINARY_DIR)/("combat-kit-assets-"+AssetId::random().text()),sources=root/"sources";std::filesystem::create_directories(sources/"animation");auto content=std::filesystem::path(DAE_SOURCE_DIR)/"content";
    std::filesystem::copy_file(content/"animation/canonical_human.daskeleton",sources/"animation/canonical_human.daskeleton");std::filesystem::copy_file(content/"royal_district/clips/idle.glb",sources/"idle.glb");auto metadata=read(content/"royal_district/clips/idle.glb.daimport");write(sources/"idle.glb.daimport",metadata);
    auto input=read(content/"input/royal_player.dainput");write(sources/"player.dainput",input);auto action=read(content/"animation/m5_attack.daaction");action["schema"]=2;action["duration"]=52*action_tick_units;action["loops"]=1;action["motion"]={{"clip","260f716a-1883-42bc-8ea7-29d53913b79d"},{"source","attack.glb"},{"policy","motor"}};write(sources/"attack.daaction",action);std::filesystem::copy_file(content/"royal_district/clips/attack.glb",sources/"attack.glb");write(sources/"attack.glb.daimport",read(content/"royal_district/clips/attack.glb.daimport"));auto kit_id=AssetId::random(),graph_id=AssetId::random(),schema_id=AssetId::random(),ability_id=AssetId::random();
    Json graph={{"schema",1},{"kind","graph"},{"asset",graph_id.text()},{"root",1},{"nodes",Json::array({{{"id",1},{"kind","clip"},{"clip",metadata.at("id")}}})},{"sources",{{metadata.at("id").get<std::string>(),"idle.glb"}}}};write(sources/"idle.dagraph",graph);
    Json schema={{"schema",1},{"kind","attributes"},{"asset",schema_id.text()},{"attributes",Json::array()}};
    auto field=[&](unsigned id,const char* name,const char* kind,double base,double maximum,unsigned maximum_attribute){schema["attributes"].push_back({{"id",id},{"name",name},{"kind",kind},{"base",base},{"minimum",0.0},{"maximum",maximum},{"maximum_attribute",maximum_attribute},{"unit","points"},{"visibility","owner"}});};field(1,"MaxHealth","statistic",100,1000,0);field(2,"Health","resource",100,1000,1);field(3,"Stamina","resource",60,60,0);write(sources/"base.daattributes",schema);
    Json ability={{"schema",1},{"kind","ability"},{"asset",ability_id.text()},{"action",action.at("asset")},{"attributes",schema_id.text()},{"sources",{{"action","attack.daaction"},{"attributes","base.daattributes"}}},{"costs",Json::array({{{"attribute",3},{"amount",20.0}}})},{"cooldown_group",1},{"cooldown_ticks",6},{"activate_on","pressed"},{"minimum_held_us",0},{"cancel_on_release",false},{"interruptible",true}};write(sources/"light.daability",ability);
    Json kit={{"schema",1},{"kind","combat_kit"},{"asset",kit_id.text()},{"input",input.at("asset")},{"attributes",schema_id.text()},{"locomotion_stance",graph_id.text()},{"slots",Json::array()},{"sources",{{"input","player.dainput"},{"attributes","base.daattributes"},{"locomotion_stance","idle.dagraph"},{"abilities",{{ability_id.text(),"light.daability"}}}}}};
    const char* names[]={"light","heavy","ranged_light","ranged_heavy","spell1","spell2","block","parry"};unsigned actions[]={8,9,14,15,12,13,10,11};for(unsigned i=0;i<combat_slot_count;++i)kit["slots"].push_back({{"slot",names[i]},{"input_action",actions[i]},{"ability",i==0?Json(ability_id.text()):Json(nullptr)}});write(sources/"player.dakit",kit);CookedCombatKit pinned,empty;std::string generation;
    {
        AssetService service(sources,root/"cache");check(service.adopt("player.dakit")==kit_id,"Embedded kit identity");service.cook("player.dakit");auto converted=service.conversion_count();check(!service.cook("player.dakit").changed&&service.conversion_count()==converted,"Warm kit skips nested conversion");service.package(kit_id,root/"registry.json");check(read(root/"registry.json").at("assets").size()==12,"Kit closure deduplicates schema and rig");pinned=load_cooked_combat_kit(root/"registry.json",service.cas_path(),kit_id);generation=pinned.definition->generation;check(pinned.abilities.size()==1&&pinned.definition->slots[1].ability==AssetId{}&&pinned.stance.id==pinned.definition->locomotion_stance,"Optional grants and real frozen stance");check(pinned.abilities[0]->action->motion.has_value(),"Kit freezes the action clip binding through the ability closure");
        auto invalid=kit;invalid["slots"][1]["slot"]="light";write(sources/"player.dakit",invalid);rejects([&]{service.cook("player.dakit");});invalid=kit;invalid["slots"][1]["input_action"]=8;write(sources/"player.dakit",invalid);rejects([&]{service.cook("player.dakit");});invalid=kit;invalid["slots"][0]["input_action"]=1;write(sources/"player.dakit",invalid);rejects([&]{service.cook("player.dakit");});invalid=kit;invalid["sources"]["locomotion_stance"]="../idle.dagraph";write(sources/"player.dakit",invalid);rejects([&]{service.cook("player.dakit");});write(sources/"player.dakit",kit);
        auto bad_ability=ability;bad_ability["attributes"]=AssetId::random().text();write(sources/"light.daability",bad_ability);rejects([&]{service.cook("player.dakit");});write(sources/"light.daability",ability);service.package(kit_id,root/"after-failure.json");check(load_cooked_combat_kit(root/"after-failure.json",service.cas_path(),kit_id).definition->generation==generation,"Invalid closure preserves previous kit head");
        auto changed=ability;changed["costs"][0]["amount"]=10;write(sources/"light.daability",changed);check(service.cook("player.dakit").changed,"Nested ability change invalidates kit");service.package(kit_id,root/"changed.json");check(load_cooked_combat_kit(root/"changed.json",service.cas_path(),kit_id).definition->generation!=generation&&pinned.definition->generation==generation,"Leased kit generation remains frozen");
        auto mixed=read(root/"registry.json"),new_manifest=read(root/"changed.json");for(auto& record:mixed["assets"])if(record["id"]==ability_id.text())for(const auto& replacement:new_manifest["assets"])if(replacement["id"]==record["id"])record=replacement;write(root/"bad.json",mixed);rejects([&]{load_cooked_combat_kit(root/"bad.json",service.cas_path(),kit_id);});
        auto unassigned=kit;unassigned["slots"][0]["ability"]=nullptr;unassigned["sources"]["abilities"]=Json::object();write(sources/"player.dakit",unassigned);service.cook("player.dakit");service.package(kit_id,root/"empty.json");empty=load_cooked_combat_kit(root/"empty.json",service.cas_path(),kit_id);check(empty.abilities.empty(),"All slots may be unassigned");write(sources/"player.dakit",kit);write(sources/"light.daability",ability);service.cook("player.dakit");
        std::filesystem::rename(sources,root/"offline-sources");check(load_cooked_combat_kit(root/"registry.json",service.cas_path(),kit_id).definition->generation==generation,"Kit loads without source mount/catalog");std::filesystem::rename(root/"offline-sources",sources);
    }
    {AssetService fresh(sources,root/"fresh");fresh.cook("player.dakit");fresh.package(kit_id,root/"fresh.json");check(load_cooked_combat_kit(root/"fresh.json",fresh.cas_path(),kit_id).definition->generation==generation,"Fresh cache reproduces kit generation");}
    WorldSession server(SessionRole::Server,{3,std::string(64,'a'),std::string(64,'b'),77});ObjectData object;object.id={4,1};auto network=server.create(object);auto owner=server.configure_abilities(network,pinned.attributes.definitions(),2,1);server.equip_combat_kit(owner,pinned.definition,pinned.input,pinned.abilities);auto grant=server.ability_snapshot(owner).grant_generation;
    AbilityRequest request{owner,1,grant,CombatSlot::Light,{8,InputEdge::Pressed,1000,0,1,false},false};check(server.request_ability(request).committed,"Cooked kit commits through existing native authority");check(server.ability_snapshot(owner).attributes[2].value==40,"Frozen ability charges once");server.equip_combat_kit(owner,empty.definition,empty.input,empty.abilities);auto swapped=server.ability_snapshot(owner);check(!swapped.active&&swapped.attributes[2].value==40&&swapped.grant_generation!=grant,"Runtime swap cancels old active grant without refund");request.operation=2;check(server.request_ability(request).failure==AbilityFailure::StaleGrant,"Old input grant rejected after swap");request.operation=3;request.grant_generation=swapped.grant_generation;check(server.request_ability(request).failure==AbilityFailure::Unassigned,"Unassigned swapped slot rejects execution");AnimationGraphInstance stance(empty.stance.plan);check(stance.advance(1,{}).count==1,"Swapped stance uses the compiled native graph");
    auto tags_id=AssetId::random();Json tags={{"schema",1},{"kind","tags"},{"asset",tags_id.text()},{"tags",Json::array({{{"key",AssetId::random().text()},{"id",2},{"parent",0},{"name","State.Blocked"},{"visibility","public"}}})}};write(sources/"state.datags",tags);auto tagged=ability;tagged["tags"]=tags_id.text();tagged["requirements"]={{"all",Json::array()},{"any",Json::array()},{"none",{2}}};tagged["sources"]["tags"]="state.datags";write(sources/"light.daability",tagged);CookedCombatKit tagged_kit;
    {AssetService service(sources,root/"tagged-cache");service.cook("player.dakit");service.package(kit_id,root/"tagged.json");tagged_kit=load_cooked_combat_kit(root/"tagged.json",service.cas_path(),kit_id);check(tagged_kit.tags&&tagged_kit.tags->id==tags_id&&tagged_kit.abilities[0]->tag_registry==tags_id&&tagged_kit.definition->generation!=generation,"CombatKit includes one frozen tag registry through assigned abilities");std::filesystem::rename(sources,root/"tagged-offline");check(load_cooked_combat_kit(root/"tagged.json",service.cas_path(),kit_id).tags->generation==tagged_kit.tags->generation,"Tagged kit prepares without source/catalog");std::filesystem::rename(root/"tagged-offline",sources);}
    auto effect_id=AssetId::random();auto effect=read(content/"royal_district/combat/burn.daeffect");effect["asset"]=effect_id.text();effect["attributes"]=schema_id.text();effect["tags"]=tags_id.text();effect["granted_tags"]={2};effect["sources"]={{"attributes","base.daattributes"},{"tags","state.datags"}};write(sources/"burn.daeffect",effect);auto effect_kit=kit;effect_kit["effects"]={effect_id.text()};effect_kit["sources"]["effects"]={{effect_id.text(),"burn.daeffect"}};auto block=std::find_if(action.at("blocks").begin(),action.at("blocks").end(),[](const auto& value){return value.at("kind")=="hit";});check(block!=action.at("blocks").end(),"Fixture has a real hit block");auto bound_ability=tagged;bound_ability["melee"]=Json::array({{{"block",block->at("id")},{"offset",{0,.6,.8}},{"radius",.5},{"power",10},{"evaluator",1},{"damage_type",1}}});write(sources/"light.daability",bound_ability);effect_kit["effect_bindings"]=Json::array({{{"ability",ability_id.text()},{"hit_block",block->at("id")},{"effect",effect_id.text()},{"power",7}}});write(sources/"player.dakit",effect_kit);
    {AssetService service(sources,root/"effects-cache");service.cook("player.dakit");service.package(kit_id,root/"effects.json");auto frozen=load_cooked_combat_kit(root/"effects.json",service.cas_path(),kit_id);check(frozen.definition->effect_bindings.size()==1&&frozen.definition->effect_bindings[0].power==7&&frozen.effects.size()==1&&frozen.definition->effects.size()==1&&frozen.effects[0]->duration_ticks==180&&frozen.tags->id==tags_id,"Kit pins effect catalogue and shared actor schema/tags");
     auto invalid=effect_kit;invalid["effect_bindings"][0]["hit_block"]=999;write(sources/"player.dakit",invalid);rejects([&]{service.cook("player.dakit");});invalid=effect_kit;invalid["effect_bindings"][0]["effect"]=AssetId::random().text();write(sources/"player.dakit",invalid);rejects([&]{service.cook("player.dakit");});invalid=effect_kit;invalid["effect_bindings"].push_back(invalid["effect_bindings"][0]);write(sources/"player.dakit",invalid);rejects([&]{service.cook("player.dakit");});invalid=effect_kit;invalid["effects"].push_back(effect_id.text());write(sources/"player.dakit",invalid);rejects([&]{service.cook("player.dakit");});invalid=effect_kit;invalid["sources"].erase("effects");write(sources/"player.dakit",invalid);rejects([&]{service.cook("player.dakit");});write(sources/"player.dakit",effect_kit);auto invalid_effect=effect;invalid_effect["attributes"]=AssetId::random().text();write(sources/"burn.daeffect",invalid_effect);rejects([&]{service.cook("player.dakit");});write(sources/"burn.daeffect",effect);service.package(kit_id,root/"effect-failure.json");check(load_cooked_combat_kit(root/"effect-failure.json",service.cas_path(),kit_id).definition->generation==frozen.definition->generation,"Invalid effect closure preserves published kit");
     effect["duration_ticks"]=120;write(sources/"burn.daeffect",effect);service.cook("player.dakit");service.package(kit_id,root/"effects-changed.json");auto changed=load_cooked_combat_kit(root/"effects-changed.json",service.cas_path(),kit_id);check(changed.definition->generation!=frozen.definition->generation&&changed.effects[0]->duration_ticks==120&&frozen.effects[0]->duration_ticks==180,"Effect changes invalidate kit while previous lease stays frozen");auto mixed=read(root/"effects.json"),latest=read(root/"effects-changed.json");for(auto& record:mixed["assets"])if(record["id"]==effect_id.text())for(const auto& replacement:latest["assets"])if(replacement["id"]==record["id"])record=replacement;write(root/"effects-mixed.json",mixed);rejects([&]{load_cooked_combat_kit(root/"effects-mixed.json",service.cas_path(),kit_id);});std::filesystem::rename(sources,root/"effects-offline");check(load_cooked_combat_kit(root/"effects.json",service.cas_path(),kit_id).effects[0]->duration_ticks==180,"Effect catalogue loads from registry/CAS without source files");std::filesystem::rename(root/"effects-offline",sources);}
    std::cout<<"Frozen optional-slot CombatKit, source-free stance/grants/tags, atomic cook and native runtime replacement passed\n";return 0;
}catch(const std::exception& error){std::cerr<<error.what()<<'\n';return 1;}}
