#include <darkangel/gns_transport.hpp>
#include <darkangel/world_session.hpp>
#include <chrono>
#include <thread>
#include <iostream>
using namespace darkangel;
namespace {
void check(bool value,const char* message){if(!value)throw std::runtime_error(message);}
std::vector<AttributeDefinition> attributes(){return {{1,"MaxHealth",AttributeKind::Statistic,100,0,1000,0,AttributeVisibility::Public},{2,"Health",AttributeKind::Resource,100,0,1000,1,AttributeVisibility::Public},{3,"Stamina",AttributeKind::Resource,60,0,60,0,AttributeVisibility::Owner}};}
std::shared_ptr<const TagDictionary> tags(){return std::make_shared<const TagDictionary>(std::vector<TagDefinition>{{1,0,"Status.Burn",AttributeVisibility::Public}},AssetId::parse("64e42f1a-b4de-4515-b2e4-ab901aa75001"),std::string(64,'a'));}
std::uint64_t activate_source(WorldSession& session,AbilityOwnerHandle owner){InputProfile input;input.id=AssetId::random();auto kit=std::make_shared<CombatKitDefinition>();kit->id=AssetId::random();kit->generation="kit";kit->locomotion_stance=AssetId::random();for(unsigned i=0;i<combat_slot_count;++i){input.actions.push_back({i+1,"combat."+std::to_string(i),InputActionKind::Button});kit->slots[i]={static_cast<CombatSlot>(i),i+1,{}};}auto action=std::make_shared<ActionDefinition>();action->id=AssetId::random();action->generation=std::string(64,'e');action->duration=60*action_tick_units;action->loops=1;auto ability=std::make_shared<AbilityDefinition>();ability->id=AssetId::random();ability->generation=std::string(64,'f');ability->action=action;kit->slots[0].ability=ability->id;std::array<std::shared_ptr<const AbilityDefinition>,1> granted{ability};session.equip_combat_kit(owner,kit,input,granted);auto receipt=session.request_ability({owner,1,session.ability_snapshot(owner).grant_generation,CombatSlot::Light,{1,InputEdge::Pressed,1000,0,1,false},false});check(receipt.committed,"Native source activation prepares real attribution");return receipt.handle.activation;}
std::vector<std::shared_ptr<const EffectDefinition>> definitions(){
 auto burn=std::make_shared<EffectDefinition>();burn->id=AssetId::parse("64e42f1a-b4de-4515-b2e4-ab901aa75002");burn->generation=std::string(64,'b');burn->duration_ticks=90;burn->period_ticks=30;burn->evaluator=1;burn->tags={1};burn->visibility=AttributeVisibility::Public;burn->cues={{AssetId::parse("64e42f1a-b4de-4515-b2e4-ab901aa75003"),"Status.Burn"}};
 auto hidden=std::make_shared<EffectDefinition>();hidden->id=AssetId::parse("64e42f1a-b4de-4515-b2e4-ab901aa75004");hidden->generation=std::string(64,'c');hidden->lifetime=EffectLifetime::UntilRemoved;hidden->visibility=AttributeVisibility::Owner;
 auto secret=std::make_shared<EffectDefinition>(*hidden);secret->id=AssetId::parse("64e42f1a-b4de-4515-b2e4-ab901aa75005");secret->generation=std::string(64,'d');secret->visibility=AttributeVisibility::Server;return {burn,hidden,secret};
}
}
int main(int argc,char** argv){try{
 check(argc==2,"Use --host or --client");bool host=std::string_view(argv[1])=="--host";check(host||std::string_view(argv[1])=="--client","Unknown GNS role");SessionHandshake hello{3,std::string(64,'a'),std::string(64,'b'),1337};auto transport=host?create_gns_host("127.0.0.1:27151",hello):create_gns_client("127.0.0.1:27151",hello);auto peer=transport->open(hello);WorldSession session(host?SessionRole::Server:SessionRole::Client,hello);auto catalogue=definitions();AbilityOwnerHandle target;
 // Prepare an already-running authority before the joining GNS connection.
 if(host){ObjectData caster;caster.id={88,1};auto source=session.create(caster);ObjectData victim;victim.id={88,2};auto network=session.create(victim);auto credit=session.configure_abilities(source,attributes(),2,1);target=session.configure_abilities(network,attributes(),2,1);session.configure_ability_tags(credit,tags());session.configure_ability_tags(target,tags());session.register_effect_evaluator(1,[](const EffectContext& context){return std::vector<ResourceDelta>{{2,-context.credit.power}};});session.advance_abilities(1);auto activation=activate_source(session,credit);session.apply_effect(target,credit,*catalogue[0],3,activation);for(unsigned i=0;i<62;++i)session.apply_effect(target,credit,*catalogue[1],3,activation);session.apply_effect(target,credit,*catalogue[2],3,activation);for(unsigned tick=2;tick<=40;++tick)session.advance_abilities(tick);session.drain_effect_outcomes();session.destroy(source);check(session.objects().at(network).health.current==97,"Warm Burn executed once before join");}
 auto connect=std::chrono::steady_clock::now()+std::chrono::seconds(10);while(!transport->connected()&&std::chrono::steady_clock::now()<connect)std::this_thread::sleep_for(std::chrono::milliseconds(2));check(transport->connected(),"GNS effect connect deadline");session.attach(*transport,peer);if(host){session.own_motor(2,peer);for(unsigned tick=1;tick<=40;++tick)session.consume_motor(2,tick,1);MotorState state;state.tick=40;state.sequence=40;session.publish_motor(2,state);}
 EffectPresentation owner(AttributeVisibility::Owner,AttributeSet(attributes()),tags(),catalogue),observer(AttributeVisibility::Public,AttributeSet(attributes()),tags(),catalogue);bool joined=false;unsigned begins{},ends{};std::uint64_t executed=40,submitted=40;auto deadline=std::chrono::steady_clock::now()+std::chrono::seconds(20);
 while(std::chrono::steady_clock::now()<deadline){session.tick();if(session.readiness(peer)==SessionReadiness::Ready){
  if(!host){auto push=[&](AttributeVisibility audience,EffectPresentation& view){auto found=session.effect_frames(audience).find(2);if(found!=session.effect_frames(audience).end())view.push(found->second);};push(AttributeVisibility::Owner,owner);push(AttributeVisibility::Public,observer);for(const auto& cue:observer.drain_cues()){begins+=cue.edge==EffectCueEdge::Begin;ends+=cue.edge==EffectCueEdge::End;}owner.drain_cues();
   if(!joined&&owner.current()&&observer.current()&&owner.current()->effects.size()==63&&observer.current()->effects.size()==1&&session.ability_corrections().contains(2)&&session.ability_corrections().at(2).motor.tick==40){const auto& burn=observer.current()->effects.front();check(burn.start==1&&burn.end==91&&burn.next_period==61&&burn.credit.source_network==1&&burn.credit.activation==1&&burn.credit.session_epoch==hello.session_epoch&&!session.objects().contains(1),"GNS late join retains current timers and destroyed source credit");check(session.objects().at(2).health.current==97&&observer.cues().size()==1&&begins==1,"Late preparation never replays old periodic damage/cues");joined=true;}
   if(joined&&session.motors().contains(2)&&session.motors().at(2).tick==submitted&&submitted<91){auto next=++submitted;check(session.submit_motor(2,{next,next,session.motors().at(2).epoch}),"GNS effect next native tick input");}
   if(joined&&submitted==91&&session.motors().at(2).tick==91&&owner.current()&&observer.current()&&owner.current()->effects.size()==62&&observer.current()->effects.empty()){check(session.objects().at(2).health.current==94&&observer.cues().empty()&&begins==1&&ends==1,"GNS period61 and end-exclusive expiry preserve Health/cue privacy");check(session.submit_motor(2,{92,92,session.motors().at(2).epoch}),"GNS final effect delivery fence");std::cout<<"GNS effect client: dense owner63/public1 late join, durable credit, no past execution, Health97->94 and one cue lifetime passed\n";std::this_thread::sleep_for(std::chrono::milliseconds(300));return 0;}
  }
  if(host&&executed<91&&session.motor_input_ready(2,executed+1)){auto tick=++executed;session.consume_motor(2,tick,1);session.advance_abilities(tick);session.drain_effect_outcomes();auto state=session.motors().at(2);state.tick=tick;state.sequence=tick;session.publish_motor(2,state);}
  if(host&&executed==91&&session.motor_input_ready(2,92)){check(session.objects().at(2).health.current==94&&session.ability_effects(target).size()==63,"GNS native status authority remains exact");std::cout<<"GNS effect host: captured Burn survives source destruction, one later period, expiry and audience snapshots passed\n";std::this_thread::sleep_for(std::chrono::milliseconds(300));return 0;}
 }std::this_thread::sleep_for(std::chrono::milliseconds(host?5:2));}throw std::runtime_error("GNS active effect late-join deadline");
}catch(const std::exception& error){std::cerr<<error.what()<<'\n';return 1;}}
