#include <darkangel/world_session.hpp>
#include "../engine/runtime/effect_wire.hpp"
#include <algorithm>
#include <deque>
#include <iostream>
using namespace darkangel;
namespace {
void check(bool b,const char* error){if(!b)throw std::runtime_error(error);}
template<class F>void rejects(F f){bool failed=false;try{f();}catch(const std::exception&){failed=true;}check(failed,"Expected effect replica rejection");}
std::uint64_t word(const std::vector<std::byte>& bytes,std::size_t offset){std::uint64_t value{};for(unsigned i=0;i<8;++i)value|=std::uint64_t(std::to_integer<unsigned char>(bytes.at(offset+i)))<<(i*8);return value;}
class Buffered:public Transport {
 Transport& inner_;
public:
 bool hold{};std::deque<TransportMessage> queue;std::size_t status_packets{},largest{};
 explicit Buffered(Transport& inner):inner_(inner){}
 ConnectionHandle open(const SessionHandshake& h)override{return inner_.open(h);}
 bool connected()const override{return inner_.connected();}
 bool valid(ConnectionHandle h)const override{return inner_.valid(h);}
 TransportLimits limits()const override{return inner_.limits();}
 bool send(ConnectionHandle h,Delivery d,std::span<const std::byte> bytes)override{return inner_.send(h,d,bytes);}
 void disconnect(ConnectionHandle h)override{inner_.disconnect(h);}
 std::vector<TransportMessage> poll(std::size_t count)override{std::vector<TransportMessage> result;if(!hold)while(!queue.empty()&&result.size()<count){result.push_back(std::move(queue.front()));queue.pop_front();}for(auto& message:inner_.poll(count-result.size())){auto kind=word(message.bytes,8);if(kind==16||kind==17){++status_packets;largest=std::max(largest,message.bytes.size());check(message.bytes.size()<=1000&&message.delivery==Delivery::UnreliableState,"Effect state retains native packet/channel bounds");if(hold){check(queue.size()<256,"Fixture bounded delayed status packets");queue.push_back(std::move(message));continue;}}result.push_back(std::move(message));}return result;}
};
struct Fixture {
 SessionHandshake hello{3,std::string(64,'a'),std::string(64,'b'),77};LoopbackPair pair=create_loopback(hello);Buffered buffered{*pair.client};WorldSession server{SessionRole::Server,hello},client{SessionRole::Client,hello};ConnectionHandle hp,cp;AbilityOwnerHandle source,target;
 std::vector<AttributeDefinition> schema{{1,"MaxHealth",AttributeKind::Statistic,100,0,1000,0,AttributeVisibility::Public},{2,"Health",AttributeKind::Resource,100,0,1000,1,AttributeVisibility::Public},{3,"SecretPower",AttributeKind::Statistic,73,0,100,0,AttributeVisibility::Server}};
 std::shared_ptr<const TagDictionary> tags=std::make_shared<const TagDictionary>(std::vector<TagDefinition>{{1,0,"State",AttributeVisibility::Public},{2,1,"State.Burn",AttributeVisibility::Public},{3,0,"Secret",AttributeVisibility::Server},{4,0,"Private",AttributeVisibility::Owner}},AssetId::random(),std::string(64,'e'));
 std::shared_ptr<EffectDefinition> burn=std::make_shared<EffectDefinition>(),hidden=std::make_shared<EffectDefinition>(),secret=std::make_shared<EffectDefinition>();
 Fixture(){hp=pair.host->open(hello);cp=buffered.open(hello);server.attach(*pair.host,hp);client.attach(buffered,cp);ObjectData object;object.id={21,1};source=server.configure_abilities(server.create(object),schema,2,1);object.id={21,2};target=server.configure_abilities(server.create(object),schema,2,1);server.configure_ability_tags(source,tags);server.configure_ability_tags(target,tags);server.own_motor(target.network,hp);server.publish_motor(target.network,{});burn->id=AssetId::random();burn->generation=std::string(64,'f');burn->duration_ticks=25;burn->period_ticks=10;burn->evaluator=1;burn->stacking=EffectStack::RefreshPerSource;burn->visibility=AttributeVisibility::Public;burn->tags={2};burn->cues={{AssetId::random(),"Status.Burn"}};*hidden=*burn;hidden->id=AssetId::random();hidden->lifetime=EffectLifetime::UntilRemoved;hidden->duration_ticks=hidden->period_ticks=0;hidden->evaluator=0;hidden->tags={4};hidden->cues.clear();hidden->visibility=AttributeVisibility::Owner;*secret=*hidden;secret->id=AssetId::random();secret->visibility=AttributeVisibility::Server;secret->tags={3};server.register_effect_evaluator(1,[](const EffectContext& c){return std::vector<ResourceDelta>{{2,-c.credit.power/10}};});pump();}
 void pump(unsigned count=32){for(unsigned i=0;i<count;++i){server.tick();client.tick();}}
 EffectHandle apply(const EffectDefinition& definition){return server.apply_effect(target,source,definition,70);}
 void step(){auto tick=server.ability_snapshot(target).tick+1;server.advance_abilities(tick);server.drain_ability_actions();server.drain_effect_outcomes();auto motor=server.motors().at(target.network);motor.tick=tick;motor.sequence=tick;server.publish_motor(target.network,motor);pump();}
 EffectPresentation prepared(AttributeVisibility audience){return {audience,AttributeSet(schema),tags,std::array<std::shared_ptr<const EffectDefinition>,3>{burn,hidden,secret}};}
 const EffectFrame& frame(AttributeVisibility audience){return client.effect_frames(audience).at(target.network);}
};
void visibility_lifetimes_credit(){
 Fixture f;auto burn=f.apply(*f.burn),hidden=f.apply(*f.hidden),secret=f.apply(*f.secret);f.pump();auto owner=f.frame(AttributeVisibility::Owner),public_frame=f.frame(AttributeVisibility::Public);check(owner.effects.size()==2&&public_frame.effects.size()==1&&public_frame.effects.front().handle==burn.value,"Owner/public frames filter private and server effect instances");check(f.client.world().valid(owner.owner.entity)&&owner.owner.entity!=f.target.entity,"Effect state resolves checked local owner identity");auto native=f.server.ability_effects(f.target);check(native.front().credit.power==70&&native.front().credit.source_attributes.size()==3,"Authoritative captures retain source power and private statistics");auto bytes=session_detail::encode_effect_frame(public_frame);check(bytes.size()==72+144,"Effect wire contains presentation attribution without captured power/statistics");auto prepared=f.prepared(AttributeVisibility::Public);check(prepared.push(public_frame)&&!prepared.push(public_frame),"Prepared effect state is idempotent");auto begins=prepared.drain_cues();check(begins.size()==1&&begins[0].edge==EffectCueEdge::Begin&&begins[0].state.id.handle==burn.value&&prepared.drain_cues().empty(),"Persistent cue begins once from current state");
 for(unsigned tick=1;tick<=10;++tick)f.step();check(f.frame(AttributeVisibility::Public).effects.front().next_period==20&&f.server.objects().at(f.target.network).health.current==93,"Period clock advances with authoritative damage; replica executes none");auto refreshed=f.apply(*f.burn);check(refreshed==burn,"Per-source refresh keeps stable effect identity");f.pump();check(f.frame(AttributeVisibility::Public).effects.front().start==0&&f.frame(AttributeVisibility::Public).effects.front().end==35&&f.frame(AttributeVisibility::Public).effects.front().next_period==20,"Refresh updates end while retaining period phase");prepared.push(f.frame(AttributeVisibility::Public));auto updates=prepared.drain_cues();check(updates.size()==1&&updates[0].edge==EffectCueEdge::Update&&updates[0].state.end==35,"Refresh updates the same persistent cue identity");
 f.server.destroy(f.source.network);f.pump();const auto& durable=f.frame(AttributeVisibility::Public).effects.front();check(!f.client.objects().contains(f.source.network)&&durable.credit.source_network==f.source.network&&durable.credit.session_epoch==77,"Replica attribution outlives destroyed source actor");for(unsigned tick=11;tick<=35;++tick)f.step();check(f.frame(AttributeVisibility::Public).effects.empty()&&f.frame(AttributeVisibility::Owner).effects.size()==1&&f.server.objects().at(f.target.network).health.current==79,"Expiry removes only visible Burn and executes no period at end");prepared.push(f.frame(AttributeVisibility::Public));check(prepared.current()->effects.empty(),"Current status presentation clears on expiry without history replay");auto ends=prepared.drain_cues();check(ends.size()==1&&ends[0].edge==EffectCueEdge::End&&prepared.cues().empty(),"Expiry ends the existing persistent cue");f.server.remove_effect(f.target,hidden);f.server.remove_effect(f.target,secret);f.pump();check(f.frame(AttributeVisibility::Owner).effects.empty(),"Empty complete owner frame removes final visible status");
}
void late_join_and_generation(){
 Fixture f;f.apply(*f.burn);f.apply(*f.hidden);f.apply(*f.secret);f.step();auto pair=create_loopback(f.hello);WorldSession late(SessionRole::Client,f.hello);auto hp=pair.host->open(f.hello),cp=pair.client->open(f.hello);f.server.attach(*pair.host,hp);late.attach(*pair.client,cp);for(unsigned i=0;i<48;++i){f.server.tick();f.client.tick();late.tick();}check(late.effect_frames(AttributeVisibility::Owner).empty()&&late.effect_frames(AttributeVisibility::Public).at(f.target.network).effects.size()==1,"Late observer receives current public effect lifetime only");auto prepared=f.prepared(AttributeVisibility::Public);prepared.push(late.effect_frames(AttributeVisibility::Public).at(f.target.network));check(prepared.current()->effects.front().start==0&&prepared.current()->effects.front().next_period==10,"Late preparation reconstructs current active state without past executions");check(prepared.drain_cues().size()==1&&prepared.cues().size()==1,"Late observer begins only the current persistent cue");auto current=*prepared.current();auto stale=current;stale.revision++;stale.effects.front().generation=std::string(64,'a');rejects([&]{prepared.push(stale);});stale=current;stale.revision++;stale.effects.front().definition=AssetId::random();rejects([&]{prepared.push(stale);});stale=current;stale.revision++;stale.effects.front().end=100;rejects([&]{prepared.push(stale);});check(prepared.current()->effects==current.effects,"Unknown/generation/clock failure preserves prepared status state");auto wrong=current;wrong.audience=AttributeVisibility::Owner;rejects([&]{prepared.push(wrong);});wrong=current;wrong.revision++;wrong.effects.push_back({99,f.hidden->id,f.hidden->generation,current.effects.front().credit,0,0,0,false});rejects([&]{prepared.push(wrong);});
}
void dense_reorder_timeout_and_codec(){
 Fixture f;auto dense=*f.hidden;dense.tags.clear();dense.visibility=AttributeVisibility::Public;dense.stacking=EffectStack::Independent;for(unsigned i=0;i<4;++i)dense.cues.push_back({AssetId::random(),"Status.Dense"});for(unsigned i=0;i<64;++i)f.apply(dense);f.buffered.hold=true;f.pump(16);check(f.client.effect_frames(AttributeVisibility::Public).empty()&&f.buffered.queue.size()>=22,"Dense status fragments cannot publish partial owner/public state");std::reverse(f.buffered.queue.begin(),f.buffered.queue.end());f.buffered.queue.push_front(f.buffered.queue.front());f.buffered.hold=false;f.pump();auto frame=f.frame(AttributeVisibility::Public);check(frame.effects.size()==64&&f.frame(AttributeVisibility::Owner).effects.size()==64&&f.buffered.largest<=1000,"Reordered duplicate fragments publish complete bounded 64-instance frames");auto bytes=session_detail::encode_effect_frame(frame);check(bytes.size()<=16384&&session_detail::decode_effect_frame(bytes).effects==frame.effects,"Maximum effect-state explicit codec roundtrip");auto bad=frame;bad.effects.push_back(bad.effects.front());rejects([&]{session_detail::encode_effect_frame(bad);});bad=frame;bad.effects[1].handle=bad.effects[0].handle;rejects([&]{session_detail::encode_effect_frame(bad);});bad=frame;bad.audience=AttributeVisibility::Server;rejects([&]{session_detail::encode_effect_frame(bad);});bytes.pop_back();rejects([&]{session_detail::decode_effect_frame(bytes);});bytes=session_detail::encode_effect_frame(frame);bytes[0]=std::byte{2};rejects([&]{session_detail::decode_effect_frame(bytes);});
 EffectPresentation cues(AttributeVisibility::Public,AttributeSet(f.schema),f.tags,std::array<std::shared_ptr<const EffectDefinition>,1>{std::make_shared<const EffectDefinition>(dense)});cues.push(frame);check(cues.cues().size()==256,"Prepared maximum persistent cue set");auto epoch=frame;epoch.avatar_epoch++;rejects([&]{cues.push(epoch);});check(cues.current()->avatar_epoch==frame.avatar_epoch&&cues.drain_cues().size()==256,"Cue backlog overflow preserves the prior lifecycle and queued events");cues.push(epoch);check(cues.drain_cues().size()==512&&!cues.push(epoch)&&cues.drain_cues().empty(),"Avatar discontinuity ends old cues and starts current cues once");
 Fixture missing;for(unsigned i=0;i<64;++i)missing.apply(dense);missing.buffered.hold=true;missing.pump(16);auto partial=std::find_if(missing.buffered.queue.begin(),missing.buffered.queue.end(),[](const auto& message){return word(message.bytes,8)==17;});check(partial!=missing.buffered.queue.end(),"Captured public status fragment");auto fragment=*partial;missing.buffered.queue.clear();missing.buffered.queue.push_back(std::move(fragment));missing.buffered.hold=false;missing.client.tick();missing.buffered.hold=true;for(unsigned i=0;i<32;++i)missing.client.tick();check(missing.client.effect_frame_needs_resync(missing.target.network,AttributeVisibility::Public)&&missing.client.effect_frames(AttributeVisibility::Public).empty(),"Incomplete effect timeout exposes resync without partial publication");missing.buffered.queue.clear();missing.buffered.hold=false;missing.pump(96);check(missing.frame(AttributeVisibility::Public).effects.size()==64&&!missing.client.effect_frame_needs_resync(missing.target.network,AttributeVisibility::Public),"Periodic complete frame recovers lost status fragments");
}
void suppression_and_four_actor_fairness(){
 Fixture f;auto status=std::make_shared<EffectDefinition>(*f.hidden);status->id=AssetId::random();status->visibility=AttributeVisibility::Public;status->ongoing.all={4};status->cues={{AssetId::random(),"Status.Conditional"}};auto handle=f.apply(*status);f.pump();EffectPresentation view(AttributeVisibility::Public,AttributeSet(f.schema),f.tags,std::array<std::shared_ptr<const EffectDefinition>,1>{status});view.push(f.frame(AttributeVisibility::Public));check(view.current()->effects.front().suppressed&&view.cues().empty()&&view.drain_cues().empty(),"Suppressed status retains its timer without active cue");auto enabling=f.apply(*f.hidden);f.step();view.push(f.frame(AttributeVisibility::Public));auto begin=view.drain_cues();check(begin.size()==1&&begin[0].edge==EffectCueEdge::Begin&&begin[0].state.id.handle==handle.value,"Confirmed resume begins its persistent cue");f.server.remove_effect(f.target,enabling);f.pump();view.push(f.frame(AttributeVisibility::Public));auto end=view.drain_cues();check(end.size()==1&&end[0].edge==EffectCueEdge::End&&view.cues().empty(),"Confirmed suppression ends presentation without removing the instance");
 Fixture actors;auto dense=*actors.hidden;dense.stacking=EffectStack::Independent;dense.visibility=AttributeVisibility::Public;dense.tags.clear();std::vector<AbilityOwnerHandle> owners{actors.source,actors.target};for(unsigned i=0;i<2;++i){ObjectData object;object.id={30,i+1};owners.push_back(actors.server.configure_abilities(actors.server.create(object),actors.schema,2,1));}for(auto owner:owners){if(!actors.server.motors().contains(owner.network))actors.server.publish_motor(owner.network,{});for(unsigned i=0;i<64;++i)actors.server.apply_effect(owner,actors.source,dense,0);}actors.pump(64);check(actors.client.effect_frames(AttributeVisibility::Public).size()==4,"Round-robin fragmented status delivery serves all four dense actors");for(auto owner:owners)check(actors.client.effect_frames(AttributeVisibility::Public).at(owner.network).effects.size()==64,"Dense actor status set is complete");check(actors.client.effect_frames(AttributeVisibility::Owner).size()==1&&actors.frame(AttributeVisibility::Owner).effects.size()==64,"Dense owner/private state delivery retains network ownership");
}
}
int main(){try{visibility_lifetimes_credit();late_join_and_generation();dense_reorder_timeout_and_codec();suppression_and_four_actor_fairness();std::cout<<"Native effect audiences, current lifetimes/durable attribution, late join, frozen preparation and bounded fragmented status recovery passed\n";return 0;}catch(const std::exception& e){std::cerr<<e.what()<<'\n';return 1;}}
