#include <darkangel/assets.hpp>
#include <darkangel/effect_assets.hpp>
#include <darkangel/world_session.hpp>
#include <nlohmann/json.hpp>
#include <fstream>
#include <iostream>
using namespace darkangel;using Json=nlohmann::json;
namespace {
void check(bool b,const char* m){if(!b)throw std::runtime_error(m);}
template<class F>void rejects(F f){bool failed=false;try{f();}catch(const std::exception&){failed=true;}check(failed,"Expected effect asset rejection");}
Json read(const std::filesystem::path& path){std::ifstream in(path);return Json::parse(in);}
void write(const std::filesystem::path& path,const Json& value){std::ofstream(path)<<value.dump(2)<<'\n';}
}
int main(){try{
 auto root=std::filesystem::temp_directory_path()/("DarkAngelEffectAssets-"+AssetId::random().text());auto source=root/"source";std::filesystem::create_directories(source);auto effect_id=AssetId::random(),tags_id=AssetId::random(),attributes_id=AssetId::random();
 Json attributes={{"schema",1},{"kind","attributes"},{"asset",attributes_id.text()},{"attributes",Json::array({{{"id",1},{"name","MaxHealth"},{"kind","statistic"},{"base",100.},{"minimum",0.},{"maximum",10000.},{"maximum_attribute",0},{"unit","points"},{"visibility","public"}},{{"id",2},{"name","Health"},{"kind","resource"},{"base",100.},{"minimum",0.},{"maximum",10000.},{"maximum_attribute",1},{"unit","points"},{"visibility","public"}},{{"id",3},{"name","Speed"},{"kind","statistic"},{"base",5.},{"minimum",0.},{"maximum",20.},{"maximum_attribute",0},{"unit","m/s"},{"visibility","owner"}}})}};
 Json tags={{"schema",1},{"kind","tags"},{"asset",tags_id.text()},{"tags",Json::array({{{"key",AssetId::random().text()},{"id",1},{"parent",0},{"name","State"},{"visibility","public"}},{{"key",AssetId::random().text()},{"id",2},{"parent",1},{"name","State.Burn"},{"visibility","public"}},{{"key",AssetId::random().text()},{"id",3},{"parent",1},{"name","State.Slow"},{"visibility","owner"}}})}};
 Json empty={{"all",Json::array()},{"any",Json::array()},{"none",Json::array()}};
 Json effect={{"schema",1},{"kind","effect"},{"asset",effect_id.text()},{"attributes",attributes_id.text()},{"tags",tags_id.text()},{"lifetime","finite"},{"stacking","refresh_per_source"},{"duration_ticks",8},{"period_ticks",2},{"execute_on_apply",false},{"remove_on_death",true},{"remove_with_source",false},{"interrupt_action",false},{"evaluator",1},{"granted_tags",{2}},{"application",empty},{"ongoing",empty},{"modifiers",Json::array()},{"sources",{{"attributes","base.daattributes"},{"tags","state.datags"}}}};
 effect["ongoing_policy"]="suppress";effect["visibility"]="public";effect["cues"]=Json::array({{{"id",AssetId::random().text()},{"key","Status.Burn"}}});write(source/"base.daattributes",attributes);write(source/"state.datags",tags);write(source/"burn.daeffect",effect);CookedEffect pinned;std::string original_generation;std::filesystem::path cas;
 {AssetService service(source,root/"cache");cas=service.cas_path();check(service.adopt("burn.daeffect")==effect_id&&service.adopt("state.datags")==tags_id,"Native embedded effect/tag identities");service.scan();check(service.cook("burn.daeffect").changed&&!service.cook("burn.daeffect").changed,"Effect warm closure skips conversion");service.package(effect_id,root/"registry.json");check(read(root/"registry.json")["assets"].size()==3,"Frozen effect/attribute/tag closure");pinned=load_cooked_effect(root/"registry.json",cas,effect_id);original_generation=pinned.definition->generation;check(pinned.definition->visibility==AttributeVisibility::Public&&pinned.definition->cues.size()==1&&pinned.definition->cues.front().key=="Status.Burn","Authored effect replication visibility freezes");check(pinned.tags.fields[1].key==AssetId::parse(tags["tags"][1]["key"].get<std::string>())&&pinned.tags.dictionary()->descends(2,1),"Stable persistent keys, compact native IDs and hierarchy");
  for(auto field:{"duration_ticks","period_ticks","evaluator"}){auto invalid=effect;invalid[field]=.5;write(source/"burn.daeffect",invalid);rejects([&]{service.cook("burn.daeffect");});}auto invalid=effect;invalid["cues"].push_back(invalid["cues"][0]);write(source/"burn.daeffect",invalid);rejects([&]{service.cook("burn.daeffect");});invalid=effect;invalid["cues"][0]["key"]="bad key";write(source/"burn.daeffect",invalid);rejects([&]{service.cook("burn.daeffect");});invalid=effect;invalid["visibility"]="unknown";write(source/"burn.daeffect",invalid);rejects([&]{service.cook("burn.daeffect");});invalid=effect;invalid["visibility"]=1;write(source/"burn.daeffect",invalid);rejects([&]{service.cook("burn.daeffect");});invalid=effect;invalid["granted_tags"]={99};write(source/"burn.daeffect",invalid);rejects([&]{service.cook("burn.daeffect");});invalid=effect;invalid["sources"]["tags"]="../state.datags";write(source/"burn.daeffect",invalid);rejects([&]{service.cook("burn.daeffect");});invalid=effect;invalid["extra"]=true;write(source/"burn.daeffect",invalid);rejects([&]{service.cook("burn.daeffect");});invalid=effect;invalid["lifetime"]="instant";write(source/"burn.daeffect",invalid);rejects([&]{service.cook("burn.daeffect");});invalid=effect;invalid["modifiers"]=Json::array({{{"attribute",2},{"kind","flat"},{"magnitude",10},{"channel",""},{"priority",0}}});write(source/"burn.daeffect",invalid);rejects([&]{service.cook("burn.daeffect");});write(source/"burn.daeffect",effect);
  auto bad_tags=tags;bad_tags["tags"][0]["parent"]=2;write(source/"state.datags",bad_tags);rejects([&]{service.cook("burn.daeffect");});bad_tags=tags;bad_tags["tags"][1]["key"]=bad_tags["tags"][0]["key"];write(source/"state.datags",bad_tags);rejects([&]{service.cook("burn.daeffect");});write(source/"state.datags",tags);service.package(effect_id,root/"preserved.json");check(load_cooked_effect(root/"preserved.json",cas,effect_id).definition->generation==original_generation,"Failed cook preserves usable effect generation");
  auto changed=tags;changed["tags"][2]["visibility"]="public";write(source/"state.datags",changed);check(service.cook("burn.daeffect").changed,"Tag dependency-only edits invalidate parent");service.package(effect_id,root/"changed.json");check(load_cooked_effect(root/"changed.json",cas,effect_id).definition->generation!=original_generation&&pinned.definition->generation==original_generation,"Complete closure generation pins old leases");auto mixed=read(root/"registry.json"),newer=read(root/"changed.json");for(auto& record:mixed["assets"])if(record["kind"]=="tags")for(const auto& next:newer["assets"])if(next["kind"]=="tags")record=next;write(root/"bad.json",mixed);rejects([&]{load_cooked_effect(root/"bad.json",cas,effect_id);});
  write(source/"state.datags",tags);service.cook("state.datags");std::array<AssetId,1> extra{tags_id};rejects([&]{service.package(effect_id,root/"conflict.json",extra);});service.cook("burn.daeffect");service.package(effect_id,root/"registry.json");auto manifest=read(root/"registry.json");auto duplicate=manifest;duplicate["assets"].push_back(duplicate["assets"][0]);write(root/"bad.json",duplicate);rejects([&]{load_cooked_effect(root/"bad.json",cas,effect_id);});auto missing=manifest;for(std::size_t i=0;i<missing["assets"].size();++i)if(missing["assets"][i]["kind"]=="tags"){missing["assets"].erase(i);break;}write(root/"bad.json",missing);rejects([&]{load_cooked_effect(root/"bad.json",cas,effect_id);});auto wrong=manifest;for(auto& record:wrong["assets"])if(record["kind"]=="effect")record["extension"]="../effect.json";write(root/"bad.json",wrong);rejects([&]{load_cooked_effect(root/"bad.json",cas,effect_id);});
  for(const auto& record:manifest["assets"])if(record["kind"]=="effect"){auto file=cas/(record["sha256"].get<std::string>()+".effect.json");std::ifstream in(file,std::ios::binary);std::string bytes{std::istreambuf_iterator<char>(in),{}};in.close();std::ofstream(file)<<"corrupt";rejects([&]{load_cooked_effect(root/"registry.json",cas,effect_id);});std::ofstream(file,std::ios::binary)<<bytes;}
 }
 std::filesystem::rename(source,root/"offline-source");auto offline=load_cooked_effect(root/"registry.json",cas,effect_id);check(offline.definition->generation==original_generation,"Source-free verified registry/CAS load");std::filesystem::rename(root/"offline-source",source);{AssetService fresh(source,root/"fresh");fresh.cook("burn.daeffect");fresh.package(effect_id,root/"fresh.json");check(load_cooked_effect(root/"fresh.json",fresh.cas_path(),effect_id).definition->generation==original_generation,"Fresh cache deterministic semantic generation");}
 WorldSession server(SessionRole::Server,{1,std::string(64,'a'),std::string(64,'b'),77});ObjectData object;object.id={9,1};auto owner=server.configure_abilities(server.create(object),offline.attributes.definitions(),2,1);server.configure_ability_tags(owner,offline.tags.dictionary());server.register_effect_evaluator(1,[](const EffectContext& c){return std::vector<ResourceDelta>{{2,-c.credit.power}};});server.apply_effect(owner,owner,*offline.definition,10);server.advance_abilities(1);server.advance_abilities(2);check(server.world().read(owner.entity).health.current==90&&server.ability_tags(owner)==std::vector<TagId>{2},"Source-free cooked effect uses existing native authority and tag ownership");
 std::cout<<"Frozen effect/tag source/CAS closure, stable keys, failed-cook preservation, generation fences and native authority passed\n";return 0;
}catch(const std::exception& e){std::cerr<<e.what()<<'\n';return 1;}}
