#include <darkangel/world_session.hpp>
#include <algorithm>
#include <iostream>
#include <stdexcept>
using namespace darkangel;
namespace {
void check(bool b,const char* m){if(!b)throw std::runtime_error(m);}
template<class F>void rejects(F f){bool failed=false;try{f();}catch(const std::exception&){failed=true;}check(failed,"Expected atomic rejection");}
std::vector<AttributeDefinition> schema(){return {{1,"MaxHealth",AttributeKind::Statistic,100,0,10000},{2,"Health",AttributeKind::Resource,100,0,10000,1},{3,"Speed",AttributeKind::Statistic,5,0,20},{4,"Armor",AttributeKind::Statistic,0,0,1000}};}
std::shared_ptr<const TagDictionary> dictionary(){return std::make_shared<const TagDictionary>(std::vector<TagDefinition>{{1,0,"State",AttributeVisibility::Public},{2,1,"State.Burn",AttributeVisibility::Public},{3,1,"State.Slow",AttributeVisibility::Public},{4,1,"State.Invulnerable",AttributeVisibility::Owner},{5,1,"State.Stagger",AttributeVisibility::Public},{6,0,"Equipment",AttributeVisibility::Server},{7,0,"Suppress",AttributeVisibility::Server}});}
EffectDefinition effect(TagId tag=2){EffectDefinition d;d.id=AssetId::random();d.generation=std::string(64,'a');d.duration_ticks=8;d.tags={tag};return d;}
EffectCredit credit(std::uint64_t source=1,double power=10){return {77,source,1,power,{{4,12}}};}
double value(const AbilityOwnerSnapshot& s,AttributeId id){for(auto a:s.attributes)if(a.id==id)return a.value;throw std::runtime_error("Attribute missing");}
void tags(){
 OwnedTags tags(dictionary());tags.add(1,std::array<TagId,1>{2});tags.add(2,std::array<TagId,1>{2});check(tags.has(1)&&tags.matches({{1},{2,3},{4}}),"Hierarchical All/Any/None queries");tags.remove(1);check(tags.has(2)&&tags.has(2,1)&&!tags.has(2,2),"One contribution cannot remove another; excluded token");tags.remove(2);check(!tags.has(1),"Exact token cleanup");
 tags.add(3,std::array<TagId,2>{4,6});check(tags.values(AttributeVisibility::Public).empty()&&tags.values(AttributeVisibility::Owner)==std::vector<TagId>{4},"Audience excludes owner/server tags");rejects([&]{tags.add(3,std::array<TagId,1>{2});});rejects([&]{tags.matches({{99},{},{}});});rejects([]{TagDictionary bad({{1,2,"A"},{2,1,"B"}});});rejects([]{TagDictionary bad({{1,9,"A"}});});
}
void owned_timing(){
 AttributeSet attributes(schema());OwnedEffects effects(dictionary());auto burn=effect();burn.period_ticks=2;burn.evaluator=1;burn.stacking=EffectStack::RefreshPerSource;
 auto damage=[](const EffectContext& c){return std::vector<ResourceDelta>{{2,-c.credit.power}};};auto lookup=[&](std::uint32_t id){check(id==1,"Frozen evaluator identity");return EffectEvaluator(damage);};
 auto first=effects.apply(burn,credit(),0,attributes,damage);check(first.second.empty()&&attributes.value(2)==100,"No implicit application execution");
 effects.advance(1,attributes,lookup);auto refreshed=effects.apply(burn,credit(1,15),1,attributes,damage);check(first.first==refreshed.first&&effects.snapshot()[0].next_period==2&&effects.snapshot()[0].end==9,"Per-source refresh preserves periodic phase and identity");
 burn.duration_ticks=4;auto second=effects.apply(burn,credit(2,5),1,attributes,damage);check(second.first!=first.first&&effects.snapshot().size()==2,"Different sources retain independent Burn instances");
 effects.advance(2,attributes,lookup);check(attributes.value(2)==85,"First periodic refresh uses captured updated magnitude");effects.advance(3,attributes,lookup);check(attributes.value(2)==80,"Independent source period");effects.remove(second.first,attributes);check(effects.tags().has(2),"Removing one Burn retains another source tag");
 for(unsigned tick=4;tick<=9;++tick)effects.advance(tick,attributes,lookup);check(attributes.value(2)==35&&effects.snapshot().empty(),"Finite [start,end), first start+period, no execution at end");
 auto instant=effect();instant.lifetime=EffectLifetime::Instant;instant.duration_ticks=0;instant.tags.clear();instant.execute_on_apply=true;instant.evaluator=1;auto result=effects.apply(instant,credit(1,5),9,attributes,damage);check(result.second.size()==1&&attributes.value(2)==30&&effects.snapshot().empty(),"Explicit instant execution retains no lifetime");
 auto before=attributes.value(2);auto invalid=[](const EffectContext&){return std::vector<ResourceDelta>{{2,-5},{99,1}};};rejects([&]{effects.apply(instant,credit(),9,attributes,invalid);});check(attributes.value(2)==before&&effects.snapshot().empty(),"Failed evaluator transaction consumes no health or effect identity");
}
void modifiers_suppression(){
 AttributeSet attributes(schema());OwnedEffects effects(dictionary());auto slow=effect(3);slow.modifiers={{0,0,3,AttributeModifierKind::ChannelBonus,-.5,"movement"}};auto a=effects.apply(slow,credit(),0,attributes,{}).first;auto b=effects.apply(slow,credit(2),0,attributes,{}).first;check(attributes.value(3)==0,"Additive channel composition");effects.remove(a,attributes);check(attributes.value(3)==2.5&&effects.tags().has(3),"Slow contributor cleanup");effects.remove(b,attributes);
 auto boost=effect(6);boost.lifetime=EffectLifetime::UntilRemoved;boost.duration_ticks=0;boost.modifiers={{0,0,1,AttributeModifierKind::Flat,100}};auto equipment=effects.apply(boost,credit(),0,attributes,{}).first;attributes.transact(std::array<ResourceDelta,1>{{{2,80}}},false);effects.advance(1,attributes,[](auto){return EffectEvaluator{};});check(attributes.value(2)==180,"Effect recomputation never clamps through temporary modifier removal");effects.remove(equipment,attributes);check(attributes.value(2)==100&&attributes.value(1)==100,"Equipment cleanup recomputes and clamps final bounds");
 auto burn=effect();burn.duration_ticks=8;burn.period_ticks=1;burn.evaluator=1;burn.ongoing.none={7};auto damage=[](const EffectContext& c){return std::vector<ResourceDelta>{{2,-c.credit.power}};};auto burn_handle=effects.apply(burn,credit(),1,attributes,damage).first;auto blocker=effect(7);blocker.duration_ticks=2;auto suppress=effects.apply(blocker,credit(),1,attributes,{}).first;
 auto result=effects.advance(2,attributes,[&](auto){return EffectEvaluator(damage);});check(result.empty()&&!effects.tags().has(2)&&effects.snapshot()[0].suppressed,"Suppression removes own tags/modifiers and skips periodic execution");effects.advance(3,attributes,[&](auto){return EffectEvaluator(damage);});check(attributes.value(2)==90&&effects.tags().has(2),"Expiry precedes periodic, resumes without replaying suppressed work");effects.remove(suppress,attributes);effects.cleanse({{1},{},{7}},attributes);check(effects.snapshot().empty(),"Hierarchical native cleanse");effects.remove(burn_handle,attributes);
 auto self=effect(7);self.ongoing.none={7};effects.apply(self,credit(),3,attributes,{});effects.advance(4,attributes,[](auto){return EffectEvaluator{};});check(effects.tags().has(7),"Ongoing requirement excludes its own contribution");
}
struct Fixture {
 WorldSession server{SessionRole::Server,{1,std::string(64,'a'),std::string(64,'b'),77}};AbilityOwnerHandle source,target;
 Fixture(){ObjectData o;o.id={9,1};source=server.configure_abilities(server.create(o),schema(),2,1);o.id={9,2};target=server.configure_abilities(server.create(o),schema(),2,1);server.configure_ability_tags(source,dictionary());server.configure_ability_tags(target,dictionary());server.register_effect_evaluator(1,[](const EffectContext& c){check(c.credit.source_attributes.size()==4,"Captured source attributes");return std::vector<ResourceDelta>{{2,c.target_tags.has(4)?0:-c.credit.power}};});}
 void step(){server.advance_abilities(server.ability_snapshot(target).tick+1,0);server.drain_ability_actions();}
};
void authority_credit_death(){
 Fixture f;auto burn=effect();burn.period_ticks=2;burn.evaluator=1;auto handle=f.server.apply_effect(f.target,f.source,burn,20);auto dodge=effect(4);dodge.duration_ticks=3;f.server.apply_effect(f.target,f.target,dodge,0);f.step();f.step();check(value(f.server.ability_snapshot(f.target),2)==100,"Game evaluator reads native invulnerability tag during hitstop");f.step();f.step();check(value(f.server.ability_snapshot(f.target),2)==80,"Simulation lifetime expires during action hitstop");
 auto armor=effect(6);armor.duration_ticks=0;armor.lifetime=EffectLifetime::UntilRemoved;armor.remove_with_source=true;armor.modifiers={{0,0,4,AttributeModifierKind::Flat,50}};f.server.apply_effect(f.target,f.source,armor,0);check(value(f.server.ability_snapshot(f.target),4)==50,"Equipment statistic contribution");f.server.destroy(f.source.network);check(value(f.server.ability_snapshot(f.target),4)==0&&f.server.ability_effects(f.target).size()==1,"Source destruction removes explicitly bound equipment and preserves captured Burn");f.step();f.step();auto outcomes=f.server.drain_effect_outcomes();check(value(f.server.ability_snapshot(f.target),2)==60&&outcomes.back().execution.credit.source_network==f.source.network&&outcomes.back().execution.credit.session_epoch==77,"Periodic credit survives source destruction without a live avatar");rejects([&]{f.server.apply_effect(f.target,f.source,burn,20);});
 auto wrong=handle;wrong.owner=f.source;rejects([&]{f.server.remove_effect(f.target,wrong);});check(f.server.ability_effects(f.target).size()==1,"Effect handle cannot cross owners");f.server.cleanse_effects(f.target,{{2},{},{}});check(f.server.ability_effects(f.target).empty(),"Native WorldSession cleanse publishes cleanup");f.server.remove_effect(f.target,handle);
 Fixture lethal;auto kill=effect();kill.duration_ticks=4;kill.period_ticks=1;kill.evaluator=1;auto slow=effect(3);slow.modifiers={{0,0,3,AttributeModifierKind::Flat,-2}};lethal.server.apply_effect(lethal.target,lethal.source,kill,100);lethal.server.apply_effect(lethal.target,lethal.source,kill,50);lethal.server.apply_effect(lethal.target,lethal.source,slow,0);lethal.step();check(lethal.server.ability_effects(lethal.target).empty()&&lethal.server.ability_tags(lethal.target).empty()&&value(lethal.server.ability_snapshot(lethal.target),3)==5&&lethal.server.drain_effect_outcomes().size()==1,"Death cleans contributors and cancels later periodic work in stable order");
 WorldSession client(SessionRole::Client,{1,std::string(64,'a'),std::string(64,'b'),77});rejects([&]{client.apply_effect(lethal.target,lethal.source,kill,1);});rejects([&]{lethal.server.configure_ability_tags(lethal.target,dictionary());});
}
void fault_capacity(){
 Fixture f;auto instant=effect();instant.lifetime=EffectLifetime::Instant;instant.duration_ticks=0;instant.tags.clear();instant.execute_on_apply=true;instant.evaluator=1;
 for(unsigned i=0;i<128;++i)f.server.apply_effect(f.target,f.source,instant,0);auto revision=f.server.ability_snapshot(f.target).revision;rejects([&]{f.server.apply_effect(f.target,f.source,instant,1);});check(value(f.server.ability_snapshot(f.target),2)==100&&f.server.ability_snapshot(f.target).revision==revision,"Outcome queue overflow preserves resource/state");check(f.server.drain_effect_outcomes().size()==128,"Bounded outcome queue");f.server.apply_effect(f.target,f.source,instant,1);
 auto persistent=effect();persistent.duration_ticks=0;persistent.lifetime=EffectLifetime::UntilRemoved;for(unsigned i=0;i<64;++i)f.server.apply_effect(f.target,f.source,persistent,0);rejects([&]{f.server.apply_effect(f.target,f.source,persistent,0);});check(f.server.ability_effects(f.target).size()==64,"Active effect bound fails closed");
}
void stagger_baseline_and_atomic_tick(){
 Fixture f;auto action=std::make_shared<ActionDefinition>();action->id=AssetId::random();action->generation=std::string(64,'c');action->duration=4*action_tick_units;action->loops=1;action->blocks={{1,0,0,4*action_tick_units,ActionBlockKind::MovementLock,"attack"}};
 auto ability=std::make_shared<AbilityDefinition>();ability->id=AssetId::random();ability->generation=std::string(64,'d');ability->action=action;ability->interruptible=false;InputProfile input;input.id=AssetId::random();auto kit=std::make_shared<CombatKitDefinition>();kit->id=AssetId::random();kit->generation="native-effects";kit->locomotion_stance=AssetId::random();for(unsigned i=0;i<combat_slot_count;++i){input.actions.push_back({i+1,"action."+std::to_string(i),InputActionKind::Button});kit->slots[i]={static_cast<CombatSlot>(i),i+1,{}};}kit->slots[0].ability=ability->id;f.server.equip_combat_kit(f.target,kit,input,std::array<std::shared_ptr<const AbilityDefinition>,1>{ability});
 auto active=f.server.request_ability({f.target,1,1,CombatSlot::Light,{1,InputEdge::Pressed,0,0,1,false}});f.server.drain_ability_actions();check(active.committed&&f.server.cancel_ability(active.handle)==AbilityFailure::CancelDenied,"Ordinary cancellation respects action policy");auto stagger=effect(5);stagger.interrupt_action=true;auto handle=f.server.apply_effect(f.target,f.source,stagger,0);auto cleanup=f.server.drain_ability_actions();check(!f.server.ability_snapshot(f.target).active&&cleanup.size()==1&&cleanup[0].batch.events[0].edge==ActionEdge::End&&f.server.ability_tags(f.target)==std::vector<TagId>{5},"Native stagger forces owned action cleanup without a second action");f.server.remove_effect(f.target,handle);
 auto pair=create_loopback({1,std::string(64,'a'),std::string(64,'b'),77});auto host=pair.host->open({1,std::string(64,'a'),std::string(64,'b'),77}),peer=pair.client->open({1,std::string(64,'a'),std::string(64,'b'),77});WorldSession client(SessionRole::Client,{1,std::string(64,'a'),std::string(64,'b'),77});f.server.attach(*pair.host,host);client.attach(*pair.client,peer);
 auto burn=effect();burn.duration_ticks=4;burn.period_ticks=1;burn.evaluator=1;f.server.apply_effect(f.target,f.source,burn,10);f.step();for(unsigned i=0;i<20;++i){f.server.tick();client.tick();}check(client.objects().at(f.target.network).health.current==90,"Existing reliable baseline carries periodic authoritative Health");
 f.server.register_effect_evaluator(2,[](const EffectContext&){return std::vector<ResourceDelta>{{99,-1}};});auto bad=effect();bad.duration_ticks=4;bad.period_ticks=1;bad.evaluator=2;f.server.apply_effect(f.source,f.source,bad,10);auto before=f.server.ability_snapshot(f.target);auto source_before=f.server.ability_snapshot(f.source);rejects([&]{f.server.advance_abilities(2);});check(f.server.ability_snapshot(f.target).tick==before.tick&&f.server.ability_snapshot(f.source).revision==source_before.revision&&value(f.server.ability_snapshot(f.target),2)==90&&f.server.ability_effects(f.target)[0].next_period==2,"Failed periodic evaluator rolls back all owners, attributes and simulation clocks");f.server.cleanse_effects(f.source,{{2},{},{}});f.step();check(value(f.server.ability_snapshot(f.target),2)==80,"Prepared tick can retry after fixing effect configuration");
}
}
int main(){try{tags();owned_timing();modifiers_suppression();authority_credit_death();fault_capacity();stagger_baseline_and_atomic_tick();std::cout<<"Native owned tags/effects, Burn refresh/periods, slow, invulnerability, stagger, equipment/cleanse/death/source cleanup, captured credit, baseline Health and atomic bounds passed\n";return 0;}catch(const std::exception& e){std::cerr<<e.what()<<'\n';return 1;}}
