#include "../apps/editor/gameplay_debug.hpp"
#include <iostream>
using namespace darkangel;using namespace darkangel::editor_app;
void check(bool value,const char* error){if(!value)throw std::runtime_error(error);}
int main(){try{
 TagDictionary tags({{1,0,"State",AttributeVisibility::Public},{2,1,"State.Burning",AttributeVisibility::Public}});
 auto effect=std::make_shared<EffectDefinition>();effect->id=AssetId::random();effect->generation="frozen";effect->tags={2};std::vector<std::shared_ptr<const EffectDefinition>> definitions{effect};
 EffectFrame frame;frame.tick=10;frame.effects={{1,effect->id,"frozen",{1,5,7},0,30,0,false},{2,effect->id,"frozen",{1,6,9},0,30,0,false}};
 auto sources=tag_debug_sources(2,tags,nullptr,&frame,{},definitions);check(sources.size()==2&&sources[0].source_network==5&&sources[1].source_network==6,"Overlapping effect sources were collapsed");frame.effects.erase(frame.effects.begin());check(tag_debug_sources(2,tags,nullptr,&frame,{},definitions).size()==1,"Removing one source hid another");frame.effects[0].suppressed=true;check(tag_debug_sources(2,tags,nullptr,&frame,{},definitions).empty(),"Suppressed effect presented as a grant");frame.effects[0].suppressed=false;frame.effects[0].generation="other";check(tag_debug_sources(2,tags,nullptr,&frame,{},definitions).empty(),"Mixed generation inferred a source");frame.effects[0].generation="frozen";frame.tick=30;check(tag_debug_sources(2,tags,nullptr,&frame,{},definitions).empty(),"Expired effect presented as current");
 auto action=std::make_shared<ActionDefinition>();action->duration=100;action->blocks={{1,0,10,20,ActionBlockKind::Cue,"window"}};auto ability=std::make_shared<AbilityDefinition>();ability->id=AssetId::random();ability->generation="ability";ability->action=action;ability->action_tags={{1,2}};std::vector<std::shared_ptr<const AbilityDefinition>> abilities{ability};AbilityOwnerSnapshot owner;owner.ability=ability->id;owner.ability_generation="ability";owner.owner.network=5;owner.active=AbilityActivationHandle{owner.owner,10};owner.action=ActionState{};owner.action->clock=10;check(tag_debug_sources(1,tags,&owner,nullptr,abilities,{}).size()==1,"Action interval/ancestor source missing");owner.action->clock=20;check(tag_debug_sources(2,tags,&owner,nullptr,abilities,{}).empty(),"Action end boundary retained grant");
 check(!debug_attribute(nullptr,2).has_value(),"Missing private values presented as zero");
 check(std::string_view(ability_failure_text(AbilityFailure::Resources)).find("resource")!=std::string_view::npos&&std::string_view(ability_failure_text(AbilityFailure::TagRequirements)).find("tag")!=std::string_view::npos,"Native failure reasons lack explanation");std::cout<<"Gameplay debug: overlapping source credit, suppression/expiry/generation fences, action intervals/ancestors and native failure explanations passed\n";return 0;
 }catch(const std::exception& error){std::cerr<<error.what()<<'\n';return 1;}}
