#include <darkangel/gns_transport.hpp>
#include <darkangel/world_session.hpp>
#include <chrono>
#include <iostream>
#include <thread>
using namespace darkangel;
void process(bool host){
    SessionHandshake hello{1,std::string(64,'a'),std::string(64,'b'),51};auto adapter=host?create_gns_host("127.0.0.1:27892",hello):create_gns_client("127.0.0.1:27892",hello);auto peer=adapter->open(hello);auto deadline=std::chrono::steady_clock::now()+std::chrono::seconds(8);while(!adapter->connected() && std::chrono::steady_clock::now()<deadline)std::this_thread::sleep_for(std::chrono::milliseconds(2));if(!adapter->connected())throw std::runtime_error("GNS process connection deadline");WorldSession session(host?SessionRole::Server:SessionRole::Client,hello);session.attach(*adapter,peer);std::uint64_t id{};if(host){ObjectData o;o.id={5,1};id=session.create(o);}unsigned stage{};bool created{},moved{};deadline=std::chrono::steady_clock::now()+std::chrono::seconds(10);
    while(std::chrono::steady_clock::now()<deadline){session.tick();if(!host && !session.objects().empty()){created=true;moved|=session.objects().begin()->second.transform.x==12;}if(session.readiness(peer)==SessionReadiness::Ready){if(host){if(stage==0){Transform t;t.x=12;session.move(id,t);++stage;}else if(stage==1){session.destroy(id);++stage;}else {std::this_thread::sleep_for(std::chrono::milliseconds(100));std::cout<<"GNS process host lifecycle accepted\n";return;}}else if(session.revision()>=3 && session.objects().empty() && created && moved){std::cout<<"GNS process client current baseline/lifecycle accepted\n";return;}}std::this_thread::sleep_for(std::chrono::milliseconds(16));}throw std::runtime_error("GNS process gameplay deadline");
}
int main(int argc,char** argv){try{
    if(argc==2){if(std::string_view(argv[1])=="--host")process(true);else if(std::string_view(argv[1])=="--client")process(false);else throw std::runtime_error("Unknown GNS process role");return 0;}
    SessionHandshake hello{1,std::string(64,'a'),std::string(64,'b'),50};auto host=create_gns_host("127.0.0.1:27891",hello),client=create_gns_client("127.0.0.1:27891",hello);auto hp=host->open(hello),cp=client->open(hello);
    auto until=std::chrono::steady_clock::now()+std::chrono::seconds(5);while((!host->connected() || !client->connected()) && std::chrono::steady_clock::now()<until)std::this_thread::sleep_for(std::chrono::milliseconds(2));
    if(!host->connected() || !client->connected())throw std::runtime_error("GNS connection deadline");WorldSession server(SessionRole::Server,hello),view(SessionRole::Client,hello);server.attach(*host,hp);view.attach(*client,cp);ObjectData o;o.id={2,1};auto id=server.create(o);
    auto drive=[&]{auto end=std::chrono::steady_clock::now()+std::chrono::seconds(5);while(std::chrono::steady_clock::now()<end){server.tick();view.tick();if(view.readiness(cp)==SessionReadiness::Ready && view.revision()==server.revision())return;std::this_thread::sleep_for(std::chrono::milliseconds(2));}throw std::runtime_error("GNS baseline deadline");};
    drive();Transform t;t.x=12;server.move(id,t);drive();if(view.objects().at(id).transform.x!=12)throw std::runtime_error("GNS authority movement mismatch");server.destroy(id);drive();if(!view.objects().empty())throw std::runtime_error("GNS despawn mismatch");client->disconnect(cp);bool rejected=false;try{client->send(cp,Delivery::ReliableOrdered,{});}catch(...){rejected=true;}if(!rejected)throw std::runtime_error("GNS stale handle accepted");
    until=std::chrono::steady_clock::now()+std::chrono::seconds(3);while(host->connected() && std::chrono::steady_clock::now()<until)std::this_thread::sleep_for(std::chrono::milliseconds(2));auto next_host=host->open(hello),next_client=client->open(hello);until=std::chrono::steady_clock::now()+std::chrono::seconds(3);while((!host->connected() || !client->connected()) && std::chrono::steady_clock::now()<until)std::this_thread::sleep_for(std::chrono::milliseconds(2));if(!host->connected() || !client->connected() || next_host.epoch==hp.epoch || next_client.epoch==cp.epoch || host->valid(hp) || client->valid(cp))throw std::runtime_error("GNS reconnect did not invalidate handles");auto foreign=create_loopback(hello);auto fp=foreign.client->open(hello);foreign.host->open(hello);if(host->valid(fp))throw std::runtime_error("Cross-provider handle alias");std::cout<<"M3 GNS UDP localhost protocol/create/move/despawn/reconnect/offline checks passed\n";return 0;
}catch(const std::exception& e){std::cerr<<e.what()<<'\n';return 1;}}
