#include <darkangel/input.hpp>
#include <darkangel/assets.hpp>
#include <darkangel/editor_document.hpp>
#include <nlohmann/json.hpp>
#include <fstream>
#include <iostream>
#include <limits>
#include <source_location>
using namespace darkangel;
using Json=nlohmann::json;
namespace {
void check(bool value,const char* message){if(!value)throw std::runtime_error(message);}
template<class F>void rejects(F call,std::source_location location=std::source_location::current()){bool failed=false;try{call();}catch(const std::exception&){failed=true;}if(!failed)throw std::runtime_error("Invalid input accepted at line "+std::to_string(location.line()));}
std::string read(const std::filesystem::path& p){std::ifstream in(p,std::ios::binary);check(bool(in),"Input fixture missing");return {std::istreambuf_iterator<char>(in),{}};}
void write(const std::filesystem::path& p,std::string_view bytes){std::ofstream out(p,std::ios::binary);out<<bytes;check(bool(out),"Input fixture write");}
InputSample sample(std::string_view control,float value,std::uint64_t time,bool cancelled=false){return {input_control(control),value,time,cancelled};}
unsigned count(const InputBatch& batch,std::uint32_t action,InputEdge edge,bool cancelled=false){unsigned result{};for(const auto& event:batch.events)if(event.action==action&&event.edge==edge&&event.cancelled==cancelled)++result;return result;}
InputBatch update(InputManager& manager,std::uint64_t time,std::initializer_list<InputSample> samples,bool enabled=true){return manager.update(time,{samples.begin(),samples.size()},enabled);}
}
int main(){try{
    auto source=read(std::filesystem::path(DAE_SOURCE_DIR)/"content/input/royal_player.dainput");auto profile=decode_input_source(source);
    for(auto control:{"Keyboard.W","Keyboard.ShiftLeft","Mouse.Left","Gamepad0.RightShoulder","Gamepad3.LeftX"})check(input_control_name(input_control(control))==control,"Control name round trip");
    {InputManager manager(profile);auto press=update(manager,1000,{sample("Mouse.Left",1,1000)});check(count(press,8,InputEdge::Pressed)==1,"Single press");auto hold=update(manager,201000,{});check(count(hold,8,InputEdge::Hold)==1&&manager.state(8).held_us==200000,"Configured hold duration");auto release=update(manager,202000,{sample("Mouse.Left",0,202000)});check(count(release,8,InputEdge::Released)==1&&!count(release,8,InputEdge::Tapped),"Long hold became tap");}
    {InputManager manager(profile);auto tap=update(manager,1,{sample("Mouse.Left",1,1),sample("Mouse.Left",0,1)});check(count(tap,8,InputEdge::Pressed)==1&&count(tap,8,InputEdge::Released)==1&&count(tap,8,InputEdge::Tapped)==1&&!manager.state(8).down,"Same-time short tap lost");}
    {InputManager manager(profile);auto chord=update(manager,1,{sample("Keyboard.ShiftLeft",1,1),sample("Mouse.Left",1,1)});check(count(chord,9,InputEdge::Pressed)==1&&!manager.state(8).down&&!manager.state(4).down,"Consuming all chord emitted singles");update(manager,2,{sample("Mouse.Left",0,2)});check(!manager.state(4).down,"Held consumed modifier reactivated");update(manager,3,{sample("Keyboard.ShiftLeft",0,3)});update(manager,4,{sample("Keyboard.ShiftLeft",1,4)});check(manager.state(4).down,"Neutral modifier failed to rearm");}
    {auto observational=profile;for(auto& binding:observational.bindings)binding.consumption=InputConsumption::None;InputManager manager(observational);update(manager,1,{sample("Keyboard.ShiftLeft",1,1),sample("Mouse.Left",1,1)});check(manager.state(8).down&&manager.state(9).down&&manager.state(4).down,"Nonconsuming chord suppressed singles");}
    {auto trigger=profile;for(auto& binding:trigger.bindings)if(binding.action==9&&binding.controls.size()==2)binding.consumption=InputConsumption::Trigger;InputManager manager(trigger);update(manager,1,{sample("Keyboard.ShiftLeft",1,1),sample("Mouse.Left",1,1)});check(!manager.state(8).down&&manager.state(9).down&&manager.state(4).down,"Trigger-only chord consumed modifier");}
    {InputManager manager(profile);update(manager,1,{sample("Mouse.Left",1,1)});auto chord=update(manager,2,{sample("Keyboard.ShiftLeft",1,2)});check(count(chord,8,InputEdge::Released,true)==1&&!count(chord,8,InputEdge::Tapped)&&manager.state(9).down,"Late chord failed balanced cancellation");auto blur=update(manager,3,{},false);check(count(blur,9,InputEdge::Released,true)==1&&!count(blur,9,InputEdge::Tapped),"Focus cancellation became tap");update(manager,4,{});check(!manager.state(9).down,"Focus regained held chord");}
    {InputManager manager(profile);update(manager,1,{sample("Gamepad0.LeftTrigger",1,1),sample("Gamepad0.LeftShoulder",1,1),sample("Gamepad0.RightShoulder",1,1)});check(manager.state(12).down&&!manager.state(14).down&&!manager.state(8).down&&!manager.state(10).down&&manager.state(11).down,"Conflicting chord priority/consumption");}
    {InputManager manager(profile);update(manager,1,{sample("Mouse.Left",1,1)});auto other=update(manager,2,{sample("Gamepad0.RightShoulder",1,2)});check(!count(other,8,InputEdge::Pressed),"Second binding duplicated press");update(manager,3,{sample("Mouse.Left",0,3)});check(manager.state(8).down,"One source released aggregated action");auto up=update(manager,4,{sample("Gamepad0.RightShoulder",0,4)});check(count(up,8,InputEdge::Released)==1&&count(up,8,InputEdge::Tapped)==1,"Aggregated release/tap");}
    {InputManager manager(profile);update(manager,1,{sample("Keyboard.W",1,1),sample("Gamepad0.LeftX",-.75f,1)});check(manager.state(1).value==1&&manager.state(2).value==.75f,"Keyboard/gamepad axes");auto disconnected=update(manager,2,{sample("Gamepad0.LeftX",0,2,true)});check(count(disconnected,2,InputEdge::Released,true)==1&&manager.state(1).down,"Disconnect cancelled another device");auto invalid=sample("Keyboard.W",std::numeric_limits<float>::quiet_NaN(),3);rejects([&]{manager.update(3,{&invalid,1});});check(manager.state(1).down,"Invalid sample partially changed state");rejects([&]{update(manager,1,{});});
        auto invalid_profile=profile;invalid_profile.actions.push_back(invalid_profile.actions[0]);rejects([&]{manager.rebind(invalid_profile,3,{});});check(manager.state(1).down,"Invalid rebind lost active generation");std::vector<InputSample> physical;for(auto control:manager.controls())physical.push_back({control,control==input_control("Keyboard.W")?1.f:0.f,3,false});auto rebind=manager.rebind(profile,3,physical);check(count(rebind,1,InputEdge::Released,true)==1&&!manager.state(1).down,"Rebind did not cancel held action");update(manager,4,{});check(!manager.state(1).down,"Rebind immediately retriggered held key");update(manager,5,{sample("Keyboard.W",0,5)});update(manager,6,{sample("Keyboard.W",1,6)});check(manager.state(1).down,"Rebound key failed to rearm");}
    {auto malformed=Json::parse(source);malformed["bindings"][0]["priority"]=UINT64_MAX;rejects([&]{decode_input_source(malformed.dump());});malformed=Json::parse(source);malformed["bindings"][0]["controls"]=Json::array({"Gamepad0.South","Gamepad1.South"});rejects([&]{decode_input_source(malformed.dump());});}
    auto workspace=std::filesystem::path(DAE_BINARY_DIR)/("input-"+AssetId::random().text());auto mount=workspace/"source";std::filesystem::create_directories(mount);write(mount/"player.dainput",source);AssetService assets(mount,workspace/"cache");check(assets.adopt("player.dainput")==profile.id,"Input source identity");assets.cook("player.dainput");assets.package(profile.id,workspace/"registry.json");auto frozen=read(workspace/"registry.json");check(load_cooked_input(workspace/"registry.json",assets.cas_path(),profile.id).bindings.size()==profile.bindings.size(),"Cooked input closure");check(!assets.cook("player.dainput").changed,"Warm input cook");write(mount/"player.dainput","broken");rejects([&]{assets.cook("player.dainput");});assets.package(profile.id,workspace/"retained.json");check(read(workspace/"retained.json")==frozen,"Failed input cook replaced frozen generation");
    auto root=AssetId::random();Json scene={{"schema",1},{"asset",root.text()},{"entities",Json::object()},{"mounts",Json::object()}};EditorDocument document(root,StableId{0,1},{{root,scene.dump()},{profile.id,source}});auto edit=Json::parse(source);edit["actions"][0]["hold_ms"]=300;auto command=document.prepare_source(0,profile.id,edit.dump());document.commit(command);document.undo(document.revision());check(decode_input_source(document.source(profile.id)).actions[0].hold_us==200000,"Input source undo");auto bad=edit;bad["bindings"][0]["action"]=0;rejects([&]{document.prepare_source(document.revision(),profile.id,bad.dump());});document.save(workspace/"input.dascene");auto opened=EditorDocument::open(workspace/"input.dascene");check(Json::parse(opened->source(profile.id))==Json::parse(document.source(profile.id)),"Input source save/open");
    std::cout<<"Input events/chords/consumption, focus/rebind/device cancellation, atomic validation, frozen cook and native source transactions passed\n";return 0;
}catch(const std::exception& error){std::cerr<<error.what()<<'\n';return 1;}}
