#include <darkangel/world_session.hpp>
#include <cmath>
#include <iostream>
#include <limits>
using namespace darkangel;
namespace {
void check(bool b,const char* message){if(!b)throw std::runtime_error(message);}
template<class F>void rejects(F f){bool rejected=false;try{f();}catch(const std::exception&){rejected=true;}check(rejected,"Expected rejection");}
struct Fixture {
    WorldSession server{SessionRole::Server,{1,std::string(64,'a'),std::string(64,'b'),77}};
    PhysicsWorld physics;std::unique_ptr<CharacterMotor> attacker,victim;AbilityOwnerHandle source,target;
    std::shared_ptr<ActionDefinition> action=std::make_shared<ActionDefinition>();
    std::shared_ptr<AbilityDefinition> ability=std::make_shared<AbilityDefinition>();
    std::shared_ptr<CombatKitDefinition> kit=std::make_shared<CombatKitDefinition>();InputProfile input;
    bool fail{};double damage{30};
    Fixture(){
        server.bind_melee_query(std::make_shared<PhysicsMeleeQuery>(physics));
        std::vector<AttributeDefinition> schema{{1,"MaxHealth",AttributeKind::Statistic,100,0,1000,0},{2,"Health",AttributeKind::Resource,100,0,1000,1},{3,"Stamina",AttributeKind::Resource,60,0,60,0}};
        ObjectData a;a.id={1,1};ObjectData b;b.id={1,2};b.transform.z=1.2;auto sid=server.create(a),tid=server.create(b);source=server.configure_abilities(sid,schema,2,1);target=server.configure_abilities(tid,schema,2,1);
        physics.add({100,{0,-.5,0},{10,.5,10}});attacker=std::make_unique<CharacterMotor>(physics,MotorVec{0,0,0},sid);victim=std::make_unique<CharacterMotor>(physics,MotorVec{0,0,1.2},tid);
        server.register_damage_evaluator(1,[this](const DamageContext& context){check(context.source.owner==source||context.source.owner==target,"Checked source credit");check(context.block==1&&context.power==30&&context.damage_type==1,"Immutable authored damage context");if(context.target_tags&&context.target_tags->dictionary().contains(1)&&context.target_tags->has(1))return 0.;return fail?std::numeric_limits<double>::quiet_NaN():damage;});
        action->id=AssetId::random();action->generation=std::string(64,'a');action->duration=4*action_tick_units;action->loops=1;action->blocks={{1,0,action_tick_units/2,3*action_tick_units,ActionBlockKind::HitWindow,"body"}};
        ability->id=AssetId::random();ability->generation=std::string(64,'b');ability->action=action;ability->costs={{3,10}};ability->melee={{1,{0,1,.9},.7,30,1,1}};
        input.id=AssetId::random();kit->id=AssetId::random();kit->generation="kit";kit->locomotion_stance=AssetId::random();for(unsigned i=0;i<combat_slot_count;++i){input.actions.push_back({i+1,"combat."+std::to_string(i),InputActionKind::Button});kit->slots[i]={static_cast<CombatSlot>(i),i+1,{}};}kit->slots[0].ability=ability->id;
        std::array<std::shared_ptr<const AbilityDefinition>,1> catalogue{ability};server.equip_combat_kit(source,kit,input,catalogue);server.equip_combat_kit(target,kit,input,catalogue);
    }
    AbilityReceipt activate(AbilityOwnerHandle owner,std::uint64_t operation){return server.request_ability({owner,operation,server.ability_snapshot(owner).grant_generation,CombatSlot::Light,{1,InputEdge::Pressed,operation*1000,0,1,false},false});}
    void step(unsigned rate=action_tick_units){auto tick=physics.tick()+1;server.advance_abilities(tick,rate);attacker->step({tick,tick,attacker->state().epoch});victim->step({tick,tick,victim->state().epoch,0,0,3.141592653589793});physics.step();attacker->post_physics();victim->post_physics();physics.finish_tick();physics.take_sensor_events();server.publish_motor(source.network,attacker->state());server.publish_motor(target.network,victim->state());}
    std::vector<DamageResult> resolve(){return server.resolve_ability_hits(physics.tick());}
    double health(){return server.objects().at(target.network).health.current;}
};
void phases(){Fixture f;f.activate(f.source,1);f.server.drain_ability_actions();f.server.advance_abilities(1);f.attacker->step({1,1,1});f.victim->step({1,1,1});f.physics.step();PhysicsMeleeQuery query(f.physics);check(!query.matches(f.source.network,f.attacker->state()),"Melee refuses queries before every motor post_physics");f.attacker->post_physics();check(!query.matches(f.source.network,f.attacker->state()),"One motor post_physics cannot qualify the whole collision context");f.victim->post_physics();f.physics.finish_tick();f.physics.take_sensor_events();f.server.publish_motor(f.source.network,f.attacker->state());f.server.publish_motor(f.target.network,f.victim->state());check(f.resolve().size()==1,"Post-physics achieved poses qualify native melee");}
void hits(){Fixture f;check(f.activate(f.source,1).committed,"Ability committed");f.server.drain_ability_actions();f.step();auto result=f.resolve();check(result.size()==1&&result[0].applied==30&&f.health()==70,"Native overlap produces attributed authoritative damage");check(f.resolve().empty()&&f.health()==70,"Duplicate resolution does not damage twice");f.server.drain_ability_actions();f.step();check(f.resolve().empty()&&f.health()==70,"One target hit per activation/block/loop");}
void rollback(){Fixture f;f.activate(f.source,1);f.server.drain_ability_actions();f.step();f.fail=true;rejects([&]{f.resolve();});check(f.health()==100,"Bad game evaluator rolls back damage and hit ledger");rejects([&]{f.server.advance_abilities(2);});f.fail=false;check(f.resolve().size()==1&&f.health()==70,"Retry consumes the retained hit once");}
void cancel_pending(){Fixture f;auto activation=f.activate(f.source,1).handle;f.server.drain_ability_actions();f.step(4*action_tick_units);check(!f.server.ability_snapshot(f.source).active,"Action completed while crossed hit work is pending");f.server.cancel_ability(activation);check(f.resolve().empty()&&f.health()==100,"Explicit cancellation discards completed activation pending hits");f.server.drain_ability_actions();f.step();f.resolve();}
void active_death(){Fixture f;f.damage=200;f.activate(f.source,1);f.activate(f.target,1);f.server.drain_ability_actions();f.step();check(f.resolve().size()==1,"Death orders later requests after earlier attacker");auto updates=f.server.drain_ability_actions();bool death=false;for(auto& update:updates)if(update.reason==AbilityActionReason::Death&&update.handle.owner==f.target&&update.phase==ActionPhase::Cancelled)death=true;check(death&&!f.server.ability_snapshot(f.target).active,"Active target death forces balanced cancellation");}
void walls(){Fixture f;f.physics.add({101,{0,1,.6},{1,1,.05}});f.activate(f.source,1);f.server.drain_ability_actions();f.step();check(f.resolve().empty()&&f.health()==100,"Present authoritative blocker prevents damage");}
void death(){Fixture f;f.damage=200;f.activate(f.source,1);f.activate(f.target,1);f.server.drain_ability_actions();f.step(4*action_tick_units);auto result=f.resolve();check(result.size()==1&&result[0].killed&&result[0].applied==100&&f.health()==0,"Crossed completed window clamps lethal damage");check(!f.server.ability_snapshot(f.target).active&&f.server.ability_snapshot(f.source).attributes[1].value==100,"Death invalidates later target-owned requests");}
void replication(){
    Fixture f;SessionHandshake hello{1,std::string(64,'a'),std::string(64,'b'),77};auto transport=create_loopback(hello);WorldSession client(SessionRole::Client,hello);auto host=transport.host->open(hello),peer=transport.client->open(hello);f.server.attach(*transport.host,host);client.attach(*transport.client,peer);
    for(unsigned i=0;i<32;++i){f.server.tick();client.tick();}check(client.objects().at(f.target.network).health.current==100,"Observer starts from authoritative Health");f.activate(f.source,1);f.server.drain_ability_actions();f.step();f.resolve();for(unsigned i=0;i<32;++i){f.server.tick();client.tick();}check(client.objects().at(f.target.network).health.current==70,"Damage uses existing WorldSession baseline replication");
    auto late_transport=create_loopback(hello);WorldSession late(SessionRole::Client,hello);auto late_host=late_transport.host->open(hello),late_peer=late_transport.client->open(hello);f.server.attach(*late_transport.host,late_host);late.attach(*late_transport.client,late_peer);for(unsigned i=0;i<32;++i){f.server.tick();late.tick();}check(late.objects().at(f.target.network).health.current==70,"Late join receives current damage without replaying it");
}
std::vector<double> trace(unsigned rate){Fixture f;f.activate(f.source,1);f.server.drain_ability_actions();SimulationClock clock;std::vector<double> result;for(unsigned i=0;i<rate;++i)for(unsigned n=clock.advance(1./rate);n;--n){f.step();f.resolve();f.server.drain_ability_actions();result.push_back(f.health());}return result;}
void authority(){Fixture f;PhysicsWorld predicted(PhysicsWorld::Mode::Prediction);rejects([&]{PhysicsMeleeQuery query(predicted);});WorldSession client(SessionRole::Client,{1,std::string(64,'a'),std::string(64,'b'),77});rejects([&]{client.register_damage_evaluator(1,[](const DamageContext&){return 1.;});});PhysicsMeleeQuery query(f.physics);rejects([&]{client.resolve_ability_hits(1);});rejects([&]{f.server.resolve_ability_hits(1);});auto bad=std::make_shared<AbilityDefinition>(*f.ability);bad->melee[0].block=99;std::array<std::shared_ptr<const AbilityDefinition>,1> catalogue{bad};rejects([&]{f.server.equip_combat_kit(f.source,f.kit,f.input,catalogue);});}
void action_invulnerability(){
 Fixture f;auto tags=std::make_shared<const TagDictionary>(std::vector<TagDefinition>{{1,0,"State.Invulnerable",AttributeVisibility::Public}},AssetId::random(),std::string(64,'e'));f.server.configure_ability_tags(f.target,tags);auto dodge=std::make_shared<AbilityDefinition>(*f.ability);auto timeline=std::make_shared<ActionDefinition>(*f.action);timeline->blocks.push_back({2,1,0,2*action_tick_units,ActionBlockKind::Invulnerability,"Dodge"});dodge->action=timeline;dodge->melee.clear();dodge->tag_registry=tags->registry();dodge->tag_generation=tags->generation();dodge->action_tags={{2,1}};f.server.equip_combat_kit(f.target,f.kit,f.input,std::array<std::shared_ptr<const AbilityDefinition>,1>{dodge});f.activate(f.target,1);f.activate(f.source,1);f.step();auto guarded=f.resolve();check(guarded.size()==1&&guarded[0].applied==0&&f.health()==100,"Authoritative Jolt melee formula observes current action invulnerability");f.server.cancel_ability(*f.server.ability_snapshot(f.target).active);f.server.cancel_ability(*f.server.ability_snapshot(f.source).active);f.activate(f.source,2);f.step();auto unguarded=f.resolve();check(unguarded.size()==1&&unguarded[0].applied==30&&f.health()==70,"Action cancellation removes invulnerability before next achieved-pose hit");
}
}
int main(){try{phases();hits();rollback();walls();death();active_death();cancel_pending();authority();action_invulnerability();replication();check(trace(30)==trace(60)&&trace(60)==trace(144),"Damage traces match at 30/60/144 render schedules");std::cout<<"Authoritative melee queries, blockers, bounded atomic damage, repeat identity, crossed windows and death cleanup passed\n";return 0;}catch(const std::exception& e){std::cerr<<e.what()<<'\n';return 1;}}
