#include <darkangel/assets.hpp>
#include <darkangel/effect_assets.hpp>
#include <darkangel/hash.hpp>
#include <nlohmann/json.hpp>
#include <fstream>
#include <iostream>
using namespace darkangel;
namespace {void check(bool value,const char* message){if(!value)throw std::runtime_error(message);}template<class F>void rejects(F f){bool failed=false;try{f();}catch(const std::exception&){failed=true;}check(failed,"Expected native source edit rejection");}std::string read(const std::filesystem::path& p){std::ifstream file(p,std::ios::binary);return {std::istreambuf_iterator<char>(file),{}};}}
int main(){try{
 auto root=std::filesystem::path(DAE_BINARY_DIR)/("native-edit-"+AssetId::random().text()),sources=root/"sources",content=std::filesystem::path(DAE_SOURCE_DIR)/"content/royal_district/combat";std::filesystem::create_directories(sources);std::filesystem::copy_file(content/"base.daattributes",sources/"base.daattributes");std::filesystem::copy_file(content/"state.datags",sources/"state.datags");auto data=nlohmann::json::parse(read(content/"burn.daeffect"));data["sources"]={{"attributes","base.daattributes"},{"tags","state.datags"}};auto original=data.dump(2);std::ofstream(sources/"burn.daeffect",std::ios::binary)<<original;auto id=AssetId::parse(data.at("asset").get<std::string>());
 AssetService assets(sources,root/"cache");auto first=assets.cook("burn.daeffect");assets.package(id,root/"before.json");auto pinned=load_cooked_effect(root/"before.json",assets.cas_path(),id);check(!assets.edit_native("burn.daeffect",sha256(original),original).changed,"Identical edit preserves warm generation");
 data["duration_ticks"]=120;auto edited=data.dump(2);auto changed=assets.edit_native("burn.daeffect",sha256(original),edited);check(changed.changed&&changed.generation==first.generation+1&&read(sources/"burn.daeffect")==edited,"Validated edit publishes source and cooked generation");assets.package(id,root/"after.json");auto current=load_cooked_effect(root/"after.json",assets.cas_path(),id);check(current.definition->duration_ticks==120&&pinned.definition->duration_ticks==180&&current.definition->generation!=pinned.definition->generation,"Previous playable lease stays immutable");
 rejects([&]{assets.edit_native("burn.daeffect",sha256(original),original);});check(read(sources/"burn.daeffect")==edited,"Stale writer cannot overwrite newer source");auto invalid=data;invalid["asset"]=AssetId::random().text();rejects([&]{assets.edit_native("burn.daeffect",sha256(edited),invalid.dump());});invalid=data;invalid["duration_ticks"]=0;rejects([&]{assets.edit_native("burn.daeffect",sha256(edited),invalid.dump());});check(read(sources/"burn.daeffect")==edited,"Failed native policy validation restores exact source bytes");assets.package(id,root/"failure.json");check(load_cooked_effect(root/"failure.json",assets.cas_path(),id).definition->generation==current.definition->generation,"Failed edit preserves last published cooked head");rejects([&]{assets.edit_native("burn.daeffect",sha256(edited),"{}");});rejects([&]{assets.edit_native("../burn.daeffect",sha256(edited),edited);});
 auto created=data;created["asset"]=AssetId::random().text();auto fresh=assets.create_native("new.daeffect",created.dump());check(fresh.root.text()==created["asset"].get<std::string>()&&fresh.changed,"Native creation validates a fresh identity");rejects([&]{assets.create_native("new.daeffect",created.dump());});rejects([&]{assets.create_native("duplicate.daeffect",created.dump());});created["asset"]=AssetId::random().text();created["duration_ticks"]=0;rejects([&]{assets.create_native("invalid.daeffect",created.dump());});check(!std::filesystem::exists(sources/"invalid.daeffect"),"Invalid creation rolls back owned source and inventory");rejects([&]{assets.create_native("../escape.daeffect",created.dump());});
 // The coordinated API also works without animation, and prepares privately.
 auto current_bytes=read(sources/"burn.daeffect"),new_bytes=read(sources/"new.daeffect");auto valid=data;valid["duration_ticks"]=125;auto invalid_second=nlohmann::json::parse(new_bytes);invalid_second["duration_ticks"]=0;std::vector<NativeSourceEdit> set{{"burn.daeffect",sha256(current_bytes),valid.dump()},{"new.daeffect",sha256(new_bytes),invalid_second.dump()}};rejects([&]{assets.prepare_native(set);});check(read(sources/"burn.daeffect")==current_bytes&&read(sources/"new.daeffect")==new_bytes,"Coordinated invalid candidate preserves every source");
 auto changed_identity=valid;changed_identity["asset"]=AssetId::random().text();NativeSourceEdit identity_edit{"burn.daeffect",sha256(current_bytes),changed_identity.dump()};rejects([&]{assets.prepare_native({&identity_edit,1});});
 NativeSourceEdit path_edit{"../escape.daeffect",sha256(current_bytes),valid.dump()};rejects([&]{assets.prepare_native({&path_edit,1});});
 invalid_second["duration_ticks"]=125;set[1].draft=invalid_second.dump();auto prepared=assets.prepare_native(set);check(read(sources/"burn.daeffect")==current_bytes,"Prepared set is invisible");auto coordinated=assets.commit_native(prepared);check(coordinated.size()==2&&read(sources/"burn.daeffect")==valid.dump(),"Coordinated source/cook publication works without animation");rejects([&]{assets.commit_native(prepared);});
 set[0].expected_sha256=sha256(valid.dump());set[1].expected_sha256=sha256(invalid_second.dump());auto warm=assets.prepare_native(set);for(auto result:assets.commit_native(warm))check(!result.changed,"Unchanged coordinated cook keeps generation");
 auto stale=assets.prepare_native(set);auto external_edit=valid;external_edit["duration_ticks"]=126;std::ofstream(sources/"burn.daeffect",std::ios::binary)<<external_edit.dump();rejects([&]{assets.commit_native(stale);});check(read(sources/"burn.daeffect")==external_edit.dump(),"Prepared stale writer preserves external changes");
 std::ofstream(sources/"external.glb")<<"external-original";rejects([&]{assets.edit_native("external.glb",sha256("external-original"),edited);});check(read(sources/"external.glb")=="external-original","External interchange files cannot enter native edit path");
 std::cout<<"Native source editing: optimistic hash, UUID/type/schema preservation, native cook rollback, coordinated candidates/stale writer and immutable generations passed\n";return 0;
}catch(const std::exception& error){std::cerr<<error.what()<<'\n';return 1;}}
