#include <darkangel/assets.hpp>
#include <darkangel/effect_assets.hpp>
#include <darkangel/hash.hpp>
#include <nlohmann/json.hpp>
#include <fstream>
#include <iostream>
#include <sqlite3.h>
#include <algorithm>
using namespace darkangel;
namespace {void check(bool value,const char* message){if(!value)throw std::runtime_error(message);}template<class F>void rejects(F f){bool failed=false;try{f();}catch(const std::exception&){failed=true;}check(failed,"Expected native source edit rejection");}std::string read(const std::filesystem::path& p){std::ifstream file(p,std::ios::binary);return {std::istreambuf_iterator<char>(file),{}};}}
int main(){try{
 auto root=std::filesystem::path(DAE_BINARY_DIR)/("native-edit-"+AssetId::random().text()),sources=root/"sources",content=std::filesystem::path(DAE_SOURCE_DIR)/"content/royal_district/combat";std::filesystem::create_directories(sources);std::filesystem::copy_file(content/"base.daattributes",sources/"base.daattributes");std::filesystem::copy_file(content/"state.datags",sources/"state.datags");auto data=nlohmann::json::parse(read(content/"burn.daeffect"));data["sources"]={{"attributes","base.daattributes"},{"tags","state.datags"}};auto original=data.dump(2);std::ofstream(sources/"burn.daeffect",std::ios::binary)<<original;auto id=AssetId::parse(data.at("asset").get<std::string>());
 AssetService assets(sources,root/"cache");auto first=assets.cook("burn.daeffect");assets.package(id,root/"before.json");auto pinned=load_cooked_effect(root/"before.json",assets.cas_path(),id);check(!assets.edit_native("burn.daeffect",sha256(original),original).changed,"Identical edit preserves warm generation");
 data["duration_ticks"]=120;auto edited=data.dump(2);auto changed=assets.edit_native("burn.daeffect",sha256(original),edited);check(changed.changed&&changed.generation==first.generation+1&&read(sources/"burn.daeffect")==edited,"Validated edit publishes source and cooked generation");assets.package(id,root/"after.json");auto current=load_cooked_effect(root/"after.json",assets.cas_path(),id);check(current.definition->duration_ticks==120&&pinned.definition->duration_ticks==180&&current.definition->generation!=pinned.definition->generation,"Previous playable lease stays immutable");
 rejects([&]{assets.edit_native("burn.daeffect",sha256(original),original);});check(read(sources/"burn.daeffect")==edited,"Stale writer cannot overwrite newer source");auto invalid=data;invalid["asset"]=AssetId::random().text();rejects([&]{assets.edit_native("burn.daeffect",sha256(edited),invalid.dump());});invalid=data;invalid["duration_ticks"]=0;rejects([&]{assets.edit_native("burn.daeffect",sha256(edited),invalid.dump());});check(read(sources/"burn.daeffect")==edited,"Failed native policy validation restores exact source bytes");assets.package(id,root/"failure.json");check(load_cooked_effect(root/"failure.json",assets.cas_path(),id).definition->generation==current.definition->generation,"Failed edit preserves last published cooked head");rejects([&]{assets.edit_native("burn.daeffect",sha256(edited),"{}");});rejects([&]{assets.edit_native("../burn.daeffect",sha256(edited),edited);});
 auto created=data;created["asset"]=AssetId::random().text();auto fresh=assets.create_native("new.daeffect",created.dump());check(fresh.root.text()==created["asset"].get<std::string>()&&fresh.changed,"Native creation validates a fresh identity");rejects([&]{assets.create_native("new.daeffect",created.dump());});rejects([&]{assets.create_native("duplicate.daeffect",created.dump());});created["asset"]=AssetId::random().text();created["duration_ticks"]=0;rejects([&]{assets.create_native("invalid.daeffect",created.dump());});check(!std::filesystem::exists(sources/"invalid.daeffect"),"Invalid creation rolls back owned source and inventory");rejects([&]{assets.create_native("../escape.daeffect",created.dump());});
 // The coordinated API also works without animation, and prepares privately.
 auto current_bytes=read(sources/"burn.daeffect"),new_bytes=read(sources/"new.daeffect");auto valid=data;valid["duration_ticks"]=125;auto invalid_second=nlohmann::json::parse(new_bytes);invalid_second["duration_ticks"]=0;std::vector<NativeSourceEdit> set{{"burn.daeffect",sha256(current_bytes),valid.dump()},{"new.daeffect",sha256(new_bytes),invalid_second.dump()}};rejects([&]{assets.prepare_native(set);});check(read(sources/"burn.daeffect")==current_bytes&&read(sources/"new.daeffect")==new_bytes,"Coordinated invalid candidate preserves every source");
 auto changed_identity=valid;changed_identity["asset"]=AssetId::random().text();NativeSourceEdit identity_edit{"burn.daeffect",sha256(current_bytes),changed_identity.dump()};rejects([&]{assets.prepare_native({&identity_edit,1});});
 NativeSourceEdit path_edit{"../escape.daeffect",sha256(current_bytes),valid.dump()};rejects([&]{assets.prepare_native({&path_edit,1});});
 invalid_second["duration_ticks"]=125;set[1].draft=invalid_second.dump();auto prepared=assets.prepare_native(set);check(read(sources/"burn.daeffect")==current_bytes,"Prepared set is invisible");auto coordinated=assets.commit_native(prepared);check(coordinated.size()==2&&read(sources/"burn.daeffect")==valid.dump(),"Coordinated source/cook publication works without animation");rejects([&]{assets.commit_native(prepared);});
 set[0].expected_sha256=sha256(valid.dump());set[1].expected_sha256=sha256(invalid_second.dump());auto warm=assets.prepare_native(set);for(auto result:assets.commit_native(warm))check(!result.changed,"Unchanged coordinated cook keeps generation");
 auto stale=assets.prepare_native(set);auto external_edit=valid;external_edit["duration_ticks"]=126;std::ofstream(sources/"burn.daeffect",std::ios::binary)<<external_edit.dump();rejects([&]{assets.commit_native(stale);});check(read(sources/"burn.daeffect")==external_edit.dump(),"Prepared stale writer preserves external changes");

 auto creation=data;auto creation_id=AssetId::random();creation["asset"]=creation_id.text();creation["duration_ticks"]=128;auto old_source=read(sources/"burn.daeffect");auto existing=nlohmann::json::parse(old_source);existing["duration_ticks"]=127;std::vector<NativeSourceEdit> mixed{{"burn.daeffect",sha256(old_source),existing.dump()},{"coordinated/new_status.daeffect","",creation.dump(),true}};assets.package(id,root/"creation-before.json");auto old_package=read(root/"creation-before.json");auto private_creation=assets.prepare_native(mixed);check(!std::filesystem::exists(sources/"coordinated/new_status.daeffect")&&read(sources/"burn.daeffect")==old_source,"Creation preparation modified real source mount");check(load_cooked_effect(private_creation.registry(),assets.cas_path(),creation_id).definition->duration_ticks==128,"Private new source lacks valid cooked effect");auto before_inventory=assets.assets();check(std::none_of(before_inventory.begin(),before_inventory.end(),[&](const auto& asset){return asset.id==creation_id;}),"Preparation registered unpublished asset");
 sqlite3* db{};check(sqlite3_open((root/"cache/catalog.sqlite").string().c_str(),&db)==SQLITE_OK,"Open creation failure fixture");check(sqlite3_exec(db,"CREATE TRIGGER reject_creation BEFORE INSERT ON generations BEGIN SELECT RAISE(ABORT,'creation fault'); END",nullptr,nullptr,nullptr)==SQLITE_OK,"Install creation publication fault");rejects([&]{assets.commit_native(private_creation);});check(!std::filesystem::exists(sources/"coordinated/new_status.daeffect")&&read(sources/"burn.daeffect")==old_source,"Failed mixed creation did not restore source existence/bytes");assets.package(id,root/"creation-failed.json");check(read(root/"creation-failed.json")==old_package,"Failed creation replaced previous playable generation");auto failed_inventory=assets.assets();check(std::none_of(failed_inventory.begin(),failed_inventory.end(),[&](const auto& asset){return asset.id==creation_id;}),"Failed creation left catalog identity");check(sqlite3_exec(db,"DROP TRIGGER reject_creation",nullptr,nullptr,nullptr)==SQLITE_OK,"Remove creation fault");sqlite3_close(db);
 auto published=assets.commit_native(private_creation);check(published.size()==2&&read(sources/"coordinated/new_status.daeffect")==creation.dump()&&read(sources/"burn.daeffect")==existing.dump(),"Mixed creation retry failed publication");auto registered=assets.assets();check(std::any_of(registered.begin(),registered.end(),[&](const auto& asset){return asset.id==creation_id&&asset.path=="coordinated/new_status.daeffect"&&asset.generation==1;}),"Committed creation missing authoritative catalog registration");assets.package(creation_id,root/"creation.json");check(load_cooked_effect(root/"creation.json",assets.cas_path(),creation_id).definition->duration_ticks==128&&pinned.definition->duration_ticks==180,"Creation changed frozen previous lease");rejects([&]{assets.commit_native(private_creation);});NativeSourceEdit occupied{"coordinated/new_status.daeffect","",creation.dump(),true};rejects([&]{assets.prepare_native({&occupied,1});});auto duplicate=creation;duplicate["asset"]=id.text();NativeSourceEdit duplicate_create{"coordinated/duplicate.daeffect","",duplicate.dump(),true};rejects([&]{assets.prepare_native({&duplicate_create,1});});auto invalid_create=creation;invalid_create["asset"]=AssetId::random().text();invalid_create["duration_ticks"]=0;NativeSourceEdit invalid_new{"coordinated/invalid.daeffect","",invalid_create.dump(),true};rejects([&]{assets.prepare_native({&invalid_new,1});});check(!std::filesystem::exists(sources/"coordinated/invalid.daeffect"),"Invalid new source was published");auto conflict=creation;conflict["asset"]=AssetId::random().text();NativeSourceEdit collision{"coordinated/collision.daeffect","",conflict.dump(),true};auto conflict_candidate=assets.prepare_native({&collision,1});std::ofstream(sources/"coordinated/collision.daeffect")<<"external-work";rejects([&]{assets.commit_native(conflict_candidate);});check(read(sources/"coordinated/collision.daeffect")=="external-work","Creation overwrote concurrent external file");std::filesystem::remove(sources/"coordinated/collision.daeffect");std::cout<<"Prepared new sources: private cook, mixed catalog-fault rollback/deletion/retry, atomic catalog identity, frozen leases, UUID/path/type validation and external creation conflicts passed\n";

 auto new_attributes=nlohmann::json::parse(read(sources/"base.daattributes"));auto attribute_id=AssetId::random();new_attributes["asset"]=attribute_id.text();auto linked=creation;auto linked_id=AssetId::random();linked["asset"]=linked_id.text();linked["attributes"]=attribute_id.text();linked["sources"]["attributes"]="coordinated/new_base.daattributes";std::vector<NativeSourceEdit> linked_creates{{"coordinated/new_base.daattributes","",new_attributes.dump(),true},{"coordinated/linked.daeffect","",linked.dump(),true}};auto linked_candidate=assets.prepare_native(linked_creates);check(!std::filesystem::exists(sources/"coordinated/new_base.daattributes")&&!std::filesystem::exists(sources/"coordinated/linked.daeffect"),"Linked creation exposed a partial source closure");auto linked_frozen=load_cooked_effect(linked_candidate.registry(),assets.cas_path(),linked_id);check(linked_frozen.attributes.id==attribute_id,"New source did not resolve another staged source");check(assets.commit_native(linked_candidate).size()==2,"Linked creation did not publish both roots");assets.package(linked_id,root/"linked.json");check(load_cooked_effect(root/"linked.json",assets.cas_path(),linked_id).attributes.id==attribute_id,"Published linked creation lost frozen dependency");auto malformed_flag=linked_creates[0];malformed_flag.path="coordinated/hash_flag.daattributes";malformed_flag.expected_sha256=std::string(64,'0');rejects([&]{assets.prepare_native({&malformed_flag,1});});auto wrong_type=linked_creates[0];wrong_type.path="coordinated/wrong.daeffect";rejects([&]{assets.prepare_native({&wrong_type,1});});auto escaping=linked_creates[0];escaping.path="../escape.daattributes";rejects([&]{assets.prepare_native({&escaping,1});});std::cout<<"Linked staged creation resolves new attribute/effect references before publication and preserves typed/frozen closure; flag/type/path fences passed\n";
 std::ofstream(sources/"external.glb")<<"external-original";rejects([&]{assets.edit_native("external.glb",sha256("external-original"),edited);});check(read(sources/"external.glb")=="external-original","External interchange files cannot enter native edit path");
 std::cout<<"Native source editing: optimistic hash, UUID/type/schema preservation, native cook rollback, coordinated candidates/stale writer and immutable generations passed\n";return 0;
}catch(const std::exception& error){std::cerr<<error.what()<<'\n';return 1;}}
