#include "../apps/editor/native_authoring.hpp"
#include "../apps/editor/character_preview.hpp"
#include <darkangel/editor_document.hpp>
#include <darkangel/hash.hpp>
#include <fstream>
#include <iostream>
#include <set>
using namespace darkangel;using namespace darkangel::editor_app;using Json=nlohmann::json;
namespace {void check(bool v,const char* m){if(!v)throw std::runtime_error(m);}template<class F>void rejects(F f){bool failed=false;try{f();}catch(const std::exception&){failed=true;}check(failed,"Expected checked authoring rejection");}std::string read(const std::filesystem::path& p){std::ifstream f(p,std::ios::binary);return {std::istreambuf_iterator<char>(f),{}};}}
int main(){try{
 auto root=std::filesystem::path(DAE_BINARY_DIR)/("authoring-fixture-"+AssetId::random().text()),source=root/"sources",content=std::filesystem::path(DAE_SOURCE_DIR)/"content";check(!std::filesystem::exists(source),"Use a fresh authoring-fixture directory");std::filesystem::create_directories(source);std::filesystem::copy(content,source,std::filesystem::copy_options::recursive);AssetService assets(source,root/"cache");assets.scan();NativeAuthoring author;
 auto id=[&](const char* file){return AssetId::parse(Json::parse(read(source/file))["asset"].get<std::string>());};auto kit=id("royal_district/combat/player.dakit"),heavy=id("royal_district/combat/heavy.daability"),burn=id("royal_district/combat/burn.daeffect"),collision=id("royal_district/collision/environment.dacollision");auto scene=EditorDocument::open(source/"royal_district/RoyalCombat.dascene");auto baseline=scene->world().serialize();auto role=[&](unsigned i){for(const auto& o:scene->plan().origins)if(o.local_path.ends_with("/"+StableId{0,i}.text()))return o.object;throw std::runtime_error("Missing scene role");};std::set<AssetId> rootset{kit,collision};for(auto [o,a]:scene->plan().models)rootset.insert(a);std::vector<AssetId> roots(rootset.begin(),rootset.end());package_authoring(assets,roots,root/"before.json");auto human=AssetId::parse(Json::parse(read(source/"royal_district/character/canonical-human.glb.daimport"))["id"].get<std::string>());auto skin=load_cooked_skinned_model(root/"before.json",assets.cas_path(),human);auto old=load_character_preview(root/"before.json",assets.cas_path(),"kit:"+kit.text(),skin,role(4),role(5),collision);
 auto copy=author.duplicate(assets,heavy,"authored_heavy"),effect=author.duplicate(assets,burn,"authored_burn");check(copy!=heavy&&effect!=burn,"Duplicates have fresh persistent identities");auto blank_ability=author.duplicate(assets,heavy,"new_ability",true);check(author.open(assets,blank_ability).value["costs"].empty(),"Create ability starts with configurable empty costs");auto blank=author.duplicate(assets,burn,"new_status",true);check(author.open(assets,blank).value["evaluator"]==0,"Create supports status without a custom execution formula");rejects([&]{author.duplicate(assets,heavy,"authored_heavy");});rejects([&]{author.duplicate(assets,heavy,"../escape");});
 auto& a=author.open(assets,copy).value;a["costs"][0]["amount"]=20;a["melee"][0]["power"]=40;auto& e=author.open(assets,effect).value;e["duration_ticks"]=120;e["period_ticks"]=30;author.assign(assets,kit,1,copy);author.bind(assets,kit,copy,2,effect,7);check(author.dirty(),"Drafts remain separate from playable generations");author.save_all(assets);check(!author.dirty(),"Save persists native source drafts");package_authoring(assets,roots,root/"after.json");auto fresh=load_character_preview(root/"after.json",assets.cas_path(),"kit:"+kit.text(),skin,role(4),role(5),collision);check(old.combat->kit->generation!=fresh.combat->kit->generation,"Dependent kit must get a fresh frozen closure");check(old.combat->abilities[1]->costs[0].amount==30,"Old playable resources stay immutable");
 auto run=[&](const char* registry,const CharacterPreviewResources& resources,double initial,double later,double cost){auto prepared=prepare_character_preview(scene->plan(),scene->world(),resources,[&](AssetId asset){return load_cooked_model(root/registry,assets.cas_path(),asset);});CharacterSceneInput press;press.combat_events={{9,InputEdge::Pressed,1000,0,1,false}};prepared.second->step(press);while(prepared.second->motor().tick<30)prepared.second->step({});auto& s=*prepared.second;check(s.presentation().read(s.presentation().find(role(5))).health.current==initial,"Fresh authored hit damage is visible on remote presentation");check(s.effects(role(5))->cues().size()==1,"Public effect status is synchronized");auto tags=s.observer(role(5),30).frame.ability.tags;check(std::find(tags.values.begin(),tags.values.end(),3)!=tags.values.end(),"Observer receives authored Burn tag");double stamina=-1;for(auto attr:s.ability()->attributes)if(attr.id==3)stamina=attr.value;check(stamina==100-cost,"Authoritative authored cost is confirmed");while(s.motor().tick<150)s.step({});check(s.presentation().read(s.presentation().find(role(5))).health.current==later&&s.pending_prediction()==0&&s.pending_abilities()==0,"Periodic damage converges over existing WorldSession");return std::move(prepared.second);};
 auto prior=run("before.json",old,65,55,30);auto current=run("after.json",fresh,60,39,20);check(current->effects(role(5))->cues().empty()&&prior->effects(role(5))->cues().size()==1,"Fresh duration differs without patching old session");check(scene->world().serialize()==baseline,"Full authoring loop preserves scene authoring world");
 auto saved=author.open(assets,effect).saved;author.open(assets,effect).value["duration_ticks"]=0;rejects([&]{author.save(assets,effect);});check(read(source/author.open(assets,effect).asset.path)==saved,"Invalid draft rolls back exact source");author.open(assets,effect).value=Json::parse(saved);auto bytes=read(root/"after.json");auto invalid=author.open(assets,kit).value;invalid["sources"]["abilities"][copy.text()]="missing.daability";rejects([&]{assets.edit_native(author.open(assets,kit).asset.path,sha256(author.open(assets,kit).saved),invalid.dump());});check(read(root/"after.json")==bytes,"Failed dependency cannot replace playable package");
 auto duplicate_id=Json::parse(saved);rejects([&]{assets.create_native("collision.daeffect",duplicate_id.dump());});duplicate_id["asset"]=AssetId::random().text();duplicate_id["duration_ticks"]=0;rejects([&]{assets.create_native("invalid.daeffect",duplicate_id.dump());});check(!std::filesystem::exists(source/"invalid.daeffect"),"Invalid creation leaves no broken owned source");
 Json receipt={{"source",source.generic_string()},{"cache",(root/"cache").generic_string()},{"registry",(root/"after.json").generic_string()},{"kit",kit.text()},{"ability",copy.text()},{"effect",effect.text()}};std::ofstream(std::filesystem::path(DAE_BINARY_DIR)/"authoring-fixture.json")<<receipt.dump(2);std::cout<<"Native authoring: create/duplicate, cost20/damage40/Burn7, kit closure, fresh Play Health60->39, Stamina80, public status/expiry, immutable prior Play and failed candidate preservation passed\n";return 0;
}catch(const std::exception& e){std::cerr<<e.what()<<'\n';return 1;}}
