#include <darkangel/assets.hpp>
#include <darkangel/effect_assets.hpp>
#include <darkangel/hash.hpp>
#include <nlohmann/json.hpp>
#include <fstream>
#include <iostream>
using namespace darkangel;
namespace {void check(bool value,const char* message){if(!value)throw std::runtime_error(message);}template<class F>void rejects(F f){bool failed=false;try{f();}catch(const std::exception&){failed=true;}check(failed,"Expected native source edit rejection");}std::string read(const std::filesystem::path& p){std::ifstream file(p,std::ios::binary);return {std::istreambuf_iterator<char>(file),{}};}}
int main(){try{
 auto root=std::filesystem::path(DAE_BINARY_DIR)/("native-edit-"+AssetId::random().text()),sources=root/"sources",content=std::filesystem::path(DAE_SOURCE_DIR)/"content/royal_district/combat";std::filesystem::create_directories(sources);std::filesystem::copy_file(content/"base.daattributes",sources/"base.daattributes");std::filesystem::copy_file(content/"state.datags",sources/"state.datags");auto data=nlohmann::json::parse(read(content/"burn.daeffect"));data["sources"]={{"attributes","base.daattributes"},{"tags","state.datags"}};auto original=data.dump(2);std::ofstream(sources/"burn.daeffect",std::ios::binary)<<original;auto id=AssetId::parse(data.at("asset").get<std::string>());
 AssetService assets(sources,root/"cache");auto first=assets.cook("burn.daeffect");assets.package(id,root/"before.json");auto pinned=load_cooked_effect(root/"before.json",assets.cas_path(),id);check(!assets.edit_native("burn.daeffect",sha256(original),original).changed,"Identical edit preserves warm generation");
 data["duration_ticks"]=120;auto edited=data.dump(2);auto changed=assets.edit_native("burn.daeffect",sha256(original),edited);check(changed.changed&&changed.generation==first.generation+1&&read(sources/"burn.daeffect")==edited,"Validated edit publishes source and cooked generation");assets.package(id,root/"after.json");auto current=load_cooked_effect(root/"after.json",assets.cas_path(),id);check(current.definition->duration_ticks==120&&pinned.definition->duration_ticks==180&&current.definition->generation!=pinned.definition->generation,"Previous playable lease stays immutable");
 rejects([&]{assets.edit_native("burn.daeffect",sha256(original),original);});check(read(sources/"burn.daeffect")==edited,"Stale writer cannot overwrite newer source");auto invalid=data;invalid["asset"]=AssetId::random().text();rejects([&]{assets.edit_native("burn.daeffect",sha256(edited),invalid.dump());});invalid=data;invalid["duration_ticks"]=0;rejects([&]{assets.edit_native("burn.daeffect",sha256(edited),invalid.dump());});check(read(sources/"burn.daeffect")==edited,"Failed native policy validation restores exact source bytes");assets.package(id,root/"failure.json");check(load_cooked_effect(root/"failure.json",assets.cas_path(),id).definition->generation==current.definition->generation,"Failed edit preserves last published cooked head");rejects([&]{assets.edit_native("burn.daeffect",sha256(edited),"{}");});rejects([&]{assets.edit_native("../burn.daeffect",sha256(edited),edited);});std::ofstream(sources/"external.glb")<<"external-original";rejects([&]{assets.edit_native("external.glb",sha256("external-original"),edited);});check(read(sources/"external.glb")=="external-original","External interchange files cannot enter native edit path");
 std::cout<<"Native source editing: optimistic hash, UUID/type/schema preservation, native cook rollback and immutable generations passed\n";return 0;
}catch(const std::exception& error){std::cerr<<error.what()<<'\n';return 1;}}
