#include <darkangel/model_collision.hpp>
#include <darkangel/editor_document.hpp>
#include <darkangel/combat_kit_assets.hpp>
#include "../apps/editor/character_preview.hpp"
#include <nlohmann/json.hpp>
#include <fstream>
#include <iostream>
#include <cmath>
using namespace darkangel;
namespace {
void check(bool b,const char* error){if(!b)throw std::runtime_error(error);}
template<class F>void rejects(F f){bool failed=false;try{f();}catch(const std::exception&){failed=true;}check(failed,"Expected checked mesh preparation failure");}
std::string read(const std::filesystem::path& path){std::ifstream file(path,std::ios::binary);return {std::istreambuf_iterator<char>(file),{}};}
MotorVec sub(MotorVec a,MotorVec b){return {a.x-b.x,a.y-b.y,a.z-b.z};}MotorVec cross(MotorVec a,MotorVec b){return {a.y*b.z-a.z*b.y,a.z*b.x-a.x*b.z,a.x*b.y-a.y*b.x};}double dot(MotorVec a,MotorVec b){return a.x*b.x+a.y*b.y+a.z*b.z;}
std::pair<double,std::uint64_t> reference(const CollisionDefinition& scene,MotorVec origin,MotorVec direction){std::pair<double,std::uint64_t> closest{2,0};for(const auto& mesh:scene.meshes)for(const auto& triangle:mesh.data->triangles){auto a=mesh.data->vertices[triangle.vertices[0]],b=mesh.data->vertices[triangle.vertices[1]],c=mesh.data->vertices[triangle.vertices[2]];auto e=sub(b,a),f=sub(c,a),p=cross(direction,f);auto determinant=dot(e,p);if(std::abs(determinant)<1e-9)continue;auto q=sub(origin,a);auto u=dot(q,p)/determinant;auto r=cross(q,e);auto v=dot(direction,r)/determinant,t=dot(f,r)/determinant;if(u>=0&&u<=1&&v>=0&&u+v<=1&&t>=0&&t<=1&&t<closest.first)closest={t,mesh.id};}return closest;}
void unit(){RuntimeModel model;model.id=AssetId::random();CookedMesh mesh;auto material=AssetId::random();mesh.vertices={{{1,0,0},{0,1,0},{}},{{0,1,0},{0,1,0},{}},{{0,0,1},{0,1,0},{}},{{1,0,0},{1,0,0},{}}};mesh.indices={0,1,2,3,1,2,0,0,1};mesh.parts={{material,0,9}};model.meshes.push_back(mesh);Transform pose;pose.x=10;pose.y=5;pose.z=20;pose.scale=2;pose.yaw=3.141592653589793/2;auto runtime=AssetId::random();auto baked=bake_model_collision(model,pose,runtime);check(baked.data->vertices.size()==3&&baked.data->triangles.size()==1&&baked.duplicate_faces==1&&baked.degenerate_faces==1,"Native model conversion welds geometric seams and filters only invalid/redundant faces");auto p=baked.data->vertices[0];check(std::abs(p.x-10)<1e-5&&std::abs(p.y-5)<1e-5&&std::abs(p.z-18)<1e-5,"Native collision uses renderer scale/yaw/translation and original pivot");model.meshes[0].vertices[0].position[0]=100;check(baked.data->vertices[0]==p,"Bake owns immutable geometry independent of source alias");
    CollisionDefinition source;source.id=AssetId::random();source.schema=3;source.meshes={{1,baked.data}};auto encoded=encode_collision_source(source);check(decode_collision_source(encoded).meshes[0].data->signature==baked.data->signature,"Canonical native collision source roundtrip");auto root=std::filesystem::path(DAE_BINARY_DIR)/("model-collision-"+AssetId::random().text());auto file=root/"sources/triangle.dacollision";publish_collision_source(file,encoded);publish_collision_source(file,encoded);check(read(file)==encoded,"No-change native publication preserves complete source bytes");rejects([&]{publish_collision_source(file,"{}");});check(read(file)==encoded,"Failed source validation preserves previously published geometry");
    {AssetService assets(root/"sources",root/"cache");assets.cook("triangle.dacollision");assets.package(source.id,root/"registry.json");}std::filesystem::rename(root/"sources",root/"offline");auto loaded=load_cooked_collision_scene(root/"registry.json",root/"cache/cas",source.id);check(loaded.meshes[0].data->signature==baked.data->signature,"Native collision loads from verified CAS without sources");
}
MotorState run(const CollisionDefinition& scene,MotorVec start,unsigned ticks,double x,double z){PhysicsWorld world;world.load_scene(scene);CharacterMotor motor(world,start,10);for(unsigned i=0;i<ticks;++i){auto tick=world.tick()+1;motor.step({tick,tick,1,x,z});world.step();motor.post_physics();world.finish_tick();}return motor.state();}
void royal(){auto project=std::filesystem::path(DAE_SOURCE_DIR)/"content",cache=std::filesystem::path(DAE_BINARY_DIR)/("royal-collision-"+AssetId::random().text());auto document=EditorDocument::open(project/"royal_district/RoyalCombat.dascene");auto original=document->world().serialize();auto source=decode_collision_source(read(project/"royal_district/collision/environment.dacollision"));check(source.boxes.empty()&&source.meshes.size()==3,"Royal has explicit native ground and two hut meshes");
    AssetService assets(project,cache);auto ground=assets.cook("royal_district/static/terrain/SM_RC_Terrain_Ground_32x32.gltf").root;std::vector<std::filesystem::path> huts;for(const auto& file:std::filesystem::directory_iterator(project/"royal_district/static/mud_huts"))if(file.path().extension()==".gltf")huts.push_back(file.path());std::sort(huts.begin(),huts.end());std::vector<AssetId> roots;for(unsigned i=0;i<2;++i)roots.push_back(assets.cook(huts[i].lexically_relative(project).generic_string()).root);auto human=assets.cook("royal_district/character/canonical-human.glb").root,kit=assets.cook("royal_district/combat/player.dakit").root;assets.cook("royal_district/collision/environment.dacollision");roots.push_back(human);roots.push_back(kit);roots.push_back(source.id);assets.package(ground,cache/"registry.json",roots);auto collision=load_cooked_collision_scene(cache/"registry.json",assets.cas_path(),source.id);check(collision.meshes[0].data->signature==source.meshes[0].data->signature,"Collision closure composes with model/kit registry under verified references");
    PhysicsWorld world;world.load_scene(collision);QueryFilter filter;filter.backfaces=true;for(auto point:std::array<MotorVec,4>{{{.3,5,3.7},{-7.31,12,-4.17},{7.31,15,-4.17},{-10.5,5,-.5}}}){MotorVec direction{0,-20,0};auto expected=reference(collision,point,direction);auto hit=world.query_ray(point,direction,filter);check(expected.second&& !hit.hits.empty()&&hit.hits.front().identity==expected.second&&std::abs(hit.hits.front().fraction-expected.first)<1e-5,"Real Jolt ground/roof queries match independent native triangle reference");}
    auto ground_hit=world.query_ray({.3,2,3.7},{0,-3,0},filter);check(ground_hit.hits.front().normal.y>.99&&world.material_key(ground_hit.hits.front()).starts_with("material."),"Native ground normal and source material identity preserved");
    CollisionDefinition proxy;proxy.id=AssetId::random();proxy.schema=2;for(const auto& mesh:collision.meshes){auto lo=mesh.data->vertices[0],hi=lo;for(auto p:mesh.data->vertices){lo={std::min(lo.x,p.x),std::min(lo.y,p.y),std::min(lo.z,p.z)};hi={std::max(hi.x,p.x),std::max(hi.y,p.y),std::max(hi.z,p.z)};}proxy.boxes.push_back({mesh.id,{(lo.x+hi.x)/2,(lo.y+hi.y)/2,(lo.z+hi.z)/2},{(hi.x-lo.x)/2,(hi.y-lo.y)/2,(hi.z-lo.z)/2}});}
    PhysicsWorld boxes;boxes.load_scene(proxy);check(world.overlap({-10.5,1.5,-.5},.1).hits.empty()&&!boxes.overlap({-10.5,1.5,-.5},.1).hits.empty(),"Precise hut mesh keeps empty bounding corners traversable");auto achieved=run(collision,{-11.5,.5,-.6},90,1,0),blocked=run(proxy,{-11.5,.5,-.6},90,1,0);check(achieved.position.x>-5&&blocked.position.x<-11&&achieved.grounded,"Native motor traverses real clearance previously blocked by the solid proxy");
    auto skin=load_cooked_skinned_model(cache/"registry.json",assets.cas_path(),human);auto role=[&](unsigned index){auto local=StableId{0,index}.text();for(const auto& origin:document->plan().origins)if(origin.local_path.ends_with("/"+local))return origin.object;throw std::runtime_error("Royal scene role missing");};auto resources=editor_app::load_character_preview(cache/"registry.json",assets.cas_path(),"kit:"+kit.text(),skin,role(4),role(5),source.id);auto loader=[&](AssetId id){return load_cooked_model(cache/"registry.json",assets.cas_path(),id);};auto prepared=editor_app::prepare_character_preview(document->plan(),document->world(),resources,loader);CharacterSceneInput pressed;pressed.combat_events={{8,InputEdge::Pressed,1000,0,1,false}};prepared.second->step(pressed);for(unsigned i=1;i<60;++i)prepared.second->step({});check(prepared.second->presentation().read(prepared.second->presentation().find(role(5))).health.current==75&&prepared.second->pending_prediction()==0,"Real packaged Royal mesh supports native attack, damage and isolated owner correction");
    rejects([&]{editor_app::prepare_character_preview(document->plan(),document->world(),resources,[&](AssetId id){auto model=loader(id);model.meshes[0].vertices[0].position[0]+=.1f;return model;});});check(document->world().serialize()==original,"Stale model/collision generation fails before Play and preserves authoring");
    auto other=EditorDocument::open(project/"royal_district/RoyalVillage.dascene");auto graph_id=AssetId::parse(nlohmann::json::parse(read(project/"royal_district/locomotion.dagraph"))["asset"].get<std::string>());auto legacy=editor_app::load_character_preview(cache/"registry.json",assets.cas_path(),"graph:"+graph_id.text(),skin,{}, {},source.id);auto locomotion=editor_app::prepare_character_preview(other->plan(),other->world(),legacy,loader);locomotion.second->step({0,1});check(locomotion.second->motor().position.y>.49,"The original scene resolves the same physical geometry independent of placed-ID order");
    std::cout<<"Royal precise mesh: vertices=";for(const auto& mesh:collision.meshes)std::cout<<mesh.data->vertices.size()<<',';std::cout<<" clearance_x="<<achieved.position.x<<" proxy_x="<<blocked.position.x<<'\n';
}
}
int main(){try{unit();royal();std::cout<<"Normalized model collision source/CAS, renderer transform/pivot, Jolt reference/clearance, native combat and stale binding checks passed\n";return 0;}catch(const std::exception& error){std::cerr<<error.what()<<'\n';return 1;}}
