#include <darkangel/tag_codegen.hpp>
#include <darkangel/assets.hpp>
#include <darkangel/script_package.hpp>
#include <Luau/Compiler.h>
#include <lua.h>
#include <lualib.h>
#include <nlohmann/json.hpp>
#include <fstream>
#include <iostream>
using namespace darkangel;
namespace {void check(bool value,const char* message){if(!value)throw std::runtime_error(message);}template<class F>void rejects(F f){bool rejected=false;try{f();}catch(const std::exception&){rejected=true;}check(rejected,"Expected tag export rejection");}}
int main(){try{
 auto path=std::filesystem::path(DAE_SOURCE_DIR)/"content/royal_district/combat/state.datags";std::ifstream file(path);auto data=nlohmann::json::parse(file);auto source=decode_tag_asset(data.dump());auto generated=generate_tag_constants(source);auto again=generate_tag_constants(source);check(generated.cpp==again.cpp&&generated.luau==again.luau,"Tag exports deterministic");check(generated.cpp.find("Tag_State_Invulnerable_2 = 2u")!=std::string::npos&&generated.luau.find("Tag_Status_Burn_3 = 3")!=std::string::npos,"Native and script constants share runtime IDs");for(const auto& field:source.fields)check(generated.cpp.find(field.key.text())!=std::string::npos&&generated.luau.find(field.key.text())!=std::string::npos,"Persistent keys survive export");
 ScriptPackage package{"game/tags",{{{0xfeed,801},"game/tags",generated.luau,{}}},{}};check(!cook_scripts(package).modules[0].bytecode.empty(),"Generated module passes existing strict Luau analyzer");
 std::unique_ptr<lua_State,decltype(&lua_close)> vm(luaL_newstate(),lua_close);check(bool(vm),"Luau allocation");luaL_openlibs(vm.get());luaL_sandbox(vm.get());auto bytecode=Luau::compile(generated.luau);check(luau_load(vm.get(),"=generated-tags",bytecode.data(),bytecode.size(),0)==0&&lua_pcall(vm.get(),0,1,0)==0,"Generated module executes in sandbox");lua_getfield(vm.get(),-1,"generation");check(std::string(lua_tostring(vm.get(),-1))==source.generation,"Script registry generation fence");lua_pop(vm.get(),1);check(lua_getreadonly(vm.get(),-1),"Registry table frozen");lua_getfield(vm.get(),-1,"ids");check(lua_getreadonly(vm.get(),-1),"ID table frozen");lua_getfield(vm.get(),-1,"Tag_Status_Burn_3");check(lua_tonumber(vm.get(),-1)==3,"Script Burn runtime ID");lua_pop(vm.get(),2);for(bool current:{true,false}){lua_getfield(vm.get(),-1,"matches");lua_pushstring(vm.get(),source.id.text().c_str());lua_pushstring(vm.get(),current?source.generation.c_str():"stale");check(lua_pcall(vm.get(),2,1,0)==0&&bool(lua_toboolean(vm.get(),-1))==current,"Script matching/stale registry fence");lua_pop(vm.get(),1);}lua_getfield(vm.get(),-1,"keys");check(lua_getreadonly(vm.get(),-1),"Persistent key table frozen");
 auto unusual=source;unusual.fields[0].definition.name="end";unusual.fields[1].definition.name="x-y";unusual.fields[2].definition.name="x_y";auto exported=generate_tag_constants(unusual);check(exported.cpp.find("Tag_end_1")!=std::string::npos&&exported.cpp.find("Tag_x_y_2")!=std::string::npos&&exported.cpp.find("Tag_x_y_3")!=std::string::npos,"Keywords and normalized name collisions remain legal distinct constants");package.modules[0].source=exported.luau;cook_scripts(package);
 auto bad=source;bad.fields[0].key={};rejects([&]{generate_tag_constants(bad);});bad=source;bad.fields[0].key=bad.fields[1].key;rejects([&]{generate_tag_constants(bad);});bad=source;bad.generation="bad";rejects([&]{generate_tag_constants(bad);});
 auto root=std::filesystem::path(DAE_BINARY_DIR)/("tag-export-"+AssetId::random().text());auto published=publish_tag_constants(source,root);check(publish_tag_constants(source,root)==published&&std::filesystem::exists(published/"tags.hpp")&&std::filesystem::exists(published/"tags.luau"),"Both exports publish together and warm reuse is stable");std::ofstream(published/"tags.luau",std::ios::binary)<<"broken";rejects([&]{publish_tag_constants(source,root);});check(std::filesystem::file_size(published/"tags.luau")==6,"Conflicting immutable export is preserved");for(const auto& entry:std::filesystem::directory_iterator(published.parent_path()))check(!entry.path().filename().string().starts_with(".tags-"),"Failed export leaves no staging generation");
 std::filesystem::create_directory(root/"sources");std::ofstream(root/"sources/state.datags")<<data.dump();{AssetService service(root/"sources",root/"cache");service.cook("state.datags");service.package(source.id,root/"registry.json");}std::filesystem::rename(root/"sources",root/"offline");auto offline=load_cooked_tags(root/"registry.json",root/"cache/cas",source.id);check(generate_tag_constants(offline).cpp==generated.cpp&&generate_tag_constants(offline).luau==generated.luau,"Source-free registry/CAS reproduces identical constants and fingerprint");
 std::cout<<"Prepared tag constants: deterministic IDs/keys/generation, native export, strict Luau analysis and frozen sandbox tables passed\n";return 0;
}catch(const std::exception& error){std::cerr<<error.what()<<'\n';return 1;}}
