import sys,os
sys.path.insert(0,os.path.dirname(__file__))
from ed import sub
os.chdir(r'C:\DarkAngel')
t='tests/native_authoring_tests.cpp'
sub(t,'''  masking.validate(assets,player,player_roots);check(!std::filesystem::exists(ember_path),"Private mask validation published sources");''',r'''  {
   // Player-owned virtual cameras: free-look default, a tuned aim camera and a tag-driven one.
   auto camera=[](const char* name,unsigned priority,Json when,double distance,double shoulder,const char* facing){return Json{{"name",name},{"priority",priority},{"when",std::move(when)},{"distance",distance},{"height",1.5},{"shoulder",shoulder},{"fov",55.0},{"pitch_min",-40.0},{"pitch_max",60.0},{"blend_seconds",0.2},{"follow_damping",0.05},{"facing",facing},{"track_look_target",false}};};
   auto plain=masking.open(assets,player).value;auto filmed=plain;filmed["cameras"]=Json::array({camera("FreeLook",0,Json::object(),4.0,0.0,"movement"),camera("Aim",10,Json{{"input","combat.ranged"}},2.0,0.5,"camera"),camera("Staggered",20,Json{{"tag",6}},3.0,0.0,"movement")});
   masking.apply(assets,player,masking.revision(),filmed,"Author Player cameras");masking.undo(assets);check(masking.open(assets,player).value==plain,"Camera Undo left a rig behind");masking.redo(assets);check(masking.open(assets,player).value==filmed,"Camera Redo lost the rig");
   auto broken=filmed;broken["cameras"][0]["when"]=Json{{"input","jump"}};masking.apply(assets,player,masking.revision(),broken,"Camera rig without a default");rejects_with([&]{masking.validate(assets,player,player_roots);},"default");masking.undo(assets);
   broken=filmed;broken["cameras"][1]["fov"]=170.0;masking.apply(assets,player,masking.revision(),broken,"Camera field of view out of range");rejects([&]{masking.validate(assets,player,player_roots);});masking.undo(assets);
   broken=filmed;broken["cameras"][1]["name"]="FreeLook";masking.apply(assets,player,masking.revision(),broken,"Duplicate camera name");rejects([&]{masking.validate(assets,player,player_roots);});masking.undo(assets);check(masking.open(assets,player).value==filmed,"Rejected camera drafts changed the valid rig");
  }
  masking.validate(assets,player,player_roots);check(!std::filesystem::exists(ember_path),"Private mask validation published sources");''')
sub(t,'''  auto worn_air=load_character_preview(root/"mask-air.json",''','''  check(cooked.definition.authored_cameras&&cooked.definition.cameras.cameras.size()==3&&cooked.definition.cameras.cameras[1].name=="Aim"&&cooked.definition.cameras.cameras[1].input_action=="combat.ranged"&&cooked.definition.cameras.cameras[1].distance==2.0&&cooked.definition.cameras.cameras[1].facing==CameraFacing::Camera&&cooked.definition.cameras.cameras[2].tag==6&&cooked.definition.cameras.cameras[0].input_action.empty(),"Frozen Player lost its authored camera rig");
  auto worn_air=load_character_preview(root/"mask-air.json",''')
sub(t,'''  auto prepared=prepare_character_preview(scene->plan(),scene->world(),worn,[&](AssetId asset){return load_cooked_model(root/"mask.json",assets.cas_path(),asset);});auto& s=*prepared.second;CharacterSceneInput press;press.combat_events={{9,InputEdge::Pressed,1000,0,1,false}};s.step(press);while(s.motor().tick<30)s.step({});''','''  check(worn.cameras.cameras.size()==3&&worn.cameras.cameras[2].name=="Staggered"&&load_character_preview(root/"mask.json",assets.cas_path(),"kit:"+kit.text(),skin,role(4),role(5),collision).cameras.cameras.size()==2,"Play resources did not carry the Player's cameras, or a kit-only Play lost the built-in rig");
  {CameraDirector director(worn.cameras,0,0);std::vector<std::string> ranged{"combat.ranged"},idle_input;std::vector<TagId> staggered{6};check(director.select(idle_input,{})==0&&director.select(ranged,{})==1&&director.select(ranged,staggered)==2,"Authored camera conditions/priorities do not drive the director");}
  auto prepared=prepare_character_preview(scene->plan(),scene->world(),worn,[&](AssetId asset){return load_cooked_model(root/"mask.json",assets.cas_path(),asset);});auto& s=*prepared.second;CharacterSceneInput press;press.combat_events={{9,InputEdge::Pressed,1000,0,1,false}};s.step(press);while(s.motor().tick<30)s.step({});''')
sub(t,'''four-slot equip/select/unequip Undo/Redo,''','''four-slot equip/select/unequip Undo/Redo, Player camera rig authoring/rejection/frozen conditions,''')
# --- editor exercises
m='apps/editor/main.cpp'
sub(m,'exercise_reaction{},exercise_death{},exercise_dodge{},','exercise_reaction{},exercise_death{},exercise_dodge{},exercise_aim{},exercise_camera_preview{},')
sub(m,'if(arg=="--exercise-dodge"){','if(arg=="--exercise-aim"){out.exercise_aim=true;out.exercise_heavy=true;continue;}if(arg=="--exercise-camera-preview"){out.exercise_camera_preview=true;continue;}if(arg=="--exercise-dodge"){')
sub(m,'''args.exercise_dodge?((control==input_control("Keyboard.C")''','''args.exercise_aim?(control==input_control("Keyboard.AltLeft")&&frame>=8):args.exercise_dodge?((control==input_control("Keyboard.C")''')
sub(m,'''if(args.exercise_heavy&&!args.exercise_death&&!args.exercise_dodge){''',r'''if(args.exercise_aim){require(bool(character)&&bool(director),"Aim exercise needs a Play session");auto target=character->presentation().find(character_resources->combat->target);const auto& live=director->rig().cameras[director->live()];const auto& pose=director->pose();const auto position=character->motor().position;const double reach=std::hypot(std::hypot(pose.position[0]-position.x,pose.position[1]-position.y),pose.position[2]-position.z);
            require(live.name=="Aim"&&live.facing==CameraFacing::Camera&&director->blend()==1&&std::abs(pose.fov_degrees-live.fov_degrees)<1e-9&&reach<4&&std::abs(std::remainder(character->motor().yaw-director->yaw(),6.283185307179586))<1e-9&&character->presentation().read(target).health.current==100&&character->pending_prediction()==0&&editor.document->world().serialize()==import_baseline,"Editor Game did not blend to the aim camera while the ranged modifier was held");
            std::cout<<"Editor camera live="<<live.name<<" blend="<<director->blend()<<" fov="<<pose.fov_degrees<<" camera_distance="<<reach<<" character_faces_camera=1 pending=0\n";editor.stop();}if(args.exercise_heavy&&!args.exercise_death&&!args.exercise_dodge&&!args.exercise_aim){''')
sub(m,'''if(args.exercise_reaction){shell.focus_gameplay_inspector=true;shell.select_effect_debug=true;}''','''if(args.exercise_reaction){shell.focus_gameplay_inspector=true;shell.select_effect_debug=true;}if(args.exercise_camera_preview){shell.camera_preview=1;shell.camera_preview_yaw=25;shell.camera_preview_pitch=10;}''')
v='scripts/verify_effect_reaction.py';s=open(v,encoding='utf8').read()
s=s.replace("'EffectAssetTests','CombatKitAssetTests','EffectReplicationTests','CombatEffectTests','--parallel'","'EffectAssetTests','CombatKitAssetTests','EffectReplicationTests','CombatEffectTests','CameraTests','--parallel'")
s=s.replace("('effect-reaction-combat-effects','CombatEffectTests')]","('effect-reaction-combat-effects','CombatEffectTests'),('camera-rig','CameraTests')]")
k="run('mask-placement-d3d12',";i=s.index(k);j=s.index('\n',i)+1
s=s[:j]+"run('camera-aim-d3d12',worn+['--exercise-aim','--frames','30','--capture',EVIDENCE/'camera-aim-d3d12.png'])\nform=[x for x in worn];run('camera-preview-d3d12',form+['--player-workspace','--authoring-asset',f['mask_player'],'--exercise-camera-preview','--height','1500','--frames','6','--capture',EVIDENCE/'camera-preview-d3d12.png'])\n"+s[j:]
s=s.replace("'engine/runtime/action.cpp',","'engine/runtime/action.cpp','engine/runtime/camera.cpp','engine/runtime/include/darkangel/camera.hpp','tests/camera_tests.cpp',")
s=s.replace("scope='Mask assets","scope='Player virtual camera rig (free-look and aim) with blending; in-Play mask switching; mask assets")
open(v,'w',encoding='utf8',newline='\n').write(s)
