#include <darkangel/eos_session.hpp>
#include <darkangel/world_session.hpp>
#include <nlohmann/json.hpp>
#include <fstream>
#include <algorithm>
#include <chrono>
#include <iostream>
#include <thread>
using namespace darkangel;
std::string read(const char* path,std::size_t limit){std::ifstream in(path,std::ios::binary|std::ios::ate);if(!in || in.tellg()<0 || static_cast<std::size_t>(in.tellg())>limit)throw std::runtime_error("Local online input file unavailable/too large");in.seekg(0);return {std::istreambuf_iterator<char>(in),{}};}
int main(int argc,char** argv){try{
    if(argc!=4 && argc!=5)throw std::runtime_error("OnlineProbe PRIVATE_CONFIG_JSON PRIVATE_TOKEN_FILE host | join EXACT_LOBBY_ID");const bool host=std::string_view(argv[3])=="host";if((host && argc!=4) || (!host && (std::string_view(argv[3])!="join" || argc!=5)))throw std::runtime_error("Invalid explicit online role/lobby selection");
    auto j=nlohmann::json::parse(read(argv[1],8192));EosConfiguration config{j.at("product"),j.at("sandbox"),j.at("deployment"),j.at("client_id"),j.at("public_client_secret"),j.at("cache_directory")};SessionHandshake hello{1,j.at("schema_hash"),j.at("content_hash"),host?static_cast<std::uint64_t>(std::chrono::system_clock::now().time_since_epoch().count()):1};EosSessionProvider provider(config,hello);auto token=read(argv[2],8192);while(!token.empty() && (token.back()=='\n' || token.back()=='\r'))token.pop_back();auto identity=j.at("identity_provider").get<std::string>();if(identity!="epic_id_token" && identity!="steam_session_ticket")throw std::runtime_error("Unsupported explicit Connect provider");provider.login(identity=="epic_id_token"?EosIdentityProvider::EpicIdToken:EosIdentityProvider::SteamSessionTicket,std::move(token));
    auto wait=[&](auto predicate){auto end=std::chrono::steady_clock::now()+std::chrono::seconds(45);while(std::chrono::steady_clock::now()<end){provider.tick();if(provider.state()==EosState::Failed)throw std::runtime_error("EOS service operation failed");if(predicate())return;std::this_thread::sleep_for(std::chrono::milliseconds(16));}throw std::runtime_error("Online acceptance deadline exceeded");};
    wait([&]{return provider.state()==EosState::LoggedIn || provider.state()==EosState::CreateUserRequired;});if(provider.state()==EosState::CreateUserRequired){if(!j.value("allow_create_user",false))throw std::runtime_error("Connect account needs explicit allow_create_user consent in private configuration");provider.create_user();wait([&]{return provider.state()==EosState::LoggedIn;});}
    if(host)provider.host();else {provider.search();wait([&]{return provider.state()==EosState::LoggedIn;});auto results=provider.lobby_results();auto found=std::find(results.begin(),results.end(),argv[4]);if(found==results.end())throw std::runtime_error("Exact selected compatible lobby not found");provider.join(static_cast<std::size_t>(found-results.begin()));}wait([&]{return provider.state()==EosState::InLobby;});if(host)std::cout<<"Lobby "<<provider.lobby_id()<<'\n'<<std::flush;
    wait([&]{return !provider.participants().empty();});auto participant=provider.participants().front();if(!host && !participant.host)throw std::runtime_error("Selected remote participant is not the authoritative lobby owner");auto transport=provider.transport(participant.id);hello=provider.handshake();auto peer=transport->open(hello);WorldSession session(host?SessionRole::Server:SessionRole::Client,hello);session.attach(*transport,peer);std::uint64_t object{};if(host){ObjectData data;data.id={1,1};object=session.create(data);}auto end=std::chrono::steady_clock::now()+std::chrono::seconds(30);unsigned stage{};bool saw_create{},saw_move{};
    while(std::chrono::steady_clock::now()<end){provider.tick();session.tick();if(!host && !session.objects().empty()){saw_create=true;saw_move|=session.objects().begin()->second.transform.x==12;}if(session.readiness(peer)==SessionReadiness::Ready){if(host){if(stage==0){Transform t;t.x=12;session.move(object,t);++stage;}else if(stage==1){session.destroy(object);++stage;}else {auto flush_until=std::chrono::steady_clock::now()+std::chrono::seconds(1);while(std::chrono::steady_clock::now()<flush_until){provider.tick();std::this_thread::sleep_for(std::chrono::milliseconds(16));}provider.leave();wait([&]{return provider.state()==EosState::LoggedIn;});std::cout<<"EOS host shared protocol/create/move/despawn accepted\n";return 0;}}else if(session.revision()>=3 && session.objects().empty() && saw_create && saw_move){std::cout<<"EOS client current baseline and lifecycle accepted\n";provider.leave();wait([&]{return provider.state()==EosState::LoggedIn;});return 0;}}std::this_thread::sleep_for(std::chrono::milliseconds(16));}throw std::runtime_error("EOS gameplay baseline deadline exceeded");
}catch(const nlohmann::json::exception&){std::cerr<<"OnlineProbe: invalid private configuration; values suppressed\n";return 1;}catch(const std::exception& e){std::cerr<<"OnlineProbe: "<<e.what()<<'\n';return 1;}}
