"""Qualified normalized Royal static model collision through native source/CAS."""
import argparse, hashlib, json, subprocess, time
from pathlib import Path
ROOT=Path(__file__).resolve().parents[1];EVIDENCE=ROOT/'docs/implementation/evidence'
parser=argparse.ArgumentParser();parser.add_argument('--build',action='store_true');args=parser.parse_args();gates=[]
def run(name,command,timeout=2400):
    start=time.monotonic();result=subprocess.run(list(map(str,command)),cwd=ROOT,capture_output=True,text=True,encoding='utf8',errors='replace',timeout=timeout)
    (EVIDENCE/(name+'.log')).write_text(result.stdout+result.stderr,encoding='utf8');gates.append(dict(name=name,exit=result.returncode,seconds=round(time.monotonic()-start,3)))
    if result.returncode:raise RuntimeError((result.stdout+result.stderr)[-5000:])
run('royal-collision-product',['python','scripts/verify_ability_observer.py',*(['--build'] if args.build else [])])
run('royal-collision-editor',[ROOT/'build/m5-editor-relwithdebinfo/RoyalCollisionTests.exe'])
inputs=['CMakeLists.txt','engine/assets/model_collision.cpp','engine/assets/include/darkangel/model_collision.hpp','engine/assets/collision_cooker.cpp','engine/runtime/include/darkangel/collision_asset.hpp','apps/editor/character_preview.cpp','apps/editor/character_preview.hpp','apps/editor/main.cpp','tools/cooker/main.cpp','tests/royal_collision_tests.cpp','scripts/prepare_royal_scene.py','scripts/open_royal_scene.ps1','scripts/verify_royal_collision.py','scripts/verify_royal_combat.py','content/royal_district/collision/environment.dacollision']
binaries=['build/m5-editor-relwithdebinfo/DarkAngelEditor.exe','build/m5-relwithdebinfo/AssetTool.exe','build/m5-relwithdebinfo/RoyalCollisionTests.exe','build/m5-editor-relwithdebinfo/RoyalCollisionTests.exe']
originals=['content/royal_district/RoyalVillage.dascene','content/royal_district/RoyalCombat.dascene','content/royal_district/character/canonical-human.glb',*map(lambda p:p.relative_to(ROOT).as_posix(),sorted((ROOT/'content/royal_district/static').rglob('*.gltf')))]
receipt=dict(schema=1,base_head=subprocess.check_output(['git','rev-parse','HEAD'],cwd=ROOT,text=True).strip(),scope='Native normalized model-to-collision source/CAS, render-placement geometry fencing, precise Royal terrain/hut Jolt rays/materials/clearance and primary editor combat plus original scene locomotion',gates=gates,related_evidence=['ability-observer.json','royal-combat.json'],source_sha256={p:hashlib.sha256((ROOT/p).read_bytes()).hexdigest() for p in inputs},original_sha256={p:hashlib.sha256((ROOT/p).read_bytes()).hexdigest() for p in originals},binary_sha256={p:hashlib.sha256((ROOT/p).read_bytes()).hexdigest() for p in binaries},limitations=['Static solid model profile; tested hut entrances contain closed geometry. Authored door state/interactions and additional collision policies remain future work.','Model/placement changes require rebaking the existing native collision asset before character Play; originals are preserved.','Full streaming/content/topology/fault/performance gates and effects/tags/combo/projectile/graph/socket/authoring remain open.','M4/M5 stay In progress; live EOS remains externally blocked; M6 has not started.'])
(EVIDENCE/'royal-collision.json').write_text(json.dumps(receipt,indent=2)+'\n',encoding='utf8');print('Royal native mesh collision, full-editor/backends/Headless/GNS and optimized integration checks passed')
