"""Authored effect reaction: native binding, frozen closure, checked public flinch and fresh Play."""
import argparse,hashlib,json,subprocess,time
from pathlib import Path
from msvc_environment import activate
ROOT=Path(__file__).resolve().parents[1];BUILD=ROOT/'build/m5-editor-relwithdebinfo';EVIDENCE=ROOT/'docs/implementation/evidence'
parser=argparse.ArgumentParser();parser.add_argument('--build',action='store_true');args=parser.parse_args();gates=[]
def run(name,command,env=None):
    start=time.monotonic();result=subprocess.run(list(map(str,command)),cwd=ROOT,env=env,capture_output=True,text=True,encoding='utf8',errors='replace',timeout=3600)
    (EVIDENCE/(name+'.log')).write_text(result.stdout+result.stderr,encoding='utf8');gates.append(dict(name=name,exit=result.returncode,seconds=round(time.monotonic()-start,3)))
    if result.returncode:raise RuntimeError((result.stdout+result.stderr)[-4000:])
    print(name+' passed',flush=True)
if args.build:
    run('effect-reaction-build',[ROOT/'.tools/cmake/cmake-4.4.4-windows-x86_64/bin/cmake.exe','--build',BUILD,'--target','DarkAngelEditor','NativeAuthoringTests','ReactionPresentationTests','ObservedCharacterPoseTests','EffectAssetTests','CombatKitAssetTests','EffectReplicationTests','CombatEffectTests','--parallel','2'],activate())
# NativeAuthoringTests writes the disposable copied fixture the later gates read.
for name,binary in [('effect-reaction-authoring','NativeAuthoringTests'),('effect-reaction-presentation','ReactionPresentationTests'),('effect-reaction-public-pose','ObservedCharacterPoseTests'),('effect-reaction-effect-assets','EffectAssetTests'),('effect-reaction-kit-assets','CombatKitAssetTests'),('effect-reaction-replication','EffectReplicationTests'),('effect-reaction-combat-effects','CombatEffectTests')]:run(name,[BUILD/(binary+'.exe')])
f=json.loads((BUILD/'authoring-fixture.json').read_text());source=Path(f['source']);cache=Path(f['cache']);model=json.loads((source/'royal_district/static/terrain/SM_RC_Terrain_Ground_32x32.gltf.daimport').read_text())['id'];collision=json.loads((source/'royal_district/collision/environment.dacollision').read_text())['asset']
common=[BUILD/'DarkAngelEditor.exe','--registry',f['reaction_registry'],'--cas',cache/'cas','--model',model,'--scene',source/'royal_district/RoyalCombat.dascene','--character-kit',f['kit'],'--character-collision',collision,'--character-player','00000000000000000000000000000004','--combat-target','00000000000000000000000000000005','--sources',source,'--asset-cache',cache,'--backend','d3d12','--hidden','--capture-workspace']
run('effect-reaction-form',common+['--ability-workspace','--authoring-asset',f['reaction_effect'],'--height','1500','--frames','5','--capture',EVIDENCE/'effect-reaction-form.png'])
run('effect-reaction-d3d12',common+['--exercise-reaction','--frames','30','--capture',EVIDENCE/'effect-reaction-d3d12.png'])
death=[f['death_registry'] if x==f['reaction_registry'] else x for x in common]
run('kit-death-d3d12',death+['--exercise-death','--frames','210','--capture',EVIDENCE/'kit-death-d3d12.png'])
files=['apps/editor/character_preview.cpp','apps/editor/editor_authoring.cpp','apps/editor/editor_ui.hpp','apps/editor/main.cpp','apps/editor/native_authoring.cpp','apps/editor/native_authoring.hpp','engine/assets/effect_cooker.cpp','engine/assets/combat_kit_cooker.cpp','engine/runtime/action.cpp','engine/runtime/effects.cpp','engine/runtime/character_presentation.cpp','engine/runtime/character_scene.cpp','engine/runtime/include/darkangel/effects.hpp','engine/runtime/include/darkangel/character_presentation.hpp','engine/runtime/include/darkangel/character_scene.hpp','tests/native_authoring_tests.cpp','tests/reaction_presentation_tests.cpp','scripts/verify_effect_reaction.py']
receipt=dict(schema=1,base_head=subprocess.check_output(['git','rev-parse','HEAD'],cwd=ROOT,text=True).strip(),scope='Kit death timeline with terminal precedence and held final pose; optional native effect reaction binding, frozen action/clip closure, stateless checked public reaction selection shared by owner and observed poses, authoring commands/forms and fresh authoritative Play',gates=gates,source_sha256={p:hashlib.sha256((ROOT/p).read_bytes()).hexdigest() for p in files},binary_sha256={p:hashlib.sha256((BUILD/p).read_bytes()).hexdigest() for p in ['DarkAngelEditor.exe','NativeAuthoringTests.exe','ReactionPresentationTests.exe']},limitations=['One visible full-body reaction per actor, root policy none; no reaction queue, blend ramps, additive or upper-body reactions.','Reaction timelines carry cue blocks only and no cue is dispatched by presentation in this slice.','The fixture reuses the existing attack clip as its flinch; no flinch clip or default Royal reaction content is shipped.','Owner-pose reaction selection shares the verified selector; a positive owner-side flinch in editor Play needs an attacker other than the player and is covered by native WorldSession tests only.','Scripted native commands and D3D12 form/rendering evidence, not physical pointer input, remote graphical timing/loss or multiplayer qualification.','M4/M5 In progress; EOS blocked; M6-M9 not started; publication crash-recovery limits unchanged.'])
(EVIDENCE/'effect-reaction.json').write_text(json.dumps(receipt,indent=2)+'\n')
