"""Frozen native joint masks over locomotion, preserving authority and four layers."""
import argparse,hashlib,json,subprocess,time
from pathlib import Path
from msvc_environment import activate
ROOT=Path(__file__).resolve().parents[1];BUILD=ROOT/'build/m5-editor-relwithdebinfo';EVIDENCE=ROOT/'docs/implementation/evidence'
parser=argparse.ArgumentParser();parser.add_argument('--build',action='store_true');args=parser.parse_args();gates=[]
def run(name,command,env=None):
    start=time.monotonic();result=subprocess.run(list(map(str,command)),cwd=ROOT,env=env,capture_output=True,text=True,encoding='utf8',errors='replace',timeout=900)
    (EVIDENCE/(name+'.log')).write_text(result.stdout+result.stderr,encoding='utf8');gates.append(dict(name=name,exit=result.returncode,seconds=round(time.monotonic()-start,3)))
    if result.returncode:raise RuntimeError((result.stdout+result.stderr)[-4000:])
    print(name+' passed',flush=True)
if args.build:
    run('upper-body-build',[ROOT/'.tools/cmake/cmake-4.4.4-windows-x86_64/bin/cmake.exe','--build',BUILD,'--target','DarkAngelEditor','NativeAuthoringTests','ObservedCharacterPoseTests','JointMaskTests','ActionClipBindingTests','--parallel','2'],activate())
for name,binary in [('upper-body-authoring','NativeAuthoringTests'),('upper-body-public','ObservedCharacterPoseTests'),('upper-body-mask','JointMaskTests'),('upper-body-root','ActionClipBindingTests')]:run(name,[BUILD/(binary+'.exe')])
f=json.loads((BUILD/'authoring-fixture.json').read_text());source=Path(f['source']);cache=Path(f['cache']);model=json.loads((source/'royal_district/static/terrain/SM_RC_Terrain_Ground_32x32.gltf.daimport').read_text())['id'];collision=json.loads((source/'royal_district/collision/environment.dacollision').read_text())['asset']
common=[BUILD/'DarkAngelEditor.exe','--registry',f['upper_registry'],'--cas',cache/'cas','--model',model,'--scene',source/'royal_district/RoyalCombat.dascene','--character-kit',f['kit'],'--character-collision',collision,'--character-player','00000000000000000000000000000004','--combat-target','00000000000000000000000000000005','--sources',source,'--asset-cache',cache,'--backend','d3d12','--hidden','--capture-workspace']
run('upper-body-preview',common+['--animation-workspace','--authoring-asset',f['upper_action'],'--exercise-composer','--composer-tick','20','--height','1800','--frames','5','--capture',EVIDENCE/'upper-body-preview.png'])
run('upper-body-d3d12',common+['--exercise-upper-body','--frames','30','--capture',EVIDENCE/'upper-body-d3d12.png'])
files=['apps/editor/character_preview.cpp','apps/editor/character_preview.hpp','apps/editor/editor_authoring.cpp','apps/editor/editor_composer.cpp','apps/editor/editor_ui.hpp','apps/editor/main.cpp','apps/editor/native_authoring.cpp','engine/assets/ability_cooker.cpp','engine/assets/action_cooker.cpp','engine/assets/assets_internal.hpp','engine/assets/combat_kit_cooker.cpp','engine/assets/graph_cooker.cpp','engine/runtime/action.cpp','engine/runtime/animation_graph.cpp','engine/runtime/character_presentation.cpp','engine/runtime/character_scene.cpp','engine/runtime/include/darkangel/action.hpp','engine/runtime/include/darkangel/animation_graph.hpp','engine/runtime/include/darkangel/character_presentation.hpp','tests/native_authoring_tests.cpp','content/animation/upper_body.damask','scripts/verify_upper_body_action.py']
receipt=dict(schema=1,base_head=subprocess.check_output(['git','rev-parse','HEAD'],cwd=ROOT,text=True).strip(),scope='Native Composer upper-body mask references, complementary locomotion/action presentation, frozen private preview and fresh authoritative Play',gates=gates,source_sha256={p:hashlib.sha256((ROOT/p).read_bytes()).hexdigest() for p in files},binary_sha256={p:hashlib.sha256((BUILD/p).read_bytes()).hexdigest() for p in ['DarkAngelEditor.exe','NativeAuthoringTests.exe','ObservedCharacterPoseTests.exe']},limitations=['One active action plus at most three locomotion layers; masked kit preparation rejects a graph whose bound is four.','Mask selection reuses existing native weights; no joint painting, gameplay mask/equipment slots, additive reactions or AI.','Isolated Composer preview samples the frozen locomotion graph at rest with empty simulated tags; reprepare after source edits.','Scripted native commands and D3D12 form/rendering evidence, not physical pointer input or multiplayer graphical qualification.','M4/M5 In progress; EOS blocked; M6-M9 not started; publication crash-recovery limits unchanged.'])
(EVIDENCE/'upper-body-action.json').write_text(json.dumps(receipt,indent=2)+'\n')
