"""Public ability/motor state, prepared observer phase, visibility and late join."""
import argparse, hashlib, json, subprocess, time
from pathlib import Path
from msvc_environment import activate
ROOT=Path(__file__).resolve().parents[1];EVIDENCE=ROOT/'docs/implementation/evidence'
CMAKE=ROOT/'.tools/cmake/cmake-4.4.4-windows-x86_64/bin/cmake.exe'
parser=argparse.ArgumentParser();parser.add_argument('--build',action='store_true');args=parser.parse_args();gates=[]
def run(name,command,env=None,timeout=900):
    start=time.monotonic();result=subprocess.run(list(map(str,command)),cwd=ROOT,capture_output=True,text=True,encoding='utf8',errors='replace',env=env,timeout=timeout)
    (EVIDENCE/(name+'.log')).write_text(result.stdout+result.stderr,encoding='utf8');gates.append(dict(name=name,exit=result.returncode,seconds=round(time.monotonic()-start,3)))
    if result.returncode:raise RuntimeError((result.stdout+result.stderr)[-5000:])
run('ability-observer-royal',['python','scripts/verify_ability_prediction.py',*(['--build'] if args.build else [])],timeout=2400)
run('ability-observer-editor',[ROOT/'build/m5-editor-relwithdebinfo/AbilityObserverTests.exe'])
if args.build:run('ability-observer-integration-build',[CMAKE,'--build','build/m5-relwithdebinfo','--parallel','2'],activate(),2400)
run('ability-observer-integration',[CMAKE.parent/'ctest.exe','--test-dir','build/m5-relwithdebinfo','--output-on-failure'],timeout=1200)
inputs=['CMakeLists.txt','engine/runtime/include/darkangel/attributes.hpp','engine/runtime/attributes.cpp','engine/assets/include/darkangel/ability_assets.hpp','engine/assets/ability_cooker.cpp','engine/runtime/include/darkangel/ability.hpp','engine/runtime/ability.cpp','engine/runtime/ability_state.hpp','engine/runtime/ability_prediction.cpp','engine/runtime/ability_observer.cpp','engine/runtime/include/darkangel/ability_observer.hpp','engine/runtime/ability_wire.cpp','engine/runtime/ability_wire.hpp','engine/runtime/world_session.cpp','engine/runtime/include/darkangel/world_session.hpp','engine/runtime/character_scene.cpp','engine/runtime/include/darkangel/character_scene.hpp','tests/ability_observer_tests.cpp','tests/ability_intent_gns_tests.cpp','tests/ability_asset_tests.cpp','tests/character_combat_scene_tests.cpp','scripts/prepare_royal_scene.py','scripts/verify_ability_observer.py']
binaries=['build/m5-editor-relwithdebinfo/DarkAngelEditor.exe','build/m5-relwithdebinfo/AbilityObserverTests.exe','build/m5-editor-relwithdebinfo/AbilityObserverTests.exe','build/m1-relwithdebinfo/AbilityObserverTests.exe']
receipt=dict(schema=1,base_head=subprocess.check_output(['git','rev-parse','HEAD'],cwd=ROOT,text=True).strip(),scope='Protocol3 atomic public motor/action frames, cooked visibility into native audience policies, server-only exclusion from owner corrections, active-action late join, prepared bounded observer interpolation and Royal coordinator; full optimized native integration',gates=gates,related_evidence=['royal-combat.json','ability-prediction.json'],source_sha256={p:hashlib.sha256((ROOT/p).read_bytes()).hexdigest() for p in inputs},binary_sha256={p:hashlib.sha256((ROOT/p).read_bytes()).hexdigest() for p in binaries},limitations=['Current four-actor arena-wide interest profile; public effects/tags/persistent cues and interest/cell restoration beyond reliable object lifecycle remain open.','Royal target remains stationary/rest pose; remote graphical scene/GNS late join and full timing/fault/bandwidth/performance gates are not qualified.','Owner native prediction requires visible cost and resource-bound attributes; server-only-dependent prediction fails preparation explicitly.','Observer tests use published synthetic motor trajectories; independent Jolt owner correction is checked by ability_motor_prediction.','Real combo/projectile/effects/Luau, graph/socket/authoring and precise collision gates remain open; M4/M5 stay In progress; EOS live service remains blocked.'])
(EVIDENCE/'ability-observer.json').write_text(json.dumps(receipt,indent=2)+'\n',encoding='utf8');print('Public ability native/full-editor/Headless/Royal/GNS and full optimized integration checks passed')
